src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Partner_Type__c</fullName>
        <label>Partner Type</label>
        <picklist>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Affiliate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Affinity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Strategic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Channel Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Portal_Outreach_Tool__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Partner_Type__c</fullName>
        <label>Partner Type</label>
        <picklist>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Affiliate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Affinity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Portal_Availability__c</fullName>
        <label>Portal Availability</label>
        <picklist>
            <picklistValues>
                <fullName>Employee Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner Portal</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Flyers (PDF)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Ads (JPG)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Portal Outreach Tool</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Outreach Tools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Portal_Referral__c.object
<CustomObject>
    <description>Referrals from the Partner Program website</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Referring Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Portal Referrals</relationshipLabel>
        <relationshipName>Portal_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead_Created_Date__c</fullName>
        <label>Lead Created Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Partner_Type__c</fullName>
        <label>Partner Type</label>
        <picklist>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Affiliate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Affinity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>OPEN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QUALIFIED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Portal Referral</label>
    <nameField>
        <displayFormat>REF-{000000}</displayFormat>
        <label>Portal Referral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PortalAffiliateHomeController.cls
public without sharing class PortalAffiliateHomeController {
    
    public Integer totalReferrals { get; private set; }        
    public Integer totalSold { get; private set; }
    public String partnerSince { get; private set; }
    private Id accountId;
    private String partnerType;
    public List<Portal_Outreach_Tool__c> getTools() {   
    
        List<Portal_Outreach_Tool__c> result =
            [SELECT Id, Name, Description__c,
                (SELECT Id, Name, BodyLength, ContentType, Description
                FROM Attachments)
            FROM Portal_Outreach_Tool__c
            WHERE Active__c = TRUE
            AND Type__c = 'Flyers (PDF)'
            AND Partner_Type__c INCLUDES (:partnerType)
            AND Portal_Availability__c INCLUDES ('Partner Portal')];

        return result;
        
    }
    
    public List<Portal_Outreach_Tool__c> getWebTools() {   
    
        List<Portal_Outreach_Tool__c> result =
            [SELECT Id, Name, Description__c,
                (SELECT Id, Name, BodyLength, ContentType, Description
                FROM Attachments)
            FROM Portal_Outreach_Tool__c
            WHERE Active__c = TRUE
             AND Type__c = 'Web Ads (JPG)'
            AND Partner_Type__c INCLUDES (:partnerType)
            AND Portal_Availability__c INCLUDES ('Partner Portal')];

        return result;
        
    }
    
    public PortalAffiliateHomeController () {
        User u = [SELECT Id, ContactId, CreatedDate FROM User WHERE Id = :UserInfo.getUserId()];
        Contact c = [SELECT Id, AccountId, Account.Partner_Type__c FROM Contact WHERE Id = :u.ContactId];
        accountId = c.AccountId;
        partnerType= c.Account.Partner_Type__c;
        AggregateResult[] minLeadDate = 
            [SELECT MIN(Lead_Created_Date__c) sinceDate 
            FROM Portal_Referral__c
            WHERE Account__c = :accountId
            AND Lead_Created_Date__c <> NULL 
            AND Status__c <> 'Duplicate'];
        
        if (minLeadDate.size() > 0 && minLeadDate[0].get('sinceDate') != null) {
          partnerSince = DateTime.newInstance((Date)minLeadDate[0].get('sinceDate'), Time.newInstance(0, 0, 0, 0)).format('MMMM, yyyy');
        } else {
          partnerSince = u.CreatedDate.format('MMMM, yyyy');
        } 
        
        populateSummary();
    }
    
    private void populateSummary() {
        totalReferrals = 0;
        //get earnings
        AggregateResult[] sumEarnings = 
          [SELECT COUNT(Id) referrals 
          FROM Portal_Referral__c 
          WHERE Account__c = :accountId 
          AND Status__c <> 'Duplicate'];
        
        if (sumEarnings.size() > 0) {         
          Decimal total = (Decimal)sumEarnings[0].get('referrals');
          if (total != null) {
            totalReferrals = total.intValue();            
          }
        }     
        
        totalSold = 0; 
        //get earnings
        AggregateResult[] statusSummary = 
          [SELECT COUNT(Id) referrals 
          FROM Portal_Referral__c 
          WHERE Account__c = :accountId 
          AND Status__c != NULL 
          AND Status__c = 'SOLD'];
        
        if (statusSummary.size() > 0) {         
          Decimal totalsd = (Decimal)statusSummary [0].get('referrals');
          if (totalsd != null) {
            totalSold = totalsd.intValue();            
          }
        }  
       
    }
}