src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_Last_Name__c</fullName>
        <formula>IF(CONTAINS(Name, &quot;,&quot;),LEFT(Name,FIND(&quot;,&quot;,Name)-1),Name)</formula>
        <label>Client Last Name</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Install_Location__c.object
<CustomObject>
    <description>AstrumPM - This object is defined as a single location on a property that has a measured TSRF, Pitch, and Azimuth.</description>
    <fields>
        <fullName>Physical_Surface_Assigned_Letter__c</fullName>
        <formula>text(Physical_Surface__r.Physical_Surface_Assigned_Letter__c)</formula>
        <label>Physical Surface Assigned Letter</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physical_Surface__c</fullName>
        <label>Physical Surface</label>
        <referenceTo>Physical_Surface__c</referenceTo>
        <relationshipLabel>Install Locations</relationshipLabel>
        <relationshipName>Install_Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Property_Owner__c</fullName>
        <formula>Physical_Surface__r.Property__r.Property_Owner__r.Name</formula>
        <label>Property Owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Install Locations</relationshipLabel>
        <relationshipName>Install_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Install Location</label>
    <nameField>
        <label>Install Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Install Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Physical_Surface__c.object
<CustomObject>
    <description>A collection of physically contiguous Install Locations sharing the same pitch and azimuth, with the same structural members and surface type, and located on the same Property.</description>
    <fields>
        <fullName>Physical_Surface_Assigned_Letter__c</fullName>
        <label>Physical Surface Assigned Letter</label>
        <picklist>
            <picklistValues>
                <fullName>A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>E</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>F</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>H</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>J</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>K</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>L</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>R</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>T</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>U</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>V</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>W</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>X</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Y</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Z</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Physical Surfaces</relationshipLabel>
        <relationshipName>Physical_Surfaces</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Physical Surface</label>
    <nameField>
        <label>Physical Surface Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Physical Surfaces</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <description>AstrumPM/AstrumCRM - Each account can have one or more properties.  A property is defined by its street address.</description>
    <fields>
        <fullName>Property_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account that represents the Owner of this Building.  This may be a Family or a Business.</description>
        <label>Property Owner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Address 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PhysicalSurfaceTriggerHandler.cls
/* FILE: PhysicalSurfaceTriggerHandler.cls
 * AUTHOR: Rohit Jain
 * DATE: Apr 24, 2014
 * PURPOSE: Physical SurfaceTrigger Handler
 * MODIFICATION HISTORY
 *
 */

public with sharing class PhysicalSurfaceTriggerHandler {
	private boolean m_isExecuting = false;
	
	public PhysicalSurfaceTriggerHandler(boolean isExecuting) {
		m_isExecuting = isExecuting;	
	}

	public void OnBeforeInsert(Physical_Surface__c[] newSurfaces){
        // EXECUTE BEFORE INSERT LOGIC
        defaultSurfaceName(newSurfaces);
        m_isExecuting = false;
    }

    public void OnAfterUpdate(Physical_Surface__c[] updatedSurfaces){
        // EXECUTE BEFORE INSERT LOGIC
        updateInstallLocations(updatedSurfaces);
        m_isExecuting = false;
    }

    public void OnAfterDelete(Physical_Surface__c[] deletedSurfaces, map<id, Physical_Surface__c> deletedSurfacesMap){
        // EXECUTE BEFORE INSERT LOGIC
        updateSystemDesignItems(deletedSurfaces);
        m_isExecuting = false;
    }

    private void updateInstallLocations(Physical_Surface__c[] updatedSurfaces)
    {
        //MK - 2014-05-01
        //After update - Need to update all SDI records.
        //Here we can simply update all child Install Location records and let that trigger fire.  The good thing here will be that if in the futre we add logic to
        //the Install Location trigger that pulls data from Physical Surface, it will automatically run as needed. 
        List<Install_Location__c> ilsToUpdate = [Select id from Install_Location__c where Physical_Surface__c in: updatedSurfaces];
        update(ilsToUpdate);
    }


    private void updateSystemDesignItems(Physical_Surface__c[] deletedSurfaces)
    {        
        //Here we need to go up the chain to grab the Property id if it exists. Then go back down the chain > SD > SDA > SDIs in order to update the 
        //SDIs so that the roll-up calculation is valid
        //Gather Prop IDs
        set<ID> propIDs = new set<ID>();
        for ( Physical_Surface__c rec : deletedSurfaces) {
            if(rec.Property__c != null) propIDs.add(rec.Property__c);
        }
        
        //Update SDIs       
        if(!propIDs.isEmpty()) PropertyCommonUtil.UpdateSDIsFromPropertyIDs(propIDs);
    }

    

    private void defaultSurfaceName(Physical_Surface__c[] newSurfaces)
    {
    	Set<Id> propertyIds = new Set<Id>();
        for(Physical_Surface__c surface : newSurfaces)
        {
            propertyIds.add(surface.Property__c);
        }       
        Map<Id,Property__c> propertiesMap;

        if(propertyIds.size() > 0)
        {
           propertiesMap = new Map<Id,Property__c> ([Select Id, Name,Property_Owner__r.Client_Last_Name__c 
                                                                                   from Property__c Where id in :propertyIds]);
        }

        for(Physical_Surface__c surface : newSurfaces)
    	{
    		if(propertiesMap.get(surface.Property__c) != null)
            {
                surface.Name = propertiesMap.get(surface.Property__c).Property_Owner__r.Client_Last_Name__c + ' - Surface '+ surface.Physical_Surface_Assigned_Letter__c;
            }
            else
            {
                surface.Name = 'Surface '+ surface.Physical_Surface_Assigned_Letter__c;    
            }   
    	} 

    }
}