src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Portal_Payment_Plan__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Portal Payment Plan</label>
        <referenceTo>Portal_Payment_Plan__c</referenceTo>
        <relationshipLabel>Referring Companies</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referring_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Partner Prospect Referring Account</inlineHelpText>
        <label>Referring Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Referred Accounts</relationshipLabel>
        <relationshipName>ReferredAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/County__c.object
<CustomObject>
    <description>Represents a County in a State</description>
    <fields>
        <fullName>State__c</fullName>
        <description>State County belongs to</description>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Counties</relationshipLabel>
        <relationshipName>Counties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <picklist>
            <picklistValues>
                <fullName>CONNECTICUT =&gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fairfield CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hartford CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Litchfield CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middlesex CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Haven CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New London CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tolland CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Windham CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DISTRICT OF COLUMBIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DELAWARE =&gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kent DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Castle DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sussex DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MARYLAND =&gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allegany MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anne Arundel MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baltimore City MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baltimore MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Calvert MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caroline MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carroll MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cecil MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charles MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dorchester MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Frederick MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Garrett MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Harford MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Howard MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kent MD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Referring_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account (if any) that referred this lead</description>
        <inlineHelpText>Account (if any) that referred this lead</inlineHelpText>
        <label>Referring Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Referred Leads</relationshipLabel>
        <relationshipName>Referred_Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <picklist>
            <picklistValues>
                <fullName>CONNECTICUT =&gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fairfield CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hartford CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Litchfield CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middlesex CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Haven CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New London CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tolland CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Windham CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DISTRICT OF COLUMBIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DELAWARE =&gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kent DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Castle DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sussex DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MARYLAND =&gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allegany MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anne Arundel MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baltimore City MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baltimore MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Calvert MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caroline MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carroll MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cecil MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charles MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dorchester MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Frederick MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Garrett MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Harford MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Howard MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kent MD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Property__c.Property_Owner__r.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referring_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Account (if any) that referred this lead</description>
        <inlineHelpText>Account (if any) that referred this lead</inlineHelpText>
        <label>Referring Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Referred Opportunities</relationshipLabel>
        <relationshipName>Referred_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Property State Associated with This Opportunity</description>
        <formula>TEXT(Property__r.Property_State__c)</formula>
        <inlineHelpText>Property State Associated with This Opportunity</inlineHelpText>
        <label>State</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Portal_Referral__c.object
<CustomObject>
    <description>Referrals from the Partner Program website</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Referring Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Portal Referrals</relationshipLabel>
        <relationshipName>Portal_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City for referral</description>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Detail__c</fullName>
        <label>Detail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of referral</description>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of referral</description>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Portal Referrals</relationshipLabel>
        <relationshipName>Portal_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Portal Referrals</relationshipLabel>
        <relationshipName>Portal_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Portal_Payment_Plan__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Portal Payment Plan</label>
        <referenceTo>Portal_Payment_Plan__c</referenceTo>
        <relationshipLabel>Portal Referrals</relationshipLabel>
        <relationshipName>Portal_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>OPEN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QUALIFIED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>Street of Referral</description>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <label>Portal Referral</label>
    <nameField>
        <displayFormat>REF-{000000}</displayFormat>
        <label>Portal Referral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LeadPortalReferralTriggerTest.cls
/* FILE: LeadPortalReferralTriggerTest.trigger
 * AUTHOR: Tino Mattheou
 * DATE: September 5, 2012
 * PURPOSE: test class for LeadPortalReferral trigger
 * MODIFICATION HISTORY
 * 10/09/2012 TCM - updates to connect referring account leads to portal
 *
 */
 
@isTest(SeeAllData=true)
public class LeadPortalReferralTriggerTest {

    static testMethod void referral_changeLeadToContacted_detailChanged() {
        
        Portal_Referral__c referral = createPortalReferral();
        
        referral = [SELECT Id, Lead__c, Status__c, Detail__c
            FROM Portal_Referral__c
            WHERE Id = :referral.Id];
            
        System.assertEquals(PortalReferralStatus.OPEN_STATUS, referral.Status__c);
        System.assertEquals('New', referral.Detail__c);     
        
        Test.startTest();
        
        Lead ld = new Lead(
            Id = referral.Lead__c,
            Status = 'Contacted by Us'
        );
        update ld;
        
        Test.stopTest();

        referral = [SELECT Id, Lead__c, Status__c, Detail__c
            FROM Portal_Referral__c
            WHERE Id = :referral.Id];
            
        System.assertEquals(PortalReferralStatus.OPEN_STATUS, referral.Status__c);
        System.assertEquals('Contacted By Us', referral.Detail__c);     
        
    }
    
    static testMethod void referral_convertToOpportunity_detailChanged() {
        
        Portal_Referral__c referral = createPortalReferral();
        
        referral = [SELECT Id, Lead__c, Status__c, Detail__c
            FROM Portal_Referral__c
            WHERE Id = :referral.Id];
            
        System.assertEquals(PortalReferralStatus.OPEN_STATUS, referral.Status__c);
        System.assertEquals('New', referral.Detail__c);     
        
        Test.startTest();
        
        Database.LeadConvert lc = new Database.LeadConvert();
        lc.setLeadId(referral.Lead__c);
        lc.setConvertedStatus('Qualified');
        
        Database.LeadConvertResult lcr = Database.convertLead(lc);
        
        Test.stopTest();

        System.assert(lcr.isSuccess());

        referral = [SELECT Id, Lead__c, Status__c, Detail__c
            FROM Portal_Referral__c
            WHERE Id = :referral.Id];
            
        System.assertEquals(PortalReferralStatus.QUALIFIED_STATUS, referral.Status__c);
        System.assertEquals('Evaluation in Progress', referral.Detail__c);      
        
    }
    
    static testMethod void referralWithOpp_changeLeadToContactedUs_detailChanged() {
        
        Portal_Referral__c referral = createPortalReferral();
            
        Account customer = new Account(Name = 'Test Customer');
        insert customer;
        Property__c property = CreateAstrumPM2ProjectTest.createProperty(customer.Id, '123 Test St');
        Opportunity opp = CreateAstrumPM2ProjectTest.createOpportunity(customer.Id, 'Test Oppty');
        
        referral.Opportunity__c = opp.Id;
        update referral;        
        
        referral = [SELECT Id, Lead__c, Status__c, Detail__c
            FROM Portal_Referral__c
            WHERE Id = :referral.Id];
            
        System.assertEquals(PortalReferralStatus.OPEN_STATUS, referral.Status__c);
        System.assertEquals('New', referral.Detail__c);     
        
        Test.startTest();
        
        Lead ld = new Lead(
            Id = referral.Lead__c,
            Status = 'Contacted Us Back'
        );
        update ld;
        
        Test.stopTest();

        referral = [SELECT Id, Lead__c, Status__c, Detail__c
            FROM Portal_Referral__c
            WHERE Id = :referral.Id];
            
        System.assertEquals(PortalReferralStatus.OPEN_STATUS, referral.Status__c);
        System.assertEquals('New', referral.Detail__c);     
        
    }

    static testMethod void standaloneLead_changeLeadToContactedUs_codeCoverage() {
        
        Lead ld = new Lead(
            FirstName = 'Test',
            LastName = 'Lead',
            Company = 'Lead, Test'
        );
        insert ld;
        
        Test.startTest();
        
        ld.Status = 'Contacted Us Back';
        update ld;
        
        Test.stopTest();

    }
    
    static testMethod void portalAccount_insertLead_referralCreated() {
        
        Portal_Payment_Plan__c plan = new Portal_Payment_Plan__c();
        insert plan;
        
        User u = PortalToolsTest.createPortalUser();

        Account a = 
            [SELECT Id, Name, Portal_Payment_Plan__c 
            FROM Account
            WHERE Id IN (SELECT AccountId FROM Contact WHERE Id = :u.ContactId)];
        
        a.Portal_Payment_Plan__c = plan.Id;
        update a;
        
        Test.startTest();
        
        Lead ld = new Lead(
            FirstName = 'Test',
            LastName = 'Lead',
            Company = 'Lead, Test',
            Street = '123 Test St',
            City = 'Test City',
            State = 'PA',
            PostalCode = '19403',
            County__c = 'Chester',
            Phone = '(215) 555-1212',
            Email = 'test@test.com',
            LeadSource = 'Individual Referral',
            Referring_Account__c = a.Id
        );
        insert ld;
        
        Test.stopTest();
        
        Portal_Referral__c referral = 
            [SELECT Id, First_Name__c, Last_Name__c, Street__c, City__c, State__c, Zip__c, 
                Email__c, Account__c, Phone__c, Portal_Payment_Plan__c, Status__c, Detail__c
            FROM Portal_Referral__c
            WHERE Lead__c = :ld.Id];
            
        System.assertEquals(ld.FirstName, referral.First_Name__c);
        System.assertEquals(ld.LastName, referral.Last_Name__c);
        System.assertEquals(ld.Street, referral.Street__c);
        System.assertEquals(ld.City, referral.City__c);
        System.assertEquals(ld.State, referral.State__c);
        System.assertEquals(ld.PostalCode, referral.Zip__c);
        System.assertEquals(ld.Phone, referral.Phone__c);
        System.assertEquals(ld.Email, referral.Email__c);
        System.assertEquals(a.Id, referral.Account__c);
        System.assertEquals(plan.Id, referral.Portal_Payment_Plan__c);
        
        System.assertEquals(PortalReferralStatus.OPEN_STATUS, referral.Status__c);
        System.assertEquals('New', referral.Detail__c);     

    }
    
    static testMethod void portalAccount_convertLead_referralCreated() {
        
        //create portal account and set payment plan
        Portal_Payment_Plan__c plan = new Portal_Payment_Plan__c();
        insert plan;
        
        User u = PortalToolsTest.createPortalUser();

        Account a = 
            [SELECT Id, Name, Portal_Payment_Plan__c 
            FROM Account
            WHERE Id IN (SELECT AccountId FROM Contact WHERE Id = :u.ContactId)];
        
        //create a lead
        Lead ld = new Lead (
            FirstName = 'Test',
            LastName = 'Lead', 
            Site_Type__c = 'Residential', 
            Company = 'Lead, Test',
            Street = '123 Test St',
            City = 'Test City',
            State = 'PA',
            PostalCode = '19403',
            County__c = 'Chester',
            Phone = '(215) 555-1212',
            Email = 'test@test.com',
            Method_of_Contact__c = 'Referral', 
            LeadSource = 'Individual Referral',
            Lead_Source_Detail__c = 'Employee',
           //Lead_Source_Detail_2__c = 'Channel',
           // Lead_Source_Detail_4__c = 'Astrum Solar Connect',
            Referring_Account__c = a.Id
        );
        insert ld;

        //make sure there isn't a referral      
        System.assertEquals(0, [SELECT count() FROM Portal_Referral__c WHERE Lead__c = :ld.Id]);

        //set the payment plan      
        a.Portal_Payment_Plan__c = plan.Id;
        update a;
                
        Test.startTest();
        
        Database.LeadConvert lc = new Database.LeadConvert();
        lc.setLeadId(ld.Id);
        lc.setConvertedStatus('Qualified');
        Database.LeadConvertResult lcr = Database.convertLead(lc);
        
        Test.stopTest();
        
        Lead ld2 = [SELECT Id, ConvertedOpportunityId FROM Lead WHERE Id = :ld.Id];

        System.assert(lcr.isSuccess());

        Portal_Referral__c referral = [SELECT Id, Lead__c, Status__c, Detail__c,
                First_Name__c, Last_Name__c, Street__c, City__c, State__c, Zip__c, 
                Email__c, Account__c, Phone__c, Portal_Payment_Plan__c
            FROM Portal_Referral__c
            WHERE Opportunity__c = :ld2.ConvertedOpportunityId];
            
        //System.assertEquals(ld.Id, referral.Lead__c);
        System.assertEquals(ld.FirstName, referral.First_Name__c);
        System.assertEquals(ld.LastName, referral.Last_Name__c);
        System.assertEquals(ld.Street, referral.Street__c);
        System.assertEquals(ld.City, referral.City__c);
        System.assertEquals(ld.State, referral.State__c);
        System.assertEquals(ld.PostalCode, referral.Zip__c);
        System.assertEquals(ld.Phone, referral.Phone__c);
        System.assertEquals(ld.Email, referral.Email__c);
        System.assertEquals(a.Id, referral.Account__c);
        System.assertEquals(plan.Id, referral.Portal_Payment_Plan__c);
            
        System.assertEquals(PortalReferralStatus.QUALIFIED_STATUS, referral.Status__c);
        System.assertEquals('Evaluation in Progress', referral.Detail__c);      
        
    }
    
    public static Portal_Referral__c createPortalReferral() {
        
        Account a = new Account(Name = 'Test');
        insert a;
        
        Contact c = new Contact(
            AccountId = a.Id,
            LastName = 'Test'
        );
        insert c;

        Portal_Referral__c referral = new Portal_Referral__c (
            First_Name__c = 'Test',
            Last_Name__c = 'Referral',
            Account__c = a.Id,
            Referred_By__c = c.Id,
            City__c = 'Test City',
            Status__c = PortalReferralStatus.OPEN_STATUS,
            Detail__c = 'New'
        );
        insert referral;
        
        Lead ld = new Lead(
            FirstName = referral.First_Name__c,
            LastName = referral.Last_Name__c,
            Company = referral.Last_Name__c + ', ' + referral.First_Name__c,
            Referring_Account__c = a.Id,
            Method_of_Contact__c = 'Referral', 
            LeadSource = 'Partner Referral',
            Lead_Source_Detail__c = 'Professional',
            Street = '123 Ocean Dr',
            City= 'Wayne',
            State = 'PA',
            PostalCode = '12345',
            County__c = 'Chester',
            Site_Type__c = 'Residential'
            //Lead_Source_Detail_2__c = 'Channel',
            //Lead_Source_Detail_4__c = 'Astrum Solar Connect'
        );
        insert ld;
        
        referral.Lead__c = ld.Id;
        update referral;
        
        return referral;
        
    } 

}