src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Accounting_ID__c</fullName>
        <description>Reference Number For Accounting System</description>
        <displayFormat>ACCT-{00000000}</displayFormat>
        <inlineHelpText>Reference Number For Accounting System</inlineHelpText>
        <label>Accounting ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>JobCount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of Jobs</description>
        <inlineHelpText>Number of Jobs</inlineHelpText>
        <label>JobCount</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Applied_Incentive_Offer__c.object
<CustomObject>
    <fields>
        <fullName>Astrum_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Astrum Contract</label>
        <referenceTo>Astrum_Contract__c</referenceTo>
        <relationshipLabel>Applied Incentive Offers</relationshipLabel>
        <relationshipName>Applied_Incentive_Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>SCRB_SalesOrder__c</referenceTo>
        <relationshipLabel>Applied Incentive Offers</relationshipLabel>
        <relationshipName>Applied_Incentive_Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Applied Incentive Offer</label>
    <nameField>
        <label>Applied Incentive Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applied Incentive Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Applied_Price_Adjustment__c.object
<CustomObject>
    <fields>
        <fullName>Astrum_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Astrum Contract</label>
        <referenceTo>Astrum_Contract__c</referenceTo>
        <relationshipLabel>Applied Price Adjustments</relationshipLabel>
        <relationshipName>Applied_Price_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>SCRB_SalesOrder__c</referenceTo>
        <relationshipLabel>Applied Price Adjustments</relationshipLabel>
        <relationshipName>Applied_Price_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Applied Price Adjustment</label>
    <nameField>
        <label>Applied Price Adjustment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applied Price Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Applied_SREC_Contract_Offer__c.object
<CustomObject>
    <fields>
        <fullName>Astrum_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Astrum Contract</label>
        <referenceTo>Astrum_Contract__c</referenceTo>
        <relationshipLabel>Applied SREC Contract Offers</relationshipLabel>
        <relationshipName>Applied_SREC_Contract_Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>SCRB_SalesOrder__c</referenceTo>
        <relationshipLabel>Applied SREC Contract Offers</relationshipLabel>
        <relationshipName>Applied_SREC_Contract_Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Applied SREC Contract Offer</label>
    <nameField>
        <label>Applied SREC Contract Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applied SREC Contract Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Astrum_Contract__c.object
<CustomObject>
    <description>Contract object to facilitate Conga Contracts</description>
    <fields>
        <fullName>Sighten_Signing_Status__c</fullName>
        <label>Sighten Signing Status</label>
        <picklist>
            <picklistValues>
                <fullName>NOT SIGHTEN</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>NOT SENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SIGNED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DOWNLOADED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ERROR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Astrum Contract</label>
    <nameField>
        <displayFormat>AC-{MM}-{DD}-{YY}-{0000}</displayFormat>
        <label>Astrum Contracts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Astrum Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <recordTypes>
        <fullName>Sales</fullName>
        <active>true</active>
        <description>Standard Sales Contract</description>
        <label>Sales</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone1_Project__c.object
<CustomObject>
    <description>AstrumPM - A solar installation project.  A project can have many milestones.</description>
    <fields>
        <fullName>Changed_By_Sales__c</fullName>
        <description>Has The Sales Order For This Project Been Changed By Sales?</description>
        <formula>IF( Sales_Order__r.Changed_By_Sales__c,&apos;YES&apos;,&apos;NO&apos;)</formula>
        <inlineHelpText>Has The Sales Order For This Project Been Changed By Sales?</inlineHelpText>
        <label>Changed By Sales</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <formula>HYPERLINK( &quot;/&quot;+Sales_Order__r.OpportunityId__r.Property__r.Id  ,  Sales_Order__r.OpportunityId__r.Property__r.Name  )</formula>
        <label>Property</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Changed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The Sales Order For This Project Was Changed By Sales After Approval</description>
        <inlineHelpText>The Sales Order For This Project Was Changed By Sales After Approval</inlineHelpText>
        <label>Sales Order Changed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>SCRB_SalesOrder__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Astrum_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Astrum Contract</label>
        <referenceTo>Astrum_Contract__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Property__c.Property_Owner__r.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Design__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>System Design</label>
        <referenceTo>System_Design__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <description>AstrumPM/AstrumCRM - Each account can have one or more properties.  A property is defined by its street address.</description>
    <label>Property</label>
    <nameField>
        <label>Property Address 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SCRB_SalesOrder__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The SalesOrder object is the result of a Closed Won Opportunity and handles the hand off from the sales team to the operations team.</description>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>R00N300000011q88EAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Astrum_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Astrum Contract</label>
        <referenceTo>Astrum_Contract__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Changed_By_Sales__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Change Alert -- After Sales Manager Approval This Sales Order Has Been Re-Synced With Opportunity At Least Once</description>
        <inlineHelpText>Change Alert -- After Sales Manager Approval This Sales Order Has Been Re-Synced With Opportunity At Least Once</inlineHelpText>
        <label>Changed By Sales</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Commission_System_Price__c</fullName>
        <label>Commission System Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contract_Admin__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Admin</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Orders4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SCRB_SalesOrderLineItem__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The SalesOrderLineItem object can contains the product line items for a sales order.</description>
    <fields>
        <fullName>SalesOrderId__c</fullName>
        <label>Sales Order ID</label>
        <referenceTo>SCRB_SalesOrder__c</referenceTo>
        <relationshipLabel>Sales Order Items</relationshipLabel>
        <relationshipName>Sales_Order_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sales Order Item</label>
    <nameField>
        <label>Item Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Senior_Project_Compliance_Member__c.object
<CustomObject>
    <fields>
        <fullName>Date_Last_SO_Assigned__c</fullName>
        <description>Date the user was last assigned to a Sales Order</description>
        <label>Date Last SO Assigned</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Senior_Project_Compliance_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Senior Project Compliance Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Senior Project Compliance Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/System_Design__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The Solar System Design.  Each Property can have one or more System Designs created as the result of a site Survey and the discovery of Install Locations.  Each System Design is made up of one or more System Design Arrays.</description>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>System Designs</relationshipLabel>
        <relationshipName>System_Designs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>System Design</label>
    <nameField>
        <displayFormat>SD-{0}</displayFormat>
        <label>System Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Designs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SalesOrderController.cls
/*
* MODIFICATION HISTORY
*  03/29/15  DK  Added support for optional Attachment ID parameter
*  06/16/15  PB  FPO Calculate and update costprojections
*  08/05/15  DK  Populate new fields that were created for CPQ-224.
*  09/09/15  DK  Calculate Commission_System_Price__c for CPQ-122.
*  10/07/15  PB  SO Apv Process - capture sold system design 
*/
global with sharing class SalesOrderController {
    
    public Account account {get; private set;}
    public Opportunity opportunity {get; private set;}
    public Property__c property {get; private set;}
    public SCRB_SalesOrder__c order {get; private set;}
    public OpportunityLineItem oppLineItem {get; private set;}
    public SCRB_SalesOrderLineItem__c[] salesOrderLineItems {get; private set;}
    public SCRB_SalesOrderLineItem__c salesOrderLineItem {get; private set;}
    public List<SCRB_SalesOrderLineItem__c> lineItems= new List<SCRB_SalesOrderLineItem__c>();
    public System_Design__c sysdes {get; private set;}
    private integer itemCount=0;
    
    private PriceBookEntry pbEntry;
    
    public Id soId;
        //Id accountId=ApexPages.currentPage().getParameters().get('aId');
    public Id oppId;
    

	webservice static void syncToOpp(String soId, String oppId){
		
		System.Debug('In SalesOrderController : syncToOpp --> ' + soId + '  oppId --> ' + oppId );
		Opportunity opportunity = SalesOrder_Utilitity.retrieveOppById(oppId);
		SCRB_SalesOrder__c order = SalesOrder_Utilitity.buildSalesOrderFromOpportunity(opportunity, soId);
		Milestone1_Project__c[] projects = [Select Sales_Order_Changed__c From Milestone1_Project__c Where Sales_Order__c=:soId];

		if(order.Changed_By_Sales__c == true && projects.size()>0){
			for(Milestone1_Project__c project:projects){
				project.Sales_Order_Changed__c=true;
				update(project);			
			}
		}
		SalesOrder_Utilitity.removeSOLineItems(order);
		List<SCRB_SalesOrderLineItem__c> salesOrderLineItems = SalesOrder_Utilitity.createSOLineItems(order, opportunity);
		update(order);
		upsert(salesOrderLineItems);

        //calculate and update cost projections
        CostProjectionProcessor.updateRtskCstProjections(order.Id);
	} 	
    
    public SalesOrderController() {
               
        Boolean ShowPartner=false;  
        soId = ApexPages.currentPage().getParameters().get('id');
        //Id accountId=ApexPages.currentPage().getParameters().get('aId');
        String oppId = ApexPages.currentPage().getParameters().get('oId');
		
		opportunity = SalesOrder_Utilitity.retrieveOppById(oppId);
		order = SalesOrder_Utilitity.buildSalesOrderFromOpportunity(opportunity, soId);
		salesOrderLineItems = SalesOrder_Utilitity.createSOLineItems(order, opportunity);
		
		account = [SELECT  
					a.name, 
                	a.Accounting_ID__c, 
                	a.JobCount__c,       
                    a.accountnumber, 
                    a.billingstreet, 
                    a.BillingCity, 
                    a.BillingState, 
                    a.BillingPostalCode, 
                    a.BillingCountry, 
                    a.ShippingStreet, 
                    a.ShippingCity, 
                    a.ShippingState, 
                    a.ShippingPostalCode, 
                    a.ShippingCountry, 
                    a.phone, 
                    a.fax 
		from Account a Where a.Id = :order.AccountId__c];
		
        //System.Debug('Finished Page Load');
	}
             
    //Returns the user back to the opportunities page this was launched from
    public PageReference cancel(){
        return (new ApexPages.StandardController(opportunity)).view();
    }

    //saves order and child orders
    public PageReference save() {
		System.Debug('Entering save() in SalesOrderController');
        
        try {
			SalesOrder_Utilitity.CreateJobId(account, opportunity, order);

            //SO Apv Process - Automated assignment of SO
            try{
                Senior_Project_Compliance_Member__c complianceSpecialist = [SELECT User__c FROM Senior_Project_Compliance_Member__c ORDER BY Date_Last_SO_Assigned__c ASC LIMIT 1];
                order.Contract_Admin__c = complianceSpecialist.User__c;

                complianceSpecialist.Date_Last_SO_Assigned__c = Datetime.now();
                update complianceSpecialist;

            }catch(QueryException qe){}
            
			insert order;
     		System.Debug('New Sales Order: ' + order.id);
     		for (SCRB_SalesOrderLineItem__c li: salesOrderLineItems){
         		li.SalesOrderId__c = order.id;                   
     		}
     		
     		insert salesOrderLineItems;

            //--- Update the "Applied" junction objects [CPQ-818] ---//
            if (order.Astrum_Contract__c != null){
                Applied_Price_Adjustment__c[] appliedPriceAdjs = [SELECT Sales_Order__c FROM Applied_Price_Adjustment__c WHERE Astrum_Contract__c = :order.Astrum_Contract__c];
                Applied_Incentive_Offer__c[] appliedIncOffers = [SELECT Sales_Order__c FROM Applied_Incentive_Offer__c WHERE Astrum_Contract__c = :order.Astrum_Contract__c];
                Applied_SREC_Contract_Offer__c[] appliedSrecOffers = [SELECT Sales_Order__c FROM Applied_SREC_Contract_Offer__c WHERE Astrum_Contract__c = :order.Astrum_Contract__c];
                //Each query should only return one record, but bulkify the handling to be safe
                for (Applied_Price_Adjustment__c apa : appliedPriceAdjs)
                    apa.Sales_Order__c = order.ID;
                for (Applied_Incentive_Offer__c aio : appliedIncOffers)
                    aio.Sales_Order__c = order.ID;
                for (Applied_SREC_Contract_Offer__c asco : appliedSrecOffers)
                    asco.Sales_Order__c = order.ID;
                update appliedPriceAdjs;
                update appliedIncOffers;
                update appliedSrecOffers;
            }
     		
     		//If the Opportunity Stage is not 'Closed Won' then update it
			if (Opportunity.StageName != 'Closed - Won'){
         		Opportunity.StageName = 'Closed - Won';
				update Opportunity;
            }

            String signedContractPdfID = ApexPages.currentPage().getParameters().get('attchID');    //DK 3-29-15
            if (String.isNotBlank(signedContractPdfID)){
                //The CloseContract VF page sent us a Contract Attachment that needs to be cloned onto the new Sales Order
                try {
                    Attachment existingPDF = [SELECT Name, Body FROM Attachment WHERE ID = :signedContractPdfID LIMIT 1];
                    Attachment newPDF = new Attachment(Name = existingPDF.Name, ContentType = 'application/pdf', Body = existingPDF.Body, ParentID = order.ID);
                    delete existingPDF;
                    insert newPDF;
                } catch (Exception e){
                    System.debug('Attachment handling failed: ' + e.getStackTraceString());
                }
            }

            // Check for Sighten External Contract
            try{
                List<Astrum_Contract__c> contracts = [SELECT Id, Sighten_Signing_Status__c FROM Astrum_Contract__c WHERE Id = :opportunity.Astrum_Contract__c LIMIT 2];
                if(contracts.size() == 1){
                    Id contractId = contracts[0].Id;

                    List<Attachment> attachmentsToInsert = new List<Attachment>();
                    List<Attachment> attachments = [SELECT Name, Body, ContentType FROM Attachment WHERE ParentId = :contractId AND Name LIKE '%_ext_Signed%' ORDER BY CreatedDate DESC LIMIT 1];
                    for(Attachment att : attachments){
                        Attachment newAtt = new Attachment();
                        newAtt.Name = att.Name;
                        newAtt.Body = att.Body;
                        newAtt.ContentType = att.ContentType;
                        newAtt.ParentId = order.Id;
                        //Attachment newAtt = att.clone();
                        //newAtt.ParentId = order.Id;
                        attachmentsToInsert.add(newAtt);
                    }
                    insert attachmentsToInsert;
                } else {
                    System.debug('**SZ: No contract could be found based on the opportunity.');
                    return null;
                }
            } catch(Exception e){
                System.debug('Update Exception --> ' + e);
                ApexPages.addMessages(e);
                return null;
            }

		} catch(System.DMLException e) {
    		System.debug('Update Exception --> ' + e);
    		ApexPages.addMessages(e);
			return null;
		}         
                     
        //  After Save, navigate to the default view page:  
        return (new ApexPages.StandardController(order)).view();
 	}
  

    public PageReference loadHelpPage(){
        PageReference pg = new PageReference('/apex/CreateSalesOrderHelp');
        return pg;
    }

}