src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Portal_Payment_Plan__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Portal Payment Plan</label>
        <referenceTo>Portal_Payment_Plan__c</referenceTo>
        <relationshipLabel>Referring Companies</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Utility_Company_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Company Master</label>
        <referenceTo>Utility_Company_master__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Company</label>
        <referenceTo>Utility_Company__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Partner_Landing_Page__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Page_Template__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Page Template</label>
        <referenceTo>Partner_Page_Template__c</referenceTo>
        <relationshipName>Partner_Landing_Pages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Partner / Employee Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Landing Pages</relationshipLabel>
        <relationshipName>Partner_Landing_Pages</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Display_Name__c</fullName>
        <inlineHelpText>How the partner or employee&apos;s name should appear on the landing page</inlineHelpText>
        <label>Partner / Employee Display Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portal_Site__c</fullName>
        <label>Portal Site</label>
        <picklist>
            <picklistValues>
                <fullName>Landing Page Site (go.astrumsolar.com)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner Portal Site (partners.astrumsolar.com)</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Site_Url__c</fullName>
        <description>The URL to display in the portal (e.g., http://partners.astrumsolar.com/partner-xyz)</description>
        <externalId>true</externalId>
        <label>Site Url</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Landing Page</label>
    <nameField>
        <displayFormat>PAGE-{00000}</displayFormat>
        <label>Page ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Landing Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Partner_Page_Template__c.object
<CustomObject>
    <description>Landing Page templates</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Portal__c</fullName>
        <label>Portal</label>
        <picklist>
            <picklistValues>
                <fullName>Landing Page Site</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner Portal Site</fullName>
                <default>true</default>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VisualForce_Page__c</fullName>
        <description>Name of VisualForce Page (IT Setting)</description>
        <label>VisualForce Page</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Landing Page Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Landing Page Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Portal_Payment_Plan__c.object
<CustomObject>
    <fields>
        <fullName>Per_Referral_Fee__c</fullName>
        <inlineHelpText>Amount o</inlineHelpText>
        <label>Per Referral Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Per_Referral_Maximum_Number__c</fullName>
        <inlineHelpText>Maximum number of referrals with per referral fee</inlineHelpText>
        <label>Per Referral Maximum Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stop_Per_Referral_After_First_Sale__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Stop Per Referral After First Sale</label>
        <type>Checkbox</type>
    </fields>
    <label>Portal Payment Plan</label>
    <nameField>
        <label>Portal Payment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Payment Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Portal_Referral__c.object
<CustomObject>
    <description>Referrals from the Partner Program website</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Referring Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Portal Referrals</relationshipLabel>
        <relationshipName>Portal_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City for referral</description>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of referral</description>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of referral</description>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Portal_Payment_Plan__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Portal Payment Plan</label>
        <referenceTo>Portal_Payment_Plan__c</referenceTo>
        <relationshipLabel>Portal Referrals</relationshipLabel>
        <relationshipName>Portal_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>Street of Referral</description>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <label>Portal Referral</label>
    <nameField>
        <displayFormat>REF-{000000}</displayFormat>
        <label>Portal Referral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility_Company__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - Each Utility Service is attached to a single Utility Company.</description>
    <fields>
        <fullName>Externally_Available__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Whether the utility company should appear in lead forms as a selection option</inlineHelpText>
        <label>Externally Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State_Serviced__c</fullName>
        <label>State Serviced</label>
        <picklist>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Utility_Company_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Company Master</label>
        <referenceTo>Utility_Company_master__c</referenceTo>
        <relationshipLabel>Utility Rate Codes</relationshipLabel>
        <relationshipName>Utility_Rate_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Rate Code</label>
    <nameField>
        <label>Utility Rate Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Rate Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility_Company_master__c.object
<CustomObject>
    <description>Utility Company (distinct from Utility Rate Code)</description>
    <fields>
        <fullName>Externally_Available__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Externally Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State_Serviced__c</fullName>
        <label>State Serviced</label>
        <picklist>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Utility Company</label>
    <nameField>
        <label>Utility Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PartnerLandingPageTest.cls
/* FILE: PartnerLandingPageTest.cls
 * AUTHOR: Tino Mattheou
 * DATE: January 14, 2013
 * PURPOSE: Test class for PartnerLandingPageController
 * MODIFICATION HISTORY:
 *    10/27/14  DK  Added a Utility_Company_master__c insertion in order to populate Utility Rate Code's State_Serviced__c formula field.
 * 06/09/2015 PB  - SFS 303 Changed Utility to derive from Utility_Company_Master__c rather than Utility_Company__c 
 */
 
@isTest
public class PartnerLandingPageTest {


    static testMethod void landingPage_submit_added() {
        
        //create portal account and set payment plan
        Portal_Payment_Plan__c plan = new Portal_Payment_Plan__c(
            Per_Referral_Fee__c = 25,
            Per_Referral_Maximum_Number__c = 40,
            Stop_Per_Referral_After_First_Sale__c = true
        );
        insert plan;

        Account partner = new Account (
            Name = 'Test Partner',
            Portal_Payment_Plan__c = plan.Id
        );
        insert partner;
        
        Partner_Page_Template__c template = new Partner_Page_Template__c (
            Name = 'Test Template', 
            VisualForce_Page__c = 'PartnerLandingTemplate1',
            Portal__c = 'Partner Portal Site',
            Active__c = true
        );
        insert template;
        
        Partner_Landing_Page__c landingPage = new Partner_Landing_Page__c (
            Partner_Account__c = partner.Id,
            Portal_Site__c = 'Partner Portal Site (partners.astrumsolar.com)',
            Partner_Display_Name__c = 'Test Partner Inc',
            Active__c = true,
            Site_Url__c = 'some-test-link-2x9483',
            Page_Template__c = template.Id
        );
        insert landingPage;
        
        Attachment logo = new Attachment(
            ParentId = landingPage.Id,
            Name = 'test.jpg',
            ContentType = 'image/jpg',
            Body = Blob.valueOf('image file'),
            Description = 'Logo'
        );
        insert logo;
        
        Utility_Company_Master__c utilMaster = new Utility_Company_Master__c(Name = 'Test Utility Company', State_Serviced__c = 'PA', Externally_Available__c = true);
        insert utilMaster;
        
        Utility_Company__c utility = new Utility_Company__c (
            Utility_Company_Master__c = utilMaster.ID,
            Name = 'Test Utility'
            //,State_Serviced__c = 'PA',
            //Externally_Available__c = true
        );
        insert utility;
        
        User siteGuest = [SELECT Id FROM User WHERE Name = 'Partner Portal Site Site Guest User'];
        
        Test.startTest();       
        
        System.runAs(siteGuest) {
            
            PageReference pr = Page.PartnerLandingPage;
            pr.getParameters().put('templateId', landingPage.Id);
            Test.setCurrentPage(pr);
            PartnerLandingPageController controller = new PartnerLandingPageController();
            
            System.assertEquals('Test Partner Inc', controller.partnerName);
            System.assertEquals(logo.Id, controller.partnerLogoId);
            
            List<SelectOption> states = controller.states;
            
            controller.newState = 'PA';
            controller.stateChanged();
            List<SelectOption> utilities = controller.getUtilities();
            System.assertEquals(2, utilities.size());
            
            Map<String,String> params = pr.getParameters();
            params.put('fname', 'Test');
            params.put('lname', 'Customer');
            params.put('email', 'test123@test.com');
            params.put('phone', '(215) 555-1212');
            params.put('street', '1 Oak St');
            params.put('city', 'Norristown');
            params.put('state', 'PA');
            params.put('zip', '19403');
            params.put('updates', 'yes');
            params.put('bill', '98.34');
            params.put('utility', utilities[1].getValue());
            
            controller.submit();

            System.assertEquals(false, ApexPages.hasMessages(), String.valueOf(ApexPages.getMessages()));
            
            System.assertEquals(true, controller.submitted);
            
        }
        
        Test.stopTest();
        
        Portal_Referral__c referral = 
            [SELECT Id, First_Name__c, Last_Name__c,
                Email__c, Phone__c, Street__c, City__c, State__c, Zip__c, Account__c, 
                Lead__r.Email_Marketing_Opt_In__c, Lead__r.Monthly_Electric_Bill__c,
                Lead__r.Utility_Company__c, Lead__r.Referring_Account__c, Lead__r.Utility_Company_Master__c
            FROM Portal_Referral__c];
            
        System.assertEquals('Test', referral.First_Name__c);
        System.assertEquals('Customer', referral.Last_Name__c);
        System.assertEquals('test123@test.com', referral.Email__c);
        System.assertEquals('1 Oak St', referral.Street__c);
        System.assertEquals('Norristown', referral.City__c);
        System.assertEquals('PA', referral.State__c);
        System.assertEquals('19403', referral.Zip__c);
        System.assertEquals(true, referral.Lead__r.Email_Marketing_Opt_In__c);
        System.assertEquals(98, referral.Lead__r.Monthly_Electric_Bill__c);
        //System.assertEquals(utility.Id, referral.Lead__r.Utility_Company__c);
        System.assertEquals(utilMaster.Id, referral.Lead__r.Utility_Company_Master__c);
        System.assertEquals(partner.Id, referral.Account__c);
        System.assertEquals(partner.Id, referral.Lead__r.Referring_Account__c);
        
    }
}