src/objects/Annual_Production__c.object
<CustomObject>
    <fields>
        <fullName>April_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>April Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>April_Production_Guarantee_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>April Production Guarantee (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>April_Projected_SRECs__c</fullName>
        <defaultValue>0</defaultValue>
        <label>April Projected SRECs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>April_SRECs_Generated__c</fullName>
        <defaultValue>0</defaultValue>
        <label>April SRECs Generated</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>August_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>August Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>August_Production_Guarantee_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>August Production Guarantee (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>August_Projected_SRECs__c</fullName>
        <defaultValue>0</defaultValue>
        <label>August Projected SRECs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>December_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>December Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>December_Production_Guarantee_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>December Production Guarantee (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>December_Projected_SRECs__c</fullName>
        <defaultValue>0</defaultValue>
        <label>December Projected SRECs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>December_SRECs_Generated__c</fullName>
        <defaultValue>0</defaultValue>
        <label>December SRECs Generated</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>February_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>February Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>February_Production_Guarantee_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>February Production Guarantee (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>February_Projected_SRECs__c</fullName>
        <defaultValue>0</defaultValue>
        <label>February Projected SRECs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>February_SRECs_Generated__c</fullName>
        <defaultValue>0</defaultValue>
        <label>February SRECs Generated</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Installed_System__c</fullName>
        <label>Installed System</label>
        <referenceTo>Installed_System__c</referenceTo>
        <relationshipLabel>Annual Production</relationshipLabel>
        <relationshipName>Annual_Production</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>January_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>January Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>January_Production_Guarantee_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>January Production Guarantee (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>January_Projected_SRECs__c</fullName>
        <defaultValue>0</defaultValue>
        <label>January Projected SRECs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>January_SRECs_Generated__c</fullName>
        <defaultValue>0</defaultValue>
        <label>January SRECs Generated</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>July_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>July Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>July_Production_Guarantee_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>July Production Guarantee (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>July_Projected_SRECs__c</fullName>
        <defaultValue>0</defaultValue>
        <label>July Projected SRECs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>June_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>June Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>June_Production_Guarantee_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>June Production Guarantee (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>June_Projected_SRECs__c</fullName>
        <defaultValue>0</defaultValue>
        <label>June Projected SRECs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>March_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>March Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>March_Production_Guarantee_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>March Production Guarantee (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>March_Projected_SRECs__c</fullName>
        <defaultValue>0</defaultValue>
        <label>March Projected SRECs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>March_SRECs_Generated__c</fullName>
        <defaultValue>0</defaultValue>
        <label>March SRECs Generated</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>May_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>May Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>May_Production_Guarantee_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>May Production Guarantee (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>May_Projected_SRECs__c</fullName>
        <defaultValue>0</defaultValue>
        <label>May Projected SRECs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>November_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>November Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>November_Production_Guarantee_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>November Production Guarantee (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>November_Projected_SRECs__c</fullName>
        <defaultValue>0</defaultValue>
        <label>November Projected SRECs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>November_SRECs_Generated__c</fullName>
        <defaultValue>0</defaultValue>
        <label>November SRECs Generated</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>October_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>October Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>October_Production_Guarantee_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>October Production Guarantee (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>October_Projected_SRECs__c</fullName>
        <defaultValue>0</defaultValue>
        <label>October Projected SRECs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>October_SRECs_Generated__c</fullName>
        <defaultValue>0</defaultValue>
        <label>October SRECs Generated</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>September_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>September Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>September_Production_Guarantee_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>September Production Guarantee (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>September_Projected_SRECs__c</fullName>
        <defaultValue>0</defaultValue>
        <label>September Projected SRECs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Annual Production</label>
    <nameField>
        <displayFormat>AP-{000000000}</displayFormat>
        <label>Annual Production Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Production</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Installed_System__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Installed Systems</relationshipLabel>
        <relationshipName>Installed_Systems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>April_Daily_Peak_Sun_Hours__c</fullName>
        <label>April Daily Peak Sun Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>August_Daily_Peak_Sun_Hours__c</fullName>
        <label>August Daily Peak Sun Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>December_Daily_Peak_Sun_Hours__c</fullName>
        <label>December Daily Peak Sun Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>February_Daily_Peak_Sun_Hours__c</fullName>
        <label>February Daily Peak Sun Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Generation_Start_Date__c</fullName>
        <label>Generation Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>January_Daily_Peak_Sun_Hours__c</fullName>
        <label>January Daily Peak Sun Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>July_Daily_Peak_Sun_Hours__c</fullName>
        <label>July Daily Peak Sun Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>June_Daily_Peak_Sun_Hours__c</fullName>
        <label>June Daily Peak Sun Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>March_Daily_Peak_Sun_Hours__c</fullName>
        <label>March Daily Peak Sun Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>May_Daily_Peak_Sun_Hours__c</fullName>
        <label>May Daily Peak Sun Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>November_Daily_Peak_Sun_Hours__c</fullName>
        <label>November Daily Peak Sun Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>October_Daily_Peak_Sun_Hours__c</fullName>
        <label>October Daily Peak Sun Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>September_Daily_Peak_Sun_Hours__c</fullName>
        <label>September Daily Peak Sun Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Installed System</label>
    <nameField>
        <displayFormat>SYS-{000000}</displayFormat>
        <label>Installed System Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installed Systems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestInstalledSystemController.cls
//07/09/2012 TCM - comment out due to Heap Limit issue
//07/11/2012 TCM - add code coverage for controller
@isTest
private class TestInstalledSystemController {
    
    private static testmethod void unitTest() {
    	
        Account acc = new Account(
            Name = 'Test'
        );
        insert acc;
        
        Installed_System__c installedSysObj = new Installed_System__c(
            Account__c = acc.id,
            Generation_Start_Date__c = Date.newInstance(2010,10,1),
            January_Daily_Peak_Sun_Hours__c = 5,
            February_Daily_Peak_Sun_Hours__c = 5,
            March_Daily_Peak_Sun_Hours__c = 5,
            April_Daily_Peak_Sun_Hours__c = 5,
            May_Daily_Peak_Sun_Hours__c = 5,
            June_Daily_Peak_Sun_Hours__c = 5,
            July_Daily_Peak_Sun_Hours__c = 5,
            August_Daily_Peak_Sun_Hours__c = 5,
            September_Daily_Peak_Sun_Hours__c = 5,
            October_Daily_Peak_Sun_Hours__c = 5,
            November_Daily_Peak_Sun_Hours__c = 5,
            December_Daily_Peak_Sun_Hours__c = 5
        );
        insert installedSysObj;

        Annual_Production__c annProd = new Annual_Production__c(
            Installed_System__c = installedSysObj.id,
            Year__c = 2010,

            October_Actual_Production_kWh__c = 5,
            November_Actual_Production_kWh__c = 5,
            December_Actual_Production_kWh__c = 5,
            
            October_Production_Guarantee_kWh__c = 5,
            November_Production_Guarantee_kWh__c = 5,
            December_Production_Guarantee_kWh__c = 5,
            
			October_Projected_SRECs__c = 1, 
			November_Projected_SRECs__c = 1, 
			December_Projected_SRECs__c = 1,
			
			October_SRECs_Generated__c = 1, 
			November_SRECs_Generated__c = 1, 
			December_SRECs_Generated__c = 1         
		);
        insert annProd;
        
        annProd = new Annual_Production__c (
            Installed_System__c = installedSysObj.id,
            Year__c = 2011,

            January_Actual_Production_kWh__c = 5,
            February_Actual_Production_kWh__c = 5,
            March_Actual_Production_kWh__c = 5,
            April_Actual_Production_kWh__c = 5,
            May_Actual_Production_kWh__c = 5,
            June_Actual_Production_kWh__c = 5,
            July_Actual_Production_kWh__c = 5,
            August_Actual_Production_kWh__c = 5,
            September_Actual_Production_kWh__c = 5,
            October_Actual_Production_kWh__c = 5,
            November_Actual_Production_kWh__c = 5,
            December_Actual_Production_kWh__c = 5,
            
            January_Production_Guarantee_kWh__c = 5,
            February_Production_Guarantee_kWh__c = 5,
            March_Production_Guarantee_kWh__c = 5,
            April_Production_Guarantee_kWh__c = 5,
            May_Production_Guarantee_kWh__c = 5,
            June_Production_Guarantee_kWh__c = 5,
            July_Production_Guarantee_kWh__c = 5,
            August_Production_Guarantee_kWh__c = 5,
            September_Production_Guarantee_kWh__c = 5,
            October_Production_Guarantee_kWh__c = 5,
            November_Production_Guarantee_kWh__c = 5,
            December_Production_Guarantee_kWh__c = 5,

			January_Projected_SRECs__c = 1, 
			February_Projected_SRECs__c = 1, 
			March_Projected_SRECs__c = 1, 
			April_Projected_SRECs__c = 1, 
			May_Projected_SRECs__c = 1, 
            June_Projected_SRECs__c = 1, 
            July_Projected_SRECs__c = 1, 
            August_Projected_SRECs__c = 1, 
			September_Projected_SRECs__c = 1, 
			October_Projected_SRECs__c = 1, 
			November_Projected_SRECs__c = 1, 
			December_Projected_SRECs__c = 1,
			
			January_SRECs_Generated__c = 1, 
			February_SRECs_Generated__c = 1, 
			March_SRECs_Generated__c = 1, 
			April_SRECs_Generated__c = 1, 
			May_SRECs_Generated__c = 1, 
			June_SRECs_Generated__c = 1, 
			July_SRECs_Generated__c = 1, 
			August_SRECs_Generated__c = 1, 
			September_SRECs_Generated__c = 1, 
			October_SRECs_Generated__c = 1, 
			November_SRECs_Generated__c = 1, 
			December_SRECs_Generated__c = 1         
        );
        insert annProd;

        annProd = new Annual_Production__c (
            Installed_System__c = installedSysObj.id,
            Year__c = System.today().year(),

            January_Actual_Production_kWh__c = 5,
            February_Actual_Production_kWh__c = 5,
            March_Actual_Production_kWh__c = 5,
            April_Actual_Production_kWh__c = 5,
            May_Actual_Production_kWh__c = 5,
            June_Actual_Production_kWh__c = 5,
            July_Actual_Production_kWh__c = 5,
            August_Actual_Production_kWh__c = 5,
            September_Actual_Production_kWh__c = 5,
            October_Actual_Production_kWh__c = 5,
            November_Actual_Production_kWh__c = 5,
            December_Actual_Production_kWh__c = 5,
            
            January_Production_Guarantee_kWh__c = 5,
            February_Production_Guarantee_kWh__c = 5,
            March_Production_Guarantee_kWh__c = 5,
            April_Production_Guarantee_kWh__c = 5,
            May_Production_Guarantee_kWh__c = 5,
            June_Production_Guarantee_kWh__c = 5,
            July_Production_Guarantee_kWh__c = 5,
            August_Production_Guarantee_kWh__c = 5,
            September_Production_Guarantee_kWh__c = 5,
            October_Production_Guarantee_kWh__c = 5,
            November_Production_Guarantee_kWh__c = 5,
            December_Production_Guarantee_kWh__c = 5,

			January_Projected_SRECs__c = 1, 
			February_Projected_SRECs__c = 1, 
			March_Projected_SRECs__c = 1, 
			April_Projected_SRECs__c = 1, 
			May_Projected_SRECs__c = 1, 
            June_Projected_SRECs__c = 1, 
            July_Projected_SRECs__c = 1, 
            August_Projected_SRECs__c = 1, 
			September_Projected_SRECs__c = 1, 
			October_Projected_SRECs__c = 1, 
			November_Projected_SRECs__c = 1, 
			December_Projected_SRECs__c = 1,
			
			January_SRECs_Generated__c = 1, 
			February_SRECs_Generated__c = 1, 
			March_SRECs_Generated__c = 1, 
			April_SRECs_Generated__c = 1, 
			May_SRECs_Generated__c = 1, 
			June_SRECs_Generated__c = 1, 
			July_SRECs_Generated__c = 1, 
			August_SRECs_Generated__c = 1, 
			September_SRECs_Generated__c = 1, 
			October_SRECs_Generated__c = 1, 
			November_SRECs_Generated__c = 1, 
			December_SRECs_Generated__c = 1         
        );
        insert annProd;
        
        InstalledSystemController controller = new InstalledSystemController();
        controller.queryType = 'outer';
        controller.sortExpression = 'Account__c';
        controller.getSystemList();
        //controller.getSysGrntURL();
        
        System.assertEquals(1, controller.setCon.getResultSize());
        
        System.assertEquals(1, controller.totalPages);
        System.assertEquals(1, controller.pageList.size());
        System.assertEquals(1, controller.pageList[0]);
        
        //controller.getSRECChartURL();
        controller.getSortDirection();
        controller.viewData();
        //controller.getPiecChartURL();

		System.assertEquals('ASC', controller.getSortDirection());
        controller.sortExpression = 'Account__c';
		System.assertEquals('DESC', controller.getSortDirection());

        controller.changePage();
        
        InstalledSystemController.InstallWrapper wrapObj = new InstalledSystemController.InstallWrapper(installedSysObj);
		wrapObj.getFieldValue('Annual_Production_Guarantee_To_Date_kWh__c');
		wrapObj.getFieldValue('Annual_Production_Guarantee__c');
		wrapObj.getFieldValue('Annual_Production_To_Date_kWh__c');
		wrapObj.getFieldValue('Annual_Guarantee_vs_Actual_Prod_To_Date__c');
		wrapObj.getFieldValue('Expected_SRECs_To_Date__c');
		wrapObj.getFieldValue('Annual_SRECs_To_Date__c');
		wrapObj.getFieldValue('Projected_vs_Actual_SRECs_To_Date__c');
        
        //List<InstalledSystemController.InstallWrapper> unSortedList = new List<InstalledSystemController.InstallWrapper>();
        //unSortedList.add(new InstalledSystemController.InstallWrapper(installedSysObj));
        //objInstSystem.customSort(unSortedList, 'Annual_Production_Guarantee_To_Date_kWh__c', 'ASC');
        //objInstSystem.getStateChartURL();
    }
    
    
}