src/objects/Annual_Production__c.object
<CustomObject>
    <fields>
        <fullName>April_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>April Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>April_Production_Guarantee_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>April Production Guarantee (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>August_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>August Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>August_Production_Guarantee_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>August Production Guarantee (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>December_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>December Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>December_Production_Guarantee_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>December Production Guarantee (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>February_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>February Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>February_Production_Guarantee_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>February Production Guarantee (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Installed_System__c</fullName>
        <label>Installed System</label>
        <referenceTo>Installed_System__c</referenceTo>
        <relationshipLabel>Annual Production</relationshipLabel>
        <relationshipName>Annual_Production</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>January_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>January Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>January_Production_Guarantee_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>January Production Guarantee (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>January_Projected_SRECs__c</fullName>
        <defaultValue>0</defaultValue>
        <label>January Projected SRECs</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>July_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>July Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>July_Production_Guarantee_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>July Production Guarantee (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>June_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>June Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>June_Production_Guarantee_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>June Production Guarantee (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>March_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>March Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>March_Production_Guarantee_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>March Production Guarantee (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>May_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>May Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>May_Production_Guarantee_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>May Production Guarantee (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>November_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>November Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>November_Production_Guarantee_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>November Production Guarantee (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>October_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>October Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>October_Production_Guarantee_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>October Production Guarantee (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>September_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>September Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>September_Production_Guarantee_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>September Production Guarantee (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Annual Production</label>
    <nameField>
        <displayFormat>AP-{000000000}</displayFormat>
        <label>Annual Production Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Production</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Installed_System__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Installed Systems</relationshipLabel>
        <relationshipName>Installed_Systems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Generation_Start_Date__c</fullName>
        <label>Generation Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Installed Systems</relationshipLabel>
        <relationshipName>Installed_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Installed System</label>
    <nameField>
        <displayFormat>SYS-{000000}</displayFormat>
        <label>Installed System Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installed Systems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <description>AstrumPM/AstrumCRM - Each account can have one or more properties.  A property is defined by its street address.</description>
    <fields>
        <fullName>Property_City__c</fullName>
        <label>Property City</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_County__c</fullName>
        <label>Property County</label>
        <picklist>
            <controllingField>Property_State__c</controllingField>
            <picklistValues>
                <fullName>Accomack</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adams</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alameda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albemarle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alcona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alexandria City</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alger</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allegan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allegany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alleghany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allegheny</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alpena</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alpine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amador</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amelia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amherst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anne Arundel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antrim</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apache</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appomattox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arenac</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arlington</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armstrong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ashland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ashtabula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Athens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Atlantic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auglaize</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account that represents the Owner of this Building.  This may be a Family or a Business.</description>
        <label>Property Owner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>Property State</label>
        <picklist>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property_ZIP__c</fullName>
        <label>Property ZIP</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Address 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InstalledSystemsChartsTest.cls
/* FILE: InstalledSystemsChartsTest.cls
 * AUTHOR: Tino Mattheou
 * DATE: July 30, 2012
 * PURPOSE: Test class for InstalledSystemsCharts component and InstalledSystemsChartsController
 * MODIFICATION HISTORY:
 * 08/23/2012 TCM - fix test due to changing BingMaps trigger to not perform callouts under test
 */
 
@isTest
private class InstalledSystemsChartsTest {

    static testMethod void twoYearsProdData_getGuarVsActual() {

		Installed_System__c installedSystem = createInstalledSystem();
		
        addAnnualProduction (installedSystem.Id, System.today().year());
        addAnnualProduction (installedSystem.Id, System.today().year() - 1);
        
        InstalledSystemsChartsController controller = new InstalledSystemsChartsController();
        
        Test.startTest();
        
        List<InstalledSystemsChartsController.GuaranteeData> guarVsActual = controller.getguarVsActual();
        
        Test.stopTest();
        
        Date workDate = System.today().toStartOfMonth().addYears(-1);
        InstalledSystemsChartsController.GuaranteeData dat;
        for (Integer i = 0; i < 12; i++) {
        	dat = guarVsActual[i];
        	System.assertEquals(workDate.month(), dat.guarantee);
        	System.assertEquals(workDate.month() / 2.0, dat.actual);
        	workDate = workDate.addMonths(1);
        }
        
        //srecs are accumulated
        System.assertEquals(13 * 6 * 2, guarVsActual[11].projSREC);
		System.assertEquals(13 * 6 * 3, guarVsActual[11].genSREC);
        
    }
    
    static testMethod void twoYearsPAProdData_getStateProd() {

		Installed_System__c installedSystem = createInstalledSystem();
		
        addAnnualProduction (installedSystem.Id, System.today().year());
        addAnnualProduction (installedSystem.Id, System.today().year() - 1);
        
        InstalledSystemsChartsController controller = new InstalledSystemsChartsController();
        
        Test.startTest();
        
        List<InstalledSystemsChartsController.StateProduction> stateProd = controller.getStateProd();
        
        Test.stopTest();
        
        //srecs are accumulated
        System.assertEquals('PA', stateProd[0].state);
        System.assertEquals(13 * 6, stateProd[0].guarantee);
		System.assertEquals(13 * 6 * 0.5, stateProd[0].actual);
        
    }
    
    static testMethod void threeSystems_getSystemOverview() {

		Installed_System__c installedSystem1 = createInstalledSystem(); //under
		Installed_System__c installedSystem2 = createInstalledSystem(); //over
		Installed_System__c installedSystem3 = createInstalledSystem(); //on target
		
		Annual_Production__c ap;
		//under (default)
        addAnnualProduction (installedSystem1.Id, System.today().year());
        addAnnualProduction (installedSystem1.Id, System.today().year() - 1);
        
        //over
        addAnnualProduction (installedSystem2.Id, System.today().year());
        ap = addAnnualProduction (installedSystem2.Id, System.today().year() - 1);
        ap.December_Actual_Production_kWh__c = 5000;
        update ap;
		
		//on target
        addAnnualProduction (installedSystem3.Id, System.today().year());
        ap = addAnnualProduction (installedSystem3.Id, System.today().year() - 1);
        ap.December_Actual_Production_kWh__c += 13 * 6 * 0.5;
        update ap;
        
        InstalledSystemsChartsController controller = new InstalledSystemsChartsController();
        
        Test.startTest();
        
        InstalledSystemsChartsController.SystemOverview overview = controller.getSystemOverview();
        
        Test.stopTest();
        
        System.assertEquals(1, overview.overProducing);
        System.assertEquals(1, overview.underProducing);
        System.assertEquals(1, overview.onTarget);
        
    }
    
    public static Installed_System__c createInstalledSystem () {
    	
        Account acct = new Account(
            Name = 'Test Account'
        );
        insert acct;
        
		Property__c property = new Property__c(
			Property_Owner__c = acct.Id,
			Name = '123 Oak St',
			Property_City__c = 'Test City',
			Property_State__c = 'PA',
			Property_Zip__c = '19403',
			Property_County__c = 'Test County'
		);
		insert property;
        
        Installed_System__c installedSystem = new Installed_System__c (
            Account__c = acct.Id,
            Property__c = property.Id,
            Generation_Start_Date__c = Date.newInstance(2010, 1, 1)
        );
        insert installedSystem;
        
        return installedSystem;    	
    }
    
    public static Annual_Production__c addAnnualProduction (Id installedSystemId, Integer year) {
    	Annual_Production__c prod = new Annual_Production__c (
    		Installed_System__c = installedSystemId,
    		Year__c = year,
			January_Production_Guarantee_kWh__c = 1,
			February_Production_Guarantee_kWh__c = 2,
			March_Production_Guarantee_kWh__c = 3,
			April_Production_Guarantee_kWh__c = 4, 
			May_Production_Guarantee_kWh__c = 5,
			June_Production_Guarantee_kWh__c = 6,
			July_Production_Guarantee_kWh__c = 7, 
			August_Production_Guarantee_kWh__c = 8, 
            September_Production_Guarantee_kWh__c = 9,
            October_Production_Guarantee_kWh__c = 10, 
            November_Production_Guarantee_kWh__c = 11, 
            December_Production_Guarantee_kWh__c = 12, 
            January_Actual_Production_kWh__c = 0.5, 
            February_Actual_Production_kWh__c = 1, 
            March_Actual_Production_kWh__c = 1.5, 
            April_Actual_Production_kWh__c = 2, 
            May_Actual_Production_kWh__c = 2.5, 
            June_Actual_Production_kWh__c = 3, 
            July_Actual_Production_kWh__c = 3.5,
            August_Actual_Production_kWh__c = 4,
            September_Actual_Production_kWh__c = 4.5, 
            October_Actual_Production_kWh__c = 5, 
            November_Actual_Production_kWh__c = 5.5, 
            December_Actual_Production_kWh__c = 6,
            January_Projected_SRECs__c = 2, 
			February_Projected_SRECs__c = 4, 
			March_Projected_SRECs__c = 6, 
			April_Projected_SRECs__c = 8, 
			May_Projected_SRECs__c = 10, 
			June_Projected_SRECs__c = 12, 
			July_Projected_SRECs__c = 14, 
			August_Projected_SRECs__c = 16, 
			September_Projected_SRECs__c = 18, 
			October_Projected_SRECs__c = 20, 
			November_Projected_SRECs__c = 22, 
			December_Projected_SRECs__c = 24,
			January_SRECs_Generated__c = 3, 
			February_SRECs_Generated__c = 6, 
			March_SRECs_Generated__c = 9, 
			April_SRECs_Generated__c = 12, 
			May_SRECs_Generated__c = 15, 
			June_SRECs_Generated__c = 18, 
			July_SRECs_Generated__c = 21, 
			August_SRECs_Generated__c = 24, 
			September_SRECs_Generated__c = 27, 
			October_SRECs_Generated__c = 30, 
			November_SRECs_Generated__c = 33, 
			December_SRECs_Generated__c = 36 
		);
		insert prod;
		
		return prod;
    } 
    
}