src/objects/Annual_Production__c.object
<CustomObject>
    <fields>
        <fullName>April_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>April Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>August_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>August Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>December_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>December Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>February_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>February Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Installed_System__c</fullName>
        <label>Installed System</label>
        <referenceTo>Installed_System__c</referenceTo>
        <relationshipLabel>Annual Production</relationshipLabel>
        <relationshipName>Annual_Production</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>January_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>January Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>January_Production_Guarantee_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>January Production Guarantee (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>July_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>July Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>June_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>June Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>March_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>March Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>May_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>May Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>November_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>November Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>October_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>October Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>September_Actual_Production_kWh__c</fullName>
        <defaultValue>0</defaultValue>
        <label>September Actual Production (kWh)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Annual Production</label>
    <nameField>
        <displayFormat>AP-{000000000}</displayFormat>
        <label>Annual Production Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Production</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Enphase_Alert__c.object
<CustomObject>
    <fields>
        <fullName>Installed_System__c</fullName>
        <label>Installed System</label>
        <referenceTo>Installed_System__c</referenceTo>
        <relationshipLabel>Enphase Alerts</relationshipLabel>
        <relationshipName>Enphase_Alerts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Enphase Alert</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Alert ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enphase Alerts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Installed_System__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Installed Systems</relationshipLabel>
        <relationshipName>Installed_Systems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>April_Daily_Peak_Sun_Hours__c</fullName>
        <label>April Daily Peak Sun Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>August_Daily_Peak_Sun_Hours__c</fullName>
        <label>August Daily Peak Sun Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>December_Daily_Peak_Sun_Hours__c</fullName>
        <label>December Daily Peak Sun Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>February_Daily_Peak_Sun_Hours__c</fullName>
        <label>February Daily Peak Sun Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Generation_Start_Date__c</fullName>
        <label>Generation Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Installation_Year__c</fullName>
        <formula>YEAR( Generation_Start_Date__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Installation Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>January_Daily_Peak_Sun_Hours__c</fullName>
        <label>January Daily Peak Sun Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>July_Daily_Peak_Sun_Hours__c</fullName>
        <label>July Daily Peak Sun Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>June_Daily_Peak_Sun_Hours__c</fullName>
        <label>June Daily Peak Sun Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>March_Daily_Peak_Sun_Hours__c</fullName>
        <label>March Daily Peak Sun Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>May_Daily_Peak_Sun_Hours__c</fullName>
        <label>May Daily Peak Sun Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>November_Daily_Peak_Sun_Hours__c</fullName>
        <label>November Daily Peak Sun Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>October_Daily_Peak_Sun_Hours__c</fullName>
        <label>October Daily Peak Sun Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Installed Systems</relationshipLabel>
        <relationshipName>Installed_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quoted_System_Design__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quoted System Design</label>
        <referenceTo>System_Design_Quote__c</referenceTo>
        <relationshipLabel>Installed Systems</relationshipLabel>
        <relationshipName>Installed_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>September_Daily_Peak_Sun_Hours__c</fullName>
        <label>September Daily Peak Sun Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Installed System</label>
    <nameField>
        <displayFormat>SYS-{000000}</displayFormat>
        <label>Installed System Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installed Systems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Monthly_Production__c.object
<CustomObject>
    <description>Stores Monthly Production data from Enphase, production guarantees, and GATS/GIS reported production</description>
    <fields>
        <fullName>Installed_System__c</fullName>
        <label>Installed System</label>
        <referenceTo>Installed_System__c</referenceTo>
        <relationshipLabel>Monthly Production</relationshipLabel>
        <relationshipName>Monthly_Production</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_of_Month__c</fullName>
        <label>Start of Month</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <formula>TEXT(YEAR(Start_of_Month__c))</formula>
        <label>Year</label>
        <type>Text</type>
    </fields>
    <label>Monthly Production</label>
    <nameField>
        <displayFormat>MP-{0000000}</displayFormat>
        <label>Monthly Production ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Production</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <description>AstrumPM/AstrumCRM - Each account can have one or more properties.  A property is defined by its street address.</description>
    <fields>
        <fullName>Optimal_Site_Quality_kWh_y_kW__c</fullName>
        <label>Optimal Site Quality (kWh/y/kW)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Address 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SREC_Certificate__c.object
<CustomObject>
    <description>SREC Certificate</description>
    <fields>
        <fullName>Account__c</fullName>
        <formula>SREC_Registry_Unit__r.Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Installed_System__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to related Installed System.</description>
        <inlineHelpText>Lookup to related Installed System.</inlineHelpText>
        <label>Installed System</label>
        <referenceTo>Installed_System__c</referenceTo>
        <relationshipLabel>SREC Certificates</relationshipLabel>
        <relationshipName>SREC_Certificates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SREC Certificate</label>
    <nameField>
        <displayFormat>SREC-CERTIFICATE-{0000000000}</displayFormat>
        <label>SREC Certificate Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SREC Certificates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/System_Design__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The Solar System Design.  Each Property can have one or more System Designs created as the result of a site Survey and the discovery of Install Locations.  Each System Design is made up of one or more System Design Arrays.</description>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>System Designs</relationshipLabel>
        <relationshipName>System_Designs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>System Design</label>
    <nameField>
        <displayFormat>SD-{0}</displayFormat>
        <label>System Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Designs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/System_Design_Item__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - System Design Item.  A collection of one or more System Design Products that are to be placed on a single Install Location.</description>
    <fields>
        <fullName>Property__c</fullName>
        <formula>System_Design_Array__r.System_Design__r.Property__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Design__c</fullName>
        <description>System Design Id</description>
        <formula>System_Design_Array__r.System_Design__r.Id</formula>
        <inlineHelpText>System Design Id</inlineHelpText>
        <label>System Design</label>
        <type>Text</type>
    </fields>
    <label>System Design Item</label>
    <nameField>
        <label>System Design Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Design Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/System_Design_Quote__c.object
<CustomObject>
    <description>AstrumCRM - System Design Quote.  Each System Design can have one or more System Design Quotes.  Each quote provides the sales consultant with the ability to adjust the negotiated price of the System Design based on the Calculated System Price.  Opportunities must choose a winning System Design Quote in order to close.</description>
    <fields>
        <fullName>System_Design__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>System Design</label>
        <referenceTo>System_Design__c</referenceTo>
        <relationshipLabel>System Design Quotes</relationshipLabel>
        <relationshipName>System_Design_Quotes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>System Design Quote</label>
    <nameField>
        <displayFormat>SDQ-{0}</displayFormat>
        <label>System Design Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Design Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_InstalledSystems_Detail.cls
//07/11/2012 TCM - add more test coverage
//10/24/2012 TCM - rewrite test coverage
@isTest
private class Test_InstalledSystems_Detail {
    
    static testMethod void testSysDesignItems() {

        Account customer = new Account(Name='Test Customer');
        insert customer;
        
        Property__c property = CreateAstrumPM2ProjectTest.createProperty(customer.Id, '123 Test St');
        property.Optimal_Site_Quality_kWh_y_kW__c = 1100;
        update property;
        
        System_Design__c sd = new System_Design__c(
            Property__c = property.Id
        );
        insert sd;
        
        System_Design_Quote__c sdq = new System_Design_Quote__c(
            System_Design__c = sd.Id
        );
        insert sdq;
        
        Installed_System__c sys = new Installed_System__c (
            Account__c = customer.Id,
            Quoted_System_Design__c = sdq.Id
        );
        insert sys;
        
        Attachment img = new Attachment (
            ParentId = sys.Id,
            Name = 'system design',
            Body = Blob.valueOf('img')
        );
        insert img;

        Test.setCurrentPage(Page.InstalledSystemsDetail);
        ApexPages.StandardController controller = new ApexPages.StandardController(sys);
        InstalledSystems_Detail extension = new InstalledSystems_Detail(controller);    
        
        List<System_Design_Item__c> items = extension.getSysDesignItems();
        
        System.assertEquals(0, items.size());
        
    }

    static testMethod void testMonthlyProd() {

        Account customer = new Account(Name='Test Customer');
        insert customer;
        
        Installed_System__c sys = new Installed_System__c (
            Account__c = customer.Id
        );
        insert sys;
        
        Monthly_Production__c mProd = new Monthly_Production__c (
            Installed_System__c = sys.Id,
            Start_of_Month__c = System.today()
        );
        insert mProd;

        Test.setCurrentPage(Page.InstalledSystemsDetail);
        ApexPages.StandardController controller = new ApexPages.StandardController(sys);
        InstalledSystems_Detail extension = new InstalledSystems_Detail(controller);    
        
        List<Monthly_Production__c> mProds = extension.production;
        List<InstalledSystems_Detail.ProdWrapper> wProds = extension.getProductionHistory();
        
        System.assertEquals(1, mProds.size());
        System.assertEquals(1, wProds.size());
        
    }    
    
    static testMethod void testAlerts() {

        Account customer = new Account(Name='Test Customer');
        insert customer;
        
        Installed_System__c sys = new Installed_System__c (
            Account__c = customer.Id
        );
        insert sys;
        
        Enphase_Alert__c alert = new Enphase_Alert__c (
            Installed_System__c = sys.Id
        );
        insert alert;

        Test.setCurrentPage(Page.InstalledSystemsDetail);
        ApexPages.StandardController controller = new ApexPages.StandardController(sys);
        InstalledSystems_Detail extension = new InstalledSystems_Detail(controller);    
        
        List<Enphase_Alert__c> alerts = extension.alerts;
        
        System.assertEquals(1, alerts.size());
        
    }    
    
    static testMethod void testSRECS() {
        
        Account customer = new Account(Name='Test Customer');
        insert customer;
        
        Installed_System__c sys = new Installed_System__c (
            Account__c = customer.Id
        );
        insert sys;
        
        SREC_Certificate__c srec = new SREC_Certificate__c ( 
           Installed_System__c = sys.Id 
        ); 
        insert srec; 
        
        Test.setCurrentPage(Page.InstalledSystemsDetail);
        ApexPages.StandardController controller = new ApexPages.StandardController(sys);
        InstalledSystems_Detail extension = new InstalledSystems_Detail(controller);    
        
        List<SREC_Certificate__c> srecs = extension.srecs; 
        
        System.assertEquals(1, srecs.size()); 
        
    }
    
    /*
    private static testmethod void unitTest() {
        Date objDate = Date.today().addMonths(-1);
       
        Account acc = new Account(
            Name = 'Test'
        );
        insert acc;
        
        Installed_System__c installedSysObj = new Installed_System__c(
            Account__c = acc.id,
            Generation_Start_Date__c = Date.newInstance(2009,11,30),
            January_Daily_Peak_Sun_Hours__c = 5,
            February_Daily_Peak_Sun_Hours__c = 5,
            March_Daily_Peak_Sun_Hours__c = 5,
            April_Daily_Peak_Sun_Hours__c = 5,
            May_Daily_Peak_Sun_Hours__c = 5,
            June_Daily_Peak_Sun_Hours__c = 5,
            July_Daily_Peak_Sun_Hours__c = 5,
            August_Daily_Peak_Sun_Hours__c = 5,
            September_Daily_Peak_Sun_Hours__c = 5,
            October_Daily_Peak_Sun_Hours__c = 5,
            November_Daily_Peak_Sun_Hours__c = 5,
            December_Daily_Peak_Sun_Hours__c = 5
        );  // Installation_Year__c = 1900 , System.today()   Date.newInstance(2011,12,30)
        insert installedSysObj;
        
        Blob content = Blob.valueOf('test image');
        Attachment image = new Attachment (
            ParentId = installedSysObj.Id,
            Name = 'systemdesign.png',
            Body = content,
            ContentType = 'image/png'
        );
        insert image;
        image = new Attachment (
            ParentId = installedSysObj.Id,
            Name = 'install.png',
            Body = content,
            ContentType = 'image/png'
        );
        insert image;
        
        Annual_Production__c annProd = new Annual_Production__c(
            Installed_System__c = installedSysObj.id,
            Year__c = 2009,
            January_Actual_Production_kWh__c = 5,
            February_Actual_Production_kWh__c = 5,
            March_Actual_Production_kWh__c = 5,
            April_Actual_Production_kWh__c = 5,
            May_Actual_Production_kWh__c = 5,
            June_Actual_Production_kWh__c = 5,
            July_Actual_Production_kWh__c = 5,
            August_Actual_Production_kWh__c = 5,
            September_Actual_Production_kWh__c = 5,
            October_Actual_Production_kWh__c = 5,
            November_Actual_Production_kWh__c = 5,
            December_Actual_Production_kWh__c = 5,            
            January_Production_Guarantee_kWh__c = 5,
            February_Production_Guarantee_kWh__c = 5,
            March_Production_Guarantee_kWh__c = 5,
            April_Production_Guarantee_kWh__c = 5,
            May_Production_Guarantee_kWh__c = 5,
            June_Production_Guarantee_kWh__c = 5,
            July_Production_Guarantee_kWh__c = 5,
            August_Production_Guarantee_kWh__c = 5,
            September_Production_Guarantee_kWh__c = 5,
            October_Production_Guarantee_kWh__c = 5,
            November_Production_Guarantee_kWh__c = 5,
            December_Production_Guarantee_kWh__c = 5
            
        );
        insert annProd;
        
        Annual_Production__c annProd2 = new Annual_Production__c(
            Installed_System__c = installedSysObj.id,
            Year__c = 2010,
            January_Actual_Production_kWh__c = 5,
            February_Actual_Production_kWh__c = 5,
            March_Actual_Production_kWh__c = 5,
            April_Actual_Production_kWh__c = 5,
            May_Actual_Production_kWh__c = 5,
            June_Actual_Production_kWh__c = 5,
            July_Actual_Production_kWh__c = 5,
            August_Actual_Production_kWh__c = 5,
            September_Actual_Production_kWh__c = 5,
            October_Actual_Production_kWh__c = 5,
            November_Actual_Production_kWh__c = 5,
            December_Actual_Production_kWh__c = 5,            
            January_Production_Guarantee_kWh__c = 5,
            February_Production_Guarantee_kWh__c = 5,
            March_Production_Guarantee_kWh__c = 5,
            April_Production_Guarantee_kWh__c = 5,
            May_Production_Guarantee_kWh__c = 5,
            June_Production_Guarantee_kWh__c = 5,
            July_Production_Guarantee_kWh__c = 5,
            August_Production_Guarantee_kWh__c = 5,
            September_Production_Guarantee_kWh__c = 5,
            October_Production_Guarantee_kWh__c = 5,
            November_Production_Guarantee_kWh__c = 5,
            December_Production_Guarantee_kWh__c = 5
            
        );
        insert annProd2; 

        annProd2 = new Annual_Production__c(
            Installed_System__c = installedSysObj.id,
            Year__c = 2011,
            January_Actual_Production_kWh__c = 5,
            February_Actual_Production_kWh__c = 5,
            March_Actual_Production_kWh__c = 5,
            April_Actual_Production_kWh__c = 5,
            May_Actual_Production_kWh__c = 5,
            June_Actual_Production_kWh__c = 5,
            July_Actual_Production_kWh__c = 5,
            August_Actual_Production_kWh__c = 5,
            September_Actual_Production_kWh__c = 5,
            October_Actual_Production_kWh__c = 5,
            November_Actual_Production_kWh__c = 5,
            December_Actual_Production_kWh__c = 5,            
            January_Production_Guarantee_kWh__c = 5,
            February_Production_Guarantee_kWh__c = 5,
            March_Production_Guarantee_kWh__c = 5,
            April_Production_Guarantee_kWh__c = 5,
            May_Production_Guarantee_kWh__c = 5,
            June_Production_Guarantee_kWh__c = 5,
            July_Production_Guarantee_kWh__c = 5,
            August_Production_Guarantee_kWh__c = 5,
            September_Production_Guarantee_kWh__c = 5,
            October_Production_Guarantee_kWh__c = 5,
            November_Production_Guarantee_kWh__c = 5,
            December_Production_Guarantee_kWh__c = 5
            
        );
        insert annProd2; 
        
        InstalledSystems_Detail ctrl = new InstalledSystems_Detail(new ApexPages.StandardController(installedSysObj));          
        
        ctrl.getInstalledPanelsData();
        ctrl.doSystemCertified();
        ctrl.getSysGrntURL();
        ctrl.getSRECChartURL();
        ctrl.getProductionHistory();
        ctrl.getSysDesignItems();
        ctrl.doDocumentsSubmitted10();
        ctrl.doDocumentsSubmitted60();
        ctrl.doDocumentsSubmitted30();
        ctrl.doInvoiceAuthorized10();
        ctrl.doInvoiceAuthorized60();
        ctrl.doInvoiceAuthorized30();
        
        //force exception
        delete installedSysObj;
        ctrl.doDocumentsSubmitted10();
        ctrl.doDocumentsSubmitted60();
        ctrl.doDocumentsSubmitted30();
        ctrl.doInvoiceAuthorized10();
        ctrl.doInvoiceAuthorized60();
        ctrl.doInvoiceAuthorized30();
    */
        
        
        /*    
        List<Annual_Production__c> objAnnualList1 = [select Id, Installed_System__c from Annual_Production__c where Year__c = 2011];
        
        Id isysId1 = objAnnualList1[0].Installed_System__c;       
        List<Installed_System__c> objInstallList1 = [select Id from Installed_System__c where Id = :isysId1];
        InstalledSystems_Detail ctrl1 = new InstalledSystems_Detail(new ApexPages.StandardController(objInstallList1[0])); 
        ctrl1.getInstalledPanelsData();
        ctrl1.doSystemCertified();
        ctrl1.getSysGrntURL();
        ctrl1.getSRECChartURL();
        ctrl1.getProductionHistory();
        ctrl1.getSysDesignItems();
        */

    //}
    
}