src/objects/Astrum_Contract__c.object
<CustomObject>
    <description>Contract object to facilitate Conga Contracts</description>
    <fields>
        <fullName>Closed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Closed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Current__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Open_Quote__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Open Quote</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Proposal__c</fullName>
        <label>Proposal</label>
        <referenceTo>Proposal__c</referenceTo>
        <relationshipLabel>Astrum Contracts</relationshipLabel>
        <relationshipName>Astrum_Contracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Scenario__c</fullName>
        <label>Scenario</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Astrum Contract</label>
    <nameField>
        <displayFormat>AC-{MM}-{DD}-{YY}-{0000}</displayFormat>
        <label>Astrum Contracts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Astrum Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Proposal__c.object
<CustomObject>
    <fields>
        <fullName>Closed_Scenario__c</fullName>
        <label>Closed Scenario</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Closed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Closed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Current__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Days_Proposal_Valid__c</fullName>
        <label>Days Proposal Valid</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Open_Quote__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Open Quote</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Proposal_Expiration_Date__c</fullName>
        <defaultValue>Today() + 21</defaultValue>
        <label>Proposal Expiration Date</label>
        <type>Date</type>
    </fields>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/System_Design_Quote_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Used to Enable/Disable behind the scenes pricing for SDQ records.</description>
    <fields>
        <fullName>Days_Proposal_Valid__c</fullName>
        <description>Default number of days for which the created Proposal will be valid</description>
        <label>Days Proposal Valid</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>System Design Quote Settings</label>
</CustomObject>

src/classes/ProposalTriggerHandler.cls
/* FILE: ProposalTriggerHandler.cls
   AUTHOR: Dan Kelner
   DATE: 12/08/14
   PURPOSE: Common trigger handler for Proposal
   MODIFICATION HISTORY: 
        07/07/15  DK  Allowed a user-defined expiration date to be set on a Proposal as per CPQ-416
*/
public class ProposalTriggerHandler {
    
    public static Boolean isProposalTriggerRunning = false;
    public static boolean skipProposalTrigger = false;

    private Boolean m_isExecuting = false;

    public ProposalTriggerHandler(Boolean isExecuting){      
        m_isExecuting = isExecuting;
    }

    public void OnBeforeInsert(Proposal__c[] newProposals){
        // EXECUTE BEFORE INSERT LOGIC 
        setProposalExpirationDate(newProposals);
        setOpenQuote(newProposals);
        m_isExecuting = false;
    }

    public void OnBeforeUpdate(Proposal__c[] updatedProposals, Map<ID, Proposal__c> proposalMap, Map<ID, Proposal__c> oldProposalMap){
        // BEFORE UPDATE LOGIC  
        closedProposalRules(proposalMap);
        //currentProposalRules(updatedProposals);
        setOpenQuote(updatedProposals);
        m_isExecuting = false;
    }

    public void OnAfterInsert(Proposal__c[] insertedProposals, Map<ID, Proposal__c> insertedProposalsMap){
        // EXECUTE AFTER INSERT LOGIC        
        m_isExecuting = false;
    }

    public void OnAfterUpdate(Proposal__c[] updatedProposals, Map<ID, Proposal__c> proposalMap, Map<ID, Proposal__c> oldProposalMap){
        //  EXECUTE AFTER UPDATE LOGIC
        
        m_isExecuting = false;
    }

    public Boolean IsTriggerContext {
        get { return m_isExecuting; }
    }
    
    //------------------------------------------------//
    
    //If one and only one child Contract is closed, than set the Proposal to closed as well
    public void closedProposalRules(Map<ID, Proposal__c> proposalMap){    //Called on "before update"
        Map<ID, Astrum_Contract__c> propClosedContracts = new Map<ID, Astrum_Contract__c>();    //Proposal ID --> Child Contract where Closed = true
        for (ID propID : proposalMap.keySet())
            propClosedContracts.put(propID, null);    //Populate Proposal ID keys
        Astrum_Contract__c[] closedContracts = [SELECT Scenario__c, Proposal__c FROM Astrum_Contract__c WHERE Closed__c = true AND Proposal__c IN :proposalMap.keySet()];
        
        for (Astrum_Contract__c contr : closedContracts){
            ID propID = contr.Proposal__c;
            if (!propClosedContracts.containsKey(propID))
                continue;    //This key has been deleted due to having more than one closed Contract
            if (propClosedContracts.get(propID) != null){
                //Another closed Contract has already been found for this Proposal. Since only one closed Contract is allowed, we will remove this key.
                propClosedContracts.remove(propID);
            } else {
                //Set this closed Contract to this Proposal key
                propClosedContracts.put(propID, contr);
            }
        }
        
        //Set the relevant fields on the Proposals
        for (ID propID : proposalMap.keySet()){
            Proposal__c prop = proposalMap.get(propID);
            if (propClosedContracts.get(propID) != null){
                //This Proposal has exactly one closed Contract
                prop.Closed__c = true;
                prop.Closed_Scenario__c = propClosedContracts.get(propID).Scenario__c;
            } else {
                //This Proposal has either zero or more than one closed Contracts
                prop.Closed__c = false;
                prop.Closed_Scenario__c = '';
            }
        }
        //No need for DML as long as this method is called from a "before" context
    }
    
    //public void currentProposalRules(Proposal__c[] updatedProposals){
    //    Set<ID> notCurrentPropIDs = new Set<ID>();
    //    for (Proposal__c prop : updatedProposals){
    //        if (prop.Current__c == false)
    //            notCurrentPropIDs.add(prop.ID);
    //    }
    //    if (notCurrentPropIDs.size() == 0)
    //        return;
        
    //    Astrum_Contract__c[] childContracts = [SELECT Current__c FROM Astrum_Contract__c WHERE Proposal__c IN :notCurrentPropIDs];
    //    for (Astrum_Contract__c contr : childContracts)
    //        contr.Current__c = false;
    //    update childContracts;
    //}
    
    public void setOpenQuote(Proposal__c[] props){
        for (Proposal__c prop : props){
            if (prop.Closed__c == false && prop.Proposal_Expiration_Date__c >= Date.today())
                prop.Open_Quote__c = true;
        }
        //No need for DML as long as this method is called from a "before" context
    }
    
    public void setProposalExpirationDate(Proposal__c[] props){
        Integer defaultDaysValid;
        try {
            defaultDaysValid = Integer.valueOf(System_Design_Quote_Settings__c.getOrgDefaults().Days_Proposal_Valid__c);
        } catch (NullPointerException e){
            System.debug('Error in ProposalTriggerHandler on line ' + e.getLineNumber());
        }
        if (defaultDaysValid == null)
            defaultDaysValid = 14;    //Fall-back value in case no custom setting is found (Useful for test classes)
        
        for (Proposal__c prop : props){
            if (prop.Proposal_Expiration_Date__c == null){   //Only set this default if no date value was specified
                prop.Days_Proposal_Valid__c = defaultDaysValid;
                prop.Proposal_Expiration_Date__c = Date.today().addDays(defaultDaysValid);
            }
        }
        //No need for DML as long as this method is called from a "before" context
    }
}