src/objects/Astrum_Contract__c.object
<CustomObject>
    <description>Contract object to facilitate Conga Contracts</description>
    <fields>
        <fullName>Closed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Closed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Current__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>Property State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proposal__c</fullName>
        <label>Proposal</label>
        <referenceTo>Proposal__c</referenceTo>
        <relationshipLabel>Astrum Contracts</relationshipLabel>
        <relationshipName>Astrum_Contracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Scenario__c</fullName>
        <label>Scenario</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Astrum Contract</label>
    <nameField>
        <displayFormat>AC-{MM}-{DD}-{YY}-{0000}</displayFormat>
        <label>Astrum Contracts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Astrum Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Astrum_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Astrum Contract</label>
        <referenceTo>Astrum_Contract__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_Site_Survey_Completed__c</fullName>
        <description>The date the site survey was completed.</description>
        <inlineHelpText>The date the site survey was completed.</inlineHelpText>
        <label>Date Site Survey Completed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <formula>TEXT(Property__r.Property_State__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proposal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proposal</label>
        <referenceTo>Proposal__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Design_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>System Design Quote</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>System_Design_Quote__c.System_Design__r.Property__c</field>
                <operation>equals</operation>
                <valueField>$Source.Property__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>System_Design_Quote__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Portal_Referral__c.object
<CustomObject>
    <description>Referrals from the Partner Program website</description>
    <fields>
        <fullName>D2D_Lead_Status__c</fullName>
        <label>D2D Lead Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed - Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Generated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Opt-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Opt-Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Door Hanger</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing Utility Bill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA Visit 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA Visit 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passed Validation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Photos Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit Scheduled</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>D2D_Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>D2D Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Portal_Referrals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of referral</description>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Portal Referrals</relationshipLabel>
        <relationshipName>Portal_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Portal Referral</label>
    <nameField>
        <displayFormat>REF-{000000}</displayFormat>
        <label>Portal Referral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Proposal__c.object
<CustomObject>
    <fields>
        <fullName>Closed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Closed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Current__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>System_Design_Quote__c</fullName>
        <label>System Design Quote</label>
        <referenceTo>System_Design_Quote__c</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/System_Design_Quote__c.object
<CustomObject>
    <description>AstrumCRM - System Design Quote.  Each System Design can have one or more System Design Quotes.  Each quote provides the sales consultant with the ability to adjust the negotiated price of the System Design based on the Calculated System Price.  Opportunities must choose a winning System Design Quote in order to close.</description>
    <fields>
        <fullName>Closed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Closed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Current__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <description>Initially used in code to cut back on extra SOQL queries in triggers.</description>
        <formula>text(System_Design__r.Property__r.Property_State__c)</formula>
        <label>Property State</label>
        <type>Text</type>
    </fields>
    <label>System Design Quote</label>
    <nameField>
        <displayFormat>SDQ-{0}</displayFormat>
        <label>System Design Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Design Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Site_Survey_Complete_Controller_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class Site_Survey_Complete_Controller_Test {

    static testMethod void testSiteSurveyComplete_EventComplete() {
		// setup    
    	// create event
		Opportunity opp = Milestone1_Test_Utility.CreateTestOpp();
		Event theEvent = createEvent(opp);    	
    	
    	// execute
		ApexPages.Standardcontroller standController = new ApexPages.Standardcontroller(theEvent);
		Site_Survey_Complete_Controller_Ext controller = new Site_Survey_Complete_Controller_Ext(standController);
    	controller.updateEvent();
    	
    	// assert
    	
    	// confirm event is completed
    	Boolean expected = true;

    	Event tempEvent = [select Completed__c from Event where id =:theEvent.id limit 1];
    	Boolean actual = tempEvent.Completed__c;
    	
    	System.assertEquals(expected, actual);
    }

    static testMethod void testSiteSurveyComplete_OpportunitySiteSurveyCompletedDate() {
		// setup    
    	// create event
		Opportunity opp = Milestone1_Test_Utility.CreateTestOpp();
		Event theEvent = createEvent(opp);    	
    	
    	// execute
		ApexPages.Standardcontroller standController = new ApexPages.Standardcontroller(theEvent);
		Site_Survey_Complete_Controller_Ext controller = new Site_Survey_Complete_Controller_Ext(standController);
    	controller.updateEvent();
    	
    	// assert    	
    	// confirm Opportunity.Date_Site_Survey_Completed__c is set
		opp = [Select Date_Site_Survey_Completed__c
							  From Opportunity o 
							  where id = :theEvent.WhatId 
							  limit 1];

    	Datetime expected = null;
    	Datetime actual = opp.Date_Site_Survey_Completed__c;

		System.assertNotEquals(expected, actual);    	
    }

    @isTest static void test_D2DEventCompleteNoContract() {
		// setup    
    	// create event
		Opportunity opp = Milestone1_Test_Utility.CreateTestOpp();
		Event theEvent = createEvent(opp, true);

		// Create the contract, and re-complete
    	Test.startTest();

    	// execute
    	Integer pageMessageCount = ApexPages.getMessages().size();

		ApexPages.Standardcontroller standController = new ApexPages.Standardcontroller(theEvent);
		Site_Survey_Complete_Controller_Ext controller = new Site_Survey_Complete_Controller_Ext(standController);
    	controller.updateEvent();
    	
    	// assert, no contract, so page message
    	system.assertNotEquals(pageMessageCount, ApexPages.getMessages().size());

    	Test.stopTest();
    } 

    @isTest static void test_D2DEventCompleteWithContract() {
		// setup
		D2DTestUtility.InitializeRequiredMethods();

		D2DTestUtility.CreateManagerUsers(1);
		User d2dMg = D2DTestUtility.d2dManagerUsers[0];

		D2DTestUtility.CreateSalesRepUsers(1);
		User d2dSr = D2DTestUtility.d2dSalesRepUsers[0];

    	// create event
		Opportunity opp = Milestone1_Test_Utility.CreateTestOpp();
		Event theEvent = createEvent(opp, true);

		// Create the contract, and re-complete
    	Test.startTest();

    	// Create proposal and contract
    	Portal_Referral__c referral = new Portal_Referral__c(
    		Last_Name__c = 'Test',
			D2D_Lead_Status__c = 'Visit Scheduled',
			D2D_Sales_Rep__c = d2dSr.Id,
			Opportunity__c = opp.Id
		);
		insert referral;

    	Proposal__c proposal = new Proposal__c(System_Design_Quote__c = opp.System_Design_Quote__c, Current__c = true);
    	insert proposal;

        Astrum_Contract__c contract = new Astrum_Contract__c(Proposal__c = proposal.Id, Scenario__c = '1', Closed__c = true, Property_State__c = 'NY');
    	//Astrum_Contract__c contract = new Astrum_Contract__c(Proposal__c = proposal.Id);
    	insert contract;

    	// execute
    	Integer pageMessageCount = ApexPages.getMessages().size();

		ApexPages.Standardcontroller standController = new ApexPages.Standardcontroller(theEvent);
		Site_Survey_Complete_Controller_Ext controller = new Site_Survey_Complete_Controller_Ext(standController);
    	controller.updateEvent();
    	
    	// assert, no contract, so page message
    	system.assertEquals(pageMessageCount, ApexPages.getMessages().size());

    	Test.stopTest();
    } 
  
    
	private static Event createEvent(Opportunity opp) {
		return createEvent(opp, false);
	}

	private static Event createEvent(Opportunity opp, Boolean isD2D) {

		Event tempEvent = new Event();
		tempEvent.OwnerId = UserInfo.getUserId();
		  
		tempEvent.Subject = 'Test';
		tempEvent.StartDateTime = Datetime.now();
		tempEvent.EndDateTime = Datetime.now().addDays(14);
		tempEvent.WhatId = opp.Id;
		tempEvent.D2D_Survey_Request__c = isD2D;

		insert tempEvent;			
	
		return tempEvent;
	}
}