src/objects/Astrum_Contract__c.object
<CustomObject>
    <description>Contract object to facilitate Conga Contracts</description>
    <fields>
        <fullName>Current__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>Property State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proposal__c</fullName>
        <label>Proposal</label>
        <referenceTo>Proposal__c</referenceTo>
        <relationshipLabel>Astrum Contracts</relationshipLabel>
        <relationshipName>Astrum_Contracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Scenario__c</fullName>
        <label>Scenario</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Astrum Contract</label>
    <nameField>
        <displayFormat>AC-{MM}-{DD}-{YY}-{0000}</displayFormat>
        <label>Astrum Contracts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Astrum Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lease_Fund__c.object
<CustomObject>
    <fields>
        <fullName>Sighten_Product_uuid__c</fullName>
        <description>Contains the uuid for the product in the Sighten system</description>
        <externalId>true</externalId>
        <label>Sighten Product uuid</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Lease Fund</label>
    <nameField>
        <label>Lease Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lease Funds</pluralLabel>
    <recordTypes>
        <fullName>Lease</fullName>
        <active>true</active>
        <description>Lease Funding Record</description>
        <label>Lease</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Proposal__c.object
<CustomObject>
    <fields>
        <fullName>Current__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Scenario_1_Included__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For creating Contracts</description>
        <label>Scenario 1 Included</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>System_Design_Quote__c</fullName>
        <label>System Design Quote</label>
        <referenceTo>System_Design_Quote__c</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/System_Design__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The Solar System Design.  Each Property can have one or more System Designs created as the result of a site Survey and the discovery of Install Locations.  Each System Design is made up of one or more System Design Arrays.</description>
    <label>System Design</label>
    <nameField>
        <displayFormat>SD-{0}</displayFormat>
        <label>System Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Designs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/System_Design_Quote__c.object
<CustomObject>
    <description>AstrumCRM - System Design Quote.  Each System Design can have one or more System Design Quotes.  Each quote provides the sales consultant with the ability to adjust the negotiated price of the System Design based on the Calculated System Price.  Opportunities must choose a winning System Design Quote in order to close.</description>
    <fields>
        <fullName>Current__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <description>Initially used in code to cut back on extra SOQL queries in triggers.</description>
        <formula>text(System_Design__r.Property__r.Property_State__c)</formula>
        <label>Property State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scenario_1_Term_Loan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lease Fund record must be a loan</description>
        <label>Scenario 1 Term Loan</label>
        <referenceTo>Lease_Fund__c</referenceTo>
        <relationshipLabel>System Design Quotes (Scenario 1 Term Loan)</relationshipLabel>
        <relationshipName>System_Design_Quotes4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Design__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>System Design</label>
        <referenceTo>System_Design__c</referenceTo>
        <relationshipLabel>System Design Quotes</relationshipLabel>
        <relationshipName>System_Design_Quotes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>System Design Quote</label>
    <nameField>
        <displayFormat>SDQ-{0}</displayFormat>
        <label>System Design Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Design Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PreviewProposalTest.cls
/*  FILE: PreviewProposalTest
    AUTHOR: Dan Kelner
    DATE: 04/13/15
    PURPOSE: Test class for PreviewProposalCtrl
    MODIFICATION HISTORY
*/
@isTest
public class PreviewProposalTest {
    private static boolean runalltests = true; // true to run all tests; false to skip tests and only run those where the 'if' is commented out
    
     @isTest(seeAllData = false) static void controllerTest1(){
        if(!runalltests){ return; }

        //Create our test data
        testData.setupCustomSettings();
        testdata.setupCustomConfigObjects();

        ID sdID = testData.setupSystemDesign('Residential', 'Purchase', null, false, 12000);
        System_Design__c sysDesign = new System_Design__c(ID = sdID);
        update sysDesign;

        System_Design_Quote__c sdq = new System_Design_Quote__c(System_Design__c = sysDesign.ID, Current__c = true);
        insert sdq;

        Proposal__c prop1 = new Proposal__c(System_Design_Quote__c = sdq.ID);
        Proposal__c prop2 = new Proposal__c(System_Design_Quote__c = sdq.ID);
        insert new Proposal__c[]{prop1, prop2};

        Astrum_Contract__c contr1 = new Astrum_Contract__c(Proposal__c = prop1.ID, Scenario__c = '1', Property_State__c = 'CA');
        Astrum_Contract__c contr2 = new Astrum_Contract__c(Proposal__c = prop1.ID, Scenario__c = '2', Property_State__c = 'CA');
        Astrum_Contract__c contr3 = new Astrum_Contract__c(Proposal__c = prop1.ID, Scenario__c = '3', Property_State__c = 'CA');
        Astrum_Contract__c contr4 = new Astrum_Contract__c(Proposal__c = prop1.ID, Scenario__c = '4', Property_State__c = 'CA');
        insert new Astrum_Contract__c[]{contr1, contr2, contr3, contr4};

        Test.startTest();
        Test.setCurrentPage(Page.PreviewProposal);
        PreviewProposalCtrl ctrl = new PreviewProposalCtrl(new ApexPages.StandardController(prop2));
        ApexPages.currentPage().getParameters().put('proposalID', prop1.ID);
        ctrl.switchProposal();
        ctrl.getPanelProduct();
        ctrl.getProperty();
        ApexPages.currentPage().getParameters().put('scenarioNum', '1');
        ctrl.saveContractPDF();
        ctrl.goToProposalPDF();
        ctrl.saveProposalPDF();
        Test.stopTest();
     }

     @isTest(seeAllData = false) static void controllerTest2(){
        if(!runalltests){ return; }

        System_Design_Quote__c sdq = testData.setupSystemDesignQuoteForContract('Residential', 12000);

        Proposal__c prop = new Proposal__c(System_Design_Quote__c = sdq.ID);
        insert prop;

        Astrum_Contract__c contr1 = new Astrum_Contract__c(Proposal__c = prop.ID, Scenario__c = '1', Property_State__c = 'CA');
        Astrum_Contract__c contr2 = new Astrum_Contract__c(Proposal__c = prop.ID, Scenario__c = '2', Property_State__c = 'CA');
        Astrum_Contract__c contr3 = new Astrum_Contract__c(Proposal__c = prop.ID, Scenario__c = '3', Property_State__c = 'CA');
        Astrum_Contract__c contr4 = new Astrum_Contract__c(Proposal__c = prop.ID, Scenario__c = '4', Property_State__c = 'CA');
        insert new Astrum_Contract__c[]{contr1, contr2, contr3, contr4};

        Test.startTest();
        Test.setCurrentPage(Page.PreviewProposal);
        PreviewProposalCtrl ctrl = new PreviewProposalCtrl(new ApexPages.StandardController(prop));
        ApexPages.currentPage().getParameters().put('proposalID', prop.ID);
        ctrl.makeProposalCurrent();
        Test.stopTest();
     }

     @isTest(seeAllData = false) static void controllerTest3(){
        if(!runalltests){ return; }

        System_Design_Quote__c sdq = testData.setupSystemDesignQuoteForContract('Residential', 12000);

        Proposal__c prop = new Proposal__c(System_Design_Quote__c = sdq.ID);
        insert prop;

        Astrum_Contract__c contr1 = new Astrum_Contract__c(Proposal__c = prop.ID, Scenario__c = '1', Property_State__c = 'CA');
        Astrum_Contract__c contr2 = new Astrum_Contract__c(Proposal__c = prop.ID, Scenario__c = '2', Property_State__c = 'CA');
        Astrum_Contract__c contr3 = new Astrum_Contract__c(Proposal__c = prop.ID, Scenario__c = '3', Property_State__c = 'CA');
        Astrum_Contract__c contr4 = new Astrum_Contract__c(Proposal__c = prop.ID, Scenario__c = '4', Property_State__c = 'CA');
        insert new Astrum_Contract__c[]{contr1, contr2, contr3, contr4};

        Test.startTest();
        Test.setCurrentPage(Page.PreviewProposal);
        PreviewProposalCtrl ctrl = new PreviewProposalCtrl(new ApexPages.StandardController(prop));
        ApexPages.currentPage().getParameters().put('proposalID', prop.ID);
        ctrl.getInverterProduct();
        Astrum_Contract__c c1 = ctrl.contr1;
        Astrum_Contract__c c2 = ctrl.contr2;
        Astrum_Contract__c c3 = ctrl.contr3;
        Astrum_Contract__c c4 = ctrl.contr4;

        ApexPages.currentPage().getParameters().put('scenarioNum', '2');
        ctrl.saveContractPDF();

        ApexPages.currentPage().getParameters().put('scenarioNum', '3');
        ctrl.saveContractPDF();

        ApexPages.currentPage().getParameters().put('scenarioNum', '4');
        ctrl.saveContractPDF();

        Test.stopTest();
     }

    @isTest static void sightenInitiateCreditCheck(){
        if(!runalltests){ return; }

        testdata.setupCustomSettingsPricing();
        testdata.setupCustomConfigObjectsPricing();

        //Create our test data
        SightenTestUtility.createSightenCustomSettings();
        
        //Create System Design Quote        
        Opportunity_Trigger_Utility.skipOpportunityTrigger = true;
        System_Design_Quote__c sdq = testdata.setupSystemDesignQuote('Residential', 'Purchase', null, true, 12000);
        Opportunity_Trigger_Utility.skipOpportunityTrigger = false;

        // Add values to the Sighten uuid field for the lease fund
        SightenTestUtility.AddSightenUUIDValues(sdq);

        System_Design_Quote__c sdqTermLoan = [SELECT Id, Scenario_1_Term_Loan__c, Scenario_1_Term_Loan__r.Sighten_Product_uuid__c FROM System_Design_Quote__c WHERE Id = :sdq.Id LIMIT 1];

        Proposal__c prop = new Proposal__c(System_Design_Quote__c = sdq.ID);
        insert prop;

        Test.startTest();
        Test.setCurrentPage(Page.PreviewProposal);
        Test.setMock(HttpCalloutMock.class, new SightenTestCalloutMock(200));

        PreviewProposalCtrl ctrl = new PreviewProposalCtrl(new ApexPages.StandardController(prop));
        ctrl.buttonScenario = '1';

        ctrl.initiateCreditCheck();
        
        Test.stopTest();
    }

    @isTest static void sightenInitiateCreditCheckError(){
        if(!runalltests){ return; }

        testdata.setupCustomSettingsPricing();
        testdata.setupCustomConfigObjectsPricing();

        //Create our test data
        SightenTestUtility.createSightenCustomSettings();
        
        //Create System Design Quote        
        Opportunity_Trigger_Utility.skipOpportunityTrigger = true;
        System_Design_Quote__c sdq = testdata.setupSystemDesignQuote('Residential', 'Purchase', null, true, 12000);
        Opportunity_Trigger_Utility.skipOpportunityTrigger = false;

        // Add values to the Sighten uuid field for the lease fund
        SightenTestUtility.AddSightenUUIDValues(sdq);

        System_Design_Quote__c sdqTermLoan = [SELECT Id, Scenario_1_Term_Loan__c, Scenario_1_Term_Loan__r.Sighten_Product_uuid__c FROM System_Design_Quote__c WHERE Id = :sdq.Id LIMIT 1];

        Proposal__c prop = new Proposal__c(System_Design_Quote__c = sdq.ID);
        insert prop;

        Test.startTest();
        Test.setCurrentPage(Page.PreviewProposal);
        Test.setMock(HttpCalloutMock.class, new SightenTestCalloutMock(400));

        PreviewProposalCtrl ctrl = new PreviewProposalCtrl(new ApexPages.StandardController(prop));
        ctrl.buttonScenario = '1';

        ctrl.initiateCreditCheck();
        
        Test.stopTest();
    }

    @isTest static void sightenUpdateCreditCheck(){
        if(!runalltests){ return; }

        testdata.setupCustomSettingsPricing();
        testdata.setupCustomConfigObjectsPricing();

        //Create our test data
        SightenTestUtility.createSightenCustomSettings();
        
        //Create System Design Quote        
        Opportunity_Trigger_Utility.skipOpportunityTrigger = true;
        System_Design_Quote__c sdq = testdata.setupSystemDesignQuote('Residential', 'Purchase', null, true, 12000);
        Opportunity_Trigger_Utility.skipOpportunityTrigger = false;

        // Add values to the Sighten uuid field for the lease fund
        SightenTestUtility.AddSightenUUIDValues(sdq);

        System_Design_Quote__c sdqTermLoan = [SELECT Id, Scenario_1_Term_Loan__c, Scenario_1_Term_Loan__r.Sighten_Product_uuid__c FROM System_Design_Quote__c WHERE Id = :sdq.Id LIMIT 1];

        Proposal__c prop = new Proposal__c(System_Design_Quote__c = sdq.ID, Scenario_1_Included__c = true);
        insert prop;

        Test.startTest();
        Test.setCurrentPage(Page.PreviewProposal);
        Test.setMock(HttpCalloutMock.class, new SightenTestCalloutMock(200));

        PreviewProposalCtrl ctrl = new PreviewProposalCtrl(new ApexPages.StandardController(prop));
        ctrl.buttonScenario = '1';

        ctrl.updateCreditStatus();
        
        Test.stopTest();
    }

    @isTest static void sightenUpdateCreditCheckError(){
        if(!runalltests){ return; }

        testdata.setupCustomSettingsPricing();
        testdata.setupCustomConfigObjectsPricing();

        //Create our test data
        SightenTestUtility.createSightenCustomSettings();
        
        //Create System Design Quote        
        Opportunity_Trigger_Utility.skipOpportunityTrigger = true;
        System_Design_Quote__c sdq = testdata.setupSystemDesignQuote('Residential', 'Purchase', null, true, 12000);
        Opportunity_Trigger_Utility.skipOpportunityTrigger = false;

        // Add values to the Sighten uuid field for the lease fund
        SightenTestUtility.AddSightenUUIDValues(sdq);

        System_Design_Quote__c sdqTermLoan = [SELECT Id, Scenario_1_Term_Loan__c, Scenario_1_Term_Loan__r.Sighten_Product_uuid__c FROM System_Design_Quote__c WHERE Id = :sdq.Id LIMIT 1];

        Proposal__c prop = new Proposal__c(System_Design_Quote__c = sdq.ID, Scenario_1_Included__c = true);
        insert prop;

        Test.startTest();
        Test.setCurrentPage(Page.PreviewProposal);
        Test.setMock(HttpCalloutMock.class, new SightenTestCalloutMock(400));

        PreviewProposalCtrl ctrl = new PreviewProposalCtrl(new ApexPages.StandardController(prop));
        ctrl.buttonScenario = '1';

        ctrl.updateCreditStatus();
        
        Test.stopTest();
    }
}