src/objects/Astrum_Sales_Region__c.object
<CustomObject>
    <description>Astrum Sales Regions</description>
    <fields>
        <fullName>Sales_Coordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Coordinator</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Astrum_Sales_Regions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Astrum Sales Region</label>
    <nameField>
        <label>Sales Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Astrum Sales Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Office_Location__c.object
<CustomObject>
    <fields>
        <fullName>Regional_Operations_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Regional Operations Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Office_Locations3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Coordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Coordinator</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserType</field>
                <operation>equals</operation>
                <value>Standard</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Office_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey_Scheduler__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey Scheduler</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Office_Locations2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Office Location</label>
    <nameField>
        <label>Office Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Property_City__c</fullName>
        <description>Initially used in code to cut back on extra SOQL queries in triggers.</description>
        <formula>Property__r.Property_City__c</formula>
        <label>Property City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_County__c</fullName>
        <formula>TEXT(Property__r.Property_County__c)</formula>
        <label>Property County</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <formula>TEXT(Property__r.Property_State__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Zip__c</fullName>
        <description>Initially used in code to cut back on extra SOQL queries in triggers.</description>
        <formula>Property__r.Property_ZIP__c</formula>
        <label>Property Zip</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Property__c.Property_Owner__r.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <description>AstrumPM/AstrumCRM - Each account can have one or more properties.  A property is defined by its street address.</description>
    <fields>
        <fullName>Astrum_Office_New__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Astrum Office Lookup</label>
        <referenceTo>Office_Location__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Astrum_Office__c</fullName>
        <label>Astrum Office</label>
        <picklist>
            <picklistValues>
                <fullName>Columbia, MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corona, CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cromwell, CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fresno, CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Henrietta, NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hopkinton, MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Long Island, NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middletown, NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Norristown, PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pennsauken, NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>San Diego, CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Simi Valley, CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Syracuse, NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taunton, MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Westford, MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Youngstown, OH</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Astrum_Sales_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Astrum Sales Region</label>
        <referenceTo>Astrum_Sales_Region__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_City__c</fullName>
        <label>Property City</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_County__c</fullName>
        <label>Property County</label>
        <picklist>
            <controllingField>Property_State__c</controllingField>
            <picklistValues>
                <fullName>Accomack</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adams</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alameda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albemarle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alcona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alexandria City</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alger</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allegan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allegany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alleghany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allegheny</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alpena</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alpine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amador</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amelia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amherst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anne Arundel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antrim</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apache</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appomattox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arenac</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arlington</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armstrong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ashland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ashtabula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Athens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Atlantic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auglaize</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>Property State</label>
        <picklist>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property_ZIP__c</fullName>
        <label>Property ZIP</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Address 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <recordTypes>
        <fullName>Commercial</fullName>
        <active>true</active>
        <label>Commercial</label>
    </recordTypes>
    <recordTypes>
        <fullName>Residential</fullName>
        <active>true</active>
        <label>Residential</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TaskTriggerHandler.cls
/* 
 * AUTHOR:Rohit Jain
 * DATE: 2016-02-05
 * PURPOSE: A single trigger handler for the Task object.
 * MODIFICATION HISTORY:
 *     
 */
public without sharing class TaskTriggerHandler {

    private boolean m_isExecuting = false;

    private map<string, Schema.RecordTypeInfo> eventRecordTypeNameMap;
    private map<id, Schema.RecordTypeInfo> eventRecordTypeIDMap;    
    private set<id> salesVisitRTIDs;
    final String SURVEYTYPE_RESIDENTIAL_REMOTE_SURVEY = 'Residential Remote Survey';
    final String SURVEYTYPE_RESIDENTIAL_FIELD_SURVEY = 'Residential Field Survey';
    final String SURVEYTYPE_COMMERCIAL_SURVEY = 'Commercial Survey';
    final String SURVEYTYPE_CHANNEL_SURVEY = 'Channel Survey';

    public TaskTriggerHandler(boolean isExecuting){
        m_isExecuting = isExecuting;
    	system.debug('TaskTriggerHandler');
        
        //Load recordtypes for Event
        Schema.DescribeSObjectResult dsr = Event.SObjectType.getDescribe();
        eventRecordTypeNameMap = dsr.getRecordTypeInfosByName();
        eventRecordTypeIDMap = dsr.getRecordTypeInfosById();

        salesVisitRTIDs = new set<id>();
        salesVisitRTIDs.add(eventRecordTypeNameMap.get('Sales Visit Onsite').getRecordTypeID());
        salesVisitRTIDs.add(eventRecordTypeNameMap.get('Sales Visit Remote').getRecordTypeID());        
        
    }
    
    public void OnBeforeInsert(Task[] newTasks){
        // EXECUTE BEFORE INSERT LOGIC    
        setSiteSurveyDate(newTasks);     
        m_isExecuting = false;
    }

    private void setSiteSurveyDate(Task[] insertedUpdatedTasks){
    	Set<id> whatIds = new Set<id>();
        for(Task ts: insertedUpdatedTasks) {
        	system.debug('TaskTriggerHandler ts.Site_Survey_Type__c '+ ts.Site_Survey_Type__c);
        	if(ts.whatid != null && ((string)ts.whatid).startsWith('006')){ //&& (ts.Site_Survey_Type__c == 'Site Survey Onsite')){
            	whatIds.add(ts.whatID);
            	system.debug('TaskTriggerHandler '+ ts.whatid );
            }
        }
        Map<id, Opportunity> OppMap = new Map<id,Opportunity>([ Select Id, o.Account.Name, o.Property__r.Property_County__c, o.Property__r.Property_ZIP__c, o.Property__r.Property_State__c, o.Property__r.Property_City__c, o.Property__r.Name, o.Property__r.Astrum_Office__c, o.Property__c, 
                                  o.Owner.Email, o.Owner.FirstName, o.Owner.LastName, o.Owner.Manager.Email, o.OwnerId, o.Name  , o.Property__r.Astrum_Office_New__r.Sales_Coordinator__r.Id,  o.Property__r.Astrum_Sales_Region__r.Sales_Coordinator__r.Id                              
                                  , o.Property__r.Astrum_Office_New__r.Regional_Operations_Manager__c, o.Property__r.Astrum_Office_New__r.Survey_Scheduler__c
                                  , (SELECT StartDateTime FROM Events WHERE RecordTypeId IN:salesVisitRTIDs AND isChild= false and Completed__c = false LIMIT 1)
                                  From Opportunity o 
                                  where id in :whatIds]);

       system.debug('TaskTriggerHandler oppMap '+ OppMap);
        
       for(Task ts: insertedUpdatedTasks) {
        	if(ts.whatid != null && ((string)ts.whatid).startsWith('006')){
                if(ts.Site_Survey_Type__c == SURVEYTYPE_RESIDENTIAL_FIELD_SURVEY 
                    || ts.Site_Survey_Type__c == SURVEYTYPE_COMMERCIAL_SURVEY){
                    ts.OwnerId = OppMap.get(ts.whatid).Property__r.Astrum_Office_New__r.Survey_Scheduler__c != null ? 
                            OppMap.get(ts.whatid).Property__r.Astrum_Office_New__r.Survey_Scheduler__c : ts.OwnerId ;

                    system.debug('TaskTriggerHandler oppMap '+ OppMap.get(ts.whatid).Events );
                    System.debug('**recType:' + ts.RecordType + ':' + ts.RecordTypeId);                      

                }else if(ts.Site_Survey_Type__c == SURVEYTYPE_RESIDENTIAL_REMOTE_SURVEY 
                    || ts.Site_Survey_Type__c == SURVEYTYPE_CHANNEL_SURVEY){
                    ts.OwnerId = OppMap.get(ts.whatid).Property__r.Astrum_Office_New__r.Sales_Coordinator__r.Id != null ? 
                            OppMap.get(ts.whatid).Property__r.Astrum_Office_New__r.Sales_Coordinator__r.Id : ts.OwnerId ;
                }else if(String.isBlank(ts.Site_Survey_Type__c)){
                    ts.OwnerId = UserInfo.getUserId();
                }

                if(OppMap.get(ts.whatid).Events != null 
                    && !(OppMap.get(ts.whatid).Events.isEmpty())
                    && (ts.activityDate != null && ts.activityDate > OppMap.get(ts.whatid).Events[0].StartDateTime.date())){
                    System.debug('setting due date: ' + ts.activitydate + 'sales startdate:' + OppMap.get(ts.whatid).Events[0].StartDateTime.date());
                    ts.activitydate = OppMap.get(ts.whatid).Events[0].StartDateTime.date();
                }
            	
            }
        }

    }
}