src/objects/Astrum_Sales_Region__c.object
<CustomObject>
    <description>Astrum Sales Regions</description>
    <label>Astrum Sales Region</label>
    <nameField>
        <label>Sales Region</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Astrum Sales Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Office_Location__c.object
<CustomObject>
    <fields>
        <fullName>State_Coverage__c</fullName>
        <description>Install States Covered by Astrum Office</description>
        <inlineHelpText>Install States Covered by Astrum Office</inlineHelpText>
        <label>State Coverage</label>
        <picklist>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Office Location</label>
    <nameField>
        <label>Office Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <description>AstrumPM/AstrumCRM - Each account can have one or more properties.  A property is defined by its street address.</description>
    <fields>
        <fullName>Astrum_Office__c</fullName>
        <label>Astrum Office</label>
        <picklist>
            <picklistValues>
                <fullName>Columbia, MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corona, CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cromwell, CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fresno, CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Henrietta, NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hopkinton, MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Long Island, NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middletown, NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Norristown, PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pennsauken, NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>San Diego, CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Simi Valley, CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Syracuse, NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taunton, MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Westford, MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Youngstown, OH</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Astrum_Sales_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Astrum Sales Region</label>
        <referenceTo>Astrum_Sales_Region__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_County__c</fullName>
        <label>Property County</label>
        <picklist>
            <controllingField>Property_State__c</controllingField>
            <picklistValues>
                <fullName>Accomack</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adams</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alameda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albemarle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alcona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alexandria City</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alger</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allegan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allegany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alleghany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allegheny</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alpena</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alpine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amador</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amelia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amherst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anne Arundel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antrim</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apache</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appomattox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arenac</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arlington</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armstrong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ashland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ashtabula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Athens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Atlantic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auglaize</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>Property State</label>
        <picklist>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>QAS_Latitude__c</fullName>
        <description>QAS Auto-Populated Latitude</description>
        <inlineHelpText>QAS Auto-Populated Latitude</inlineHelpText>
        <label>QAS Latitude</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QAS_Longitude__c</fullName>
        <description>QAS Auto-Populated Longitude</description>
        <inlineHelpText>QAS Auto-Populated Longitude</inlineHelpText>
        <label>QAS Longitude</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QAS_Property_County__c</fullName>
        <description>Auto-Populated County From QAS</description>
        <inlineHelpText>Auto-Populated County From QAS</inlineHelpText>
        <label>QAS Property County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Region__c</fullName>
        <label>Sales Region</label>
        <picklist>
            <picklistValues>
                <fullName>CA Region</fullName>
                <color>#006600</color>
            </picklistValues>
            <picklistValues>
                <fullName>CT Region</fullName>
                <color>#33FFFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>MA Region</fullName>
                <color>#FFCC66</color>
            </picklistValues>
            <picklistValues>
                <fullName>MD Region</fullName>
                <color>#6600CC</color>
            </picklistValues>
            <picklistValues>
                <fullName>NJ Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NYC Region</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>OH Region</fullName>
                <color>#3366FF</color>
            </picklistValues>
            <picklistValues>
                <fullName>PA Region</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>WNY Region</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Address 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Property_Batch_Update.cls
global class Property_Batch_Update implements Database.Batchable<sObject>{
public String query = 'Select Name,Astrum_Office__c,QAS_Property_County__c,QAS_Latitude__c,QAS_Longitude__c, Property_State__c,Property_County__C from Property__c ' ;
public String batch = 'Office';


global Database.QueryLocator start(Database.BatchableContext BC){
    return Database.getQueryLocator(query);
}

global void execute(Database.BatchableContext BC, List<sObject> scope){
    List<Property__c> propUpdate = new List<Property__c>();
    if(batch == 'Office') {
        List<Office_Location__c> officeLocations = [Select Name,Location__Latitude__s, Location__Longitude__s,State_Coverage__c from Office_Location__c];
      
        Map<String,String> officeMap = new Map<String,String>();
        String[] tmpString;
       
        for (Office_Location__c ol :officeLocations  )
        {   
            System.Debug('**Prop Off');
            if(ol.State_Coverage__c != null)
                tmpString = ol.State_Coverage__c.split(';');
                
            if(tmpString != null && tmpString.size() > 0) 
            {
               for(String s : tmpString)
                    officeMap.put(s,ol.Name);   
               tmpString.clear();          
            }        
            
        }
            
        for(sObject s : scope)
        {
          
          Property__c propUpd = (Property__c)s;
          System.Debug('**Prop Off-'+propUpd.Name);
          propUpd.Astrum_Office__c = Astrum_Distance_Calculation.assignOfficeToProperty(officeMap,officeLocations,propUpd);  
          System.debug('Property - '+propUpd.Name);
          if(propUpd.Astrum_Office__c != null)
              propUpdate.add(PropUpd);           
                
        }
        if(! propUpdate.isEmpty())
            update(propUpdate); 
    }
    else if( batch == 'SalesRegion')
    {
         Map<String, Astrum_Sales_Region__c> salesRegionMap = new Map<String, Astrum_Sales_Region__c>(); 
         for( Astrum_Sales_Region__c objCS : [Select z.Name, z.Id From  Astrum_Sales_Region__c z])
            salesRegionMap.put(objCS.Name, objCS);
    
         for(sObject s : scope)
         { 
              Property__c p = (Property__c)s;
              p.Astrum_Sales_Region__c = salesRegionMap.get(p.Sales_Region__c).Id;      
              propUpdate.add(p);         
         }
         if(! propUpdate.isEmpty())
             update(propUpdate);   
    }   
  
}
global void finish(Database.BatchableContext BC){
  }

     
}