src/objects/Astrum_Doc__c.object
<CustomObject>
    <fields>
        <fullName>Bin__c</fullName>
        <description>Astrum PM Bin</description>
        <label>Bin</label>
        <picklist>
            <picklistValues>
                <fullName>Kickoff Photos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signed Conduit Run and Layout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drivers Licenses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Install Prep Sheet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utility Bill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ SREC Docs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permit Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrical Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Permit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrical Permit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utility Interconnect Part 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Notice to Construct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grant Reservation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOA Submitted Documents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoice at Start of Installation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Equip. Delivery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation Photos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panel and Inverter Serial Numbers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pull List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunpower Warranty Cards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enphase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Comm. Checklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proof of Inspection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Subst. Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utility Interconnect Part 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grant Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property Tax</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SREC Docs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Final Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Completion Forms</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <controllingField>Bin__c</controllingField>
            <picklistValues>
                <fullName>3 Line diagram</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acceptance Letter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Affidavit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved Application Part 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved Building Permit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved Electrical Permit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved Utility Interconnect Part 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved Utility Interconnect Part 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Array Detail Photos: Clearance, Pitch, Clamps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Branch Map</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Permit Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CB Panel, Interconnect, Disconnect Box Photos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certificate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certification Document</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commissioning and Production Verification Checklists</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commissioning Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completion Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conduit (Roof, Interior, Exterior) Photos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conduit Run and Layout - Customer Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivered Materials Photo (NRG only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drawing Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drivers License</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrical Drawings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrical Permit Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy Audit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineering Permit Design Package</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Document_Key_Date__c</fullName>
        <label>Document Key Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PM_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Document is linked to an Astrum PM project</description>
        <label>PM Project</label>
        <referenceTo>PM_Project__c</referenceTo>
        <relationshipLabel>Astrum Docs</relationshipLabel>
        <relationshipName>Astrum_Docs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Verified__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Verified</label>
        <type>Checkbox</type>
    </fields>
    <label>Astrum Doc</label>
    <nameField>
        <displayFormat>AD-{0000000}</displayFormat>
        <label>Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Astrum Docs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PM_Project__c.object
<CustomObject>
    <description>Astrum PM 2.0 Project Object</description>
    <label>PM Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PM Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DocumentPrintController.cls
/* FILE: DocumentPrintController.cls
 * AUTHOR: Tino Mattheou
 * DATE: June 6, 2012
 * PURPOSE: Controller for DocumentPrint page.  Displays only selected image files in a PDF
 * MODIFICATION HISTORY
 * 06/28/2012 TCM - zen-10 create image thumbnails when uploading 
 * 01/25/2013 TCM - zen-38 portrait images split - use landscape portrait settings
 * 01/28/2013 TCM - zen-24 print project notes with images
 */ 

public class DocumentPrintController {

	private String projectId;
	private Map<String,String> orientationMap = new Map<String,String>();  

	private List<String> selectedIds;
	private List<String> noteIds;
	
	public DocumentPrintController() {
		Map<String,String> params = ApexPages.currentPage().getParameters();
		projectId = params.get('id');
		String selection = params.get('ids');
		if (selection != null) {
			selectedIds = selection.split(' ');
		}
		String orients = params.get('orients');
		if (selection != null && orients != null) {
			List<String> orientations = orients.split(' ');
			if (selectedIds.size() == orientations.size()) {
				for (Integer i = 0; i < selectedIds.size(); i++) {
					orientationMap.put(selectedIds[i], orientations[i]);
				}
			}
		}
		String notes = params.get('noteIds');
		if (notes != null) {
			noteIds = notes.split(' ');
		}
	}
	
	public PM_Project__c getProject() {
		
		PM_Project__c result;
		
		if (projectId != null) {
			result = [SELECT Id, Name FROM PM_Project__c WHERE Id = :projectId];
		}
		
		return result; 
	}
	
	public List<Astrum_Doc__c> getDocuments() {
		
		List<Astrum_Doc__c> result;
		
		if (selectedIds != null && selectedIds.size() > 0) {
			
			Map<Id,Id> docToThumbMap = new Map<Id,Id>();
			
			Set<Id> docIds = new Set<Id>();
			List<Attachment> atts = [SELECT Id, ParentId FROM Attachment WHERE Id IN :selectedIds];
			
			for (Attachment a : atts) {
				docIds.add(a.ParentId);
				docToThumbMap.put(a.ParentId, a.Id);
			}
			
			result = [
				SELECT Id, Category__c, Bin__c,
			 		(SELECT Id, Name, Description FROM Attachments ORDER BY BodyLength DESC LIMIT 1)
			 	FROM Astrum_Doc__c
			 	WHERE Id IN :docIds
			];	
			
			for (Astrum_Doc__c doc : result) {
				for (Attachment att : doc.Attachments) {
					att.Description = orientationMap.get(docToThumbMap.get(doc.Id));
				}
			}
			
		}
		
		return result;
		
	} 
	
	public List<Astrum_Doc__c> getNotes() {
		
		List<Astrum_Doc__c> result;
		
		if (noteIds != null && noteIds.size() > 0) {

			Map<Id,Id> docToThumbMap = new Map<Id,Id>();
			
			Set<Id> docIds = new Set<Id>();
			List<Note> notes = [SELECT Id, ParentId FROM Note WHERE Id IN :noteIds];
			
			for (Note n : notes) {
				docIds.add(n.ParentId);
			}
			
			result = 
				[SELECT Id, Name, CreatedDate, CreatedBy.Name, Document_Key_Date__c, Verified__c, Category__c, Bin__c, 
					(SELECT Id, Title, Body, LastModifiedDate, LastModifiedBy.Name
			 		FROM Notes 
			 		ORDER BY CreatedDate DESC LIMIT 1) 
				FROM Astrum_Doc__c
				WHERE Id IN :docIds
				ORDER BY Bin__c, Category__c, Name];
			
		}
		
		return result;
		
	} 

}