src/objects/Astrum_Doc__c.object
<CustomObject>
    <fields>
        <fullName>Bin__c</fullName>
        <description>Astrum PM Bin</description>
        <label>Bin</label>
        <picklist>
            <picklistValues>
                <fullName>Kickoff Photos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signed Conduit Run and Layout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drivers Licenses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Install Prep Sheet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utility Bill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ SREC Docs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permit Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrical Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Permit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrical Permit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utility Interconnect Part 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Notice to Construct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grant Reservation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOA Submitted Documents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoice at Start of Installation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Equip. Delivery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation Photos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panel and Inverter Serial Numbers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pull List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunpower Warranty Cards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enphase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Comm. Checklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proof of Inspection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Subst. Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utility Interconnect Part 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grant Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property Tax</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SREC Docs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Final Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Completion Forms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kickoff Documents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Final Documents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permitting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Permit Documents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Structural Engineering</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <controllingField>Bin__c</controllingField>
            <picklistValues>
                <fullName>3 Line diagram</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acceptance Letter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Affidavit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved Application Part 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved Building Permit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved Electrical Permit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved Utility Interconnect Part 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved Utility Interconnect Part 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Array Detail Photos: Clearance, Pitch, Clamps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Branch Map</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Permit Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CB Panel, Interconnect, Disconnect Box Photos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certificate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certification Document</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commissioning and Production Verification Checklists</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commissioning Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completion Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conduit (Roof, Interior, Exterior) Photos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conduit Run and Layout - Customer Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivered Materials Photo (NRG only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drawing Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drivers License</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrical Drawings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrical Permit Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy Audit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineering Permit Design Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final PDP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Historical Document</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOA Document</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Install Prep Sheet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property Photo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Structural Drawings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Structural Engineering Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Structural Engineer Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System Design Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utility Bill</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PM_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Document is linked to an Astrum PM project</description>
        <label>PM Project</label>
        <referenceTo>PM_Project__c</referenceTo>
        <relationshipLabel>Astrum Docs</relationshipLabel>
        <relationshipName>Astrum_Docs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Astrum Doc</label>
    <nameField>
        <displayFormat>AD-{0000000}</displayFormat>
        <label>Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Astrum Docs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PM_Project__c.object
<CustomObject>
    <description>Astrum PM 2.0 Project Object</description>
    <label>PM Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PM Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PMProjUpdateBinCatBatch.cls
/*
 *  PMProjUpdateBinCatBatch projBatch = new PMProjUpdateBinCatBatch();
 *  Id batchId = Database.executeBatch(projBatch, 250);
 *  TODO: Bin complete check. If the bindate is null check for if bin is complate and update bin date.
 *  
 */
global class PMProjUpdateBinCatBatch implements Database.Batchable<sObject>, Database.Stateful{
    
    public String errors = '';
    private Integer batchNumber = 0;    
    
    global PMProjUpdateBinCatBatch(){}
    
    global Database.QueryLocator start(Database.BatchableContext bc){
        
        String query ='';
        query+= 'SELECT Id, Bin__c, PM_Project__c, Category__c ';
        query+= ' FROM Astrum_Doc__c';
        query+= ' WHERE PM_Project__c <> null AND Bin__c <> null AND Category__c <> null';
        query+= ' AND Bin__c IN(\'Drivers Licenses\',\'Kickoff Photos\', \'HOA Submitted Documents\',\'Utility Bill\'';
        query+= '   , \'Install Prep Sheet\', \'Signed Conduit Run and Layout\', \'Permit Design\'';
        query+= '   , \'Building Permit\', \'Electrical Permit\')';
        System.debug('*Query '+query);
        return Database.getQueryLocator(query);
        
    }
    
    global void execute(Database.BatchableContext bc, List<sObject> scope){

        List<Astrum_Doc__c> docsToUpdate = new List<Astrum_Doc__c>();
        
        for(SObject s: scope)
        {
            Astrum_Doc__c doc = (Astrum_Doc__c)s;
            docsToUpdate.add(doc);
        }

        //Reset Bin/Cat to new values
        for(Astrum_Doc__c doc: docsToUpdate){
            if(doc.Bin__c.equalsIgnoreCase('Drivers Licenses') &&  doc.Category__c.equalsIgnoreCase('Drivers License')){
                doc.Bin__c = 'Kickoff Documents';
            }
            if(doc.Bin__c.equalsIgnoreCase('Kickoff Photos') &&  doc.Category__c.equalsIgnoreCase('Property Photo')){
                doc.Bin__c = 'Kickoff Documents';
            }
            if(doc.Bin__c.equalsIgnoreCase('HOA Submitted Documents') &&  (doc.Category__c.equalsIgnoreCase('HOA Document') || doc.Category__c.equalsIgnoreCase('Historical Document'))){
                doc.Bin__c = 'Kickoff Documents';
            }            
            if(doc.Bin__c.equalsIgnoreCase('Utility Bill') &&  doc.Category__c.equalsIgnoreCase('Utility Bill')){
                doc.Bin__c = 'Kickoff Documents';
            }
            if(doc.Bin__c.equalsIgnoreCase('Install Prep Sheet') &&  doc.Category__c.equalsIgnoreCase('Install Prep Sheet')){
                doc.Bin__c = 'Kickoff Documents';
            }

            if(doc.Bin__c.equalsIgnoreCase('Signed Conduit Run and Layout') &&  doc.Category__c.equalsIgnoreCase('Conduit Run and Layout - Customer Signed')){
                doc.Bin__c = 'Approval Final Documents';
            }
            if(doc.Bin__c.equalsIgnoreCase('Permit Design') &&  doc.Category__c.equalsIgnoreCase('Structural Engineer Review')){
                doc.Bin__c = 'Structural Engineering';
            }
            if(doc.Bin__c.equalsIgnoreCase('Building Permit') &&  (doc.Category__c.equalsIgnoreCase('Building Permit Package') || doc.Category__c.equalsIgnoreCase('Approved Building Permit'))){
                doc.Bin__c = 'Permitting';
            }
            if(doc.Bin__c.equalsIgnoreCase('Electrical Permit') &&  (doc.Category__c.equalsIgnoreCase('Electrical Permit Package') || doc.Category__c.equalsIgnoreCase('Approved Electrical Permit'))){
                doc.Bin__c = 'Permitting';
            }
            // additional steps added later
            if(doc.Bin__c.equalsIgnoreCase('Permit Design') &&  (doc.Category__c.equalsIgnoreCase('System Design Plan'))){
                doc.Bin__c = 'Final Permit Documents';
                doc.Category__c = 'Final PDP';
            }
            if(doc.Bin__c.equalsIgnoreCase('Permit Design') &&  (doc.Category__c.equalsIgnoreCase('Structural Drawings'))){
                doc.Bin__c = 'Final Permit Documents';
                doc.Category__c = 'Structural Engineering Review';
            }             
        }
        TriggerUtility.skipAstrumDocVerificationTrigger = true;
        Database.SaveResult[] results;
        if(!docsToUpdate.isEmpty()){
            results = Database.update(docsToUpdate,false);
            for (Database.SaveResult result : results) {
                if (!result.isSuccess()) {
                    // Operation failed, so get all errors                
                    for(Database.Error err : result.getErrors()) {
                        errors += result.getId() + ':'+err.getFields() + ':' + err.getStatusCode() + ': ' + err.getMessage() +'\n\n';
                    }
                }
            } 
        }
        TriggerUtility.skipAstrumDocVerificationTrigger = false;

    }
    
    global void finish(Database.BatchableContext bc){
        String[] toAddresses = new String[]{'pavitra.burla@directenergysolar.com'};
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setToAddresses(toAddresses);
        
        if (!String.isBlank(errors)) {            
            mail.setSubject('PM Project Bin/Categories Update completed with Errors');
            mail.setPlainTextBody(errors);                 
        }
        else{
            mail.setSubject('M Project Bin/Categories Update completed successfully without errors');
            mail.setPlainTextBody(errors);            
        }        
        mail.setSaveAsActivity(false);
        Messaging.sendEmail(new Messaging.Email[] { mail }, false);
        
    }

}