src/objects/Astrum_Contract__c.object
<CustomObject>
    <description>Contract object to facilitate Conga Contracts</description>
    <fields>
        <fullName>Lease_Fund__c</fullName>
        <formula>IF (ISPICKVAL(Scenario__c, &apos;1&apos;),
	Proposal__r.System_Design_Quote__r.Scenario_1_Lease_Fund__r.Name,
	
	IF (ISPICKVAL(Scenario__c, &apos;2&apos;),
		Proposal__r.System_Design_Quote__r.Scenario_2_Lease_Fund__r.Name,
		
		IF (ISPICKVAL(Scenario__c, &apos;3&apos;),
			Proposal__r.System_Design_Quote__r.Scenario_3_Lease_Fund__r.Name,
			
			IF (ISPICKVAL(Scenario__c, &apos;4&apos;),
				Proposal__r.System_Design_Quote__r.Scenario_4_Lease_Fund__r.Name, &apos;&apos;
			)
		)
	)
)</formula>
        <label>Lease Fund</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PPA_System_Buyout_Basis_EPC__c</fullName>
        <description>See the &quot;System Buyout Basis EPC&quot; field on Lease Fund</description>
        <label>PPA System Buyout Basis EPC</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <label>Astrum Contract</label>
    <nameField>
        <displayFormat>AC-{MM}-{DD}-{YY}-{0000}</displayFormat>
        <label>Astrum Contracts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Astrum Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lease_Fund__c.object
<CustomObject>
    <label>Lease Fund</label>
    <nameField>
        <label>Lease Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lease Funds</pluralLabel>
    <recordTypes>
        <fullName>Lease</fullName>
        <active>true</active>
        <description>Lease Funding Record</description>
        <label>Lease</label>
    </recordTypes>
    <recordTypes>
        <fullName>PPA</fullName>
        <active>true</active>
        <description>PPA Funding Record</description>
        <label>PPA</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/System_Design__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The Solar System Design.  Each Property can have one or more System Designs created as the result of a site Survey and the discovery of Install Locations.  Each System Design is made up of one or more System Design Arrays.</description>
    <fields>
        <fullName>Total_System_Size_kW__c</fullName>
        <label>Total System Size (kW)</label>
        <summarizedField>System_Design_Array__c.Array_Size_kW__c</summarizedField>
        <summaryForeignKey>System_Design_Array__c.System_Design__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>System Design</label>
    <nameField>
        <displayFormat>SD-{0}</displayFormat>
        <label>System Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Designs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/System_Design_Quote__c.object
<CustomObject>
    <description>AstrumCRM - System Design Quote.  Each System Design can have one or more System Design Quotes.  Each quote provides the sales consultant with the ability to adjust the negotiated price of the System Design based on the Calculated System Price.  Opportunities must choose a winning System Design Quote in order to close.</description>
    <fields>
        <fullName>Scenario_1_Included_in_Proposal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Scenario 1 Included in Proposal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>System_Design__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>System Design</label>
        <referenceTo>System_Design__c</referenceTo>
        <relationshipLabel>System Design Quotes</relationshipLabel>
        <relationshipName>System_Design_Quotes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Size_kW__c</fullName>
        <formula>System_Design__r.Total_System_Size_kW__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>System Size (kW)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_System_Size_kW__c</fullName>
        <label>Total System Size (kW)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>System Design Quote</label>
    <nameField>
        <displayFormat>SDQ-{0}</displayFormat>
        <label>System Design Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Design Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AstrumContractCalculationsTest.cls
/*  FILE: AstrumContractCalculationsTest
    AUTHOR: Dan Kelner
    DATE: 04/13/15
    PURPOSE: Test class for AstrumContractCalculations
    MODIFICATION HISTORY
*/
@isTest
public class AstrumContractCalculationsTest {

    @isTest(seeAllData = false) static void contractCreationTest(){
        testData.setupCustomSettingsPricing();
        testData.setupCustomConfigObjectsPricing();
        Lease_Fund__c[] funds = testData.createLeaseFunds();    //Fund[0] - SAC Loan, Fund[1] - Term Loan, Fund[2] - Lease, Fund[3] - Term & SAC 

        //Create our test data
        //ID sdID = testData.setupSystemDesign('Residential', 'Purchase', null, false, 12000);
        //System_Design__c sysDesign = new System_Design__c(ID = sdID);
        //update sysDesign;

        //System_Design_Quote__c sdq = SalesWorkflowValidationUtility.systemDesignQuoteWorkflowOnCreate(sysDesign);
        System_Design_Quote__c sdq = TestData.setupSystemDesignQuotePricing('Residential', funds, false, 12000);

        sdq.Scenario_1_Included_in_Proposal__c = true;
        sdq.Total_System_Size_kW__c = sdq.System_Size_kW__c != null ? sdq.System_Size_kW__c : 7.5;
        SystemDesignQuoteTriggerHandler.skipSystemDesignQuoteTrigger = true;
        update sdq;
        SystemDesignQuoteTriggerHandler.skipSystemDesignQuoteTrigger = false;
        
        Test.startTest();
        ProposalProcessor pp = new ProposalProcessor();
        ID propID = pp.createProposal(sdq, true, true, false, false, false, null);
        
        Astrum_Contract__c contr = AstrumContractCalculations.initilizeContract(propID, 1);
        contr.PPA_System_Buyout_Basis_EPC__c = 4.32;    //Set this manually because the financing type isn't PPA
        insert contr;

        contr = Database.query('SELECT ' + AstrumContractCalculations.allContractFields + ' FROM Astrum_Contract__c WHERE ID = \'' + contr.ID + '\'');
        AstrumContractCalculations.getOneRoofBuyoutCostsPPA(contr, 0.5);    //CPQ-749
        Test.stopTest();        
    }
}