src/objects/Astrum_Daily_Report__c.object
<CustomObject>
    <fields>
        <fullName>Daily_Goal_Avg_Time_Opty_to_Sales_Visit__c</fullName>
        <label>Daily Goal Avg Time Opty to Sales Visit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Daily_Goal_Avg_Time_Sales_to_Inspection__c</fullName>
        <label>Daily Goal Avg Time Sales to Inspection</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Daily_Goal_Cancel_KW_Num__c</fullName>
        <label>Daily Goal Cancel KW Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Daily_Goal_Cancel_Num__c</fullName>
        <label>Daily Goal Cancel Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Daily_Goal_Inspection_KW_Num__c</fullName>
        <label>Daily Goal Inspection KW Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Daily_Goal_Inspection_Num__c</fullName>
        <label>Daily Goal Inspection Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Daily_Goal_Leads_Num__c</fullName>
        <label>Daily Goal Leads Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Daily_Goal_Oppty_Num__c</fullName>
        <label>Daily Goal Oppty Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Daily_Goal_Sales_KW_Num__c</fullName>
        <label>Daily Goal Sales KW Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Daily_Goal_Sales_Num__c</fullName>
        <label>Daily Goal Sales Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Daily_Stretch_Goal_Avg_Time_to_Ins__c</fullName>
        <label>Daily Stretch Goal Avg Time to Ins</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Daily_Stretch_Goal_Avg_Time_to_Sales__c</fullName>
        <label>Daily Stretch Goal Avg Time To Sales</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Daily_Stretch_Goal_Leads_Num__c</fullName>
        <label>Daily Stretch Goal Leads Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Daily_Stretch_Goal_Oppty_Num__c</fullName>
        <label>Daily Stretch Goal Oppty Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Daily_Stretch_Goal_Sales_Num__c</fullName>
        <label>Daily Stretch Goal Sales Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Daily_Stretch_Goal_Sales_kw_Num__c</fullName>
        <label>Daily Stretch Goal Sales kw Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Daily_Stretch_Goal_cancel_Num__c</fullName>
        <label>Daily Stretch Goal cancel Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Daily_Stretch_Goal_cancel_kw_Num__c</fullName>
        <label>Daily Stretch Goal cancel kw Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Daily_Stretch_Goal_inspection_Num__c</fullName>
        <label>Daily Stretch Goal inspection Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Daily_Stretch_Goal_inspection_kw_Num__c</fullName>
        <label>Daily Stretch Goal inspection kw Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_Goal_Avg_Time_Opty_to_Sales_Visit__c</fullName>
        <label>Month Goal Avg Time Opty to Sales Visit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_Goal_Avg_Time_Sales_to_Inspection__c</fullName>
        <label>Month Goal Avg Time Sales to Inspection</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_Stretch_Goal_Avg_Time_to_Ins__c</fullName>
        <label>Month Stretch Goal Avg Time to Ins</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Month_Stretch_Goal_Avg_Time_to_Sales__c</fullName>
        <label>Month Stretch Goal Avg Time to Sales</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Goal_Cancel_KW_Num__c</fullName>
        <label>Monthly Goal Cancel KW Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Goal_Cancel_Num__c</fullName>
        <label>Monthly Goal Cancel Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Goal_Inspection_KW_Num__c</fullName>
        <label>Monthly Goal Inspection KW Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Goal_Inspection_Num__c</fullName>
        <label>Monthly Goal Inspection Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Goal_Leads_Num__c</fullName>
        <label>Monthly Goal Leads Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Goal_Oppty_Num__c</fullName>
        <label>Monthly Goal Oppty Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Goal_Sales_KW_Num__c</fullName>
        <label>Monthly Goal Sales KW Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Goal_Sales_Num__c</fullName>
        <label>Monthly Goal Sales Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Stretch_Goal_Leads_Num__c</fullName>
        <label>Monthly Stretch Goal Leads Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Stretch_Goal_Oppty_Num__c</fullName>
        <label>Monthly Stretch Goal Oppty Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Stretch_Goal_Sales_Num__c</fullName>
        <label>Monthly Stretch Goal Sales Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Stretch_Goal_Sales_kw_Num__c</fullName>
        <label>Monthly Stretch Goal Sales kw Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Stretch_Goal_cancel_Num__c</fullName>
        <label>Monthly Stretch Goal cancel Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Stretch_Goal_cancel_kw_Num__c</fullName>
        <label>Monthly Stretch Goal cancel kw Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Stretch_Goal_inspection_Num__c</fullName>
        <label>Monthly Stretch Goal inspection Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Stretch_Goal_inspection_kw_Num__c</fullName>
        <label>Monthly Stretch Goal inspection kw Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year_Stretch_Goal_Avg_Time_to_Ins__c</fullName>
        <label>Year Stretch Goal Avg Time to Ins</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year_Stretch_Goal_Avg_Time_to_Sales__c</fullName>
        <label>Year Stretch Goal Avg Time to Sales</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Yearly_Goal_Avg_Time_Opty_to_Sales_Visit__c</fullName>
        <label>Yearly Goal Avg Time Opty to Sales Visit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Yearly_Goal_Avg_Time_Sales_to_Inspection__c</fullName>
        <label>Yearly Goal Avg Time Sales to Inspection</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Yearly_Goal_Cancel_KW_Num__c</fullName>
        <label>Yearly Goal Cancel KW Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Yearly_Goal_Cancel_Num__c</fullName>
        <label>Yearly Goal Cancel Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Yearly_Goal_Inspection_KW_Num__c</fullName>
        <label>Yearly Goal Inspection KW Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Yearly_Goal_Inspection_Num__c</fullName>
        <label>Yearly Goal Inspection Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Yearly_Goal_Leads_Num__c</fullName>
        <label>Yearly Goal Leads Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Yearly_Goal_Oppty_Num__c</fullName>
        <label>Yearly Goal Oppty Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Yearly_Goal_Sales_KW_Num__c</fullName>
        <label>Yearly Goal Sales KW Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Yearly_Goal_Sales_Num__c</fullName>
        <label>Yearly Goal Sales Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Yearly_Stretch_Goal_Leads_Num__c</fullName>
        <label>Yearly Stretch Goal Leads Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Yearly_Stretch_Goal_Oppty_Num__c</fullName>
        <label>Yearly Stretch Goal Oppty Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Yearly_Stretch_Goal_Sales_Num__c</fullName>
        <label>Yearly Stretch Goal Sales Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Yearly_Stretch_Goal_Sales_kw_Num__c</fullName>
        <label>Yearly Stretch Goal Sales kw Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Yearly_Stretch_Goal_cancel_Num__c</fullName>
        <label>Yearly Stretch Goal_cancel Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Yearly_Stretch_Goal_cancel_kw_Num__c</fullName>
        <label>Yearly Stretch Goal cancel kw Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Yearly_Stretch_Goal_inspection_Num__c</fullName>
        <label>Yearly Stretch Goal inspection Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Yearly_Stretch_Goal_inspection_kw_Num__c</fullName>
        <label>Yearly Stretch Goal inspection kw Num</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Astrum Daily Report</label>
    <nameField>
        <displayFormat>ADR-{000000}</displayFormat>
        <label>Astrum Daily Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Astrum Daily Report</pluralLabel>
    <recordTypes>
        <fullName>Goal</fullName>
        <active>true</active>
        <description>Record Type for Storing Goals</description>
        <label>Goal</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AstrumDailyReportSettingsController.cls
/* FILE: AstrumDailyReportSettingsController.page
 * AUTHOR: Rohit Jain
 * DATE: Aug 18, 2013
 * PURPOSE: Edit page for Astrum daily Report Goals
 * MODIFICATION HISTORY 
 */
public class AstrumDailyReportSettingsController {    
   public boolean isEdit {get; set;}
   public Astrum_Daily_Report__c adr {get; set;}

   public AstrumDailyReportSettingsController() {
		adr = [Select id,daily_Goal_Leads_Num__c,monthly_Goal_Leads_Num__c,yearly_Goal_Leads_Num__c
					 ,daily_Goal_Oppty_Num__c,monthly_Goal_Oppty_Num__c,yearly_Goal_Oppty_Num__c
					 ,daily_Goal_Sales_Num__c,monthly_Goal_Sales_Num__c,yearly_Goal_Sales_Num__c 
					 ,daily_Goal_cancel_Num__c,monthly_Goal_cancel_Num__c,yearly_Goal_cancel_Num__c 
					 ,daily_Goal_inspection_Num__c,monthly_Goal_inspection_Num__c,yearly_Goal_inspection_Num__c 
					  ,daily_Goal_Sales_kw_Num__c,monthly_Goal_Sales_kw_Num__c,yearly_Goal_Sales_kw_Num__c 
					 ,daily_Goal_cancel_kw_Num__c,monthly_Goal_cancel_kw_Num__c,yearly_Goal_cancel_kw_Num__c 
					 ,daily_Goal_inspection_kw_Num__c,monthly_Goal_inspection_kw_Num__c,yearly_Goal_inspection_kw_Num__c 
                     ,daily_Goal_Avg_Time_Opty_to_Sales_Visit__c,month_Goal_Avg_Time_Opty_to_Sales_Visit__c,yearly_Goal_Avg_Time_Opty_to_Sales_Visit__c 
                     ,daily_Goal_Avg_Time_Sales_to_Inspection__c,month_Goal_Avg_Time_Sales_to_Inspection__c,yearly_Goal_Avg_Time_Sales_to_Inspection__c
                     ,daily_Stretch_Goal_Leads_Num__c,monthly_Stretch_Goal_Leads_Num__c,yearly_Stretch_Goal_Leads_Num__c
                    ,daily_Stretch_Goal_Oppty_Num__c,monthly_Stretch_Goal_Oppty_Num__c,yearly_Stretch_Goal_Oppty_Num__c
                    ,daily_Stretch_Goal_Sales_Num__c,monthly_Stretch_Goal_Sales_Num__c,yearly_Stretch_Goal_Sales_Num__c 
                    ,daily_Stretch_Goal_cancel_Num__c,monthly_Stretch_Goal_cancel_Num__c,yearly_Stretch_Goal_cancel_Num__c 
                    ,daily_Stretch_Goal_inspection_Num__c,monthly_Stretch_Goal_inspection_Num__c,yearly_Stretch_Goal_inspection_Num__c 
                    ,daily_Stretch_Goal_Sales_kw_Num__c,monthly_Stretch_Goal_Sales_kw_Num__c,yearly_Stretch_Goal_Sales_kw_Num__c 
                    ,daily_Stretch_Goal_cancel_kw_Num__c,monthly_Stretch_Goal_cancel_kw_Num__c,yearly_Stretch_Goal_cancel_kw_Num__c 
                    ,daily_Stretch_Goal_inspection_kw_Num__c,monthly_Stretch_Goal_inspection_kw_Num__c,yearly_Stretch_Goal_inspection_kw_Num__c
                    ,daily_Stretch_Goal_Avg_Time_to_Sales__c,month_Stretch_Goal_Avg_Time_to_Sales__c,year_Stretch_Goal_Avg_Time_to_Sales__c
                    ,daily_Stretch_Goal_Avg_Time_to_Ins__c,month_Stretch_Goal_Avg_Time_to_Ins__c,year_Stretch_Goal_Avg_Time_to_Ins__c
		         From Astrum_Daily_Report__c 
		        Where RecordType.DeveloperName = 'Goal' limit 1];

		isEdit = false;
	}
    

    public PageReference save()
    {
        update adr;
        isEdit = false;
        return null;
    }

    public PageReference edit()
    {
        isEdit = true;
        return null;
    }

    public PageReference cancel()
    {        
        
        isEdit = false;
        return null;
    }
    
}