src/objects/Astrum_Contract__c.object
<CustomObject>
    <description>Contract object to facilitate Conga Contracts</description>
    <fields>
        <fullName>Closed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Closed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Proposal__c</fullName>
        <label>Proposal</label>
        <referenceTo>Proposal__c</referenceTo>
        <relationshipLabel>Astrum Contracts</relationshipLabel>
        <relationshipName>Astrum_Contracts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Scenario__c</fullName>
        <label>Scenario</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Astrum Contract</label>
    <nameField>
        <displayFormat>AC-{MM}-{DD}-{YY}-{0000}</displayFormat>
        <label>Astrum Contracts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Astrum Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DER_Bundle_Log__c.object
<CustomObject>
    <fields>
        <fullName>Email_To_Contact__c</fullName>
        <label>Email To Contact</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Failed_Transfers__c</fullName>
        <label>Failed Transfers</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Successful_Transfers__c</fullName>
        <label>Successful Transfers</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Timestamp__c</fullName>
        <label>Timestamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Total_Records__c</fullName>
        <label>Total Records</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transfers_Missing_Attachment__c</fullName>
        <label>Transfers Missing Attachment</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>DER Bundle Log</label>
    <nameField>
        <displayFormat>DEB-{00000}</displayFormat>
        <label>DER Bundle Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DER Bundle Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Entitlement_Offer__c.object
<CustomObject>
    <fields>
        <fullName>DE_Outbound_Referral_Offer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Picklist value willl determine the destination for outbound lead generation among DE sister companies.</description>
        <inlineHelpText>Picklist value willl determine the destination for outbound lead generation among DE sister companies.</inlineHelpText>
        <label>DE Outbound Referral Offer</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Entitlement Offers</relationshipLabel>
        <relationshipName>Entitlement_Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Entitlement Offer</label>
    <nameField>
        <label>Entitlement Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entitlement Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Astrum_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Astrum Contract</label>
        <referenceTo>Astrum_Contract__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Closed_Scenario__c</fullName>
        <label>Closed Scenario</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Proposal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proposal</label>
        <referenceTo>Proposal__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Design_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>System Design Quote</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>System_Design_Quote__c.System_Design__r.Property__c</field>
                <operation>equals</operation>
                <valueField>$Source.Property__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>System_Design_Quote__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PM_Project__c.object
<CustomObject>
    <description>Astrum PM 2.0 Project Object</description>
    <fields>
        <fullName>Inspection_Verified__c</fullName>
        <inlineHelpText>Inspection has been verified by either the VP of Ops or the Controller.</inlineHelpText>
        <label>Inspection Verified</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Inspection__c</fullName>
        <label>Inspection</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>SCRB_SalesOrder__c</referenceTo>
        <relationshipLabel>PM Projects</relationshipLabel>
        <relationshipName>PM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PM Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PM Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Price_Adjustment__c.object
<CustomObject>
    <description>AstrumCRM - An object for tracking pricing adjustments to be applied to a calculated system price on a System Design Quote.</description>
    <fields>
        <fullName>Adjustment_Applied__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Adjustment Applied</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Applicable_Scenario__c</fullName>
        <label>Applicable Scenario</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DE_Outbound_Referral_Offer__c</fullName>
        <description>Look up Entitlement Offer Picklist value willl determine the destination for outbound lead generation among DE sister companies.</description>
        <formula>Entitlement_Offer__r.DE_Outbound_Referral_Offer__c</formula>
        <inlineHelpText>Look up Entitlement Offer Picklist value willl determine the destination for outbound lead generation among DE sister companies.</inlineHelpText>
        <label>DE Outbound Referral Offer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entitlement_Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entitlement Offer</label>
        <referenceTo>Entitlement_Offer__c</referenceTo>
        <relationshipLabel>Price Adjustments</relationshipLabel>
        <relationshipName>Price_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Design_Quote__c</fullName>
        <label>System Design Quote</label>
        <referenceTo>System_Design_Quote__c</referenceTo>
        <relationshipLabel>Price Adjustments</relationshipLabel>
        <relationshipName>Price_Adjustments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Price Adjustment</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Adjustments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Proposal__c.object
<CustomObject>
    <fields>
        <fullName>Closed_Scenario__c</fullName>
        <label>Closed Scenario</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Closed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Closed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>System_Design_Quote__c</fullName>
        <label>System Design Quote</label>
        <referenceTo>System_Design_Quote__c</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SCRB_SalesOrder__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The SalesOrder object is the result of a Closed Won Opportunity and handles the hand off from the sales team to the operations team.</description>
    <fields>
        <fullName>Astrum_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Astrum Contract</label>
        <referenceTo>Astrum_Contract__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Closed_Scenario__c</fullName>
        <label>Closed Scenario</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OpportunityId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>R00N300000011q6hEAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Design_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>System Design Quote</label>
        <referenceTo>System_Design_Quote__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/System_Design_Quote__c.object
<CustomObject>
    <description>AstrumCRM - System Design Quote.  Each System Design can have one or more System Design Quotes.  Each quote provides the sales consultant with the ability to adjust the negotiated price of the System Design based on the Calculated System Price.  Opportunities must choose a winning System Design Quote in order to close.</description>
    <fields>
        <fullName>Closed_Scenario__c</fullName>
        <label>Closed Scenario</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Closed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Closed</label>
        <type>Checkbox</type>
    </fields>
    <label>System Design Quote</label>
    <nameField>
        <displayFormat>SDQ-{0}</displayFormat>
        <label>System Design Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Design Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DEBundle_UnitTest.cls
@isTest
private class DEBundle_UnitTest {
    private static boolean runalltests = true; // true to run all tests; false to skip tests and only run those where the 'if' is commented out

	@testSetup static void setupData() {
        testdata.setupCustomSettingsPricing();
        testdata.setupCustomConfigObjectsPricing();

		Id campaignId = DEBundle_TestUtility.CreateCampaign();

        //Create our test data
        DEBundle_TestUtility.CreateCustomSettings(campaignId);

        //Create System Design Quote        
        Opportunity_Trigger_Utility.skipOpportunityTrigger = true;
        System_Design_Quote__c sdq = testdata.setupSystemDesignQuote('Residential', 'Purchase', null, true, 12000);
        Opportunity_Trigger_Utility.skipOpportunityTrigger = false;

        Entitlement_Offer__c eo = new Entitlement_Offer__c(Name = 'DE OB EO', DE_Outbound_Referral_Offer__c = campaignId);
        insert eo;

        Price_Adjustment__c pa = new Price_Adjustment__c(System_Design_Quote__c = sdq.Id, Adjustment_Applied__c = true, Applicable_Scenario__c = '1', Entitlement_Offer__c = eo.Id);
        insert pa;

        Proposal__c prop = new Proposal__c(System_Design_Quote__c = sdq.ID);
        insert prop;

        Astrum_Contract__c contr1 = new Astrum_Contract__c(Proposal__c = prop.ID, Closed__c = true, Scenario__c = '1');
        insert contr1;

        Opportunity opp = [SELECT Id FROM Opportunity WHERE System_Design_Quote__c = :sdq.Id LIMIT 1];

		SCRB_SalesOrder__c salesOrder = new SCRB_SalesOrder__c(System_Design_Quote__c = sdq.Id, OpportunityId__c = opp.Id, Closed_Scenario__c = '1');
		insert salesOrder;
    }

	@isTest static void testUploadFileToSalesOrder() {
		if(!runalltests){ return; }

		SCRB_SalesOrder__c salesOrder = [SELECT Id FROM SCRB_SalesOrder__c LIMIT 1];

		PageReference pageRef = Page.DEBundle_UploadDEReferral;
		pageRef.getParameters().put('id', salesOrder.Id);
		Test.setCurrentPage(pageRef);

		Test.startTest();

		Integer pageMessageCount = 0;
		DEBundle_UploadDEReferralController controller = new DEBundle_UploadDEReferralController(new ApexPages.StandardController(salesOrder));
	    controller.uploadFile = new Attachment(
	        Name = 'samplefile.pdf',
	        ContentType = 'application/pdf'
		);
		controller.upload();

		System.assertNotEquals(pageMessageCount, ApexPages.getMessages().size());
		Boolean foundText = false;
		for(ApexPages.Message msg : ApexPages.getMessages()){
			if(msg.getSummary().contains('upload file cannot be null')){
				system.debug('**SZ: message = ' + msg.getSummary());
				foundText = true;
				break;
			}
		}
		System.assert(foundText);

	    controller.uploadFile = new Attachment(
	        Name = 'samplefile.pdf',
		    Body = Blob.valueOf('Sample DER Solar Advantage Plan Attachment'),
	        ContentType = 'application/pdf'
		);
	    controller.upload();

		Test.stopTest();

		List<Attachment> attList = [SELECT Id FROM Attachment WHERE ParentId = :salesOrder.Id];

		system.assertNotEquals(0, attList.size());
	}
	
	@isTest static void testLeadTransferJob() {
		if(!runalltests){ return; }

		String CRON_EXP = '0 0 0 15 3 ? 2022';

		Test.startTest();

		String jobId = System.schedule('DEBundleLeadTransferJobTest',
			CRON_EXP, 
			new DEBundle_LeadTransferJob());
		CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];

		System.assertEquals(CRON_EXP, ct.CronExpression);
		System.assertEquals(0, ct.TimesTriggered);
		System.assertEquals('2022-03-15 00:00:00', String.valueOf(ct.NextFireTime));

		Test.stopTest();

		system.debug('**SZ: stop test called.');
	}
	
	@isTest static void testLeadTransferBatch_NoRecords() {
		if(!runalltests){ return; }

        Test.startTest();

		DEBundle_LeadTransferBatch b = new DEBundle_LeadTransferBatch();
		Database.executebatch(b);
        
        Test.stopTest();

		List<DER_Bundle_Log__c> bundleLog = [SELECT Email_To_Contact__c, Timestamp__c, Error_Message__c, Total_Records__c,
			Successful_Transfers__c, Transfers_Missing_Attachment__c, Failed_Transfers__c FROM DER_Bundle_Log__c];
		system.assertEquals(1, bundleLog.size());
		system.assertEquals('No records to process.', bundleLog[0].Error_Message__c);
	}
	
	@isTest static void testLeadTransferBatch_TokenFail() {
		if(!runalltests){ return; }

		System.runAs(new User(Id = UserInfo.getUserId())){
			SCRB_SalesOrder__c salesOrder = [SELECT Id FROM SCRB_SalesOrder__c LIMIT 1];

			PM_Project__c project = new PM_Project__c(Name = 'Test Proj', Sales_Order__c = salesOrder.Id);
			insert project;

			project.Inspection__c = Datetime.now().addDays(-5);
			project.Inspection_Verified__c = Date.today().addDays(-2);
			update project;

	        Test.startTest();
	        Test.setMock(HttpCalloutMock.class, new DEBundle_CalloutMock(new Map<String, Integer>{ 'oauth2/token' => 400 }));

			DEBundle_LeadTransferBatch b = new DEBundle_LeadTransferBatch();
			Database.executebatch(b);
	        
	        Test.stopTest();

			List<DER_Bundle_Log__c> bundleLog = [SELECT Email_To_Contact__c, Timestamp__c, Error_Message__c, Total_Records__c,
				Successful_Transfers__c, Transfers_Missing_Attachment__c, Failed_Transfers__c FROM DER_Bundle_Log__c];
			system.assertEquals(2, bundleLog.size());

			Integer foundMessages = 0;
			for(DER_Bundle_Log__c dbl : bundleLog){
				system.debug('**SZ: error message = "' + dbl.Error_Message__c + '"');
				if(dbl.Error_Message__c == 'Could not acquire the access token.' || dbl.Error_Message__c == 'access token error: access token error description'){
					foundMessages++;
				}
			}
			system.assertEquals(2, foundMessages);
		}
	}
	
	@isTest static void testLeadTransferBatch_LeadFail() {
		if(!runalltests){ return; }

		System.runAs(new User(Id = UserInfo.getUserId())){
			SCRB_SalesOrder__c salesOrder = [SELECT Id FROM SCRB_SalesOrder__c LIMIT 1];

			PM_Project__c project = new PM_Project__c(Name = 'Test Proj', Sales_Order__c = salesOrder.Id);
			insert project;

			project.Inspection__c = Datetime.now().addDays(-5);
			project.Inspection_Verified__c = Date.today().addDays(-2);
			update project;

			DEBundle_TestUtility.CreateSalesOrderAttachment(salesOrder.Id);

	        Test.startTest();
	        Test.setMock(HttpCalloutMock.class, new DEBundle_CalloutMock(new Map<String, Integer>{ 'oauth2/token' => 200, 'sobjects/Lead' => 400 }));

			DEBundle_LeadTransferBatch b = new DEBundle_LeadTransferBatch();
			Database.executebatch(b);
	        
	        Test.stopTest();

			List<DER_Bundle_Log__c> bundleLog = [SELECT Email_To_Contact__c, Timestamp__c, Error_Message__c, Total_Records__c,
				Successful_Transfers__c, Transfers_Missing_Attachment__c, Failed_Transfers__c FROM DER_Bundle_Log__c];
			for(DER_Bundle_Log__c dbl : bundleLog){
				system.debug('**SZ: error message = "' + dbl.Error_Message__c + '"');
			}
			system.assertEquals(1, bundleLog.size());
			system.assertEquals(1, bundleLog[0].Failed_Transfers__c);
		}
	}
	
	@isTest static void testLeadTransferBatch_AttachFail() {
		if(!runalltests){ return; }

		System.runAs(new User(Id = UserInfo.getUserId())){
			SCRB_SalesOrder__c salesOrder = [SELECT Id FROM SCRB_SalesOrder__c LIMIT 1];

			PM_Project__c project = new PM_Project__c(Name = 'Test Proj', Sales_Order__c = salesOrder.Id);
			insert project;

			project.Inspection__c = Datetime.now().addDays(-5);
			project.Inspection_Verified__c = Date.today().addDays(-2);
			update project;

			DEBundle_TestUtility.CreateSalesOrderAttachment(salesOrder.Id);

	        Test.startTest();
	        Test.setMock(HttpCalloutMock.class, new DEBundle_CalloutMock(new Map<String, Integer>{ 'oauth2/token' => 200, 'sobjects/Lead' => 200, 'sobjects/Attachment' => 400 }));

			DEBundle_LeadTransferBatch b = new DEBundle_LeadTransferBatch();
			Database.executebatch(b);
	        
	        Test.stopTest();

			List<DER_Bundle_Log__c> bundleLog = [SELECT Email_To_Contact__c, Timestamp__c, Error_Message__c, Total_Records__c,
				Successful_Transfers__c, Transfers_Missing_Attachment__c, Failed_Transfers__c FROM DER_Bundle_Log__c];
			for(DER_Bundle_Log__c dbl : bundleLog){
				system.debug('**SZ: error message = "' + dbl.Error_Message__c + '"');
			}
			system.assertEquals(1, bundleLog.size());
			system.assertEquals(1, bundleLog[0].Transfers_Missing_Attachment__c);
		}
	}
	
	@isTest static void testLeadTransferBatch_AllPass() {
		if(!runalltests){ return; }

		System.runAs(new User(Id = UserInfo.getUserId())){
			SCRB_SalesOrder__c salesOrder = [SELECT Id FROM SCRB_SalesOrder__c LIMIT 1];

			PM_Project__c project = new PM_Project__c(Name = 'Test Proj', Sales_Order__c = salesOrder.Id);
			insert project;

			project.Inspection__c = Datetime.now().addDays(-5);
			project.Inspection_Verified__c = Date.today().addDays(-2);
			update project;

			DEBundle_TestUtility.CreateSalesOrderAttachment(salesOrder.Id);

	        Test.startTest();
	        Test.setMock(HttpCalloutMock.class, new DEBundle_CalloutMock(new Map<String, Integer>{ 'oauth2/token' => 200, 'sobjects/Lead' => 200, 'sobjects/Attachment' => 200 }));

			DEBundle_LeadTransferBatch b = new DEBundle_LeadTransferBatch();
			Database.executebatch(b);
	        
	        Test.stopTest();

			List<DER_Bundle_Log__c> bundleLog = [SELECT Email_To_Contact__c, Timestamp__c, Error_Message__c, Total_Records__c,
				Successful_Transfers__c, Transfers_Missing_Attachment__c, Failed_Transfers__c FROM DER_Bundle_Log__c];
			for(DER_Bundle_Log__c dbl : bundleLog){
				system.debug('**SZ: error message = "' + dbl.Error_Message__c + '"');
			}
			system.assertEquals(1, bundleLog.size());
			system.assertEquals(1, bundleLog[0].Successful_Transfers__c);
		}
	}
}