src/objects/Bin_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Astrum_Application__c</fullName>
        <inlineHelpText>Astrum Application configuration belongs to</inlineHelpText>
        <label>Astrum Application</label>
        <referenceTo>Astrum_Application__c</referenceTo>
        <relationshipLabel>Bin Configuration</relationshipLabel>
        <relationshipName>Bin_Configuration</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Bin_Column_Width__c</fullName>
        <label>Bin Column Width</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bin_Grouping_Name__c</fullName>
        <inlineHelpText>Grouping of Bin</inlineHelpText>
        <label>Bin Grouping Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bin_Order__c</fullName>
        <inlineHelpText>Order of Bin within Grouping</inlineHelpText>
        <label>Bin Order</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bin__c</fullName>
        <description>Astrum PM Bin</description>
        <label>Bin</label>
        <picklist>
            <picklistValues>
                <fullName>Kickoff Photos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signed Conduit Run and Layout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drivers Licenses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Install Prep Sheet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utility Bill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ SREC Docs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permit Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrical Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Permit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrical Permit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utility Interconnect Part 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Notice to Construct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grant Reservation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOA Submitted Documents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoice at Start of Installation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Equip. Delivery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation Photos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panel and Inverter Serial Numbers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pull List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunpower Warranty Cards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enphase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Completion Forms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proof of Inspection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Subst. Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utility Interconnect Part 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grant Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property Tax</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SREC Docs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submit Utility Interconnect Part 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved Utility Interconnect Part 1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <inlineHelpText>Field name to update</inlineHelpText>
        <label>Field Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Bin Configuration</label>
    <nameField>
        <displayFormat>BC-{00000}</displayFormat>
        <label>Bin Configuration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bin Configuration</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Category_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Astrum_Application__c</fullName>
        <inlineHelpText>Astrum Application configuration belongs to</inlineHelpText>
        <label>Astrum Application</label>
        <referenceTo>Astrum_Application__c</referenceTo>
        <relationshipLabel>Category Configuration</relationshipLabel>
        <relationshipName>Category_Configuration</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Bin__c</fullName>
        <description>Astrum PM Bin</description>
        <label>Bin</label>
        <picklist>
            <picklistValues>
                <fullName>Kickoff Photos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signed Conduit Run and Layout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drivers Licenses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Install Prep Sheet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utility Bill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ SREC Docs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Permit Design</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrical Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Permit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrical Permit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utility Interconnect Part 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Notice to Construct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grant Reservation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOA Submitted Documents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoice at Start of Installation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation Photos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panel and Inverter Serial Numbers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pull List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunpower Warranty Cards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enphase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Completion Forms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proof of Inspection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Subst. Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utility Interconnect Part 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grant Completion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property Tax</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SREC Docs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submit Utility Interconnect Part 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved Utility Interconnect Part 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grant Documents</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category_Order_In_Bin__c</fullName>
        <inlineHelpText>Order of Category in Bin</inlineHelpText>
        <label>Category Order In Bin</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <controllingField>Bin__c</controllingField>
            <picklistValues>
                <fullName>3 Line diagram</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acceptance Letter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Affidavit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved Application Part 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved Building Permit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved Electrical Permit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved Utility Interconnect Part 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved Utility Interconnect Part 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Array Detail Photos: Clearance, Pitch, Clamps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Branch Map</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Permit Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Permit Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Permit Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CB Panel, Interconnect, Disconnect Box Photos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certificate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certification Document</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commissioning and Production Verification Checklists</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commissioning Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completion Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conduit (Roof, Interior, Exterior) Photos</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conduit Run and Layout - Customer Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivered Materials Photo (NRG only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drawing Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drivers License</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrical Drawings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrical Permit Application</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <label>Field Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Category Configuration</label>
    <nameField>
        <displayFormat>CC-{00000}</displayFormat>
        <label>Category Config ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Category Configuration</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DocumentConfigurationHelper.cls
/* FILE: DocumentConfigurationHelper.cls
 * AUTHOR: Tino Mattheou
 * DATE: March 26, 2012
 * PURPOSE: Astrum PM Bin/Category Document Configuration
 * MODIFICATION HISTORY:
 * 4/2/2012 TCM - added new config options
 */ 
 
public class DocumentConfigurationHelper {
	
	public static final String APP_ASTRUM_PM_20 = 'Astrum PM 2.0';
	public static final String APP_ASTRUM_GRANTS = 'Astrum Grants';

	public static List<Bin_Configuration__c> getBins(String appName) {
		
		List<Bin_Configuration__c> configuration = 
			[SELECT Id, Bin__c, Bin_Grouping_Name__c, Field_Name__c, Bin_Column_Width__c
			FROM Bin_Configuration__c
			WHERE Astrum_Application__r.Name = :appName 	
			ORDER BY Bin_Order__c, Bin__c];

		return configuration;
	}

	public static List<Category_Configuration__c> getBinCategories(String appName, String binName) { 
	
		LIST<Category_Configuration__c> configuration = 
			[SELECT Id, Bin__c, Category__c, Category_Order_In_Bin__c, Document_Types_Restriction__c, 
					Maximum_Allowed__c, Minimum_Required__c,
					Document_Date_Required__c, Document_Bin_State__c, Field_Name__c 
			FROM Category_Configuration__c
			WHERE Bin__c = :binName
			AND Astrum_Application__r.Name = :appName 	
			ORDER BY Category_Order_In_Bin__c, Category__c];
			
		return configuration;
	}
	
	public static List<Category_Configuration__c> getAllCategories(String appName) { 
	
		LIST<Category_Configuration__c> configuration = 
			[SELECT Id, Bin__c, Category__c, Category_Order_In_Bin__c, Document_Types_Restriction__c, 
					Maximum_Allowed__c, Minimum_Required__c,
					Document_Date_Required__c, Document_Bin_State__c, Field_Name__c 
			FROM Category_Configuration__c
			WHERE Astrum_Application__r.Name = :appName 	
			ORDER BY Bin__c, Category_Order_In_Bin__c, Category__c];
			
		return configuration;
	}
	
	//returns categories in bins with 
	public static List<SpecialCategory> getSpecialCategories(String appName) {
		List<SpecialCategory> result = new List<SpecialCategory>();
		Map<String, String> binToDateMap = new Map<String, String>();
		
		Astrum_Application__c config = 
			[SELECT Id,
				(SELECT Bin__c, Field_Name__c 
				FROM Bin_Configuration__r), 
				(SELECT Bin__c, Field_Name__c, Category__c, Category_Order_In_Bin__c, Document_Bin_State__c 
				FROM Category_Configuration__r 
				WHERE Field_Name__c <> null
				ORDER BY Category_Order_In_Bin__c) 
			FROM Astrum_Application__c 
			WHERE Name = :appName];
			
		for (Bin_Configuration__c bin : config.Bin_Configuration__r) {
			binToDateMap.put(bin.Bin__c, bin.Field_Name__c);
		}
		
		//only include categories that don't match the bin date
		for (Category_Configuration__c cat : config.Category_Configuration__r) {
			String binFieldName = binToDateMap.get(cat.Bin__c);
			if (binFieldName != cat.Field_Name__c) {
				SpecialCategory sg = new SpecialCategory();
				sg.binName = cat.Bin__c;
				sg.categoryName = cat.Category__c;
				sg.categoryOrderInBin = cat.Category_Order_In_Bin__c; 
				sg.binDateFieldName = binFieldName;
				sg.categoryDateFieldName = cat.Field_Name__c;
				sg.binState = cat.Document_Bin_State__c;
				result.add(sg);
			}
		}
		
		return result;
	} 	
	
	public class SpecialCategory {
		public String binName;
		public String categoryName;
		public Double categoryOrderInBin;
		public String binDateFieldName;
		public String categoryDateFieldName;
		public String binState;
	}

}