src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Lead_Created_Date__c</fullName>
        <description>Custom field that contains a copy of the CreatedDate</description>
        <label>Lead Created Date</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Portal_Referral__c.object
<CustomObject>
    <description>Referrals from the Partner Program website</description>
    <fields>
        <fullName>City__c</fullName>
        <description>City for referral</description>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>D2D_Lead_Status__c</fullName>
        <label>D2D Lead Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed - Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Generated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Opt-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Opt-Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Door Hanger</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing Utility Bill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA Visit 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA Visit 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passed Validation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Photos Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit Scheduled</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>D2D_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>D2D Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Portal_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of referral</description>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of referral</description>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Created_Date__c</fullName>
        <label>Lead Created Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Segment_Priority__c</fullName>
        <label>Segment Priority</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>Street of Referral</description>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Portal Referral</label>
    <nameField>
        <displayFormat>REF-{000000}</displayFormat>
        <label>Portal Referral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/State__c.object
<CustomObject>
    <description>Represents a State</description>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>D2D_Manager__c</fullName>
        <label>D2D Manager</label>
        <relationshipName>D2DSalesReps</relationshipName>
        <restrictedAdminField>false</restrictedAdminField>
        <type>Hierarchy</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/LeadsAssignmentControllerTest.cls
@isTest
private class LeadsAssignmentControllerTest {
    private static boolean runalltests = true; // true to run all tests; false to skip tests and only run those where the 'if' is commented out

	@testSetup static void setupData() {
		D2DTestUtility.InitializeRequiredMethods();
		D2DTestUtility.CreateManagerUsers(1);

		D2DTestUtility.CreatePortalReferralRequiredObjects(1, 'NY', '24 Panel');
		D2DTestUtility.CreatePortalReferralsWithLeads(1, null, null, 'Prospect New', 'Prospect New', '24 Panel', '1', 'ref1', 'Joe', '125 Fifth Avenue', 'New York', 'NY', '10980', 'Rockland', false);
		D2DTestUtility.CreatePortalReferralsWithLeads(1, null, null, 'Prospect New', 'Prospect New', '24 Panel', '2', 'ref2', 'Joe', '129 Fifth Avenue', 'New York', 'NY', '10980', 'Rockland', false);
		D2DTestUtility.CreatePortalReferralsWithLeads(1, null, null, 'Prospect New', 'Prospect New', '24 Panel', '3', 'ref3', 'Joe', '133 Wacker Drive', 'Chicago', 'IL', '60016', 'Rockland', false);
	}
	
	@isTest static void test_filtersAndCancel() {
		if(!runalltests){ return; }

		PageReference pageRef = Page.LeadsAssignment;
		Test.setCurrentPage(pageRef);

		Campaign campaign = [SELECT Id FROM Campaign WHERE Name LIKE '%D2D%' LIMIT 1];

		Test.startTest();

		LeadsAssignmentController controller = new LeadsAssignmentController();
		system.assertEquals(3, controller.filteredReferrals.size());

		controller.selectedSegment = '1';
		controller.filterChanged();
		system.assertEquals(1, controller.filteredReferrals.size());
		system.assertEquals('ref10', controller.filteredReferrals[0].portalReferral.Last_Name__c);

		controller.selectedSegment = '2';
		controller.filterChanged();
		system.assertEquals(1, controller.filteredReferrals.size());
		system.assertEquals('ref20', controller.filteredReferrals[0].portalReferral.Last_Name__c);

		controller.selectedSegment = '3';
		controller.filterChanged();
		system.assertEquals(1, controller.filteredReferrals.size());
		system.assertEquals('ref30', controller.filteredReferrals[0].portalReferral.Last_Name__c);

		controller.cancel();
		system.assertEquals(3, controller.filteredReferrals.size());

		controller.selectedAffiliateCommunityProgram = 'XYZ';
		controller.filterChanged();
		system.assertEquals(0, controller.filteredReferrals.size());
		controller.selectedAffiliateCommunityProgram = 'D2D Long Island';
		controller.filterChanged();
		system.assertEquals(3, controller.filteredReferrals.size());

		controller.cancel();
		system.assertEquals(3, controller.filteredReferrals.size());

		controller.selectedPrimarySourceCampaign = campaign.Id;
		controller.filterChanged();
		system.assertEquals(3, controller.filteredReferrals.size());

		controller.cancel();
		system.assertEquals(3, controller.filteredReferrals.size());

		controller.selectedState = 'NY';
		controller.filterChanged();
		system.assertEquals(2, controller.filteredReferrals.size());
		for(LeadsAssignmentController.PortalReferralWrapper prw : controller.filteredReferrals){
			system.assertNotEquals('ref30', prw.portalReferral.Last_Name__c);
		}

		controller.selectedState = 'IL';
		controller.filterChanged();
		system.assertEquals(1, controller.filteredReferrals.size());
		system.assertEquals('ref30', controller.filteredReferrals[0].portalReferral.Last_Name__c);

		controller.selectedState = 'DE';
		controller.filterChanged();
		system.assertEquals(0, controller.filteredReferrals.size());

		Test.stopTest();
	}
	
	@isTest static void test_assignAndSave() {
		if(!runalltests){ return; }

		User d2dManager = [SELECT Id FROM User WHERE Profile.Name = 'D2D Manager' LIMIT 1];

		PageReference pageRef = Page.LeadsAssignment;
		Test.setCurrentPage(pageRef);

		Test.startTest();

		LeadsAssignmentController controller = new LeadsAssignmentController();
		system.assertEquals(3, controller.filteredReferrals.size());

		ApexPages.Message[] pageMessages = ApexPages.getMessages();
		Integer pageMessagesCount = pageMessages.size();

		// Testing for no manager selected
		controller.save();
		pageMessages = ApexPages.getMessages();
		system.assertNotEquals(pageMessagesCount, pageMessages.size());

		// testing for no rows selected
		pageMessagesCount = pageMessages.size();
		controller.selectedManager = d2dManager.Id;
		controller.save();
		pageMessages = ApexPages.getMessages();
		system.assertNotEquals(pageMessagesCount, pageMessages.size());

		pageMessagesCount = pageMessages.size();
		for(LeadsAssignmentController.PortalReferralWrapper prw : controller.filteredReferrals){
			if(prw.portalReferral.State__c == 'NY'){
				prw.selected = true;
			}
		}
		controller.save();
		pageMessages = ApexPages.getMessages();
		system.assertEquals(pageMessagesCount, pageMessages.size());

		List<Portal_Referral__c> prList = [SELECT Id, Last_Name__c, State__c FROM Portal_Referral__c WHERE D2D_Manager__c = null];
		system.assertEquals(1, prList.size());
		system.assertEquals('ref30', prList[0].Last_Name__c);
		system.assertEquals('IL', prList[0].State__c);

		Test.stopTest();
	}

/*	private static void CreateTestData(){
		// User w/ D2D Manager Profile
		UserRole role = [SELECT Id FROM UserRole WHERE Name LIKE '%Project Lead' LIMIT 1];
		Profile prof = [SELECT Id FROM Profile WHERE Name = 'Operations User'];
		User acctOwner = new User(
			Email = 'acctOwner@email.com',
			UserName = 'acctOwner@email.com',
			LastName = 'D2D',
			Alias = 'd2d.man',
			CommunityNickName = 'Acct Owner Test',
			TimeZoneSidKey = 'America/New_York',
			LocaleSidKey = 'en_US',
			LanguageLocaleKey = 'en_US',
			EmailEncodingKey = 'UTF-8',
			ProfileId = prof.Id,
			UserRoleId = role.Id
		);
		System.runAs(new User(Id = UserInfo.getUserId())){
			insert acctOwner;
		}

		Account acct = new Account(Name = 'D2D Mgr Test Acct', OwnerId = acctOwner.Id);
		insert acct;
		Contact cntc = new Contact(AccountId = acct.Id, FirstName = 'D2D', LastName = 'Mgr Test');
		insert cntc;

		prof = [SELECT Id FROM Profile WHERE Name = 'D2D Manager'];
		User d2dManager = new User(
			Email = 'tester@email.com',
			UserName = 'tester@email.com',
			LastName = 'D2D',
			Alias = 'd2d.man',
			CommunityNickName = 'D2D Manager Test',
			TimeZoneSidKey = 'America/New_York',
			LocaleSidKey = 'en_US',
			LanguageLocaleKey = 'en_US',
			EmailEncodingKey = 'UTF-8',
			ProfileId = prof.Id,
			ContactId = cntc.Id
		);
		insert d2dManager;

		List<Portal_Referral__c> prList = new List<Portal_Referral__c>();
		prList.add(new Portal_Referral__c(
			Segment_Priority__c = '1', D2D_Lead_Status__c = 'Prospect New', Last_Name__c = 'test1', First_Name__c = 'yo',
			Street__c = '125 Fifth Avenue', City__c = 'New York', State__c = 'NY', Zip__c = '10980', Lead_Created_Date__c = Date.today()
		));
		prList.add(new Portal_Referral__c(
			Segment_Priority__c = '2', D2D_Lead_Status__c = 'Prospect New', Last_Name__c = 'test2', First_Name__c = 'yo',
			Street__c = '128 Fifth Avenue', City__c = 'New York', State__c = 'NY', Zip__c = '10980', Lead_Created_Date__c = Date.today()
		));
		prList.add(new Portal_Referral__c(
			Segment_Priority__c = '3', D2D_Lead_Status__c = 'Prospect New', Last_Name__c = 'test3', First_Name__c = 'yo',
			Street__c = '133 Wacker Drive', City__c = 'Chicago', State__c = 'IL', Zip__c = '60016', Lead_Created_Date__c = Date.today()
		));
		insert prList;

		List<Document> docs = new List<Document>();
		docs.add(new Document(Name='DESLogo', FolderId=UserInfo.getUserId()));
		insert docs;
	}*/
}