src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Conversion_Status__c</fullName>
        <label>Conversion Status</label>
        <picklist>
            <picklistValues>
                <fullName>Trying to Reach</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Contract Presented</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Contract Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Order Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer Property Related to this Case</description>
        <inlineHelpText>Customer Property Related to this Case</inlineHelpText>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>SCRB_SalesOrder__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Property__c.Property_Owner__r.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PM_Project__c.object
<CustomObject>
    <description>Astrum PM 2.0 Project Object</description>
    <fields>
        <fullName>Lease_Funding_Status__c</fullName>
        <label>Lease Funding Status</label>
        <picklist>
            <picklistValues>
                <fullName>Change Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Prepare</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Install</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>SCRB_SalesOrder__c</referenceTo>
        <relationshipLabel>PM Projects</relationshipLabel>
        <relationshipName>PM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PM Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PM Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <description>AstrumPM/AstrumCRM - Each account can have one or more properties.  A property is defined by its street address.</description>
    <label>Property</label>
    <nameField>
        <label>Property Address 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SCRB_SalesOrder__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The SalesOrder object is the result of a Closed Won Opportunity and handles the hand off from the sales team to the operations team.</description>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>R00N300000011q88EAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StatusCode__c</fullName>
        <label>Status Code</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>Submit Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Assigned to Sales Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Submit To Sales Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Coordinator Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Manager Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Coordinator Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final/Accounting Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Administrator Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated to VP Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VP Sales Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VP Sales Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Controller Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Proposal Creation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Proposal Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Ongoing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Controller Rejected - Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Admin Approved - Finance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LeaseFundStatusCheckTest.cls
/* FILE: LeaseFundStatusCheckTest.cls
 * AUTHOR: Rohit Jain
 * DATE: Aug 30, 2013
 * PURPOSE: Test class for LeaseFundStatusCheck_BIBU trigger on Case
 * MODIFICATION HISTORY:
 *
 */

@isTest(seeAllData=true)
public class LeaseFundStatusCheckTest{
    
    static testMethod void LeaseFundStatusCheck_Insert_Test() {
        
        Account customer = new Account(Name = 'Test Customer');
        insert customer;
        Property__c property = CreateAstrumPM2ProjectTest.createProperty(customer.Id, '123 Test St');
        Opportunity opp = CreateAstrumPM2ProjectTest.createOpportunity(customer.Id, 'Test Oppty');    
        SCRB_SalesOrder__c salesOrder = CreateAstrumPM2ProjectTest.createSalesOrder(property.Id, opp.Id);
        salesOrder.AccountId__c = customer.Id;
        salesOrder.StatusCode__c = 'Conversion Processing';
        update salesOrder;
        RootstockAutomation amr = new RootstockAutomation();
        String projectId = amr.createProject(salesOrder );
        
        Test.startTest();
               
        Case cs = new Case();
        
        cs.Sales_Order__c = salesOrder.Id;
        cs.Conversion_Status__c = 'Conversion Contract Signed';   
        cs.Origin = 'Customer Care';  
        
        insert cs;
        
        Test.stopTest();   
    
        PM_Project__c project =  
          [SELECT Id, Lease_Funding_Status__c
          FROM PM_Project__c 
          WHERE Id = :projectid];
    
    
        System.assertEquals(project.Lease_Funding_Status__c, 'Ready to Prepare'); 
    }    
    
    static testMethod void LeaseFundStatusCheck_Update_Test() {
        
        Account customer = new Account(Name = 'Test Customer');
        insert customer;
        Property__c property = CreateAstrumPM2ProjectTest.createProperty(customer.Id, '123 Test St');
        Opportunity opp = CreateAstrumPM2ProjectTest.createOpportunity(customer.Id, 'Test Oppty');    
        SCRB_SalesOrder__c salesOrder = CreateAstrumPM2ProjectTest.createSalesOrder(property.Id, opp.Id);
        salesOrder.AccountId__c = customer.Id;
        salesOrder.StatusCode__c = 'Conversion Processing';
        update salesOrder;
        RootstockAutomation amr = new RootstockAutomation();
        String projectId = amr.createProject(salesOrder );
        
        Case cs = new Case();        
        cs.Sales_Order__c = salesOrder.Id;
        cs.Conversion_Status__c = 'Conversion Contract Presented';   
        cs.Origin = 'Customer Care';          
        insert cs;
        
        Test.startTest();
        cs.Conversion_Status__c = 'Conversion Contract Signed'; 
        update cs;
        Test.stopTest();   
    
        PM_Project__c project =  
          [SELECT Id, Lease_Funding_Status__c
          FROM PM_Project__c 
          WHERE Id = :projectid];
    
    
        System.assertEquals(project.Lease_Funding_Status__c, 'Ready to Prepare'); 
    } 
    
    static testMethod void Sales_ORder_Approval_Trigger_Test() {
        
        Account customer = new Account(Name = 'Test Customer');
        insert customer;
        Property__c property = CreateAstrumPM2ProjectTest.createProperty(customer.Id, '123 Test St');
        Opportunity opp = CreateAstrumPM2ProjectTest.createOpportunity(customer.Id, 'Test Oppty');    
        SCRB_SalesOrder__c salesOrder = CreateAstrumPM2ProjectTest.createSalesOrder(property.Id, opp.Id);
        salesOrder.AccountId__c = customer.Id;
        salesOrder.StatusCode__c = 'Conversion Going';
        update salesOrder;
        RootstockAutomation amr = new RootstockAutomation();
        String projectId = amr.createProject(salesOrder );
        
        Case cs = new Case();        
        cs.Sales_Order__c = salesOrder.Id;
        cs.Conversion_Status__c = 'Conversion Contract Signed';   
        cs.Origin = 'Customer Care';          
        insert cs;
        
        Test.startTest();
        salesOrder.StatusCode__c = 'Conversion Processing';
        update salesOrder;
        Test.stopTest();   
    
        PM_Project__c project =  
          [SELECT Id, Lease_Funding_Status__c
          FROM PM_Project__c 
          WHERE Id = :projectid];
    
    
        System.assertEquals(project.Lease_Funding_Status__c, 'Ready to Prepare'); 
    }                       
}