src/objects/CB_Panel__c.object
<CustomObject>
    <description>AstrumPM - Circuit Breaker Panel - This is an object to keep track of the panels available on a utility service to which System Design Arrays can be attached.</description>
    <fields>
        <fullName>Property__c</fullName>
        <description>Property Where This CB Panel is Located</description>
        <formula>HYPERLINK( Utility_Service__r.Property__r.Id , Utility_Service__r.Property__r.Name )</formula>
        <inlineHelpText>Property Where This CB Panel is Located</inlineHelpText>
        <label>Property</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility_Service__c</fullName>
        <description>Meter ID of the Utility Service This CB Panel is connected to.</description>
        <inlineHelpText>Meter ID of the Utility Service This CB Panel is connected to.</inlineHelpText>
        <label>Meter ID</label>
        <referenceTo>Utility_Service__c</referenceTo>
        <relationshipLabel>CB Panels</relationshipLabel>
        <relationshipName>CB_Panels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CB Panel</label>
    <nameField>
        <label>CB Panel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Panels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Property__c.Property_Owner__r.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Design__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>System Design</label>
        <referenceTo>System_Design__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <description>AstrumPM/AstrumCRM - Each account can have one or more properties.  A property is defined by its street address.</description>
    <fields>
        <fullName>Property_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account that represents the Owner of this Building.  This may be a Family or a Business.</description>
        <label>Property Owner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Address 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <recordTypes>
        <fullName>Residential</fullName>
        <active>true</active>
        <label>Residential</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/System_Design__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The Solar System Design.  Each Property can have one or more System Designs created as the result of a site Survey and the discovery of Install Locations.  Each System Design is made up of one or more System Design Arrays.</description>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>System Designs</relationshipLabel>
        <relationshipName>System_Designs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>System Design</label>
    <nameField>
        <displayFormat>SD-{0}</displayFormat>
        <label>System Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Designs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/System_Design_Array__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The Solar System Design Array.  Each System Design is made up of one or more System Design Arrays.  Primarily defined by their mounting system and CB Panel connection, System Design Arrays are made up of one or more System Design Items.</description>
    <fields>
        <fullName>CB_Panel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Panel</label>
        <referenceTo>CB_Panel__c</referenceTo>
        <relationshipLabel>System Design Arrays</relationshipLabel>
        <relationshipName>System_Design_Arrays</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Default_Mounting_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Default Mounting Type</label>
        <referenceTo>System_Design_Product__c</referenceTo>
        <relationshipLabel>System Design Arrays (Default Mounting Type)</relationshipLabel>
        <relationshipName>System_Design_Arrays1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mounting_Type__c</fullName>
        <label>Mounting Type</label>
        <picklist>
            <picklistValues>
                <fullName>Attached Through Metal Panel Roof</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ballasted System</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clamped on Metal Seam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flush Mounted on curved concrete tile, penetrations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flush Mounted on flat concrete tile, penetrations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flush Mounted on flat roof, no penetrations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flush Mounted on flat roof, penetrating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flush Mounted on pitched roof, penetrating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flush Mounted on Slate Shingle, penetrating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flush Mounted on tile roof, requires comp shingle re-roof, penetrations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ground Mount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I-Beam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RapidRac</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tilted off flat roof, no penetrations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tilted off flat roof, penetrations</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>System_Design__c</fullName>
        <label>System Design</label>
        <referenceTo>System_Design__c</referenceTo>
        <relationshipLabel>System Design Arrays</relationshipLabel>
        <relationshipName>System_Design_Arrays</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Utility_Service__c</fullName>
        <formula>CB_Panel__r.Utility_Service__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Utility Service</label>
        <type>Text</type>
    </fields>
    <label>System Design Array</label>
    <nameField>
        <displayFormat>SDA-{0}</displayFormat>
        <label>System Design Array Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Design Arrays</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility_Service__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - Each Property can have one or more Utility Service(s).  A Utility Service is primarily defined by the Meter ID and the Utility Company to which is connects.</description>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Utility Services</relationshipLabel>
        <relationshipName>Utility_Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Utility Service</label>
    <nameField>
        <label>Meter ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SystemDesignUpdateBatchTest.cls
@isTest
public class SystemDesignUpdateBatchTest {
    
    static testMethod void updateSystemDesign(){
        testData.setupCustomSettings();
        testdata.setupCustomConfigObjects();
        Id sdID = testData.setupSystemDesign('Residential', 'Purchase', null, true, 12000);
        System_Design_Array__c sda = [SELECT Id, Default_Mounting_Type__c, Mounting_Type__c, CB_Panel__r.Utility_Service__c 
                                      FROM System_Design_Array__c 
                                      WHERE System_Design__c =:sdID][0];
        sda.Default_Mounting_Type__c = null;
        sda.Mounting_Type__c = 'I-Beam';
        update sda;
        
        System_Design__c sysDes = [SELECT Id, Property__c FROM System_Design__c WHERE Id=:sdID];
        Property__c prop = [SELECT Id, Property_Owner__c FROM Property__c WHERE Id=:sysDes.Property__c];
        Opportunity opp = testdata.createTestOppForProperty(prop);        
        
        Test.startTest();
        SystemDesignUpdateBatch batch = new SystemDesignUpdateBatch();
        batch.execute(null, new List<Opportunity>{opp});
        batch.errors = 'Test Errors';
        batch.finish(null);
        Test.stopTest();        
        
    }
    
    static testMethod void updateSQValidation(){
        testData.setupCustomSettings();
        testdata.setupCustomConfigObjects();
        Id sdID = testData.setupSystemDesign('Residential', 'Purchase', null, true, 12000);
        System_Design_Array__c sda = [SELECT Id, Default_Mounting_Type__c, Mounting_Type__c, CB_Panel__r.Utility_Service__c 
                                      FROM System_Design_Array__c 
                                      WHERE System_Design__c =:sdID][0];
        sda.Default_Mounting_Type__c = null;
        sda.Mounting_Type__c = 'I-Beam';
        update sda;
        
        System_Design__c sysDes = [SELECT Id, Property__c FROM System_Design__c WHERE Id=:sdID];
        Property__c prop = [SELECT Id, Property_Owner__c FROM Property__c WHERE Id=:sysDes.Property__c];
        Opportunity opp = testdata.createTestOppForProperty(prop);        
        
        Test.startTest();
        SystemDesignUpdateSQValidationBatch batch = new SystemDesignUpdateSQValidationBatch();
        batch.execute(null, new List<System_Design__c>{sysDes});
        batch.errors = 'Test Errors';
        batch.finish(null);
        Test.stopTest();        
        
    }

}