src/objects/CB_Panel__c.object
<CustomObject>
    <description>AstrumPM - Circuit Breaker Panel - This is an object to keep track of the panels available on a utility service to which System Design Arrays can be attached.</description>
    <fields>
        <fullName>Property__c</fullName>
        <description>Property Where This CB Panel is Located</description>
        <formula>HYPERLINK( Utility_Service__r.Property__r.Id , Utility_Service__r.Property__r.Name )</formula>
        <inlineHelpText>Property Where This CB Panel is Located</inlineHelpText>
        <label>Property</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility_Service__c</fullName>
        <description>Meter ID of the Utility Service This CB Panel is connected to.</description>
        <inlineHelpText>Meter ID of the Utility Service This CB Panel is connected to.</inlineHelpText>
        <label>Meter ID</label>
        <referenceTo>Utility_Service__c</referenceTo>
        <relationshipLabel>CB Panels</relationshipLabel>
        <relationshipName>CB_Panels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CB Panel</label>
    <nameField>
        <label>CB Panel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Panels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lease_Fund__c.object
<CustomObject>
    <fields>
        <fullName>Eligible_States__c</fullName>
        <label>Eligible States</label>
        <picklist>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Fund_Partner__c</fullName>
        <label>Fund Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Lease Funds</relationshipLabel>
        <relationshipName>Lease_Funds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Max_Finance_Percent_of_Price__c</fullName>
        <label>Maximum Finance % of Price</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <label>Lease Fund</label>
    <nameField>
        <label>Lease Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lease Funds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Price_Adjustment__c.object
<CustomObject>
    <description>AstrumCRM - An object for tracking pricing adjustments to be applied to a calculated system price on a System Design Quote.</description>
    <fields>
        <fullName>Adjustment_Applied__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Adjustment Applied</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Applicable_Scenario__c</fullName>
        <label>Applicable Scenario</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lease_Fund__c</fullName>
        <formula>if(Promotion__c != null
  ,Promotion__r.Lease_Fund__r.Name
  ,Entitlement_Offer__r.Lease_Fund__r.Name
)</formula>
        <label>Lease Fund</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Promotion__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promotion</label>
        <referenceTo>Promotion__c</referenceTo>
        <relationshipLabel>Price Adjustments</relationshipLabel>
        <relationshipName>Price_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Design_Quote__c</fullName>
        <label>System Design Quote</label>
        <referenceTo>System_Design_Quote__c</referenceTo>
        <relationshipLabel>Price Adjustments</relationshipLabel>
        <relationshipName>Price_Adjustments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Line Item</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VP Override</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Price Adjustment</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Adjustments</pluralLabel>
    <recordTypes>
        <fullName>Percentage</fullName>
        <active>true</active>
        <label>Percentage</label>
    </recordTypes>
    <recordTypes>
        <fullName>Rate</fullName>
        <active>true</active>
        <label>Rate</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Promotion__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lease_Fund__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lease Fund</label>
        <referenceTo>Lease_Fund__c</referenceTo>
        <relationshipLabel>Promotions</relationshipLabel>
        <relationshipName>Promotions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Promotion</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <recordTypes>
        <fullName>Program</fullName>
        <active>true</active>
        <label>Program</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <description>AstrumPM/AstrumCRM - Each account can have one or more properties.  A property is defined by its street address.</description>
    <fields>
        <fullName>Utility_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>DEPRECATED AS OF 11/25/14</description>
        <label>Utility Rate Code</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Utility_Company__c.RecordType.Name</field>
                <operation>notEqual</operation>
                <value>Custom</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Utility_Company__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Address 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <recordTypes>
        <fullName>Residential</fullName>
        <active>true</active>
        <label>Residential</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rate_Period__c.object
<CustomObject>
    <fields>
        <fullName>Period_Type__c</fullName>
        <label>Period Type</label>
        <picklist>
            <picklistValues>
                <fullName>Peak</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Part_Peak</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Off_Peak</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flat</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rate_Period__c</fullName>
        <label>Rate Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Utility_Company__c</fullName>
        <label>Utility Company</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Utility_Company__c.RecordType.Name</field>
                <operation>notEqual</operation>
                <value>Custom</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Utility_Company__c</referenceTo>
        <relationshipLabel>Rate Period</relationshipLabel>
        <relationshipName>Rate_Period</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Rate Period</label>
    <nameField>
        <label>Rate Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Period</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/System_Design__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The Solar System Design.  Each Property can have one or more System Designs created as the result of a site Survey and the discovery of Install Locations.  Each System Design is made up of one or more System Design Arrays.</description>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>System Designs</relationshipLabel>
        <relationshipName>System_Designs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>System Design</label>
    <nameField>
        <displayFormat>SD-{0}</displayFormat>
        <label>System Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Designs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/System_Design_Quote__c.object
<CustomObject>
    <description>AstrumCRM - System Design Quote.  Each System Design can have one or more System Design Quotes.  Each quote provides the sales consultant with the ability to adjust the negotiated price of the System Design based on the Calculated System Price.  Opportunities must choose a winning System Design Quote in order to close.</description>
    <fields>
        <fullName>Scenario_1_Available_SREC_Contract_Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scenario 1 Available SREC Contract Offer</label>
        <referenceTo>Available_SREC_Contract_Offer__c</referenceTo>
        <relationshipLabel>System Design Quotes</relationshipLabel>
        <relationshipName>System_Design_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scenario_1_SAC_Loan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lease Fund record must be a loan</description>
        <label>Scenario 1 SAC Loan</label>
        <referenceTo>Lease_Fund__c</referenceTo>
        <relationshipLabel>System Design Quotes (Scenario 1 SAC Loan)</relationshipLabel>
        <relationshipName>System_Design_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Design__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>System Design</label>
        <referenceTo>System_Design__c</referenceTo>
        <relationshipLabel>System Design Quotes</relationshipLabel>
        <relationshipName>System_Design_Quotes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>System Design Quote</label>
    <nameField>
        <displayFormat>SDQ-{0}</displayFormat>
        <label>System Design Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Design Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility_Service__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - Each Property can have one or more Utility Service(s).  A Utility Service is primarily defined by the Meter ID and the Utility Company to which is connects.</description>
    <fields>
        <fullName>Net_Method_1_Tier_Cost__c</fullName>
        <label>Net Method 1 Tier Cost</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Utility Services</relationshipLabel>
        <relationshipName>Utility_Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Utility Service</label>
    <nameField>
        <label>Meter ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SystemDesignQuoteConfigExtensionTest.cls
/*
* MODIFICATION HISTORY:
*  07/18/2015 - SPRINT4- Turned off pricing while running test methods
*/
@isTest
public class SystemDesignQuoteConfigExtensionTest {
    private static boolean runalltests = true; // true to run all tests; false to skip tests and only run those where the 'if' is commented out

    @isTest static void SDQTest(){
        if(!runalltests){ return; }
        
        //Create Custom Settings
        //testdata.setupCustomSettings();
        //testdata.setupCustomConfigObjects();
        testdata.setupCustomSettingsPricing();
        testdata.setupCustomConfigObjectsPricing();
        
        //Create System Design Quote        
        System_Design_Quote__c sdq = testdata.setupSystemDesignQuote('Residential', 'Purchase', null, true, 12000);
        
        test.startTest();
        
        test.setCurrentPage(Page.SystemDesignQuoteConfig);
        ApexPages.StandardController standController = new ApexPages.StandardController(sdq);
        SystemDesignQuoteConfigExtension extn = new SystemDesignQuoteConfigExtension(standController);
        
        extn.initSDQEditMode();
        SystemDesignQuoteConfigExtension.getRoles();
        extn.getRateCodes();
        extn.getTerritorries();
        extn.getAllElectrics();
        extn.getTermLoans();
        extn.getSACLoans1();
        extn.getSACLoans2();
        extn.getSACLoans3();
        extn.getSACLoans4();
        extn.getLeaseOptions1();
        extn.getLeaseOptions2();
        
        extn.getSystemDesignInfo();
        extn.getSysDesignArrays();
        extn.getPropertyInfo();
        extn.getSDQContactInfos();
        extn.getSpecialParts();
        
        extn.selectedStdPromotion1 = 'Dollar Amount';
		extn.selectedStdPromotion2 = 'Percentage';
		extn.selectedStdPromotion3 = 'Dollar per Watt';
        extn.getStandardPromotions1();
        extn.getStandardPromotions2();
        extn.getStandardPromotions3();
        extn.getStandardPromotions4();
        
        extn.resetFinanceOptions1();
        extn.resetFinanceOptions2();
        extn.resetFinanceOptions3();
        extn.resetFinanceOptions4();
        try { extn.resetSACOptions1(); } catch(Exception e){}
        try { extn.resetSACOptions2(); } catch(Exception e){}
        try { extn.resetSACOptions3(); } catch(Exception e){}
        try { extn.resetSACOptions4(); } catch(Exception e){}
        extn.resetLeaseOp1();
        extn.resetLeaseOp2();
        extn.resetLeaseOp3();
        extn.resetLeaseOp4();

        /* cpq-460
        extn.getAvailableSRECOffers1();
        extn.getAvailableSRECOffers2();
        extn.getAvailableSRECOffers3();
        extn.getAvailableSRECOffers4();
        */
        //cpq-460
        extn.getSRECContOffers1();
        extn.getSRECContOffers2();
        extn.getSRECContOffers3();
        extn.getSRECContOffers4();

        System.assert(extn.standardPriceAdjustments1 != null);
        System.assert(extn.standardPriceAdjustments2 != null);
        System.assert(extn.standardPriceAdjustments3 != null);
        System.assert(extn.standardPriceAdjustments4 != null);

        extn.getFunds1();
        extn.getFunds2();
        extn.getFunds3();
        extn.getFunds4();        

        extn.getPortfolioRateTiers1();
        extn.getPortfolioRateTiers2();
        extn.getPortfolioRateTiers3();
        extn.getPortfolioRateTiers4();

        //extn.getDisplayVPOverride();
        Boolean vpOverride = extn.isVPOverride;
        extn.getDisplayChannelPartner();
		
        extn.getMaxSACAllowed1();
        extn.getMaxSACAllowed2();
        extn.getMaxSACAllowed3();
        extn.getMaxSACAllowed4();

        extn.getUsageTypes();
        extn.compMasterChanged();
        extn.offerChanged();
        
        
        extn.saveCustomerInfo();
        //extn.saveUtilityService();
        extn.saveUtility();
        extn.calcSQ();
        extn.saveAndConfig();
        test.stopTest();
        
    }

    @isTest static void SDQTestPricing(){
        if(!runalltests){ return; }
        
        //Create Custom Settings
        //testdata.setupCustomSettings();
        //testdata.setupCustomConfigObjects();
        testdata.setupCustomSettingsPricing();
        testdata.setupCustomConfigObjectsPricing();
        
        //Create System Design Quote        
        System_Design_Quote__c sdq = testdata.setupSystemDesignQuote('Residential', 'Purchase', null, true, 12000);
        
        test.startTest();
        
        test.setCurrentPage(Page.SystemDesignQuoteConfig);
        ApexPages.StandardController standController = new ApexPages.StandardController(sdq);
        SystemDesignQuoteConfigExtension extn = new SystemDesignQuoteConfigExtension(standController);
        
        extn.initSDQEditMode();
        extn.getLeaseOptions3();
        extn.getLeaseOptions4();                
        extn.saveAndReturnPrice();   

        Utility_Service__c utilService = [SELECT Net_Method_1_Tier_Cost__c FROM Utility_Service__c WHERE ID = :extn.utilityService.ID LIMIT 1];
        if (utilService.Net_Method_1_Tier_Cost__c == null)
            utilService.Net_Method_1_Tier_Cost__c = 'T1:3.12;-2.29;-7.70;-38.17;-19.29;-38.93;-52.05;-40.11;16.59;8.12;10.67;8.88;' + 
                                                    + 'T2:0;0;0;0;0;0;0;0;0;0;0;0;'
                                                    + 'T3:0;0;0;0;0;0;0;0;0;0;0;0;'
                                                    + 'T4:0;0;0;0;0;0;0;0;0;0;0;0;'
                                                    + 'T5:0;0;0;0;0;0;0;0;0;0;0;0;';    //Set a value to this field to assist code coverage
        update utilService;     
              
        extn.getPricingCalcs1();
        extn.getPricingCalcs2();
        extn.getPricingCalcs3();
        extn.getPricingCalcs4();
        SystemDesignQuoteConfigExtension.generatePreviewProposal(sdq.Id, sdq.System_Design__c, extn.utilityService.Id, false, false, false, false,null);
        SystemDesignQuoteConfigExtension.generatePreviewProposal(sdq.Id, sdq.System_Design__c, extn.utilityService.Id, true, true, true, true,null);
        SystemDesignQuoteConfigExtension.insertAttachment('Test: Image;Data,Test', 'Test Image', sdq.Id);
        
        extn.getProposals();     
        Property__c p = extn.prop;
        Boolean b = extn.isSdqInsert;
        String str = extn.selectedStdPromotion;
        SystemDesignQuoteConfigExtension.DisplaySysDesignArray innerClass = new SystemDesignQuoteConfigExtension.DisplaySysDesignArray();
        String mtype = innerClass.Mounting_Type;
        String wmat = innerClass.Wire_Material;
        
        test.stopTest();
        
    }
    
    
    @isTest Static void SDQTestMakeNewSDQ1(){
        if(!runalltests){ return; }
        
        //Create Custom Settings
        //testdata.setupCustomSettings();
        //testdata.setupCustomConfigObjects();
        testdata.setupCustomSettingsPricing();
        testdata.setupCustomConfigObjectsPricing();
        
        //Create System Design Quote        
        System_Design_Quote__c sdq = testdata.setupSystemDesignQuote('Residential', 'Purchase', null, false, 12000);        
        
        test.startTest();
        
        test.setCurrentPage(Page.SystemDesignQuoteConfig);
        ApexPages.StandardController standController = new ApexPages.StandardController(sdq);
        SystemDesignQuoteConfigExtension extn = new SystemDesignQuoteConfigExtension(standController);
        extn.initSDQEditMode();        
        extn.makeNewSDQ(sdq.Id);

        //Get code coverage
        String level = extn.level;
        String message = extn.message;
        Boolean bool1 = extn.isMakeCurrentValid;
        Boolean bool2 = extn.includeScenario1;
        Boolean bool3 = extn.includeScenario2;
        Boolean bool4 = extn.includeScenario3;
        Boolean bool5 = extn.includeScenario4;
        String str1 = extn.selectedSRECOffer1;
        String str2 = extn.selectedSRECOffer2;
        String str3 = extn.selectedSRECOffer3;
        String str4 = extn.selectedSRECOffer4;
        extn.showPopup2();
        extn.closePopup2();
        
        Account acct = new Account();
        acct.name='TestLeaseAcct';        
        insert acct;
        
        Lease_Fund__c fund = new Lease_Fund__c();
        fund.Name = 'Test Fund';
        fund.Eligible_States__c = 'CA; CT; DC; MA; MD; NJ; NY; OH; PA; VA';
        fund.Fund_Partner__c = acct.Id;
        fund.Max_Finance_Percent_of_Price__c = 0.5;
        insert fund;

        sdq.Scenario_1_SAC_Loan__c = fund.ID;
        try {
            extn.getMaxSACAllowed1();
        } catch (Exception e){}     //Might encounter a null pointer exception

        test.stopTest();
    }

    @isTest Static void SDQTestMakeNewSDQ2(){
        if(!runalltests){ return; }
        
        //Create Custom Settings
        testdata.setupCustomSettingsPricing();
        testdata.setupCustomConfigObjectsPricing();
        
        //Create System Design Quote        
        System_Design_Quote__c sdq = testdata.setupSystemDesignQuote('Residential', 'Purchase', null, false, 12000);

        test.startTest();
        test.setCurrentPage(Page.SystemDesignQuoteConfig);
        ApexPages.StandardController standController = new ApexPages.StandardController(sdq);
        SystemDesignQuoteConfigExtension extn = new SystemDesignQuoteConfigExtension(standController);
        extn.initSDQEditMode();        
        extn.makeNewQuote();
        
        SystemDesignQuoteConfigExtension.generatePreviewProposal(String.valueOf(sdq.ID), null, null, true, false, false, false, '-1'); //Will fail

        Promotion__c promotion = new Promotion__c(Name='Test', Start_Date__c = Date.today(), End_Date__c = Date.today().addDays(14));
        insert promotion;

        Price_Adjustment__c pa = new Price_Adjustment__c(Name = 'Test', Type__c = 'Program', System_Design_Quote__c = sdq.ID, 
                                                         Adjustment_Applied__c = true, Applicable_Scenario__c = '1', Promotion__c = promotion.ID);
        insert pa;
        try {
            SystemDesignQuoteConfigExtension.generatePreviewProposal(String.valueOf(sdq.ID), null, null, true, false, false, false, '14'); //Will fail
        } catch(Exception e){}

        test.stopTest();
        
    }

    @isTest Static void SDQTestMakeCurrent(){
        if(!runalltests){ return; }
        
        //Create Custom Settings
        testdata.setupCustomSettings();
        testdata.setupCustomConfigObjects();

        //Create System Design Quote
        Opportunity_Trigger_Utility.skipOpportunityTrigger = true;
        System_Design_Quote__c sdq = testdata.setupSystemDesignQuote('Residential', 'Purchase', null, false, 12000);
        Opportunity_Trigger_Utility.skipOpportunityTrigger = false;       
        
        Test.startTest();
        PageReference pgref = Page.SystemDesignQuoteConfig;
        Test.setCurrentPage(pgref);
        ApexPages.StandardController standController = new ApexPages.StandardController(sdq);
        SystemDesignQuoteConfigExtension extn = new SystemDesignQuoteConfigExtension(standController);

        SystemDesignQuoteTriggerHandler.skipSystemDesignQuoteTrigger = true;
        extn.makeCurrent();
        SystemDesignQuoteTriggerHandler.skipSystemDesignQuoteTrigger = false;
        
        //Code coverage
        extn.closePopup();
        extn.showPopup();
        extn.closeCustPopup();
        extn.showCustPopup();
        extn.showPageMessage();
        extn.setSelectedOffer('test string', '1');
        extn.setSelectedOffer('test string', '2');
        extn.setSelectedOffer('test string', '3');
        extn.setSelectedOffer('test string', '4');
        Boolean b = extn.hasErrors;
        extn.closeErrorPopUp();

        try {
            ID srecID = sdq.Scenario_1_Available_SREC_Contract_Offer__c;
            extn.createAvailableSREC(srecID, '1');    //Will fail
        } catch (Exception e){}

        test.stopTest();        
    }

    @isTest static void testCustomRateCodes(){      //CPQ-224
        if(!runalltests){ return; }

        testdata.setupCustomSettingsPricing();
        testdata.setupCustomConfigObjectsPricing();
            
        System_Design_Quote__c sdq = testdata.setupSystemDesignQuote('Residential', 'Purchase', null, false, 12000);

        Rate_Period__c rp = new Rate_Period__c();
        rp.Period_Type__c = 'Flat';
        rp.Name = 'Existing Rate Period';
        rp.Utility_Company__c = sdq.System_Design__r.Default_CB_Panel__r.Utility_Service__r.Utility_Rate_Code_Before_Solar__c;
        rp.Rate_Period__c = 1;
        rp.Tier_1_Rate_kWh__c = 0.16077;
        rp.Tier_2_Rate_kWh__c = 0.21050;
        rp.Tier_3_Rate_kWh__c = 0.26440;
        rp.Tier_4_Rate_kWh__c = 0.31250;
        rp.Tier_5_Rate_kWh__c = 0.34922;
        insert rp;

        Utility_Company__c urc = [SELECT Baseline_Consumption_kWh_day__c, Tier_1_Cap__c, Tier_2_Cap__c, Tier_3_Cap__c FROM Utility_Company__c WHERE ID = :sdq.System_Design__r.Default_CB_Panel__r.Utility_Service__r.Utility_Rate_Code_Before_Solar__c LIMIT 1];
        urc.Baseline_Consumption_kWh_day__c = '13.8; 13.8; 13.8; 13.8; 13.8; 9.9; 9.9; 9.9; 9.9; 9.9; 13.8; 13.8';
        urc.Tier_1_Cap__c = 100;
        urc.Tier_2_Cap__c = 130;
        urc.Tier_3_Cap__c = 200;
        update urc;

        Custom_Utility_Rate_Settings__c setting = Custom_Utility_Rate_Settings__c.getOrgDefaults();
        if (setting == null) setting = new Custom_Utility_Rate_Settings__c();
        setting.Minimum_Tier_Rate__c = 0.01;
        setting.Maximum_Tier_Rate__c = 1.0;
        setting.Maximum_Tier_Rate_Increase__c = 0.12;
        setting.Maximum_Tier_Rate_Decrease__c = 1.0;
        upsert setting;

        Test.startTest();
        Test.setCurrentPage(Page.SystemDesignQuoteConfig);
        ApexPages.StandardController stdCon = new ApexPages.StandardController(sdq);
        SystemDesignQuoteConfigExtension extn = new SystemDesignQuoteConfigExtension(stdCon);
        
        extn.showPopup3();
        extn.getCurrentTier1Rate();
        extn.getCurrentTier2Rate();
        extn.getCurrentTier3Rate();
        extn.getCurrentTier4Rate();
        extn.getCurrentTier5Rate();
        extn.getTier1RateCap();
        extn.getTier2RateCap();
        extn.getTier3RateCap();
        extn.getTier4RateCap();
        extn.getTier5RateCap();

        extn.customRates = new String[]{'-1', '', '', '', ''};
        extn.createCustomRateCode();    //Fail on -1

        extn.customRates = new String[]{'0.16077', '7.8.9', '', '', ''};
        extn.createCustomRateCode();    //Fail on 7.8.9

        //extn.customRates = new String[]{'0.002', '0.21050', '0.26440', '0.31250', '0.34922'};
        //extn.createCustomRateCode();    //Fail on 0.002

        //extn.customRates = new String[]{'1.1', '0.21050', '0.26440', '0.31250', '0.34922'};
        //extn.createCustomRateCode();    //Fail on 1.1

        //extn.customRates = new String[]{'0.3', '0.21050', '0.26440', '0.31250', '0.34922'};
        //extn.createCustomRateCode();    //Fail on 0.3

        extn.customRates = new String[]{'0.16', '0.21', '0.26', '0.31', '0.35'};
        extn.createCustomRateCode();    //Pass

        extn.closePopup3();

        Test.stopTest();
    }
}