src/objects/CB_Panel__c.object
<CustomObject>
    <description>AstrumPM - Circuit Breaker Panel - This is an object to keep track of the panels available on a utility service to which System Design Arrays can be attached.</description>
    <fields>
        <fullName>Property__c</fullName>
        <description>Property Where This CB Panel is Located</description>
        <formula>HYPERLINK( Utility_Service__r.Property__r.Id , Utility_Service__r.Property__r.Name )</formula>
        <inlineHelpText>Property Where This CB Panel is Located</inlineHelpText>
        <label>Property</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility_Service__c</fullName>
        <description>Meter ID of the Utility Service This CB Panel is connected to.</description>
        <inlineHelpText>Meter ID of the Utility Service This CB Panel is connected to.</inlineHelpText>
        <label>Meter ID</label>
        <referenceTo>Utility_Service__c</referenceTo>
        <relationshipLabel>CB Panels</relationshipLabel>
        <relationshipName>CB_Panels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CB Panel</label>
    <nameField>
        <label>CB Panel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Panels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Property__c.Property_Owner__r.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Design__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>System Design</label>
        <referenceTo>System_Design__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <description>AstrumPM/AstrumCRM - Each account can have one or more properties.  A property is defined by its street address.</description>
    <fields>
        <fullName>Utility_Company_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>DEPRECATED AS OF 11/25/14</description>
        <label>Utility Company Master</label>
        <referenceTo>Utility_Company_master__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>DEPRECATED AS OF 11/25/14</description>
        <label>Utility Rate Code</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Utility_Company__c.RecordType.Name</field>
                <operation>notEqual</operation>
                <value>Custom</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Utility_Company__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Address 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/System_Design__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The Solar System Design.  Each Property can have one or more System Designs created as the result of a site Survey and the discovery of Install Locations.  Each System Design is made up of one or more System Design Arrays.</description>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>System Designs</relationshipLabel>
        <relationshipName>System_Designs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>System Design</label>
    <nameField>
        <displayFormat>SD-{0}</displayFormat>
        <label>System Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Designs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/System_Design_Array__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The Solar System Design Array.  Each System Design is made up of one or more System Design Arrays.  Primarily defined by their mounting system and CB Panel connection, System Design Arrays are made up of one or more System Design Items.</description>
    <fields>
        <fullName>CB_Panel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Panel</label>
        <referenceTo>CB_Panel__c</referenceTo>
        <relationshipLabel>System Design Arrays</relationshipLabel>
        <relationshipName>System_Design_Arrays</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Default_Mounting_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Default Mounting Type</label>
        <referenceTo>System_Design_Product__c</referenceTo>
        <relationshipLabel>System Design Arrays (Default Mounting Type)</relationshipLabel>
        <relationshipName>System_Design_Arrays1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mounting_Type__c</fullName>
        <label>Mounting Type</label>
        <picklist>
            <picklistValues>
                <fullName>Attached Through Metal Panel Roof</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ballasted System</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clamped on Metal Seam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flush Mounted on curved concrete tile, penetrations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flush Mounted on flat concrete tile, penetrations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flush Mounted on flat roof, no penetrations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flush Mounted on flat roof, penetrating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flush Mounted on pitched roof, penetrating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flush Mounted on Slate Shingle, penetrating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flush Mounted on tile roof, requires comp shingle re-roof, penetrations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ground Mount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I-Beam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RapidRac</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tilted off flat roof, no penetrations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tilted off flat roof, penetrations</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>System_Design__c</fullName>
        <label>System Design</label>
        <referenceTo>System_Design__c</referenceTo>
        <relationshipLabel>System Design Arrays</relationshipLabel>
        <relationshipName>System_Design_Arrays</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Trench_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup</description>
        <label>Trench Type</label>
        <referenceTo>System_Design_Product__c</referenceTo>
        <relationshipLabel>System Design Arrays</relationshipLabel>
        <relationshipName>System_Design_Arrays</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Service__c</fullName>
        <formula>CB_Panel__r.Utility_Service__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Utility Service</label>
        <type>Text</type>
    </fields>
    <label>System Design Array</label>
    <nameField>
        <displayFormat>SDA-{0}</displayFormat>
        <label>System Design Array Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Design Arrays</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/System_Design_Product__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - System Design Products are the individual products (i.e. panels, inverters, etc) to be included in System Design Items.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>System Design Product</label>
    <nameField>
        <displayFormat>SDP-{0}</displayFormat>
        <label>System Design Product Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Design Products</pluralLabel>
    <recordTypes>
        <fullName>Mounting</fullName>
        <active>true</active>
        <label>Mounting</label>
    </recordTypes>
    <recordTypes>
        <fullName>Panel</fullName>
        <active>true</active>
        <label>Panel</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility_Company__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - Each Utility Service is attached to a single Utility Company.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Utility_Company_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Company Master</label>
        <referenceTo>Utility_Company_master__c</referenceTo>
        <relationshipLabel>Utility Rate Codes</relationshipLabel>
        <relationshipName>Utility_Rate_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Rate Code</label>
    <nameField>
        <label>Utility Rate Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Rate Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility_Company_master__c.object
<CustomObject>
    <description>Utility Company (distinct from Utility Rate Code)</description>
    <label>Utility Company</label>
    <nameField>
        <label>Utility Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility_Service__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - Each Property can have one or more Utility Service(s).  A Utility Service is primarily defined by the Meter ID and the Utility Company to which is connects.</description>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Utility Services</relationshipLabel>
        <relationshipName>Utility_Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Utility_Company_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Company Master</label>
        <referenceTo>Utility_Company_master__c</referenceTo>
        <relationshipLabel>Utility Services</relationshipLabel>
        <relationshipName>Utility_Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Company</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Utility_Company__c.RecordType.Name</field>
                <operation>notEqual</operation>
                <value>Custom</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Utility_Company__c</referenceTo>
        <relationshipLabel>Utility Services</relationshipLabel>
        <relationshipName>Utility_Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Rate_Code_After_Solar__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate Code After Solar</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Utility_Company__c.RecordType.Name</field>
                <operation>notEqual</operation>
                <value>Custom</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Utility_Company__c</referenceTo>
        <relationshipLabel>Utility Services (Utility Rate Code After Solar)</relationshipLabel>
        <relationshipName>Utility_Services2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Rate_Code_Before_Solar__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate Code Before Solar</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Utility_Company__c.RecordType.Name</field>
                <operation>notEqual</operation>
                <value>Custom</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Utility_Company__c</referenceTo>
        <relationshipLabel>Utility Services (Utility Rate Code Before Solar)</relationshipLabel>
        <relationshipName>Utility_Services1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Service</label>
    <nameField>
        <label>Meter ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SystemDesignUpdateBatch.cls
global class SystemDesignUpdateBatch implements Database.Batchable<sObject>, Database.Stateful{
    
    public String errors = '';
    private Integer batchNumber = 0;
    public Map<String,Id> productsMap;
    public Map<String,String> prodDescCalcToSFMap;
    
    global SystemDesignUpdateBatch(){
        
        productsMap =  new Map<String,Id>();
        
        ID recId = Schema.Sobjecttype.System_Design_Product__c.getRecordTypeInfosByName().get('Mounting').getRecordTypeId();
        List<System_Design_Product__c> sysProducts= [SELECT Id, Description__c 
                                                      FROM System_Design_Product__c 
                                                      WHERE RecordTypeId =:recId];
        for(System_Design_Product__c prod: sysProducts){
            productsMap.put(prod.Description__c, prod.Id);
            System.debug('Adding sdp to Map:' + prod.Id + '' + prod.Description__c);
        }
        
        prodDescCalcToSFMap = new Map<String,String>();
        prodDescCalcToSFMap.put('Attached Through Metal Panel Roof','Flush mounted on tilted roof with penetrations');
        prodDescCalcToSFMap.put('Ballasted System','Flush mounted on flat roof no penetrations');
        prodDescCalcToSFMap.put('Clamped on Metal Seam','Clamped on metal seams, flat or tilted');
        prodDescCalcToSFMap.put('Flush Mounted on curved concrete tile, penetrations','Curved Concrete Tile');
        prodDescCalcToSFMap.put('Flush Mounted on flat concrete tile, penetrations','Flat Concrete Tile');
        prodDescCalcToSFMap.put('Flush Mounted on flat roof, no penetrations','Flush mounted on flat roof no penetrations');
        prodDescCalcToSFMap.put('Flush Mounted on flat roof, penetrating','Flush or tilted off of flat roof with penetrations');
        prodDescCalcToSFMap.put('Flush Mounted on pitched roof, penetrating','Flush mounted on tilted roof with penetrations');
        prodDescCalcToSFMap.put('Flush Mounted on Slate Shingle, penetrating','Clay/LightWeight Tile (requires comp shingle re-roof)');
        prodDescCalcToSFMap.put('Flush Mounted on tile roof, requires comp shingle re-roof, penetrations','Clay/LightWeight Tile (requires comp shingle re-roof)');
        prodDescCalcToSFMap.put('Ground Mount','Ground Mount - Portrait MPM');
        prodDescCalcToSFMap.put('I-Beam','I-Beam Installation');
        prodDescCalcToSFMap.put('RapidRac','Tilted off of flat roof with no penetrations');
        prodDescCalcToSFMap.put('Tilted off flat roof, no penetrations','Tilted off of flat roof with no penetrations');
        prodDescCalcToSFMap.put('Tilted off flat roof, penetrations','Flush or tilted off of flat roof with penetrations');
        
        for(String prodCalcDesc: prodDescCalcToSFMap.keySet()){
            productsMap.put(prodCalcDesc,productsMap.get(prodDescCalcToSFMap.get(prodCalcDesc)));
        }

        
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc){
        
        String query ='';
        query+= 'Select Property__c from Opportunity Where StageName Not in (\'Closed - Won\', \'Closed - Lost\', \'Contract Cancelled\' ) And Property__c != null';
        System.debug('*Query '+query);
        return Database.getQueryLocator(query);
        /*
        query+= 'SELECT Id, (SELECT Default_Mounting_Type__c,Mounting_Type__c, CB_Panel__r.Utility_Service__c';
        query+= '         FROM System_Design_Arrays__r';
        query+= '         WHERE Default_Mounting_Type__c = null AND Mounting_Type__c != null)';
        query+= 'FROM System_Design__c WHERE Id IN (SELECT System_Design__c FROM System_Design_Array__c)';
        return Database.getQueryLocator(query);
        */
        
    }
    
    global void execute(Database.BatchableContext bc, List<sObject> scope){
        
        
        Opportunity_Trigger_Utility.skipOpportunityTrigger = true;
        SystemDesignTriggerHandler.skipSystemDesignTrigger = true;
        SystemDesignQuoteTriggerHandler.skipSystemDesignQuoteTrigger = true;
        SalesOrderTriggerHandler.skipSalesOrderTrigger = true;


        List<Opportunity> opps = new List<Opportunity>();
        Set<Id> propIds = new Set<Id>();
        for(SObject s: scope)
        {
            Opportunity opp = (Opportunity)s;
            System.debug('**opp - '+ opp.Id);
            if(opp.Property__c != null)
            {
                propIds.add(opp.Property__c);
            }
        }
        System.debug('**propIds '+ propIds.size());


        List<System_Design__c> sysDesigns = [SELECT Id, (SELECT Default_Mounting_Type__c,Mounting_Type__c, CB_Panel__r.Utility_Service__c
                                                FROM System_Design_Arrays__r WHERE Default_Mounting_Type__c = null AND Mounting_Type__c != null) 
                                                FROM System_Design__c WHERE Property__c in :propIds];
        
        
        System.debug('**sysDesigns '+ sysDesigns.size());
        /*
        for(SObject s: scope){
            System_Design__c sysDes = (System_Design__c)s;
            sysDesigns.add(sysDes);
        }
        */
        
        List<System_Design_Array__c> arraysToUpdate = new List<System_Design_Array__c>();
        List<Utility_Service__c> utilityServicesToUpdate = new List<Utility_Service__c>();
        Set<Id> utilityServicesSet = new Set<Id>();
        
        try{
            for(System_Design__c sysDes: sysDesigns){
                System.debug('**sysDes - '+ sysDes.Id);
                if(sysDes.System_Design_Arrays__r != null){
                    System.debug('**System_Design_Arrays__r '+ sysDes.System_Design_Arrays__r.size());
                    for(System_Design_Array__c arr: sysDes.System_Design_Arrays__r){
                        if(productsMap.containsKey(arr.Mounting_Type__c)){
                            arr.Default_Mounting_Type__c = productsMap.get(arr.Mounting_Type__c);
                            arraysToUpdate.add(arr);
                            utilityServicesSet.add(arr.CB_Panel__r.Utility_Service__c);
                            System.debug('Updating Systemdesign:' + arr.System_Design__c + ' ' + 'sdarray:' + arr.Id);            
                        }        
                    }                    
                }                    
            }
            
            utilityServicesToUpdate = [SELECT Id, Utility_Company__c, Utility_Company__r.Utility_Company_Master__c 
                                                                FROM Utility_Service__c 
                                                                WHERE Id IN:utilityServicesSet];
            for(Integer i = 0; i< utilityServicesToUpdate.size() ;i++){
                if(utilityServicesToUpdate[i].Utility_Company__c != null)
                {
                    System.debug('Updating utility service:' + utilityServicesToUpdate[i].Id);
                    utilityServicesToUpdate[i].Utility_Rate_Code_Before_Solar__c = utilityServicesToUpdate[i].Utility_Company__c;
                    utilityServicesToUpdate[i].Utility_Rate_Code_After_Solar__c = utilityServicesToUpdate[i].Utility_Company__c;
                    utilityServicesToUpdate[i].Utility_Company_Master__c = utilityServicesToUpdate[i].Utility_Company__r.Utility_Company_Master__c;     
                }
            }
            
        }catch(Exception e){
            errors += 'SystemDesign Id:' + sysDesigns[0].Id + ' ' + e.getMessage() + ' ' + e.getStackTraceString();            
        }
        
        
        if(String.isBlank(errors)){
            Database.SaveResult[] results;
            if(!arraysToUpdate.isEmpty()){
                results = Database.update(arraysToUpdate,false);
                for (Database.SaveResult result : results) {
                    if (!result.isSuccess()) {
                        // Operation failed, so get all errors                
                        for(Database.Error err : result.getErrors()) {
                            errors += result.getId() + ':'+err.getFields() + ':' + err.getStatusCode() + ': ' + err.getMessage() +'\n\n';
                        }
                    }
                } 
            }
            
            if(!utilityServicesToUpdate.isEmpty()){
                results = Database.update(utilityServicesToUpdate,false);
                for (Database.SaveResult result : results) {
                    if (!result.isSuccess()) {
                        // Operation failed, so get all errors                
                        for(Database.Error err : result.getErrors()) {
                            errors += result.getId() + ':'+err.getFields() + ':' + err.getStatusCode() + ': ' + err.getMessage() +'\n\n';
                        }
                    }
                } 
            }
            System.debug('Updated SDAs and UtilityServices');            
        }

        Opportunity_Trigger_Utility.skipOpportunityTrigger = false;
        SystemDesignTriggerHandler.skipSystemDesignTrigger = false;
        SystemDesignQuoteTriggerHandler.skipSystemDesignQuoteTrigger = false;
        SalesOrderTriggerHandler.skipSalesOrderTrigger = false;

    }
    
    global void finish(Database.BatchableContext bc){
        String[] toAddresses = new String[]{'rohit.jain@directenergysolar.com'};
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        //mail.setTargetObjectId(UserInfo.getUserId());
        mail.setToAddresses(toAddresses);
        
        if (!String.isBlank(errors)) {
            
            mail.setSubject('System Design Update completed with Errors');
            mail.setPlainTextBody(errors);
                 
        }
        else{
            mail.setSubject('System design update completed successfully without errors');
            mail.setPlainTextBody(errors);
            
        }
        
        mail.setSaveAsActivity(false);
        Messaging.sendEmail(new Messaging.Email[] { mail }, false);
        
    }

}