src/objects/CB_Panel__c.object
<CustomObject>
    <description>AstrumPM - Circuit Breaker Panel - This is an object to keep track of the panels available on a utility service to which System Design Arrays can be attached.</description>
    <fields>
        <fullName>Property__c</fullName>
        <description>Property Where This CB Panel is Located</description>
        <formula>HYPERLINK( Utility_Service__r.Property__r.Id , Utility_Service__r.Property__r.Name )</formula>
        <inlineHelpText>Property Where This CB Panel is Located</inlineHelpText>
        <label>Property</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility_Service__c</fullName>
        <description>Meter ID of the Utility Service This CB Panel is connected to.</description>
        <inlineHelpText>Meter ID of the Utility Service This CB Panel is connected to.</inlineHelpText>
        <label>Meter ID</label>
        <referenceTo>Utility_Service__c</referenceTo>
        <relationshipLabel>CB Panels</relationshipLabel>
        <relationshipName>CB_Panels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CB Panel</label>
    <nameField>
        <label>CB Panel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CB Panels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Utility_Company_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Company Master</label>
        <referenceTo>Utility_Company_master__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Company</label>
        <referenceTo>Utility_Company__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <description>AstrumPM/AstrumCRM - Each account can have one or more properties.  A property is defined by its street address.</description>
    <fields>
        <fullName>Property_ZIP__c</fullName>
        <label>Property ZIP</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility_Company_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>DEPRECATED AS OF 11/25/14</description>
        <label>Utility Company Master</label>
        <referenceTo>Utility_Company_master__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>DEPRECATED AS OF 11/25/14</description>
        <label>Utility Rate Code</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Utility_Company__c.RecordType.Name</field>
                <operation>notEqual</operation>
                <value>Custom</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Utility_Company__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Service_Territory__c</fullName>
        <description>DEPRECATED AS OF 11/25/14</description>
        <formula>Utility_Company__r.Utility_Service_Territory__c</formula>
        <label>Utility Service Territory</label>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Address 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/System_Design__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The Solar System Design.  Each Property can have one or more System Designs created as the result of a site Survey and the discovery of Install Locations.  Each System Design is made up of one or more System Design Arrays.</description>
    <fields>
        <fullName>Astrum_Invalid_SQ_Error_Message__c</fullName>
        <label>Astrum Invalid SQ Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Astrum_SQ_Calculation_Status__c</fullName>
        <label>Astrum SQ Calculation Status</label>
        <picklist>
            <picklistValues>
                <fullName>Valid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invalid</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>System Designs</relationshipLabel>
        <relationshipName>System_Designs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>System Design</label>
    <nameField>
        <displayFormat>SD-{0}</displayFormat>
        <label>System Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Designs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/System_Design_Array__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The Solar System Design Array.  Each System Design is made up of one or more System Design Arrays.  Primarily defined by their mounting system and CB Panel connection, System Design Arrays are made up of one or more System Design Items.</description>
    <fields>
        <fullName>CB_Panel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CB Panel</label>
        <referenceTo>CB_Panel__c</referenceTo>
        <relationshipLabel>System Design Arrays</relationshipLabel>
        <relationshipName>System_Design_Arrays</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Design__c</fullName>
        <label>System Design</label>
        <referenceTo>System_Design__c</referenceTo>
        <relationshipLabel>System Design Arrays</relationshipLabel>
        <relationshipName>System_Design_Arrays</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Utility_Service__c</fullName>
        <formula>CB_Panel__r.Utility_Service__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Utility Service</label>
        <type>Text</type>
    </fields>
    <label>System Design Array</label>
    <nameField>
        <displayFormat>SDA-{0}</displayFormat>
        <label>System Design Array Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Design Arrays</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility_by_Zip_Code__c.object
<CustomObject>
    <fields>
        <fullName>Utility_Company_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Company Master</label>
        <referenceTo>Utility_Company_master__c</referenceTo>
        <relationshipLabel>Utility by Zip Code</relationshipLabel>
        <relationshipName>Utility_by_Zip_Code</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Company</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Utility_Company__c.RecordType.Name</field>
                <operation>notEqual</operation>
                <value>Custom</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Utility_Company__c</referenceTo>
        <relationshipLabel>Utility by Zip Code</relationshipLabel>
        <relationshipName>Utility_by_Zip_Code</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Zip_Code__c</fullName>
        <label>Utility Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Utility by Zip Code</label>
    <nameField>
        <label>Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility by Zip Code</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility_Company__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - Each Utility Service is attached to a single Utility Company.</description>
    <fields>
        <fullName>Default_Rate_Code__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default Rate Code ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Utility_Company_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Company Master</label>
        <referenceTo>Utility_Company_master__c</referenceTo>
        <relationshipLabel>Utility Rate Codes</relationshipLabel>
        <relationshipName>Utility_Rate_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Service_Territory__c</fullName>
        <label>Utility Service Territory</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value_of_Solar_Tariiff__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Value of Solar Tariff</label>
        <type>Checkbox</type>
    </fields>
    <label>Utility Rate Code</label>
    <nameField>
        <label>Utility Rate Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Rate Codes</pluralLabel>
    <recordTypes>
        <fullName>Custom</fullName>
        <active>true</active>
        <label>Custom</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility_Company_master__c.object
<CustomObject>
    <description>Utility Company (distinct from Utility Rate Code)</description>
    <fields>
        <fullName>Solar_Compensation_Method__c</fullName>
        <label>Solar Compensation Method</label>
        <picklist>
            <picklistValues>
                <fullName>Net Metering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VOST</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Utility Company</label>
    <nameField>
        <label>Utility Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility_Service__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - Each Property can have one or more Utility Service(s).  A Utility Service is primarily defined by the Meter ID and the Utility Company to which is connects.</description>
    <fields>
        <fullName>Annual_Electricity_Consumption_kWh__c</fullName>
        <label>Annual Electricity Consumption (kWh)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Custom_Utility_Rate_Applied__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Custom Utility Rate Applied</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Utility Services</relationshipLabel>
        <relationshipName>Utility_Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Utility_Company_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Company Master</label>
        <referenceTo>Utility_Company_master__c</referenceTo>
        <relationshipLabel>Utility Services</relationshipLabel>
        <relationshipName>Utility_Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Company</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Utility_Company__c.RecordType.Name</field>
                <operation>notEqual</operation>
                <value>Custom</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Utility_Company__c</referenceTo>
        <relationshipLabel>Utility Services</relationshipLabel>
        <relationshipName>Utility_Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Rate_Code_After_Solar__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate Code After Solar</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Utility_Company__c.RecordType.Name</field>
                <operation>notEqual</operation>
                <value>Custom</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Utility_Company__c</referenceTo>
        <relationshipLabel>Utility Services (Utility Rate Code After Solar)</relationshipLabel>
        <relationshipName>Utility_Services2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Rate_Code_Before_Solar__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate Code Before Solar</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Utility_Company__c.RecordType.Name</field>
                <operation>notEqual</operation>
                <value>Custom</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Utility_Company__c</referenceTo>
        <relationshipLabel>Utility Services (Utility Rate Code Before Solar)</relationshipLabel>
        <relationshipName>Utility_Services1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Utility_Value_of_Solar_Tariff__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Value of Solar Tariff</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Utility_Company__c.RecordType.Name</field>
                <operation>notEqual</operation>
                <value>Custom</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Utility_Company__c</referenceTo>
        <relationshipLabel>Utility Services (Utility Value of Solar Tariff)</relationshipLabel>
        <relationshipName>Utility_Services3</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Service</label>
    <nameField>
        <label>Meter ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/UtilityServiceTriggerHandler.cls
/* FILE: UtilityServiceTriggerHandler.cls
   AUTHOR: Mike Katulka
   DATE: 2014-08-28
   PURPOSE: Common trigger handler for Utility Service
   MODIFICATION HISTORY: 
       10/31/14  DK  Created invalidateSystemDesigns().
       11/24/14  DK  Created updateRateCodeServiceTerritories().
       12/09/14  DK  Created setDefaultUtilityCompanyDetails().
       08/04/15  DK  Created checkCustomUtilityRate() for CPQ-224.
       08/04/15  RJ  Added skipUtilityServiceTriggerSDValidation for CPQ-224.
*/
public class UtilityServiceTriggerHandler {
    
    public static boolean isUtilityServiceTriggerRunning = false;
    public static boolean skipUtilityServiceTrigger = false;
    public static boolean skipUtilityServiceTriggerSDValidation = false; //08/04/15  RJ 224

    private boolean m_isExecuting = false;

    public UtilityServiceTriggerHandler (boolean isExecuting){      
        m_isExecuting = isExecuting;

    }

    public void OnBeforeInsert(Utility_Service__c[] newUtilityServices){
        // EXECUTE BEFORE INSERT LOGIC  
        setDefaultUtilityCompanyDetails(newUtilityServices);
        updateRateCodeServiceTerritories(newUtilityServices);
        m_isExecuting = false;
    }

    public void OnBeforeUpdate(Utility_Service__c[] updatedUtilityServices, Map<ID, Utility_Service__c> utilityServiceMap, Map<ID, Utility_Service__c> oldUtilityServiceMap){
        // BEFORE UPDATE LOGIC  
        updateRateCodeServiceTerritories(updatedUtilityServices);
        m_isExecuting = false;
    }

    public void OnAfterInsert(Utility_Service__c[] insertedUtilityServices, map<id, Utility_Service__c> insertedUtilityServicesMap){
        // EXECUTE AFTER INSERT LOGIC
        checkCustomUtilityRate(insertedUtilityServicesMap);
        m_isExecuting = false;
    }

    public void OnAfterUpdate(Utility_Service__c[] updatedUtilityServices, Map<ID, Utility_Service__c> utilityServiceMap, Map<ID, Utility_Service__c> oldUtilityServiceMap,Boolean runValidation){
        //  EXECUTE AFTER UPDATE LOGIC
        //calculateUtilityServiceValues(updatedUtilityServices, oldUtilityServiceMap);
        invalidateSystemDesigns(utilityServiceMap, oldUtilityServiceMap,runValidation);
        checkCustomUtilityRate(utilityServiceMap);
        m_isExecuting = false;
    }

    
    /*
    public void OnBeforeDelete(Object[] ObjectsToDelete, Map<Id,Lead> MapObjectMap){
        // BEFORE DELETE LOGIC
    }

    public void OnAfterDelete(Object[] deletedObjects, Map<Id,Lead> MapObjectMap){
        // AFTER DELETE LOGIC
    }

    public void OnUndelete(Object[] restoredObjects){
        // AFTER UNDELETE LOGIC
    }
    */
    public boolean IsTriggerContext{
        get{ return m_isExecuting;}
    }
    
    //If Utility.Solar Compensation Method = 'Net Metering' and if Utility Rate Code After Solar is updated OR 
    //If Utility.Solar Compensation method = 'VOST' and if Utility Value of Solar Tariff is updated
    //Invalidate the associated System Designs
    public void invalidateSystemDesigns(Map<ID, Utility_Service__c> utilityServices, Map<ID, Utility_Service__c> oldUtilityServices, Boolean runValidation){
        if(!runValidation) //08/04/15  RJ 224
        {
            Set<ID> updatedRateCode = new Set<ID>();
            Set<ID> updatedTariff = new Set<ID>();
            Set<ID> utilCompanyIDs = new Set<ID>();
            
            for (Utility_Service__c us : utilityServices.values()){
                if (us.Utility_Company_master__c != null)
                    utilCompanyIDs.add(us.Utility_Company_master__c);
            }
            
            Map<ID, Utility_Company_master__c> utilCompanies = new Map<ID, Utility_Company_master__c>(
                                                                    [SELECT Solar_Compensation_Method__c FROM Utility_Company_master__c WHERE ID IN :utilCompanyIDs]);
            for (ID usID : utilityServices.keySet()){
                Utility_Service__c us = utilityServices.get(usID);
                if (!utilCompanies.containsKey(us.Utility_Company_master__c))
                    continue;
                if (utilCompanies.get(us.Utility_Company_master__c).Solar_Compensation_Method__c == 'Net Metering' 
                    && us.Utility_Rate_Code_After_Solar__c != oldUtilityServices.get(usID).Utility_Rate_Code_After_Solar__c){
                    updatedRateCode.add(usID);
                } else if (utilCompanies.get(us.Utility_Company_master__c).Solar_Compensation_Method__c == 'VOST' 
                           && us.Utility_Value_of_Solar_Tariff__c != oldUtilityServices.get(usID).Utility_Value_of_Solar_Tariff__c){
                    updatedTariff.add(usID);
                }
            }
            
            Set<ID> rateCode_systemDesignIDs = new Set<ID>();
            Set<ID> tariff_systemDesignIDs = new Set<ID>();
            for (System_Design_Array__c sda : [SELECT System_Design__c, CB_Panel__r.Utility_Service__c FROM System_Design_Array__c 
                                               WHERE CB_Panel__r.Utility_Service__c IN :updatedRateCode OR CB_Panel__r.Utility_Service__c IN :updatedTariff]){
                
                //Get System Design IDs from the System Design Arrays related to the CB Panels related to the changed Utility Services
                if (updatedRateCode.contains(sda.CB_Panel__r.Utility_Service__c)){
                    rateCode_systemDesignIDs.add(sda.System_Design__c);
                } else if (updatedTariff.contains(sda.CB_Panel__r.Utility_Service__c)){
                    tariff_systemDesignIDs.add(sda.System_Design__c);
                }
            }
            
            System_Design__c[] systemDesigns = [SELECT Astrum_SQ_Calculation_Status__c, Astrum_Invalid_SQ_Error_Message__c FROM System_Design__c 
                                                WHERE ID IN :rateCode_systemDesignIDs OR ID IN :tariff_systemDesignIDs];
            for (System_Design__c sd : systemDesigns){
                sd.Astrum_SQ_Calculation_Status__c = 'Invalid';
                if (rateCode_systemDesignIDs.contains(sd.ID)){
                    sd.Astrum_Invalid_SQ_Error_Message__c = 'Utility Rate Code has changed';
                } else if (tariff_systemDesignIDs.contains(sd.ID)){
                    sd.Astrum_Invalid_SQ_Error_Message__c = 'Value of Solar Tariff has changed';
                }
            }
            update systemDesigns;
        }
    }
    
    //Enforce the rule: RateCodeBeforeSolar.ServiceTerritory must equal RateCodeAfterSolar.ServiceTerritory
    private void updateRateCodeServiceTerritories(Utility_Service__c[] utilityServices){
        Set<ID> rateCodeIDs = new Set<ID>();
        for (Utility_Service__c us : utilityServices){
            rateCodeIDs.add(us.Utility_Rate_Code_Before_Solar__c);
            rateCodeIDs.add(us.Utility_Rate_Code_After_Solar__c);
        }
        Map<ID, Utility_Company__c> rateCodes = new Map<ID, Utility_Company__c>([SELECT Utility_Service_Territory__c FROM Utility_Company__c WHERE ID IN :rateCodeIDs]);
        Set<Utility_Company__c> rateCodesToUpdate = new Set<Utility_Company__c>();
        for (Utility_Service__c us : utilityServices){
            ID beforeSolar = us.Utility_Rate_Code_Before_Solar__c;
            ID afterSolar = us.Utility_Rate_Code_After_Solar__c;
            if (beforeSolar == null || afterSolar == null)
                continue;
            if (rateCodes.get(beforeSolar).Utility_Service_Territory__c != rateCodes.get(afterSolar).Utility_Service_Territory__c){
                //Alert the user if the two territories are different
                if (String.isNotBlank(rateCodes.get(beforeSolar).Utility_Service_Territory__c) && 
                    String.isNotBlank(rateCodes.get(afterSolar).Utility_Service_Territory__c)){
                    
                    us.Utility_Rate_Code_Before_Solar__c.addError('Rate Code Before Solar\'s Service Territory does not match that of Rate Code After Solar');
                    us.Utility_Rate_Code_After_Solar__c.addError('Rate Code After Solar\'s Service Territory does not match that of Rate Code Before Solar');
                    continue;
                }
                
                //If one territory is null, then set it to the value of the other one
                if (String.isBlank(rateCodes.get(beforeSolar).Utility_Service_Territory__c) && 
                     String.isNotBlank(rateCodes.get(afterSolar).Utility_Service_Territory__c)){
                    rateCodes.get(beforeSolar).Utility_Service_Territory__c = rateCodes.get(afterSolar).Utility_Service_Territory__c;
                    rateCodesToUpdate.add(rateCodes.get(beforeSolar));
                } else if (String.isBlank(rateCodes.get(afterSolar).Utility_Service_Territory__c) && 
                            String.isNotBlank(rateCodes.get(beforeSolar).Utility_Service_Territory__c)){
                    rateCodes.get(afterSolar).Utility_Service_Territory__c = rateCodes.get(beforeSolar).Utility_Service_Territory__c;
                    rateCodesToUpdate.add(rateCodes.get(afterSolar));
                }
            }
        }
        update new List<Utility_Company__c>(rateCodesToUpdate);    //Will not update if we added errors
    }
    
    public void setDefaultUtilityCompanyDetails(Utility_Service__c[] newUtilServices){
        Set<ID> propSet = new Set<ID>();
        for (Utility_Service__c us : newUtilServices){
            propSet.add(us.Property__c);
        }
        
        Map<ID, String> propZips = new Map<ID, String>();   //Property ID --> Full Zip Code (Including hyphen)
        Map<ID, String> propZipsPartial = new Map<ID, String>();    //Property ID --> Partial Zip Code (Ending before hyphen)
        for (Property__c prop : [SELECT Property_Zip__c FROM Property__c WHERE ID IN :propSet AND Property_Zip__c != null]){
            propZips.put(prop.ID, prop.Property_Zip__c);
            propZipsPartial.put(prop.ID, prop.Property_Zip__c.substringBefore('-'));
        }
                
        Map<String, ID> defaultUtilComps = new Map<String, ID>();   //Zip Code --> Utility Company ID
        for (Utility_by_Zip_Code__c utilZip :[SELECT Utility_Company_Master__c, Utility_Zip_Code__c FROM Utility_by_Zip_Code__c 
                                              WHERE Utility_Zip_Code__c IN :propZips.values() OR Utility_Zip_Code__c IN :propZipsPartial.values()]){
            defaultUtilComps.put(utilZip.Utility_Zip_Code__c, utilZip.Utility_Company_Master__c);
        }
        
        Map<ID, Utility_Company__c> rateCodes = new Map<ID, Utility_Company__c>();  //Utility Company ID --> Utility Rate Code
        for (Utility_Company__c urc : [SELECT Utility_Company_Master__c, Utility_Company_Master__r.Solar_Compensation_Method__c FROM Utility_Company__c 
                                       WHERE Utility_Company_Master__c IN :defaultUtilComps.values() AND Default_Rate_Code__c = true ORDER BY Name]){
            if (rateCodes.get(urc.Utility_Company_Master__c) == null)
                rateCodes.put(urc.Utility_Company_Master__c, urc);
        }
        
        //For the VOST option
        Map<ID, ID> tariffRateCodes = new Map<ID, ID>();    //Utility Company ID --> Utility Rate Code ID
        for (Utility_Company__c urc : [SELECT Utility_Company_Master__c FROM Utility_Company__c WHERE Value_of_Solar_Tariiff__c = true AND 
                                       Utility_Company_Master__c IN :rateCodes.keySet() ORDER BY Name]){
            if (tariffRateCodes.get(urc.Utility_Company_Master__c) == null)
                tariffRateCodes.put(urc.Utility_Company_Master__c, urc.ID);
        }
        
        for (Utility_Service__c us : newUtilServices){
            ID propID = us.Property__c;
            String zip = propZips.get(propID);
            String partialZip = propZipsPartial.get(propID);
            ID utilCompID = defaultUtilComps.get(zip);
            if (utilCompID == null)
                utilCompID = defaultUtilComps.get(partialZip);
            Utility_Company__c rateCode = rateCodes.get(utilCompID);
            
            //Populate Utility Service.Utility Company Master by matching Property ZIP for Utility by ZIP Code record
            if (us.Utility_Company_Master__c == null)
                us.Utility_Company_Master__c = utilCompID;
            
            if (rateCode == null)
                continue;    //No match
            
            //Populate Utility Service.Rate Code Before Solar by finding the Utility Rate Code for the matched Utility Company where Default = true
            if (us.Utility_Rate_Code_Before_Solar__c == null)
                us.Utility_Rate_Code_Before_Solar__c = rateCode.ID;
            
            //Populate Utility Service.Rate Code After Solar with same record as Rate Code Before Solar
            if (us.Utility_Rate_Code_After_Solar__c == null)
                us.Utility_Rate_Code_After_Solar__c = rateCode.ID;
            
            //If Utility Service.Utility Company.Solar Compensation Method = 'Net Metering': Utility Value of Solar Tariff = null
            if (rateCode.Utility_Company_Master__r.Solar_Compensation_Method__c == 'Net Metering')
                us.Utility_Value_of_Solar_Tariff__c = null;
            
            //If Utility Service.Utility Company.Solar Compensation Method = 'VOST':
            //Utility Service.Utility Value of Solar Tariff = Utility Rate Code record for Utility Service.Utility Company Master where Utility Rate Code.Value of Solar Tariff = true
            if (rateCode.Utility_Company_Master__r.Solar_Compensation_Method__c == 'VOST' && tariffRateCodes.containsKey(us.Utility_Company_Master__c))
                us.Utility_Value_of_Solar_Tariff__c = tariffRateCodes.get(us.Utility_Company_Master__c);
        }
        //No DML necessary as long as this method is called in a "before" context
    }
    
    public void checkCustomUtilityRate(Map<ID, Utility_Service__c> utilServiceMap){
        Utility_Service__c[] utilServices = [SELECT Utility_Rate_Code_Before_Solar__r.RecordType.Name, Utility_Rate_Code_After_Solar__r.RecordType.Name, Custom_Utility_Rate_Applied__c FROM Utility_Service__c WHERE ID IN :utilServiceMap.keySet()];
        for (Utility_Service__c us : utilServices){
            if (us.Utility_Rate_Code_Before_Solar__r.RecordType.Name == 'Custom' || us.Utility_Rate_Code_After_Solar__r.RecordType.Name == 'Custom'){
                us.Custom_Utility_Rate_Applied__c = true;
            } else {
                us.Custom_Utility_Rate_Applied__c = false;
            }
        }
        update utilServices;
    }

    //MK - 2014-08-28 - This is used for when a user makes a change to the Annual Electricity Consumption (kWh) or 
    //Forecasted Add. Ann. Consumption (kW) fields.
    //private void calculateUtilityServiceValues(Utility_Service__c[] updatedUtilityServices, Map<Id,Utility_Service__c> oldUtilityServiceMap){
    //  system.debug('calculateUtilityServiceValues');
    //    set<id> usIDs = new set<id>();
    //  for(Utility_Service__c us : updatedUtilityServices){            
    //      Utility_Service__c oldUs = oldUtilityServiceMap.get(us.id);
    //      if(
    //            (us.Annual_Electricity_Consumption_kWh__c != oldus.Annual_Electricity_Consumption_kWh__c)
    //            ||
    //            (us.Forecasted_Add_Annual_Consumption_kWh__c != oldus.Forecasted_Add_Annual_Consumption_kWh__c)
    //      ){
    //          //Values changed
    //          usIDs.add(us.id);
    //      }           
    //  }

    //  AggregateResult[] groupedResults = [select System_Design__c 
    //                                          from System_Design_Array__c
    //                                          where CB_Panel__r.Utility_Service__c in : usIDs
    //                                          group by System_Design__c];

    //  map<id, System_Design__c> systemDesignMap = new map<id, System_Design__c>();
    //  for (AggregateResult ar : groupedResults){
    //        systemDesignMap.put((id)ar.get('System_Design__c'), new System_Design__c(id = (id)ar.get('System_Design__c')));
    //    }

    //    SystemDesignTriggerHandler handler = new SystemDesignTriggerHandler (false);
    //    //Call common class and tell the method to run a DML on the system designs.
    //    handler.calculateUtilityServiceValues(systemDesignMap, true);

    //}
 
}