src/objects/Change_Request__c.object
<CustomObject>
    <fields>
        <fullName>Change_From__c</fullName>
        <label>Change From</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Change_To__c</fullName>
        <label>Change To</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PM_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PM Project</label>
        <referenceTo>PM_Project__c</referenceTo>
        <relationshipName>Astrum_Change_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason_for_Change_1__c</fullName>
        <label>Reason for Change 1</label>
        <picklist>
            <picklistValues>
                <fullName>Customer Preference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Astrum Preference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inventory Shortage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Change/Assignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Measurement Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract/Pricing Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Error</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOA/Historical Committee/Zoning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <label>Sales Order</label>
        <referenceTo>SCRB_SalesOrder__c</referenceTo>
        <relationshipLabel>Change Requests</relationshipLabel>
        <relationshipName>Astrum_Change_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New Request</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Electrical Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Master Electrician Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Master Electrician Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to Accounting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accounting Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved/Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completion Approval Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completion Approval Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completion Pending Accounting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completion Accounting Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete/Ready for Install</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_1__c</fullName>
        <label>Type 1</label>
        <picklist>
            <picklistValues>
                <fullName>Electrical Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Field Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financing Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Layout Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mounting Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panel Change</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Change Request</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Change Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Property__c.Property_Owner__r.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PM_Project__c.object
<CustomObject>
    <description>Astrum PM 2.0 Project Object</description>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>SCRB_SalesOrder__c</referenceTo>
        <relationshipLabel>PM Projects</relationshipLabel>
        <relationshipName>PM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PM Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PM Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <description>AstrumPM/AstrumCRM - Each account can have one or more properties.  A property is defined by its street address.</description>
    <label>Property</label>
    <nameField>
        <label>Property Address 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SCRB_SalesOrder__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The SalesOrder object is the result of a Closed Won Opportunity and handles the hand off from the sales team to the operations team.</description>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>R00N300000011q88EAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ChangeRequestProcessTest.cls
/* FILE: ChangeRequestProcessTest.cls
 * AUTHOR: Rohit Jain
 * DATE: June 4, 2013
 * PURPOSE: Test class for ChangeRequest Process
 * MODIFICATION HISTORY:
 *
 */

@isTest(seeAllData=true)
public class ChangeRequestProcessTest{

    
  static testMethod void Change_Request_BIBU_Test() {
    
    Account customer = new Account(Name = 'Test Customer');
    insert customer;
    Property__c property = CreateAstrumPM2ProjectTest.createProperty(customer.Id, '123 Test St');
    Opportunity opp = CreateAstrumPM2ProjectTest.createOpportunity(customer.Id, 'Test Oppty');    
    SCRB_SalesOrder__c salesOrder = CreateAstrumPM2ProjectTest.createSalesOrder(property.Id, opp.Id);
    salesOrder.AccountId__c = customer.Id;
    update salesOrder;
    
    Test.setCurrentPage(Page.CreateAstrumPM2Project);
    //ApexPages.StandardController controller = new ApexPages.StandardController(salesOrder);
    //CreateAstrumPM2ProjectExtension extension = new CreateAstrumPM2ProjectExtension(controller);
    //PageReference result = extension.createProject();
    //String projectId = result.getUrl().substring(1);
    RootstockAutomation amr = new RootstockAutomation();
    String projectId = amr.createProject(salesOrder );
    
    Test.startTest();
    
    Change_Request__C cr = new Change_Request__C(
        Sales_Order__c = salesOrder.Id
       ,Type_1__c = 'Panel Change'
       ,Reason_for_Change_1__c = 'Design Change'
       ,Change_From__c = 'From'
       ,Change_To__c = 'To'        
    );
    
    insert cr; 
    
    cr.Status__c = 'Rejected';
    update cr;   
    
    ApexPages.StandardController crcontroller = new ApexPages.StandardController(cr);
    Change_Request_Escalation_Controller escController = new Change_Request_Escalation_Controller(crcontroller);    
    escController.comments = 'Test Comments';
    
    PageReference escResult = escController.submitEscalation();
    
    
    //ApexPages.StandardController crcontroller = new ApexPages.StandardController(cr);
    Change_Request_Cancellation_Controller cancelController = new Change_Request_Cancellation_Controller(crcontroller);    
    cancelController.comments = 'Test Comments';
    
    PageReference cancelResult = cancelController.submitCancellation();
    
    cr.Status__c = 'Approved/Pending';
    update cr; 
    
    Change_Request_Completion_Controller compController = new Change_Request_Completion_Controller (crcontroller);    
    compController.comments = 'Test Comments';
    
    PageReference compResult = compController.submitCompletion();
    
    
    
    Test.stopTest();   
    
    cr =  
      [SELECT Id, PM_Project__c 
      FROM Change_Request__C
      WHERE Id = :cr.Id];
    
    
    System.assertEquals(cr.PM_Project__c , projectId ); 
      
  }
}