src/objects/Change_Request__c.object
<CustomObject>
    <fields>
        <fullName>Completion_Comments__c</fullName>
        <label>Completion/Cancellation Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New Request</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for Electrical Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Master Electrician Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Master Electrician Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to Accounting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accounting Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved/Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completion Approval Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completion Approval Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completion Pending Accounting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completion Accounting Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete/Ready for Install</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Change Request</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Change Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Change_Request_Completion_Controller.cls
public with sharing class Change_Request_Completion_Controller {

    private Change_Request__c cr;
    public boolean completionDone {get; private set;}
    public String comments {get; set;} 
    private static final Set<String> VALID_STATUS_FOR_COMPLETION = new Set<String> {
        'Approved/Pending', 'Completion Approval Rejected'
         };
  
    public Change_Request_Completion_Controller(ApexPages.StandardController stdController) {
        cr = (Change_Request__c) stdController.getRecord();  
        Change_Request__c crequest = [Select Status__c from Change_Request__c Where Id = :cr.Id];
        if (crequest != null && !(VALID_STATUS_FOR_COMPLETION.contains(crequest.Status__c)))
            completionDone = true;          
    }

   public PageReference submitCompletion() {
    
    if(comments == null || comments.trim().length() == 0)
    {
        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Completion Comments are Required.'));
        return null;
    }    
    else
    {
        if (cr != null) {
              cr.Completion_Comments__c = comments ;       
              cr.Status__c = 'Completion Approval Pending'; 
              update cr;
                 
        }
            return (new ApexPages.StandardController(cr)).view();
      }    
    }
}