src/objects/Community_Program_Offer__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Makes the offer available. This is key for when an area has repetitive community programs. If there is already a program offer which ends in 1 month, and you are adding a new one 2 months out, don&apos;t check this checkbox until the first one ends.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Eligibility_Criterion__c</fullName>
        <label>Eligibility Criterion</label>
        <picklist>
            <picklistValues>
                <fullName>City</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zip</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Affiliate Program</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Extension_End_Date__c</fullName>
        <label>Extension End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Initial_End_Date__c</fullName>
        <label>Initial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Community Program Offer</label>
    <nameField>
        <displayFormat>CPO-{00000}</displayFormat>
        <label>Community Program Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Program Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Community_Program_Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Community Program Offer</label>
        <referenceTo>Community_Program_Offer__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QAS_County__c</fullName>
        <description>QAS Auto-Populated County</description>
        <inlineHelpText>QAS Auto-Populated County</inlineHelpText>
        <label>QAS County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/System_Design_Quote__c.object
<CustomObject>
    <description>AstrumCRM - System Design Quote.  Each System Design can have one or more System Design Quotes.  Each quote provides the sales consultant with the ability to adjust the negotiated price of the System Design based on the Calculated System Price.  Opportunities must choose a winning System Design Quote in order to close.</description>
    <fields>
        <fullName>Community_Program_Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Community Program Offer</label>
        <referenceTo>Community_Program_Offer__c</referenceTo>
        <relationshipLabel>System Design Quotes</relationshipLabel>
        <relationshipName>System_Design_Quotes_CP</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>System Design Quote</label>
    <nameField>
        <displayFormat>SDQ-{0}</displayFormat>
        <label>System Design Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Design Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CommunityProgramOfferUtilityTest.cls
/*
* MODIFICATION HISTORY:
*  07/18/2015 - SPRINT4- Turned off pricing while running test methods
*/
@isTest
private class CommunityProgramOfferUtilityTest {
    private static boolean runalltests = true; // true to run all tests; false to skip tests and only run those where the 'if' is commented out

	@isTest static void test_method_one() {
		if(!runalltests){ return; }

        //Create Custom Settings
        //testdata.setupCustomSettings();
        //testdata.setupCustomConfigObjects();
        testdata.setupCustomSettingsPricing();
        testdata.setupCustomConfigObjectsPricing();
        testdata.setupCommunityProgramOffers();

        List<Community_Program_Offer__c> cpoList = [SELECT Eligibility_Criterion__c, Start_Date__c, Extension_End_Date__c, Initial_End_Date__c FROM Community_Program_Offer__c];

        Test.startTest();

        System_Design_Quote__c sdq = testData.setupSystemDesignQuote('Residential', 'Purchase', null, true, 12000);

        Test.stopTest();
	}

	@isTest static void test_method_two() {
		if(!runalltests){ return; }

        //Create Custom Settings
        //testdata.setupCustomSettings();
        //testdata.setupCustomConfigObjects();
        testdata.setupCustomSettingsPricing();
        testdata.setupCustomConfigObjectsPricing();
        testdata.setupCommunityProgramOffers();

        List<Community_Program_Offer__c> cpoList = [SELECT Eligibility_Criterion__c FROM Community_Program_Offer__c];
        //for(Community_Program_Offer__c cpo : cpoList){
        //	if(cpo.Eligibility_Criterion__c == 'ZIP'){
        //		cpo.Active__c = false;
        //	}
        //}
        update cpoList;

        Test.startTest();

        System_Design_Quote__c sdq = testData.setupSystemDesignQuote('Residential', 'Purchase', null, true, 12000);

        Test.stopTest();
	}

	@isTest static void test_method_three() {
		if(!runalltests){ return; }

        //Create Custom Settings
        //testdata.setupCustomSettings();
        //testdata.setupCustomConfigObjects();
        testdata.setupCustomSettingsPricing();
        testdata.setupCustomConfigObjectsPricing();
        testdata.setupCommunityProgramOffers();

        List<Community_Program_Offer__c> cpoList = [SELECT Eligibility_Criterion__c FROM Community_Program_Offer__c];
        //for(Community_Program_Offer__c cpo : cpoList){
        //	if(cpo.Eligibility_Criterion__c == 'ZIP' || cpo.Eligibility_Criterion__c == 'City'){
        //		cpo.Active__c = false;
        //	}
        //}
        update cpoList;

        Test.startTest();

        System_Design_Quote__c sdq = testData.setupSystemDesignQuote('Residential', 'Purchase', null, true, 12000);

        Test.stopTest();
	}
	
	@isTest static void test_method_four() {
		if(!runalltests){ return; }

        //Create Custom Settings
        //testdata.setupCustomSettings();
        //testdata.setupCustomConfigObjects();
        testdata.setupCustomSettingsPricing();
        testdata.setupCustomConfigObjectsPricing();
        testdata.setupCommunityProgramOffers();

        Test.startTest();

        Lead l = new Lead (
            LastName = 'Test',
            Company = 'Test',
            Street = '99 Oakmark Ave',
            City = 'Annapolis Junction',
            State = 'MD',
            QAS_County__c = 'Howard County, MD',
            PostalCode = '20701'
        );
        insert l;

        l = [SELECT Id, QAS_County__c FROM Lead WHERE LastName = 'Test'];
        l.QAS_County__c = 'XXXX, MD';
        update l;

        Test.stopTest();
	}
}