src/objects/Community_Program_Offer__c.object
<CustomObject>
    <fields>
        <fullName>Eligibility_Criterion__c</fullName>
        <label>Eligibility Criterion</label>
        <picklist>
            <picklistValues>
                <fullName>City</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zip</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Affiliate Program</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Eligible_Values__c</fullName>
        <inlineHelpText>Semicolon delimited list of either zip codes, cities, or counties.  (Cities and counties must be given a state code as well.  For example: &quot;Norristown, PA; Annapolis Junction, MD;&quot;)</inlineHelpText>
        <label>Eligible Values</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Extension_End_Date__c</fullName>
        <label>Extension End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Initial_End_Date__c</fullName>
        <label>Initial End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Community Program Offer</label>
    <nameField>
        <displayFormat>CPO-{00000}</displayFormat>
        <label>Community Program Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Program Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Affiliate_Community_Program__c</fullName>
        <label>Affiliate Community Program</label>
        <picklist>
            <picklistValues>
                <fullName>CUNY/Pepsi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D2D Atlantic City Electric</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D2D BG&amp;E</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D2D ConEd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D2D Connecticut L&amp;P</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D2D Delmarva</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D2D JCP&amp;L</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D2D Long Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D2D National Grid MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D2D NSTAR MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D2D Pacific Gas &amp; Electric</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D2D PEPCO MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D2D PSEG NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D2D SCE - 10B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D2D United Illuminating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE Delmarva</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE Houston Employee Offer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gloucester Challenge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mass Energy Solar Connect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Norwalk CPO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retrofit Baltimore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solarize Sagewell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solarize SecondChance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solarize VCCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temple Sinai Solar Co-Op DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temple Sinai Solar Co-Op MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temple Sinai Solar Co-Op VA</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Community_Program_Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Community Program Offer</label>
        <referenceTo>Community_Program_Offer__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <picklist>
            <picklistValues>
                <fullName>CONNECTICUT =&gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fairfield CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hartford CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Litchfield CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middlesex CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Haven CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New London CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tolland CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Windham CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DISTRICT OF COLUMBIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DELAWARE =&gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kent DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Castle DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sussex DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MARYLAND =&gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allegany MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anne Arundel MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baltimore City MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baltimore MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Calvert MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caroline MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carroll MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cecil MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charles MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dorchester MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Frederick MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Garrett MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Harford MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Howard MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kent MD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>QAS_County__c</fullName>
        <description>QAS Auto-Populated County</description>
        <inlineHelpText>QAS Auto-Populated County</inlineHelpText>
        <label>QAS County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Community_Program_Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Community Program Offer</label>
        <referenceTo>Community_Program_Offer__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <picklist>
            <picklistValues>
                <fullName>CONNECTICUT =&gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fairfield CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hartford CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Litchfield CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middlesex CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Haven CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New London CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tolland CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Windham CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DISTRICT OF COLUMBIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DELAWARE =&gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kent DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Castle DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sussex DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MARYLAND =&gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allegany MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anne Arundel MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baltimore City MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baltimore MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Calvert MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caroline MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carroll MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cecil MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charles MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dorchester MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Frederick MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Garrett MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Harford MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Howard MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kent MD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <description>AstrumPM/AstrumCRM - Each account can have one or more properties.  A property is defined by its street address.</description>
    <fields>
        <fullName>Community_Program_Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Community Program Offer</label>
        <referenceTo>Community_Program_Offer__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Address 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/System_Design_Quote__c.object
<CustomObject>
    <description>AstrumCRM - System Design Quote.  Each System Design can have one or more System Design Quotes.  Each quote provides the sales consultant with the ability to adjust the negotiated price of the System Design based on the Calculated System Price.  Opportunities must choose a winning System Design Quote in order to close.</description>
    <fields>
        <fullName>Community_Program_Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Community Program Offer</label>
        <referenceTo>Community_Program_Offer__c</referenceTo>
        <relationshipLabel>System Design Quotes</relationshipLabel>
        <relationshipName>System_Design_Quotes_CP</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>System Design Quote</label>
    <nameField>
        <displayFormat>SDQ-{0}</displayFormat>
        <label>System Design Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Design Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CommunityProgramOfferUtility.cls
/* FILE: CommunityProgramOfferUtility.cls
 * AUTHOR: Mike Katulka
 * DATE: Aug 18, 2014
 * PURPOSE: Utility class called from triggers to help match a Community Program Offer to the source record.
 * MODIFICATION HISTORY: 
 *
 */
public class CommunityProgramOfferUtility {

	//Public variable which would first be populated from an SDQ update, then in the Opportunity trigger
	//we could reference this to save on querying for the same data
	public static List<Community_Program_Offer__c> CPOs;

	public static void matchCommunityProgramOffer(list<sObject> sourceRecs){
		system.debug('matchCommunityProgramOffer');
		schema.sObjectType sourceType = sourceRecs[0].getsObjectType();		
		
		system.debug('Get list of Community_Program_Offer__c');
		
		//CPOs could have been queried already through SDQ trigger and be needed for the Opp trigger later on
		if(CommunityProgramOfferUtility.CPOs == null){
			CommunityProgramOfferUtility.CPOs = [SELECT Start_Date__c, Eligibility_Criterion__c, Eligible_Values__c, 
														Extension_End_Date__c, Initial_End_Date__c
												FROM Community_Program_Offer__c
												ORDER BY Start_Date__c DESC
												LIMIT 10000]; //This object should never reach this number but just in case..
		}

		//Even if CPO's returns no records, go through the records to clear values as needed
		system.debug('CPO Size: ' + CommunityProgramOfferUtility.CPOs.size());
		system.debug('Find out which type of object this is.');
		
		//LEADS
		if(sourceType == Lead.sObjectType){
			system.debug('These are leads');
			
			List<Lead> leadListForUpdate = new List<Lead>();

			// Cast the sObject List to a Lead List....
			List<Lead> leadList = (List<Lead>)sourceRecs;
			for(Lead l : leadList){	
				if(l.isConverted) continue; //Skip if this lead has been converted
				system.debug('Lead being matched: ' + l.id);

				string county = (l.QAS_County__c != null ? l.QAS_County__c : SalesRegionHelper.removeState(l.County__c));
				Community_Program_Offer__c cpo = CommunityProgramOfferUtility.getCPO(county, l.State, l.City, l.PostalCode, l.Affiliate_Community_Program__c);
				if(cpo == null){
					//Need to clear the community program fields					
					l.Community_Program_Offer__c = null;
					l.Split_Community_Program_Credit__c = false;
				}else{					
					date startDate = l.CreatedDate == null ? date.today() : l.CreatedDate.date();
					list<string> vals = CommunityProgramOfferUtility.getNewCommFieldValues(startDate, date.today(), cpo, null);

					//Check to see if there is a community program for this record
					if(vals[0] == 'NULL') l.Community_Program_Offer__c = null;
					else l.Community_Program_Offer__c = vals[0];

					//Check if the cpo credit should be split
					if(vals[1] == 'TRUE') l.Split_Community_Program_Credit__c = true;
					else l.Split_Community_Program_Credit__c = false;

				}
				leadListForUpdate.add(l);
			}

			if(!leadListForUpdate.isEmpty() && !trigger.isExecuting) update leadListForUpdate;

		//OPPORTUNITIES
		}else if(sourceType == Opportunity.sObjectType){
			system.debug('These are Opps');

			List<Opportunity> oppList = (List<Opportunity>)sourceRecs;
			List<Opportunity> opportunityListForUpdate = new List<Opportunity>();
			Set<Id> propIds = new Set<Id>();
			for(Opportunity o : oppList){	
				propIds.add(o.Property__c);
			}

			Map<Id,Property__c> PropertyMap = new Map<Id,Property__c>([Select Id, Community_Program_Offer__c from Property__c Where Id in : PropIds]);

			
			// Cast the sObject List to an Opp List....
			
			for(Opportunity o : oppList){	
				//if(o.isClosed) continue; //Skip if this Opportunity has been closed
				system.debug('Opportunity being matched: ' + o.id);

				string county = (o.QAS_Property_County__c != null ? o.QAS_Property_County__c : SalesRegionHelper.removeState(o.Property_County__c));				
				Community_Program_Offer__c cpo = CommunityProgramOfferUtility.getCPO(county, o.Property_State__c, o.Property_City__c, o.Property_Zip__c, o.Affiliate_Community_Program__c);
				if(cpo == null){
					//Need to clear the community program fields					
					o.Community_Program_Offer__c = null;					
					o.Split_Community_Program_Credit__c = false;
					if(PropertyMap.get(o.Property__c) != null)
					{
						PropertyMap.get(o.Property__c).Community_Program_Offer__c = null;	
					}
				}else{					
					date startDate = o.CreatedDate == null ? date.today() : o.CreatedDate.date();
					list<string> vals = CommunityProgramOfferUtility.getNewCommFieldValues(startDate, o.closeDate, cpo, o);

					//Check to see if there is a community program for this record
					if(vals[0] == 'NULL') 
					{
						o.Community_Program_Offer__c = null;
						if(PropertyMap.get(o.Property__c) != null)
						{
							PropertyMap.get(o.Property__c).Community_Program_Offer__c = null;	
						}
					}
					else {
						o.Community_Program_Offer__c = vals[0];
						if(PropertyMap.get(o.Property__c) != null)
						{
							PropertyMap.get(o.Property__c).Community_Program_Offer__c = vals[0];
						}
					}

					//Check if the cpo credit should be split
					if(vals[1] == 'TRUE') o.Split_Community_Program_Credit__c = true;
					else o.Split_Community_Program_Credit__c = false;
				}
				opportunityListForUpdate.add(o);
			}

			if(!opportunityListForUpdate.isEmpty() && !trigger.isExecuting) update opportunityListForUpdate;
			if(!PropertyMap.isEmpty() && !trigger.isExecuting) update PropertyMap.Values();

		//SYSTEM DESIGN QUOTE
		}else if(sourceType == System_Design_Quote__c.sObjectType){
			system.debug('These are SDQs');

			List<System_Design_Quote__c> sdqListForUpdate = new List<System_Design_Quote__c>();
			
			// Cast the sObject List to an SDQ List....
			List<System_Design_Quote__c> sdqList = (List<System_Design_Quote__c>)sourceRecs;
			for(System_Design_Quote__c sdq : sdqList){	
				if(sdq.Pricing_Locked__c) continue; //Skip if pricing is locked
				system.debug('System_Design_Quote__c being matched: ' + sdq.id);

				string county = (sdq.QAS_Property_County__c != null ? sdq.QAS_Property_County__c : SalesRegionHelper.removeState(sdq.Property_County__c));				
				Community_Program_Offer__c cpo = CommunityProgramOfferUtility.getCPO(county, sdq.Property_State__c, sdq.Property_City__c, sdq.Property_Zip__c, sdq.Affiliate_Community_Program__c);
				if(cpo == null){
					//Need to clear the community program fields					
					sdq.Community_Program_Offer__c = null;					
				}else{
					Date pricingDate = Date.today();    //sdq.CreatedDate == null ? date.today() : sdq.CreatedDate.date();
			        if (sdq.Pricing_Date__c != null)
			            pricingDate = Date.newInstance(sdq.Pricing_Date__c.year(), sdq.Pricing_Date__c.month(), sdq.Pricing_Date__c.day());	//CPQ-717

					list<string> vals = CommunityProgramOfferUtility.getNewCommFieldValues(pricingDate, pricingDate, cpo, null);

					//Check to see if there is a community program for this record
					if(vals[0] == 'NULL') sdq.Community_Program_Offer__c = null;
					else sdq.Community_Program_Offer__c = vals[0];

					//SDQ does not have split checkbox field, ignore vals[1]					
				}
				sdqListForUpdate.add(sdq);
			}

			if(!sdqListForUpdate.isEmpty() && !trigger.isExecuting) update sdqListForUpdate;
		}

	}


	public static List<String> getNewCommFieldValues(date startDate, date endDate, Community_Program_Offer__c cpo, Opportunity opp){
		system.debug('getNewCommFieldValues');
		system.debug('startDate of source record: ' + startDate);
		system.debug('endDate of source record: ' + endDate);
		system.debug('Start_Date__c of cpo record: ' + cpo.Start_Date__c);
		system.debug('Extension_End_Date__c of cpo record: ' + cpo.Extension_End_Date__c);
		system.debug('Initial_End_Date__c of cpo record: ' + cpo.Initial_End_Date__c);

		//startDate usually represents the created date of the record
		//endDate usually represents today() or the opp closed date

		//default values if nothing below matches
		boolean splitComm = false;
		id cpoId;

		//1. If the Record StartDate is before the CommStartDate AND
		if(startDate < cpo.Start_Date__c){
			//The Record EndDate is before the CommStartDate AND
			if(endDate < cpo.Start_Date__c){				
				//This is not an Opp
				if(opp == null){
					system.debug('outcome 1');
					//Community Program fields should be blank
					cpoId = null;
					//Split Community Program Credit fields = FALSE
					splitComm = false;
				//This is an Opp
				}else{
					system.debug('Opp ID: ' + opp.id);
					system.debug('Opp Stage: ' + opp.stagename);
					system.debug('Opp isClosed: ' + opp.isclosed);					
					//Stage = Closed - Won or Closed - Lost	
					if(opp.isClosed){
						system.debug('outcome 2');
						//Community Program fields should be blank
						cpoId = null;
						//Split Community Program Credit fields = FALSE
						splitComm = false;
					//Stage <> Closed - Won or Closed - Lost
					}else{
						system.debug('outcome 3');
						//Community Program fields should be blank
						cpoId = cpo.id;
						//Split Community Program Credit fields = FALSE
						splitComm = true;
					}
				}				
			}

			//The Record EndDate is after the CommStartDate and before the Extension End Date
			else if(endDate > cpo.Start_Date__c && (cpo.Extension_End_Date__c == null || endDate < cpo.Extension_End_Date__c)){
				//This is not an Opp
				if(opp == null){
					system.debug('outcome 4');
					//Community Program fields should be populated
					cpoId = cpo.id;
					//Split Community Program Credit fields = TRUE
					splitComm = true;
				//This is an Opp
				}else{
					system.debug('Opp ID: ' + opp.id);
					system.debug('Opp Stage: ' + opp.stagename);
					system.debug('Opp isClosed: ' + opp.isclosed);
					//Stage = Closed - Won or Closed - Lost	
					if(opp.isClosed){
						system.debug('outcome 5');
						//Community Program fields should be populated
						cpoId = cpo.id;
						//Split Community Program Credit fields = TRUE
						splitComm = true;
					//Stage <> Closed - Won or Closed - Lost
					}else{
						system.debug('outcome 6');
						//Community Program fields should be populated
						cpoId = cpo.id;
						//Split Community Program Credit fields = TRUE
						splitComm = true;
					}
				}				
			}

			//The Record Enddate is after the CPOExtensionEndDate
			else if(cpo.Extension_End_Date__c != null && endDate > cpo.Extension_End_Date__c){
				system.debug('outcome 7');
				//Community Program fields should be blank
				cpoId = null;
				//Split Community Program Credit fields = FALSE
				splitComm = false;
			}
		}
		//2. OR If the Opportunity Created Date is between Start Date and Extension End Date AND
		else if(startDate >= cpo.Start_Date__c && (cpo.Extension_End_Date__c == null || startDate < cpo.Extension_End_Date__c)){
			//The Record EndDate is before the CPOExtensionEndDate
			if(cpo.Extension_End_Date__c == null || endDate < cpo.Extension_End_Date__c){
				system.debug('outcome 8');
				//Community Program fields should be blank
				cpoId = cpo.id;
				//Split Community Program Credit fields = FALSE
				splitComm = false;
			}
			
			//The Record Enddate is after the CPOExtensionEndDate
			else if(cpo.Extension_End_Date__c != null && endDate > cpo.Extension_End_Date__c){
				system.debug('outcome 9');
				//Community Program fields should be blank
				cpoId = cpo.id;
				//Split Community Program Credit fields = FALSE
				splitComm = true;
			}
		}

		
		//Extra checking for special circumstances... separate if statements

		//3. If the Record StartDate is after the CPOInitialEndDate AND		
		if(cpo.Initial_End_Date__c != null && startDate > cpo.Initial_End_Date__c){
			//The Record EndDate is before the CPOExtensionEndDate
			if(cpo.Extension_End_Date__c == null || endDate < cpo.Extension_End_Date__c){
				system.debug('extra outcome 1');
				//Community Program fields should be blank
				cpoId = cpo.id;
				//Split Community Program Credit fields = FALSE
				splitComm = false;
			}
			//The Record Enddate is after the CPOExtensionEndDate
			else if(cpo.Extension_End_Date__c != null && endDate > cpo.Extension_End_Date__c){
				system.debug('extra outcome 2');
				//Community Program fields should be blank
				cpoId = null;
				//Split Community Program Credit fields = FALSE
				splitComm = false;
			}
		}


		//4. If the Record StartDate is after the CPOExtensionEndDate AND
		if(cpo.Extension_End_Date__c != null && startDate > cpo.Extension_End_Date__c
					//The Record Enddate is after the CPOExtensionEndDate
					&& endDate > cpo.Extension_End_Date__c){

			system.debug('extra outcome 3');
			//Community Program fields should be blank
			cpoId = null;
			//Split Community Program Credit fields = FALSE
			splitComm = false;
			
		}

		//Construct the return variables into a list of strings
		list<string> retVal = new list<string>();
		retVal.add(cpoId == null ? 'NULL' : cpoId);
		retVal.add(splitComm ? 'TRUE' : 'FALSE');
		return retVal;
	}

	public static Community_Program_Offer__c getCPO(string county, string state, string city, string zip, String affiliateProgram){
		system.debug('getCPO');
		string cityState;
		string countyState;


		//Validate that data pulled from the record is good.
		if(county == null) system.debug('***Missing County on this record');
		if(city == null) system.debug('***Missing City on this record');
		if(state == null) system.debug('***Missing State on this record');
		if(zip == null) system.debug('***Missing Zip on this record');
		else{
			zip = zip.length() > 5 ? zip.substring(0,5) : zip;
		}
		
		//build the search strings
		if(city != null && state != null){
			cityState = city.trim().tolowercase() + ', ' + state.trim().tolowercase();
		}
		
		if(county != null && state != null){
			countyState = county.trim().tolowercase() + ', ' + state.trim().tolowercase();
		}


		system.debug('CityState: ' + cityState);
		system.debug('countyState: ' + countyState);
		system.debug('Zip: ' + zip);	
		system.debug('affiliateProgram: ' + affiliateProgram);		

		Community_Program_Offer__c cpo;

		for(Community_Program_Offer__c c : CommunityProgramOfferUtility.CPOs){			
			
			system.debug('CPO: ' + c.id);
			system.debug('Eligibility_Criterion__c: ' + c.Eligibility_Criterion__c);
			system.debug('Eligible_Values__c: ' + c.Eligible_Values__c);
			if(c.Eligibility_Criterion__c == null || c.Eligible_Values__c == null){
				system.debug('***ERROR, skip: This CPO is missing the Eligibility_Criterion__c and/or Eligible_Values__c values.');
				continue; //next record
			}


			//Split the semi-colon space delimited text into a searchable set
			//Split returns a list, that we can put in the constructor of the set
			//Split into set insead of string.contains search because these can get mixed up: "west goshen, pa"... where searching for "goshen, pa" 
					//will return true using string.contains
			set<string> valSet = new set<string>(c.Eligible_Values__c.tolowercase().replace('; ', ';').replace(' ;', ';').split(';'));
			//CITY
			if(c.Eligibility_Criterion__c == 'City'){
				if(cityState == null){					
					continue; //next record
				}
				if(valSet.contains(cityState)){
					//We have a match!
					system.debug('Found the first matching record! - ' + c.id);
					cpo = c;
					break;
				}
			}
			//COUNTY
			else if(c.Eligibility_Criterion__c == 'County'){
				if(countyState == null){					
					continue; //next record
				}
				if(valSet.contains(countyState)){
					//We have a match!
					system.debug('Found the first matching record! - ' + c.id);
					cpo = c;
					break;
				}
			}
			//ZIP
			else if(c.Eligibility_Criterion__c == 'Zip'){
				if(zip == null){					
					continue; //next record
				}
				if(valSet.contains(zip)){
					//We have a match!
					system.debug('Found the first matching record! - ' + c.id);
					cpo = c;
					break;
				}
			}

			else if(c.Eligibility_Criterion__c == 'Affiliate Program'){
				if(affiliateProgram == null){					
					continue; //next record
				}
				if(valSet.contains(affiliateProgram.tolowercase())){
					//We have a match!
					system.debug('Found the first matching record! - ' + c.id);
					cpo = c;
					break;
				}
			}
		}

		return cpo;
	}
}