src/objects/Company_Wide_Report__c.object
<CustomObject>
    <description>This object represents the actual running of the Company Wide Report and contains the results of calculations based on the time the report was run</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ready_To_Send__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Ready To Send</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reporting_Frequency__c</fullName>
        <label>Reporting Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Daily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Company Wide Report</label>
    <nameField>
        <displayFormat>CWR-{0000000}</displayFormat>
        <label>Company Wide Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Company Wide Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Metric__c.object
<CustomObject>
    <description>This object represents the definition of a metric in the Company Wide Report</description>
    <fields>
        <fullName>Display_Order__c</fullName>
        <label>Display Order</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Include_On_Report__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Include On Report?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Calculated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Calculated?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reporting_Frequency__c</fullName>
        <label>Reporting Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Daily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Metric</label>
    <nameField>
        <label>Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metrics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Reported_Metric_Value__c.object
<CustomObject>
    <description>The object represents the actual reported value of a metric object for use in a company wide report</description>
    <fields>
        <fullName>Company_Wide_Report__c</fullName>
        <label>Company Wide Report</label>
        <referenceTo>Company_Wide_Report__c</referenceTo>
        <relationshipLabel>Reported Metric Values</relationshipLabel>
        <relationshipName>Reported_Metric_Values</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Delta__c</fullName>
        <label>Delta</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Headcount__c</fullName>
        <label>Headcount</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Metric__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Metric</label>
        <referenceTo>Metric__c</referenceTo>
        <relationshipLabel>Reported Metric Values</relationshipLabel>
        <relationshipName>Reported_Metric_Values</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Month_To_Date__c</fullName>
        <label>Month To Date</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reported_Value__c</fullName>
        <label>Reported Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Week_To_Date__c</fullName>
        <label>Week To Date</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year_To_Date__c</fullName>
        <label>Year To Date</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>Reported Metric Value</label>
    <nameField>
        <displayFormat>RMV-{0000000}</displayFormat>
        <label>Reported Metric Value Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reported Metric Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CompanyWideReportInputController.cls
public with sharing class CompanyWideReportInputController {

    public Company_Wide_Report__c companyWideReport {get;private set;}
    public List<ReportedMetricValueWrapper> reportedMetricValues {get;private set;}
    public Boolean previewReport {get;set;}
    public Integer rowToDelete {get;set;}

    public List<SelectOption> years {get;private set;}
    public Integer selectedYear {get;set;}
    public List<SelectOption> periods {get;private set;}
    public String selectedPeriod {get;set;}

    private List<SelectOption> metricOptions {get;private set;}

    public CompanyWideReportInputController() {
        system.debug('**SZ: (constructor) reportedMetricValues = ' + reportedMetricValues);
        this.previewReport = false;

        this.years = new List<SelectOption>();
        this.years.add(new SelectOption(String.valueOf(Date.today().year() - 1), String.valueOf(Date.today().year() - 1)));
        this.years.add(new SelectOption(String.valueOf(Date.today().year()), String.valueOf(Date.today().year())));
        this.selectedYear = Date.today().year();

        this.periods = new List<SelectOption>();
        this.periods.add(new SelectOption('', ''));
        this.periods.add(new SelectOption('1', 'DEC16-JAN15'));
        this.periods.add(new SelectOption('2', 'JAN16-FEB15'));
        this.periods.add(new SelectOption('3', 'FEB16-MAR15'));
        this.periods.add(new SelectOption('4', 'MAR16-APR15'));
        this.periods.add(new SelectOption('5', 'APR16-MAY15'));
        this.periods.add(new SelectOption('6', 'MAY16-JUN15'));
        this.periods.add(new SelectOption('7', 'JUN16-JUL15'));
        this.periods.add(new SelectOption('8', 'JUL16-AUG15'));
        this.periods.add(new SelectOption('9', 'AUG16-SEP15'));
        this.periods.add(new SelectOption('10', 'SEP16-OCT15'));
        this.periods.add(new SelectOption('11', 'OCT16-NOV15'));
        this.periods.add(new SelectOption('12', 'NOV16-DEC15'));

        this.metricOptions = new List<SelectOption>();
        this.metricOptions.add(new SelectOption('', ''));
        List<Metric__c> metrics = [SELECT Id, Name FROM Metric__c WHERE Reporting_Frequency__c INCLUDES ('Monthly') AND Include_On_Report__c = true AND Is_Calculated__c = false ORDER BY Display_Order__c];
        for(Metric__c metric : metrics){
            this.metricOptions.add(new SelectOption(metric.Id, metric.Name));
        }

        if(reportedMetricValues == null){
            reportedMetricValues = new List<ReportedMetricValueWrapper>();
        }
    }

    private Date ReportingPeriodEndDate(){
        if(this.selectedYear != null && this.selectedPeriod != null){
            return Date.newInstance(this.selectedYear, Integer.valueOf(this.selectedPeriod), 15);
        } else {
            return null;
        }
    }

    public PageReference load(){
        if(previewReport){ previewReport = false; }
        reportedMetricValues = new List<ReportedMetricValueWrapper>();

        if(ReportingPeriodEndDate() != null){
            List<Company_Wide_Report__c> cwrList = [SELECT Id, Reporting_Frequency__c, End_Date__c, Ready_To_Send__c FROM Company_Wide_Report__c WHERE Reporting_Frequency__c = 'Monthly' AND End_Date__c = :ReportingPeriodEndDate() LIMIT 1];
            if(cwrList.size() == 1){
                companyWideReport = cwrList[0];
                List<Reported_Metric_Value__c> rmvList = [SELECT Id, Company_Wide_Report__c, Metric__c, Reported_Value__c, Delta__c, Headcount__c, Week_To_Date__c, Month_To_Date__c, Year_To_Date__c FROM Reported_Metric_Value__c WHERE Company_Wide_Report__c = :companyWideReport.Id AND Metric__r.Is_Calculated__c = false];
                for(Reported_Metric_Value__c rmv : rmvList){
                    reportedMetricValues.add(new ReportedMetricValueWrapper(rmv, metricOptions, rmv.Metric__c));
                }
            } else {
                companyWideReport = new Company_Wide_Report__c(Reporting_Frequency__c = 'Monthly', End_Date__c = ReportingPeriodEndDate());
                reportedMetricValues = new List<ReportedMetricValueWrapper>();
            }
        }
        return null;
    }

    public PageReference newRMV(){
        if(previewReport){ previewReport = false; }

        //if(reportedMetricValues == null){
        //    reportedMetricValues = new List<ReportedMetricValueWrapper>();
        //}
        system.debug('**SZ: reportedMetricValues = ' + reportedMetricValues);
        reportedMetricValues.add(new ReportedMetricValueWrapper(new Reported_Metric_Value__c(), metricOptions, null));

        return null;
    }

    public PageReference preview(){
        previewReport = true;
        return null;
    }

    public PageReference save(){
        upsert companyWideReport;
        system.debug('**SZ: reportedMetricValues = ' + reportedMetricValues);
        List<Reported_Metric_Value__c> rmvList = new List<Reported_Metric_Value__c>();
        for(ReportedMetricValueWrapper rmv : reportedMetricValues){
            if (rmv.reportedMetricValue.Company_Wide_Report__c == null){
                rmv.reportedMetricValue.Company_Wide_Report__c = companyWideReport.Id;
            }
            rmv.reportedMetricValue.Metric__c = rmv.selectedValue;
            rmvList.add(rmv.reportedMetricValue);
        }
        upsert rmvList;
        previewReport = true;
        
        return null;
    }

    public PageReference saveAndPreview(){
        CompanyWideReportCalculator.processMonthly(companyWideReport.End_Date__c);
        companyWideReport = [SELECT Id, Reporting_Frequency__c, End_Date__c, Ready_To_Send__c FROM Company_Wide_Report__c WHERE Reporting_Frequency__c = 'Monthly' AND End_Date__c = :companyWideReport.End_Date__c];
        save();
        previewReport = true;
        
        return null;
    }

    public PageReference send(){
        PageReference reference = saveAndPreview();

        companyWideReport.Ready_To_Send__c = true;
        update companyWideReport;

        return null;
    }

    public PageReference deleteRow(){
        if(previewReport){ previewReport = false; }

        reportedMetricValues.remove(rowToDelete);
        return null;
    }

    public class ReportedMetricValueWrapper {
        public Reported_Metric_Value__c reportedMetricValue {get;set;}
        public List<SelectOption> metricOptions {get;set;}
        public String selectedValue {get;set;}

        public ReportedMetricValueWrapper(Reported_Metric_Value__c rmv, List<SelectOption> options, Id metricId){
            this.reportedMetricValue = rmv;
            this.metricOptions = options;
            this.selectedValue = metricId;
        }
    }
}