src/objects/Contract.object
<CustomObject>
    <recordTypes>
        <fullName>Sales</fullName>
        <active>true</active>
        <description>Standard Sales Contract</description>
        <label>Sales</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Data_Tracking_Project__c.object
<CustomObject>
    <description>Data Tracking Project for 2012 Summer Interns</description>
    <fields>
        <fullName>Project_Lead__c</fullName>
        <description>Project Lead</description>
        <inlineHelpText>Enter status of Project Lead</inlineHelpText>
        <label>Project Lead</label>
        <picklist>
            <picklistValues>
                <fullName>Already Correct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Added</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incorrect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corrected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Can&apos;t Find</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Data Tracking Project Sales Order</description>
        <inlineHelpText>Data Tracking Project Sales Order</inlineHelpText>
        <label>Sales Order</label>
        <referenceTo>SCRB_SalesOrder__c</referenceTo>
        <relationshipLabel>Data Tracking Projects</relationshipLabel>
        <relationshipName>Data_Tracking_Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Data Tracking Project</label>
    <nameField>
        <label>Data Tracking Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Tracking Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PM_Project__c.object
<CustomObject>
    <description>Astrum PM 2.0 Project Object</description>
    <fields>
        <fullName>Approval_Date__c</fullName>
        <formula>Sales_Order__r.Approval_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Electrical_Designer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Electrical Designer associated with this PM Project.</description>
        <inlineHelpText>Electrical Designer associated with this PM Project.</inlineHelpText>
        <label>Electrical Designer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PM_Projects2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Finance_Associate__c</fullName>
        <formula>Sales_Order__r.Finance_Associate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Finance Associate</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Engineer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Solar Engineer assigned to this Project.</description>
        <inlineHelpText>The Solar Engineer assigned to this Project.</inlineHelpText>
        <label>Solar Engineer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PM_Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>SCRB_SalesOrder__c</referenceTo>
        <relationshipLabel>PM Projects</relationshipLabel>
        <relationshipName>PM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Designer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>System Designer assigned to this PM Project.</description>
        <inlineHelpText>System Designer assigned to this PM Project.</inlineHelpText>
        <label>Operations Surveyor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PM_Projects3</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PM Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PM Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SCRB_SalesOrder__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The SalesOrder object is the result of a Closed Won Opportunity and handles the hand off from the sales team to the operations team.</description>
    <fields>
        <fullName>Approval_Date__c</fullName>
        <label>Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Contract_Admin__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Admin</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Orders4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Finance_Associate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Finance Associate</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Orders3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Incentive_Associate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Assigned Compliance Department Specialist</description>
        <inlineHelpText>Assigned Compliance Department Specialist</inlineHelpText>
        <label>Incentive Associate</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Orders_Incentive</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OpportunityId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>R00N300000011q6hEAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prelim_Approval_Date__c</fullName>
        <label>Prelim Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>StatusCode__c</fullName>
        <label>Status Code</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>Submit Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Assigned to Sales Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Submit To Sales Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Coordinator Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Manager Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Coordinator Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final/Accounting Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Administrator Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated to VP Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VP Sales Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VP Sales Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Controller Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Proposal Creation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Proposal Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Ongoing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Controller Rejected - Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Admin Approved - Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prelim Approved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SalesOrderTriggerHandlerTest.cls
/* FILE: SalesOrderTriggerHandlerTest.cls
 * AUTHOR: Mike Katulka
 * DATE: 2014-04-07
 * PURPOSE: Test class for SalesOrderTrigger
 * MODIFICATION HISTORY
 *
 */
 
@isTest(seealldata=true)
public class SalesOrderTriggerHandlerTest {
	
	static testMethod void testSalesOrderApprovalProcess() {
		
		Data_Tracking_Project__c dtp= testData.createDtpWithAllData();

        Test.startTest();
        
	    SCRB_SalesOrder__c salesOrder = [select id, statusCode__c from SCRB_SalesOrder__c where id =: dtp.Sales_Order__c];	    
	    salesOrder.statusCode__c = 'Submit Pending';
        salesOrder.Contract_Admin__c = UserInfo.getUserId();
	    update salesOrder;

        Map<id, SCRB_SalesOrder__c> salesMap = new Map<id, SCRB_SalesOrder__c>();
        salesMap.put(salesOrder.Id, salesOrder);
        SalesOrderTriggerHandler.salesOrderCaptureData(new List<SCRB_SalesOrder__c>{salesOrder}, salesMap, true); 

	    //Entry criteria for first approval process:
	    System.assertEquals('Submit Pending', [select statusCode__c from SCRB_SalesOrder__c where id =: salesOrder.id].statusCode__c);
	    System.assertEquals('Closed - Won', [select OpportunityId__r.StageName from SCRB_SalesOrder__c where id =: salesOrder.id].OpportunityId__r.StageName);
	    

		// Create an approval request
        //ProcessResult class: http://www.salesforce.com/us/developer/docs/apexcode/Content/apex_ProcessResult.htm
        //Valid values are: Approved, Rejected, Removed or Pending.        
        Approval.ProcessSubmitRequest req1 = 
            new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(salesOrder.id);
        
        // Submit the approval request
        Approval.ProcessResult result = Approval.process(req1);
        
        // Verify the result
        System.assert(result.isSuccess());
        
        System.assertEquals('Pending', result.getInstanceStatus()); 
        //System.assertEquals('Submitted', [select statusCode__c from SCRB_SalesOrder__c where id =: salesOrder.id].statusCode__c);
        //System.assertEquals('Sales Submitted', [select statusCode__c from SCRB_SalesOrder__c where id =: salesOrder.id].statusCode__c);
        
        // Approve the submitted request
        // First, get the ID of the newly created item
        List<Id> newWorkItemIds = result.getNewWorkitemIds();
        
        // Instantiate the new ProcessWorkitemRequest object and populate it
        Approval.ProcessWorkitemRequest req2 = 
            new Approval.ProcessWorkitemRequest();
        req2.setComments('Approving request.');
        req2.setAction('Approve');
        req2.setNextApproverIds(new Id[] {UserInfo.getUserId()});
        
        // Use the ID from the newly created item to specify the item to be worked
        req2.setWorkitemId(newWorkItemIds.get(0));
        
        // Submit the request for approval
        Approval.ProcessResult result2 =  Approval.process(req2);
        
        // Verify the results
        System.assert(result2.isSuccess(), 'Result Status:'+result2.isSuccess());
        
        System.assertEquals('Approved', result2.getInstanceStatus());
        //Automatic rejection based on step 1 of "Contract Administrator Approval 4"
        //System.assertEquals('Contract Administrator Rejected', [select statusCode__c from SCRB_SalesOrder__c where id =: salesOrder.id].statusCode__c);
        //System.assertEquals('Prelim Approved', [select statusCode__c from SCRB_SalesOrder__c where id =: salesOrder.id].statusCode__c);

        Test.stopTest();
	}

    //SOA PB 11/20/2015
    static testMethod void salesorderEmailTest(){
        
        Data_Tracking_Project__c dtp= testData.createDtpWithAllData();

        Test.startTest();
        
        SCRB_SalesOrder__c salesOrder = [select id, statusCode__c from SCRB_SalesOrder__c where id =: dtp.Sales_Order__c];      
        
        PM_Project__c proj = new PM_Project__c();
        proj.Name = 'Test proj for salesorder';
        proj.Sales_Order__c = salesOrder.Id;
        proj.Project_Lead__c = UserInfo.getUserId();
        proj.Electrical_Designer__c = UserInfo.getUserId();
        proj.Project_Engineer__c = UserInfo.getUserId();
        proj.System_Designer__c = UserInfo.getUserId();
        insert proj;

        salesOrder.StatusCode__c = 'Canceled';
        salesOrder.Contract_Admin__c = UserInfo.getUserId();
        salesOrder.Finance_Associate__c = UserInfo.getUserId();
        salesOrder.Incentive_Associate__c = UserInfo.getUserId();
        update salesOrder;

        Test.stopTest();
         /*   
        salesOrder = [select id, statusCode__c from SCRB_SalesOrder__c where id =: salesOrder.Id];      
        salesOrder.StatusCode__c = 'Prelim Approved';
        salesOrder.Prelim_Approval_Date__c = Datetime.now();
        update salesOrder;

        salesOrder = [select id, statusCode__c from SCRB_SalesOrder__c where id =: salesOrder.Id];      
        salesOrder.StatusCode__c = 'Final/Accounting Approved';
        salesOrder.Approval_Date__c = Datetime.now();
        update salesOrder;*/
    }

    //SOA PB 11/20/2015
    static testMethod void salesorderEmailTest2(){
        
        Data_Tracking_Project__c dtp= testData.createDtpWithAllData();

        Test.startTest();
        
        SCRB_SalesOrder__c salesOrder = [select id, statusCode__c from SCRB_SalesOrder__c where id =: dtp.Sales_Order__c];      
        
        PM_Project__c proj = new PM_Project__c();
        proj.Name = 'Test proj for salesorder';
        proj.Sales_Order__c = salesOrder.Id;
        proj.Project_Lead__c = UserInfo.getUserId();
        proj.Electrical_Designer__c = UserInfo.getUserId();
        proj.Project_Engineer__c = UserInfo.getUserId();
        proj.System_Designer__c = UserInfo.getUserId();
        insert proj;

        salesOrder.Contract_Admin__c = UserInfo.getUserId();
        salesOrder.Finance_Associate__c = UserInfo.getUserId();
        salesOrder.Incentive_Associate__c = UserInfo.getUserId();
        salesOrder.StatusCode__c = 'Prelim Approved';
        salesOrder.Prelim_Approval_Date__c = Datetime.now();
        update salesOrder;

        Test.stopTest();

    }
    //SOA PB 11/20/2015
    static testMethod void salesorderEmailTest3(){
        
        Data_Tracking_Project__c dtp= testData.createDtpWithAllData();

        Test.startTest();
        
        SCRB_SalesOrder__c salesOrder = [select id, statusCode__c from SCRB_SalesOrder__c where id =: dtp.Sales_Order__c];      
        
        PM_Project__c proj = new PM_Project__c();
        proj.Name = 'Test proj for salesorder';
        proj.Sales_Order__c = salesOrder.Id;
        proj.Project_Lead__c = UserInfo.getUserId();
        proj.Electrical_Designer__c = UserInfo.getUserId();
        proj.Project_Engineer__c = UserInfo.getUserId();
        proj.System_Designer__c = UserInfo.getUserId();
        insert proj;

        salesOrder.Contract_Admin__c = UserInfo.getUserId();
        salesOrder.Finance_Associate__c = UserInfo.getUserId();
        salesOrder.Incentive_Associate__c = UserInfo.getUserId();
        salesOrder.StatusCode__c = 'Final/Accounting Approved';
        salesOrder.Approval_Date__c = Datetime.now();
        update salesOrder;

        Test.stopTest();

    }   	
	
}