src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Primary_Phone__c</fullName>
        <description>What is this contact&apos;s primary contact number?</description>
        <inlineHelpText>What is this contact&apos;s primary contact number?</inlineHelpText>
        <label>Primary Phone</label>
        <picklist>
            <picklistValues>
                <fullName>Phone</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Home Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Phone</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Work_Phone__c</fullName>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/County__c.object
<CustomObject>
    <description>Represents a County in a State</description>
    <fields>
        <fullName>State__c</fullName>
        <description>State County belongs to</description>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Counties</relationshipLabel>
        <relationshipName>Counties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <picklist>
            <picklistValues>
                <fullName>CONNECTICUT =&gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fairfield CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hartford CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Litchfield CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middlesex CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Haven CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New London CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tolland CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Windham CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DISTRICT OF COLUMBIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DELAWARE =&gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kent DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Castle DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sussex DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MARYLAND =&gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allegany MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anne Arundel MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baltimore City MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baltimore MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Calvert MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caroline MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carroll MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cecil MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charles MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dorchester MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Frederick MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Garrett MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Harford MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Howard MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kent MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rockland NY</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>D2D_System_Size__c</fullName>
        <label>D2D System Size</label>
        <picklist>
            <controllingField>D2D_State__c</controllingField>
            <picklistValues>
                <fullName>16 Panel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24 Panel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>36 Panel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Primary_Phone__c</fullName>
        <inlineHelpText>Preferred phone number</inlineHelpText>
        <label>Primary Phone</label>
        <picklist>
            <picklistValues>
                <fullName>Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>QAS_County__c</fullName>
        <description>QAS Auto-Populated County</description>
        <inlineHelpText>QAS Auto-Populated County</inlineHelpText>
        <label>QAS County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Phone__c</fullName>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Portal_Referral__c.object
<CustomObject>
    <description>Referrals from the Partner Program website</description>
    <fields>
        <fullName>City__c</fullName>
        <description>City for referral</description>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>D2D_Lead_Status__c</fullName>
        <label>D2D Lead Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed - Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Generated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Opt-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Opt-Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Door Hanger</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing Utility Bill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA Visit 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA Visit 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passed Validation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Photos Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit Scheduled</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>D2D_Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>D2D Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Portal_Referrals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>D2D_System_Size__c</fullName>
        <label>D2D System Size</label>
        <picklist>
            <controllingField>State__c</controllingField>
            <picklistValues>
                <fullName>16 Panel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24 Panel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>36 Panel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of referral</description>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of referral</description>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile_Phone__c</fullName>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Primary_Phone__c</fullName>
        <label>Primary Phone</label>
        <picklist>
            <picklistValues>
                <fullName>Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>QAS_County__c</fullName>
        <label>QAS County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SSG_Accepted__c</fullName>
        <defaultValue>&quot;false&quot;</defaultValue>
        <label>SSG_Accepted</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>Street of Referral</description>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Work_Phone__c</fullName>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Portal Referral</label>
    <nameField>
        <displayFormat>REF-{000000}</displayFormat>
        <label>Portal Referral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/State__c.object
<CustomObject>
    <description>Represents a State</description>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/D2D_LeadInformationControllerTest.cls
@isTest
private class D2D_LeadInformationControllerTest {
    private static boolean runalltests = true; // true to run all tests; false to skip tests and only run those where the 'if' is commented out

	@testSetup static void setupData() {
		D2DTestUtility.InitializeRequiredMethods();
		D2DTestUtility.CreateCustomSettings('sales.coordinator@email.com');
		
		D2DTestUtility.CreateManagerUsers(1);
		User d2dMg = D2DTestUtility.d2dManagerUsers[0];

		D2DTestUtility.CreateSalesRepUsers(1);
		User d2dSr = D2DTestUtility.d2dSalesRepUsers[0];

		D2DTestUtility.CreatePortalReferralRequiredObjects(1, 'NY', '24 Panel');
		D2DTestUtility.CreatePortalReferralsWithLeads(1, d2dMg.Id, d2dSr.Id, 'QUALIFIED', 'Prospect New', '', '2', 'ref', 'Joe', '101 Boolean Way', 'Stony Point', 'NY', '10980', 'Rockland', false);
	}

	@isTest static void test_DropDowns() {
		if(!runalltests){ return; }

		Portal_Referral__c referral = [SELECT Id, D2D_System_Size__c, Email__c, D2D_Sales_Rep__c FROM Portal_Referral__c LIMIT 1];
		User d2dSr = [SELECT Id FROM User WHERE Id = :referral.D2D_Sales_Rep__c];

		PageReference pageRef = Page.D2D_LeadInformation;
		pageRef.getParameters().put('id', referral.Id);
		Test.setCurrentPage(pageRef);

		Test.startTest();

		System.runAs(d2dSr){
			D2D_LeadInformationController controller = new D2D_LeadInformationController();

			// Select a utility company master
			system.assertEquals(17, controller.states.size());
			system.assertEquals(5, controller.timelines.size());
			system.assertEquals(8, controller.salutations.size());
			system.assertEquals(5, controller.bestTimes.size());
			system.assertNotEquals(0, controller.affiliateCommunityPrograms.size());
			system.assertNotEquals(0, controller.getCampaigns().size());
			system.assertEquals(123, controller.counties.size());
			system.assertEquals(3, controller.systemSizes.size());
		}

		Test.stopTest();
	}

	@isTest static void test_EmptyReferral() {
		if(!runalltests){ return; }

		Portal_Referral__c referral = [SELECT Id, D2D_System_Size__c, Email__c, D2D_Sales_Rep__c FROM Portal_Referral__c LIMIT 1];
		User d2dSr = [SELECT Id FROM User WHERE Id = :referral.D2D_Sales_Rep__c];

		PageReference pageRef = Page.D2D_LeadInformation;
		pageRef.getParameters().put('id', referral.Id);
		Test.setCurrentPage(pageRef);

		Test.startTest();

		System.runAs(d2dSr){

			D2D_LeadInformationController controller = new D2D_LeadInformationController();

			controller.referral.Street__c = '';
	        controller.referral.City__c = '';
	        controller.referral.State__c = '';
	        controller.referral.Zip__c = '';
	        controller.referral.First_Name__c = '';
	        controller.referral.Last_Name__c = '';
	        controller.referral.Email__c = '';
	        controller.referral.Phone__c = '';
	        controller.referral.Work_Phone__c = '';
	        controller.referral.Mobile_Phone__c = '';
	        controller.utilityId = '';
	        controller.homeOwner = '';
	        controller.electricBill = '';
	        controller.affiliateCommunityProgram = '';
	        controller.primarySourceCampaign = '';
		    controller.timeline = '';
		    controller.salutation = '';
		    controller.bestTime = '';

			PageReference returnedRef = controller.submit();
			system.assertNotEquals('', controller.errorMessage.Message);
			system.assert(controller.errorMessage.ErrorFields.contains('Last_Name__c'));
			system.assertEquals(null, returnedRef);
		}

		Test.stopTest();
	}
	
	@isTest static void test_NewLead() {
		if(!runalltests){ return; }
		
		Portal_Referral__c srUserId = [SELECT D2D_Sales_Rep__c FROM Portal_Referral__c LIMIT 1];
		User d2dSr = [SELECT Id FROM User WHERE Id = :srUserId.D2D_Sales_Rep__c];

		PageReference pageRef = Page.D2D_LeadInformation;
		Test.setCurrentPage(pageRef);

		Test.startTest();

		System.runAs(d2dSr){

			D2D_LeadInformationController controller = new D2D_LeadInformationController();
			
			controller.referral = new Portal_Referral__c();
            controller.relatedLead = new Lead();
            
			controller.referral.First_Name__c = 'Bob';
	        controller.referral.Last_Name__c = 'Test';
		    controller.submitAndReload();
		    
			system.assert(controller.errorMessage.Message.contains('An address must be entered to create a new lead.'));
			
			controller.referral.Street__c = '79 Pine Dr';
	        controller.referral.City__c = 'Stony Point';
	        controller.referral.State__c = 'NY';
			controller.newState = 'NY';
	        controller.referral.Zip__c = '10980';
	        controller.referral.QAS_County__c = 'Rockland';
	        controller.utilityId = controller.getUtilities()[controller.getUtilities().size() - 1].getValue();
			controller.referral.D2D_System_Size__c = '24 Panel';
			controller.referral.Email__c = 'referral@email.com';
			controller.referral.Phone__c = '999-999-9999';
	        controller.referral.Work_Phone__c = '';
	        controller.referral.Mobile_Phone__c = '';
			controller.homeOwner = 'Yes';
			controller.electricBill = '350.00';
	        controller.affiliateCommunityProgram = 'D2D Orange & Rockland';
	        controller.primarySourceCampaign = controller.getCampaigns()[controller.getCampaigns().size() - 1].getValue();
	        controller.county = 'Rockland NY';
		    controller.timeline = '';
		    controller.salutation = '';
		    controller.bestTime = '';
		    controller.propertyNotes  = '';
		    controller.referral.Confirmed_Location__Latitude__s = 0;
			controller.referral.Confirmed_Location__Longitude__s = 0;
		    controller.submitAndReload();
		    
			system.assertEquals('', controller.errorMessage.Message);
		}

		Test.stopTest();
	}
	
	@isTest static void test_InvalidAndMissingData() {
		if(!runalltests){ return; }

		Portal_Referral__c referral = [SELECT Id, D2D_System_Size__c, Email__c, D2D_Sales_Rep__c FROM Portal_Referral__c LIMIT 1];
		User d2dSr = [SELECT Id FROM User WHERE Id = :referral.D2D_Sales_Rep__c];

		PageReference pageRef = Page.D2D_LeadInformation;
		pageRef.getParameters().put('id', referral.Id);
		Test.setCurrentPage(pageRef);

		Test.startTest();

		System.runAs(d2dSr){
			D2D_LeadInformationController controller = new D2D_LeadInformationController();

			// Select a utility company master
			controller.utilityId = controller.getUtilities()[controller.getUtilities().size() - 1].getValue();
			controller.homeOwner = 'XCV';
			controller.electricBill = 'ALPHA';
			controller.subscribe = false;
			PageReference returnedRef = controller.submit();

			system.assertNotEquals('', controller.errorMessage.Message);
			system.assert(controller.errorMessage.ErrorFields.contains('D2D_LeadInformationController.createLead'));
			system.assertEquals(null, returnedRef);

			controller.referral.Phone__c = '999-888-7777';
			controller.validate();

			system.assertNotEquals('', controller.errorMessage.Message);
			system.assert(!controller.errorMessage.ErrorFields.contains('primary'));

			controller.referral.Primary_Phone__c = '';
			controller.referral.Phone__c = '999-888-7777';
			controller.referral.Work_Phone__c = '999-888-7777';
			controller.referral.Mobile_Phone__c = '999-888-7777';
			controller.validate();

			system.assertNotEquals('', controller.errorMessage.Message);
			system.assert(controller.errorMessage.ErrorFields.contains('primary'));

			controller.referral.Primary_Phone__c = 'Home Phone';
			controller.referral.Phone__c = '';
			controller.validate();

			system.debug('**SZ: Message = ' + controller.errorMessage.Message);
			system.debug('**SZ: Fields = ' + controller.errorMessage.ErrorFields);
			system.assertNotEquals('', controller.errorMessage.Message);
			system.assert(controller.errorMessage.ErrorFields.contains('primary'));

			controller.referral.Primary_Phone__c = 'Work Phone';
			controller.referral.Phone__c = '999-888-7777';
			controller.referral.Work_Phone__c = '';
			controller.validate();

			system.assertNotEquals('', controller.errorMessage.Message);
			system.assert(controller.errorMessage.ErrorFields.contains('primary'));

			controller.referral.Primary_Phone__c = 'Mobile Phone';
			controller.referral.Work_Phone__c = '999-888-7777';
			controller.referral.Mobile_Phone__c = '';
			controller.validate();

			system.assertNotEquals('', controller.errorMessage.Message);
			system.assert(controller.errorMessage.ErrorFields.contains('primary'));
		}

		Test.stopTest();
	}
	
	@isTest static void test_SaveAndClose() {
		if(!runalltests){ return; }

		Portal_Referral__c referral = [SELECT Id, D2D_System_Size__c, Email__c, D2D_Sales_Rep__c FROM Portal_Referral__c LIMIT 1];
		User d2dSr = [SELECT Id FROM User WHERE Id = :referral.D2D_Sales_Rep__c];

		PageReference pageRef = Page.D2D_LeadInformation;
		pageRef.getParameters().put('id', referral.Id);
		Test.setCurrentPage(pageRef);

		Test.startTest();

		System.runAs(d2dSr){
			D2D_LeadInformationController controller = new D2D_LeadInformationController();

			// Select a utility company master
			controller.utilityId = controller.getUtilities()[controller.getUtilities().size() - 1].getValue();
			controller.referral.D2D_System_Size__c = '24 Panel';
			controller.referral.Email__c = 'referral@email.com';
			controller.referral.Phone__c = '999-999-9999';
			controller.homeOwner = 'Yes';
			controller.electricBill = '350.00';
			PageReference returnedRef = controller.submit();

			String expectRef = Page.D2D_SalesRepDashboard.getUrl().substringAfterLast('/').toLowerCase();
			String actualRef = returnedRef.getUrl().substringAfterLast('/').toLowerCase();
			system.assertEquals('', controller.errorMessage.Message);
			system.assertEquals(expectRef, actualRef);
		}

		Test.stopTest();
	}
	
	@isTest static void test_SaveAndReload() {
		if(!runalltests){ return; }

		Portal_Referral__c referral = [SELECT Id, D2D_System_Size__c, Email__c, D2D_Sales_Rep__c FROM Portal_Referral__c LIMIT 1];
		User d2dSr = [SELECT Id FROM User WHERE Id = :referral.D2D_Sales_Rep__c];

		PageReference pageRef = Page.D2D_LeadInformation;
		pageRef.getParameters().put('id', referral.Id);
		Test.setCurrentPage(pageRef);

		Test.startTest();

		System.runAs(d2dSr){
			D2D_LeadInformationController controller = new D2D_LeadInformationController();

			// Select a utility company master
			controller.utilityId = controller.getUtilities()[controller.getUtilities().size() - 1].getValue();
			controller.referral.D2D_System_Size__c = '24 Panel';
			controller.referral.Email__c = 'referral@email.com';
			controller.referral.Phone__c = '999-999-9999';
			controller.homeOwner = 'Yes';
			controller.electricBill = '350.00';
			PageReference returnedRef = controller.submitAndReload();

			String expectRef = Page.D2D_LeadInformation.getUrl().substringAfterLast('/').toLowerCase();
			String actualRef = returnedRef.getUrl().substringAfterLast('/').substringBeforeLast('?').toLowerCase();
			system.assertEquals('', controller.errorMessage.Message);
			system.assertEquals(expectRef, actualRef);
		}

		Test.stopTest();
	}
	
	@isTest static void test_SaveAndContinue() {
		if(!runalltests){ return; }

		Portal_Referral__c referral = [SELECT Id, D2D_System_Size__c, Email__c, D2D_Sales_Rep__c FROM Portal_Referral__c LIMIT 1];
		User d2dSr = [SELECT Id FROM User WHERE Id = :referral.D2D_Sales_Rep__c];

		PageReference pageRef = Page.D2D_LeadInformation;
		pageRef.getParameters().put('id', referral.Id);
		Test.setCurrentPage(pageRef);

		Test.startTest();

		System.runAs(d2dSr){
			D2D_LeadInformationController controller = new D2D_LeadInformationController();

			// Select a utility company master
			controller.utilityId = controller.getUtilities()[controller.getUtilities().size() - 1].getValue();
			controller.referral.D2D_System_Size__c = '24 Panel';
			controller.referral.Email__c = 'referral@email.com';
			controller.referral.Phone__c = '999-999-9999';
			controller.homeOwner = 'Yes';
			controller.electricBill = '350.00';
			PageReference returnedRef = controller.submitAndContinue();

			String expectRef = Page.D2D_SolarSavingsGuidePreview.getUrl().substringAfterLast('/').toLowerCase();
			String actualRef = returnedRef.getUrl().substringAfterLast('/').substringBeforeLast('?').toLowerCase();
			system.assertEquals('', controller.errorMessage.Message);
			system.assertEquals(expectRef, actualRef);
		}

		Test.stopTest();
	}
	
	@isTest static void test_SSG() {
		if(!runalltests){ return; }

		Portal_Referral__c referral = [SELECT Id, D2D_System_Size__c, Email__c, D2D_Sales_Rep__c FROM Portal_Referral__c LIMIT 1];
		User d2dSr = [SELECT Id FROM User WHERE Id = :referral.D2D_Sales_Rep__c];

		PageReference pageRef = Page.D2D_LeadInformation;
		pageRef.getParameters().put('id', referral.Id);
		Test.setCurrentPage(pageRef);
		
		Test.startTest();

		System.runAs(d2dSr){
			D2D_LeadInformationController controller = new D2D_LeadInformationController();

			system.assertEquals('', controller.ssgWarningText);

			// Select a utility company master
			controller.utilityId = controller.getUtilities()[controller.getUtilities().size() - 1].getValue();
			controller.referral.D2D_System_Size__c = '24 Panel';
			controller.referral.Email__c = 'referral@email.com';
			controller.referral.Phone__c = '999-999-9999';
			controller.homeOwner = 'Yes';
			controller.electricBill = '350.00';
			controller.validate();

			system.assert(controller.ssgWarningText.contains('Contact an administrator.'));
			PageReference returnedRef = controller.submitAndReload();

			String expectRef = Page.D2D_LeadInformation.getUrl().substringAfterLast('/').toLowerCase();
			String actualRef = returnedRef.getUrl().substringAfterLast('/').substringBeforeLast('?').toLowerCase();
			system.assertEquals('', controller.errorMessage.Message);
			system.assertEquals(expectRef, actualRef);

			controller = new D2D_LeadInformationController();
			system.assertEquals('', controller.ssgWarningText);

			controller.referral.D2D_Lead_Status__c = 'Test';
			system.assert(controller.ssgWarningText.contains('Save the lead to validate.'));

			controller.referral.SSG_Accepted__c = 'True';
			system.assert(controller.ssgWarningText.contains('already accepted'));

			controller.referral.SSG_Accepted__c = 'False';
			controller.relatedLead.County__c = null;
			system.assert(controller.ssgWarningText.contains('Address validation is not yet complete.'));
		}

		Test.stopTest();
	}
}