src/objects/Contract.object
<CustomObject>
    <recordTypes>
        <fullName>Sales</fullName>
        <active>true</active>
        <description>Standard Sales Contract</description>
        <label>Sales</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Installed_System__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Installed Systems</relationshipLabel>
        <relationshipName>Installed_Systems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Installed Systems</relationshipLabel>
        <relationshipName>Installed_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>SCRB_SalesOrder__c</referenceTo>
        <relationshipLabel>Installed Systems</relationshipLabel>
        <relationshipName>Installed_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Installed System</label>
    <nameField>
        <displayFormat>SYS-{000000}</displayFormat>
        <label>Installed System Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installed Systems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>QAS_Latitude__c</fullName>
        <description>QAS Auto-Populated Latitude</description>
        <inlineHelpText>QAS Auto-Populated Latitude</inlineHelpText>
        <label>QAS Latitude</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QAS_Longitude__c</fullName>
        <description>QAS Auto-Populated Longitude</description>
        <inlineHelpText>QAS Auto-Populated Longitude</inlineHelpText>
        <label>QAS Longitude</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Milestone1_Project__c.object
<CustomObject>
    <description>AstrumPM - A solar installation project.  A project can have many milestones.</description>
    <fields>
        <fullName>Property__c</fullName>
        <formula>HYPERLINK( &quot;/&quot;+Sales_Order__r.OpportunityId__r.Property__r.Id  ,  Sales_Order__r.OpportunityId__r.Property__r.Name  )</formula>
        <label>Property</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>SCRB_SalesOrder__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>The current status of the project.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Property_City__c</fullName>
        <description>Initially used in code to cut back on extra SOQL queries in triggers.</description>
        <formula>Property__r.Property_City__c</formula>
        <label>Property City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <formula>TEXT(Property__r.Property_State__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Zip__c</fullName>
        <description>Initially used in code to cut back on extra SOQL queries in triggers.</description>
        <formula>Property__r.Property_ZIP__c</formula>
        <label>Property Zip</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Property__c.Property_Owner__r.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <description>AstrumPM/AstrumCRM - Each account can have one or more properties.  A property is defined by its street address.</description>
    <fields>
        <fullName>Latitude__c</fullName>
        <label>Latitude</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Longitude__c</fullName>
        <label>Longitude</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property_Address_2__c</fullName>
        <label>Property Address 2</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_City__c</fullName>
        <label>Property City</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>Property State</label>
        <picklist>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property_ZIP__c</fullName>
        <label>Property ZIP</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QAS_Latitude__c</fullName>
        <description>QAS Auto-Populated Latitude</description>
        <inlineHelpText>QAS Auto-Populated Latitude</inlineHelpText>
        <label>QAS Latitude</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QAS_Longitude__c</fullName>
        <description>QAS Auto-Populated Longitude</description>
        <inlineHelpText>QAS Auto-Populated Longitude</inlineHelpText>
        <label>QAS Longitude</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Address 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SCRB_SalesOrder__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The SalesOrder object is the result of a Closed Won Opportunity and handles the hand off from the sales team to the operations team.</description>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>R00N300000011q88EAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StatusCode__c</fullName>
        <label>Status Code</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>Submit Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Assigned to Sales Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Submit To Sales Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Coordinator Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Manager Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Coordinator Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final/Accounting Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Administrator Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated to VP Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VP Sales Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VP Sales Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Controller Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Proposal Creation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Proposal Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Ongoing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Controller Rejected - Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Admin Approved - Finance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AstrumMapViewerController.cls
public class AstrumMapViewerController {
	
	private static Integer rowLimit {
		get {
			if (Test.isRunningTest()) {
				return 10;
			} else {
				return 50000;
			}
		}
	} 

	//get sales orders
	@RemoteAction
	public static List<AstrumMapItem> getSalesOrders() {
	
		List<AstrumMapItem> result = new List<AstrumMapItem>();
		
		List<SCRB_SalesOrder__c> orders = 
			[SELECT Id,
				Name,
				AccountId__r.Name, 
				Property__r.Name, 
				StatusCode__c,
				Property__r.Property_Address_2__c, 
				Property__r.Property_City__c, 
				Property__r.Property_State__c, 
				Property__r.Property_ZIP__c, 
				Property__r.Latitude__c, 
				Property__r.Longitude__c 
			FROM SCRB_SalesOrder__c
			LIMIT :rowLimit];
			//WHERE Property__r.Longitude__c > -86.2914 //IN
			//AND Property__r.Latitude__c > 36 ]; //top of NC

		for (SCRB_SalesOrder__c o : orders) {
			AstrumMapItem item = new AstrumMapItem();
			item.id = o.Id;
			item.name = o.Name;
			item.status = o.StatusCode__c;
			item.address = o.AccountId__r.Name + '\n' + o.Property__r.Name;
			if (o.Property__r.Property_Address_2__c != null) {
				item.address += '\n' + o.Property__r.Property_Address_2__c;
			}
			item.address += '\n' + o.Property__r.Property_City__c + ' ' + o.Property__r.Property_State__c + ' ' + o.Property__r.Property_ZIP__c;
			item.lat = o.Property__r.Latitude__c;
			item.lon = o.Property__r.Longitude__c;
			result.add(item);
		}
		
		return result;				
	}	 
	
	//get opportunities
	@RemoteAction
	public static List<AstrumMapItem> getOpportunities(Boolean pipelineOnly) {
	
		List<AstrumMapItem> result = new List<AstrumMapItem>();
		
		List<String> exclusions = new List<String>();
		
		if (pipelineOnly == true) {
			exclusions.add('On Hold');
			exclusions.add('Closed - Won');
			exclusions.add('Contract Cancelled');
			exclusions.add('Closed - Lost');
			exclusions.add('Unresponsive');
		}
		
		List<Opportunity> opportunities = 
			[SELECT Id,
				Name,
				StageName, 
				Account.Name,
				Property__r.Name, 
				Property__r.Property_Address_2__c, 
				Property__r.Property_City__c, 
				Property__r.Property_State__c, 
				Property__r.Property_ZIP__c, 
				Property__r.Latitude__c, 
				Property__r.Longitude__c 
			FROM Opportunity
			WHERE StageName NOT IN :exclusions
			AND Property__r.Longitude__c <> NULL
			AND Property__r.Latitude__c <> NULL
			LIMIT :rowLimit];
			//AND Property__r.Longitude__c > -86.2914 //IN
			//AND Property__r.Latitude__c > 36 ]; //top of NC

		for (Opportunity o : opportunities) {
			AstrumMapItem item = new AstrumMapItem();
			item.id = o.Id;
			item.name = o.Name;
			item.status = o.StageName;
			item.address = o.Account.Name + '\n' + o.Property__r.Name;
			if (o.Property__r.Property_Address_2__c != null) {
				item.address += '\n' + o.Property__r.Property_Address_2__c;
			}
			item.address += '\n' + o.Property__r.Property_City__c + ' ' + o.Property__r.Property_State__c + ' ' + o.Property__r.Property_ZIP__c;
			item.lat = o.Property__r.Latitude__c;
			item.lon = o.Property__r.Longitude__c;
			result.add(item);
		}
		
		return result;				
	}	 
	
	//get leads
	@RemoteAction
	public static List<AstrumMapItem> getLeads(Boolean pipelineOnly) {
	
		List<AstrumMapItem> result = new List<AstrumMapItem>();
		
		List<String> exclusions = new List<String>();
		
		if (pipelineOnly == true) {
			exclusions.add('On Hold');
			exclusions.add('Qualified');
			exclusions.add('Unqualified');
			exclusions.add('Unresponsive');
			exclusions.add('Marketing – Influencer');
			exclusions.add('Lost – Competition');
		}
		
		List<Lead> leads = 
			[SELECT Id,
				Name,
				Status, 
				Street, 
				City, 
				State, 
				PostalCode, 
				QAS_Latitude__c, 
				QAS_Longitude__c 
			FROM Lead
			WHERE Status NOT IN :exclusions
			AND IsConverted <> true
			AND QAS_Latitude__c <> NULL
			AND QAS_Longitude__c <> NULL
			LIMIT :rowLimit];

		for (Lead l : leads) {
			AstrumMapItem item = new AstrumMapItem();
			item.id = l.Id;
			item.name = l.Name;
			item.status = l.Status;
			item.address = l.Street + '\n' + l.City + ' ' + l.State + ' ' + l.PostalCode; 
			item.lat = Double.valueOf(l.QAS_Latitude__c);
			item.lon = Double.valueOf(l.QAS_Longitude__c);
			//if (item.lon > -86.2914 && item.lat > 36) {
			result.add(item);
			//}
		}
		
		return result;				
	}	 
	
	//get installed systems
	@RemoteAction
	public static List<AstrumMapItem> getProjects() {
	
		List<AstrumMapItem> result = new List<AstrumMapItem>();
		
		List<Milestone1_Project__c> projects = 
			[SELECT Id,
				Name,
				Status__c,
				Sales_Order__r.AccountId__r.Name,
				Sales_Order__r.Property__r.Name, 
				Sales_Order__r.Property__r.Property_Address_2__c, 
				Sales_Order__r.Property__r.Property_City__c, 
				Sales_Order__r.Property__r.Property_State__c, 
				Sales_Order__r.Property__r.Property_ZIP__c, 
				Sales_Order__r.Property__r.Latitude__c, 
				Sales_Order__r.Property__r.Longitude__c 
			FROM Milestone1_Project__c
			LIMIT :rowLimit];

		for (Milestone1_Project__c o : projects) {
			AstrumMapItem item = new AstrumMapItem();
			item.id = o.Id;
			item.name = o.Name;
			item.status = o.Status__c;
			item.address = o.Sales_Order__r.AccountId__r.Name + '\n' + o.Sales_Order__r.Property__r.Name;
			if (o.Sales_Order__r.Property__r.Property_Address_2__c != null) {
				item.address += '\n' + o.Sales_Order__r.Property__r.Property_Address_2__c;
			}
			item.address += '\n' + o.Sales_Order__r.Property__r.Property_City__c + ' ' + o.Sales_Order__r.Property__r.Property_State__c + ' ' 
				+ o.Sales_Order__r.Property__r.Property_ZIP__c;
			item.lat = o.Sales_Order__r.Property__r.Latitude__c;
			item.lon = o.Sales_Order__r.Property__r.Longitude__c;
			result.add(item);
		}
		
		return result;				
	}	 
	

	//get installed systems
	@RemoteAction
	public static List<AstrumMapItem> getInstalled() {
	
		List<AstrumMapItem> result = new List<AstrumMapItem>();
		
		List<Installed_System__c> installed = 
			[SELECT Id,
				Name,
				Account__r.Name,
				Property__r.Name, 
				Property__r.Property_Address_2__c, 
				Property__r.Property_City__c, 
				Property__r.Property_State__c, 
				Property__r.Property_ZIP__c, 
				Property__r.Latitude__c, 
				Property__r.Longitude__c 
			FROM Installed_System__c
			LIMIT :rowLimit];
			//WHERE Property__r.Longitude__c > -86.2914 //IN
			//AND Property__r.Latitude__c > 36 ]; //top of NC

		for (Installed_System__c o : installed) {
			AstrumMapItem item = new AstrumMapItem();
			item.id = o.Id;
			item.name = o.Name;
			item.status = 'Installed';
			item.address = o.Account__r.Name + '\n' + o.Property__r.Name;
			if (o.Property__r.Property_Address_2__c != null) {
				item.address += '\n' + o.Property__r.Property_Address_2__c;
			}
			item.address += '\n' + o.Property__r.Property_City__c + ' ' + o.Property__r.Property_State__c + ' ' + o.Property__r.Property_ZIP__c;
			item.lat = o.Property__r.Latitude__c;
			item.lon = o.Property__r.Longitude__c;
			result.add(item);
		}
		
		return result;				
	}	 
	
	public class AstrumMapItem {
		public String id;
		public String name;
		public String status;
		public String address;
		public double lat;
		public double lon;
	}

}