src/objects/County__c.object
<CustomObject>
    <description>Represents a County in a State</description>
    <fields>
        <fullName>FIPS_Code__c</fullName>
        <description>FIPS Code for county (2-digit state + 3 digit county code)</description>
        <externalId>true</externalId>
        <label>FIPS Code</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sales_Region__c</fullName>
        <label>Sales Region</label>
        <picklist>
            <picklistValues>
                <fullName>MA Region</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>MD Region</fullName>
                <color>#6600CC</color>
            </picklistValues>
            <picklistValues>
                <fullName>NYC Region</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>OH Region</fullName>
                <color>#3366FF</color>
            </picklistValues>
            <picklistValues>
                <fullName>PA Region</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>WNY Region</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <picklistValues>
                <fullName>CA Region</fullName>
                <color>#006600</color>
            </picklistValues>
            <picklistValues>
                <fullName>CT Region</fullName>
                <color>#33FFFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>NJ Region</fullName>
                <color>#F96FB7</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>State_Abbreviation__c</fullName>
        <formula>State__r.State_Abbreviation__c</formula>
        <label>State Abbreviation</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>State County belongs to</description>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Counties</relationshipLabel>
        <relationshipName>Counties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <picklist>
            <picklistValues>
                <fullName>CONNECTICUT =&gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fairfield CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hartford CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Litchfield CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middlesex CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Haven CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New London CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tolland CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Windham CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DISTRICT OF COLUMBIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DELAWARE =&gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kent DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Castle DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sussex DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MARYLAND =&gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allegany MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anne Arundel MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baltimore City MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baltimore MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Calvert MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caroline MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carroll MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cecil MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charles MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dorchester MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Frederick MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Garrett MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Harford MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Howard MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kent MD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead_Created_Date__c</fullName>
        <description>Custom field that contains a copy of the CreatedDate</description>
        <label>Lead Created Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>QAS_County__c</fullName>
        <description>QAS Auto-Populated County</description>
        <inlineHelpText>QAS Auto-Populated County</inlineHelpText>
        <label>QAS County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Region__c</fullName>
        <label>Sales Region</label>
        <picklist>
            <picklistValues>
                <fullName>MA Region</fullName>
                <color>#FFCC66</color>
            </picklistValues>
            <picklistValues>
                <fullName>MD Region</fullName>
                <color>#6600CC</color>
            </picklistValues>
            <picklistValues>
                <fullName>NYC Region</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>OH Region</fullName>
                <color>#3366FF</color>
            </picklistValues>
            <picklistValues>
                <fullName>PA Region</fullName>
                <color>#009900</color>
            </picklistValues>
            <picklistValues>
                <fullName>WNY Region</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <picklistValues>
                <fullName>CA Region</fullName>
                <color>#006600</color>
            </picklistValues>
            <picklistValues>
                <fullName>CT Region</fullName>
                <color>#33FFFF</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead_Sales_Region__c.object
<CustomObject>
    <description>Holds Sales Region for converted leads</description>
    <fields>
        <fullName>Lead_Created_Date__c</fullName>
        <label>Lead Created Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lead_ID_Unique__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Lead ID Unique</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sales_Region__c</fullName>
        <label>Sales Region</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Lead Sales Region</label>
    <nameField>
        <label>Lead Sales Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Sales Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/State__c.object
<CustomObject>
    <description>Represents a State</description>
    <fields>
        <fullName>FIPS_Code__c</fullName>
        <description>2-digit FIPS state code</description>
        <label>FIPS Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>State_Abbreviation__c</fullName>
        <externalId>true</externalId>
        <label>State Abbreviation</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LeadSalesRegionTriggerTest.cls
/* FILE: LeadSalesRegionTriggerTest.cls
 * AUTHOR: Tino Mattheou
 * DATE: August 14, 2012
 * PURPOSE: Test class for LeadSalesRegion and LeadSalesRegion_AIAU triggers
 * MODIFICATION HISTORY
 * 09/10/2012 TCM - delete Lead_Sales_Region__c record when Lead is deleted - zen-52
 */
 
@isTest
public class LeadSalesRegionTriggerTest {

    static testMethod void counties_insertLeads_RegionSet () {
        
        createCounties();
        
        Test.startTest();
        
        Lead lead1 = new Lead (
            LastName = 'Test1',
            Company = 'Testco1',
            County__c = 'Test1 County',
            Street = 'Test',
            State = 'PA' 
        );
        insert lead1;
        Lead lead2 = new Lead (
            LastName = 'Test2',
            Company = 'Testco2',
            Street = 'Test12',
            QAS_County__c = 'test2 county',
            State = 'PA' 
        );
        insert lead2;
        Lead lead3 = new Lead (
            LastName = 'Test3',
            Company = 'Testco3',
            QAS_County__c = 'Washington DC',
            State = 'DC' 
        );
        insert lead3;

        Test.stopTest();
        
        lead1 = [SELECT Id, Sales_Region__c FROM Lead WHERE Id = :lead1.Id];
        lead2 = [SELECT Id, Sales_Region__c FROM Lead WHERE Id = :lead2.Id];
        lead3 = [SELECT Id, Sales_Region__c FROM Lead WHERE Id = :lead3.Id];

        System.assertEquals('TEST1 Region', lead1.Sales_Region__c);     
        System.assertEquals('TEST2 Region', lead2.Sales_Region__c);     
        System.assertEquals('DC Region', lead3.Sales_Region__c);
        
        Lead_Sales_Region__c lsr1 = [SELECT Id, Sales_Region__c, Lead_Created_Date__c FROM Lead_Sales_Region__c WHERE Lead_ID_Unique__c = :lead1.Id];   
        Lead_Sales_Region__c lsr2 = [SELECT Id, Sales_Region__c, Lead_Created_Date__c FROM Lead_Sales_Region__c WHERE Lead_ID_Unique__c = :lead2.Id];   
        Lead_Sales_Region__c lsr3 = [SELECT Id, Sales_Region__c, Lead_Created_Date__c FROM Lead_Sales_Region__c WHERE Lead_ID_Unique__c = :lead3.Id];   

        System.assertEquals('TEST1 Region', lsr1.Sales_Region__c);      
        System.assertEquals('TEST2 Region', lsr2.Sales_Region__c);      
        System.assertEquals('DC Region', lsr3.Sales_Region__c);
        
    } 
    
    static testMethod void counties_updateLead_RegionSet () {
        
        createCounties();
        
        Lead lead1 = new Lead (
            LastName = 'Test1',
            Company = 'Testco',
            County__c = 'Some County',
            State = 'PA' 
        );
        insert lead1;
        
        Lead_Sales_Region__c lsr1 = [SELECT Id, Sales_Region__c, Lead_Created_Date__c FROM Lead_Sales_Region__c WHERE Lead_ID_Unique__c = :lead1.Id];   
        System.assertEquals(null, lsr1.Sales_Region__c);        
        
        Test.startTest();
        
        lead1 = new Lead(Id = lead1.Id, QAS_County__c = 'Test1 County');
        update lead1;

        Test.stopTest();
        
        lead1 = [SELECT Id, Sales_Region__c FROM Lead WHERE Id = :lead1.Id];
        System.assertEquals('TEST1 Region', lead1.Sales_Region__c);
        
        lsr1 = [SELECT Id, Sales_Region__c, Lead_Created_Date__c FROM Lead_Sales_Region__c WHERE Lead_ID_Unique__c = :lead1.Id];    
        System.assertEquals('TEST1 Region', lsr1.Sales_Region__c);      
        
    }
    
    static testMethod void bypassTriggers_updateLead_NoRegionSet () {
        
        createCounties();
        
        Lead lead1 = new Lead (
            LastName = 'Test1',
            Company = 'Testco',
            County__c = 'Some County',
            State = 'PA' 
        );
        insert lead1;
        
        Test.startTest();
        
        SalesRegionHelper.bypassSalesRegionTriggers = true;
        
        lead1 = new Lead(Id = lead1.Id, QAS_County__c = 'Test1 County');
        update lead1;

        Test.stopTest();
        
        lead1 = [SELECT Id, Sales_Region__c FROM Lead WHERE Id = :lead1.Id];

        System.assertEquals(null, lead1.Sales_Region__c);       
        
    }  
    
    public static void createCounties() {
        
        State__c state1 = new State__c (
            Name = 'Pennsylvania',
            FIPS_Code__c = '00',
            State_Abbreviation__c = 'PA'
        );
        insert state1;
        
        County__c county1 = new County__c (
            Name = 'Test1 County, PA',
            FIPS_Code__c = '00000',
            State__c = state1.Id,
            Sales_Region__c = 'TEST1 Region'
        );
        insert county1;
        
        County__c county2 = new County__c (
            Name = 'Test2 County, PA',
            FIPS_Code__c = '00001',
            State__c = state1.Id,
            Sales_Region__c = 'TEST2 Region'            
        );
        insert county2;

        State__c state2 = new State__c (
            Name = 'District of Columbia',
            FIPS_Code__c = '01',
            State_Abbreviation__c = 'DC'
        );
        insert state2;

        County__c county3 = new County__c (
            Name = 'District of Columbia',
            FIPS_Code__c = '01000',
            State__c = state2.Id,
            Sales_Region__c = 'DC Region'
        );
        insert county3;
        
    }
    
    static testMethod void counties_deleteLeads_RegionsDeleted () {
        
        createCounties();

        Lead lead1 = new Lead (
            LastName = 'Test1',
            Company = 'Testco1',
            County__c = 'Test1 County',
            State = 'PA' 
        );
        insert lead1;
        Lead lead2 = new Lead (
            LastName = 'Test2',
            Company = 'Testco2',
            Street = 'ZTest1',
            QAS_County__c = 'test2 county',
            State = 'PA' 
        );
        insert lead2;
        Lead lead3 = new Lead (
            LastName = 'Test3',
            Company = 'Testco3',
            Street = 'ZTest2',
            QAS_County__c = 'Washington DC',
            State = 'DC' 
        );
        insert lead3;
        
        System.assertEquals(3, [SELECT count() FROM Lead WHERE Id IN (:lead1.Id, :lead2.Id, :lead3.Id)]);

        Test.startTest();

        delete lead1;
        
        delete new Lead[] { lead2, lead3 };
        
        Test.stopTest();
        
        System.assertEquals(0, [SELECT count() FROM Lead WHERE Id IN (:lead1.Id, :lead2.Id, :lead3.Id)]);
        
    } 
    

}