src/objects/County__c.object
<CustomObject>
    <description>Represents a County in a State</description>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <picklist>
            <picklistValues>
                <fullName>CONNECTICUT =&gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fairfield CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hartford CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Litchfield CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middlesex CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Haven CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New London CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tolland CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Windham CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DISTRICT OF COLUMBIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DELAWARE =&gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kent DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Castle DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sussex DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MARYLAND =&gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allegany MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anne Arundel MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baltimore City MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baltimore MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Calvert MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caroline MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carroll MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cecil MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charles MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dorchester MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Frederick MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Garrett MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Harford MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Howard MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kent MD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead_Source_Detail_2__c</fullName>
        <description>Lead Source Detail 2</description>
        <inlineHelpText>Lead Source Detail 2</inlineHelpText>
        <label>Lead Source Detail 2</label>
        <picklist>
            <picklistValues>
                <fullName>Ari Silver-Isenstadt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Article/Broadcast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Channel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CHEP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cleveland Park</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer (Self)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Directory/Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Donald Small</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Network</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Groupon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jon Cardin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Living Social</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mt. Pleasant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>News</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rawat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rochelle Bartolomei</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Russ Prechtl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Self Generated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Schott</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shelley Cohen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solar</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead_Source_Detail_4__c</fullName>
        <description>Lead Source Detail 4</description>
        <inlineHelpText>Lead Source Detail 4</inlineHelpText>
        <label>Lead Source Detail 4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Source_Detail__c</fullName>
        <label>Lead Source Detail</label>
        <picklist>
            <controllingField>LeadSource</controllingField>
            <picklistValues>
                <fullName>1BOG Network</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>800 MySolar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Addition 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Addition 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AdMediary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Affiliate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Affinity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Airtron (DES)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angie</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angie&apos;s List 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angie&apos;s List 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angie’s List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Astrum AXP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BaltimoreM 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baltimore Magazine 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baltimore Sun 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baltimore Sun 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baltimore Sun 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baltimore Sun 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baltimore Sun 5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baltimore Sun 6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beacon Leads</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benjamin Franklin (DES)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bethesda 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bethesda Magazine 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boston Home 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boston Home 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BostonM 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BostonM 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boston Magazine 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Method_of_Contact__c</fullName>
        <inlineHelpText>Email field includes Jotforms, emails to info@astrumsolar.com, and any other emails or digital correspondence sent to Astrum ASIDE FROM CALCULATOR SUBMISSIONS.</inlineHelpText>
        <label>Method of Contact</label>
        <picklist>
            <picklistValues>
                <fullName>Astrum Web Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Person</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3rd Party Lead Generator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Astrum Input</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Calculator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referral</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Site_Type__c</fullName>
        <label>Site Type</label>
        <picklist>
            <picklistValues>
                <fullName>Residential</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Profit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Server_Info__c.object
<CustomObject>
    <description>Contains server information.</description>
    <label>Server Info</label>
    <nameField>
        <label>Server Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Server Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LeadDuplicateHandlingTests.cls
@isTest(SeeAlldata=true)
public class LeadDuplicateHandlingTests{
    static testMethod void testLeadDuplicate() {
      
      Server_Info__c serverinfo = New Server_Info__c();
      serverinfo.Name = 'Test';
      insert serverinfo;   
      // Bulk Insert Works Fine
      Lead lead1 = new Lead(LastName='TestAbc2', Company='Test1 Inc.',
                            Street= '100 Astrum Lane' , City = 'Wayne', State = 'PA', PostalCode = '19087' , LeadSource = 'Search Engine', Method_Of_Contact__c = 'Astrum Web Form'
                           );
      Lead lead2 = new Lead(LastName='TestAbc2', Company='Test2 Inc.',
                            Street= '201 Astrum Lane' , City = 'Wayne', State = 'PA', PostalCode = '19087' , LeadSource = 'Search Engine', Method_Of_Contact__c = 'Astrum Web Form'
                           );
      Lead lead3 = new Lead(LastName='TestAbc3', Company='Test3 Inc.',
                            Street= '301 Astrum Lane' , City = 'Wayne', State = 'PA', PostalCode = '19087' , LeadSource = 'Search Engine', Method_Of_Contact__c = 'Astrum Web Form'
                           );
                           
      List<Lead> leads  = new List<Lead>(); 
      
      leads.add(lead1);
      leads.add(lead2);
      leads.add(lead3);      
      
      insert leads;
      
      // Bulk Update Works Fine         
      lead2.Street = '200 Astrum Lane';
      lead3.Street = '300 Astrum Lane';
      Lead[] upLeads = new Lead[] {lead2 , lead3 };   
      update upLeads ;        
         
      // Insert Dup             
      Lead dup1= new Lead(LastName='TestAbc4', Company='Test4 Inc.',
                            Street= '100 Astrum Lane' , City = 'Wayne', State = 'PA', PostalCode = '19087' , LeadSource = 'Search Engine', Method_Of_Contact__c = 'Astrum Web Form'
                           );
      
      insert dup1; 
      
      dup1 = [Select Status from Lead Where Id = :dup1.Id ]; 
      List<Task> tasks = [Select t.WhoId, t.Description, t.ActivityDate, t.Status From Task t where whoId = :lead1.Id];
           
      System.assertEquals(1, tasks.size());      
      System.assert(dup1.Status == 'Not a Lead - DUPLICATE');
     
      Lead dup2= new Lead(LastName='TestAbc5', Company='Test5 Inc.',
                            Street= '400 Astrum Lane' , City = 'Wayne', State = 'PA', PostalCode = '19087' , LeadSource = 'Search Engine', Method_Of_Contact__c = 'Astrum Web Form'
                           );
      
      insert dup2; 

      // Update Dup 
      dup2.Street = '100 Astrum Lane';
      update dup2;
      
      dup2 = [Select Status from Lead Where Id = :dup2.Id ]; 
      List<Task> tasks2 = [Select t.WhoId, t.Description, t.ActivityDate, t.Status From Task t where whoId = :lead1.Id];
      
      System.assertEquals(2, tasks2 .size()); 
      System.assert(dup2.Status == 'Not a Lead - DUPLICATE');
          
      // Bulk Insert Dup  
      Lead lead4 = new Lead(LastName='TestAbc44', Company='Test44 Inc.',
                            Street= '4400 Astrum Lane' , City = 'Wayne', State = 'PA', PostalCode = '19087' , LeadSource = 'Search Engine', Method_Of_Contact__c = 'Astrum Web Form'
                           );
      Lead lead5 = new Lead(LastName='TestAbc55', Company='Test55 Inc.',
                            Street= '4400 Astrum Lane' , City = 'Wayne', State = 'PA', PostalCode = '19087' , LeadSource = 'Search Engine', Method_Of_Contact__c = 'Astrum Web Form'
                           );
      Lead lead6 = new Lead(LastName='TestAbc66', Company='Test66 Inc.',
                            Street= '300 Astrum Lane' , City = 'Wayne', State = 'PA', PostalCode = '19087' , LeadSource = 'Search Engine', Method_Of_Contact__c = 'Astrum Web Form'
                           );
                           
      Lead[] dups = new Lead[] {lead4 , lead5 , lead6 };      
      
      insert dups;
      
      lead4 = [Select Status from Lead Where Id = :lead4.Id ]; 
      lead5 = [Select Status from Lead Where Id = :lead5.Id ]; 
      lead6 = [Select Status from Lead Where Id = :lead6.Id ]; 
      
      System.assert(lead4.Status != 'Not a Lead - DUPLICATE');
      System.assert(lead5.Status == 'Not a Lead - DUPLICATE');
      System.assert(lead6.Status == 'Not a Lead - DUPLICATE');   
    
      // Bulk Update Dup     
      lead2.Street = '100 Astrum Lane';
      lead3.Street = '100 Astrum Lane';
      lead4.Street = '500 Astrum Lane';
      
      dups = new Lead[] {lead2, lead3, lead4};
     
      update dups;
      lead2 = [Select Status from Lead Where Id = :lead2.Id ]; 
      lead3 = [Select Status from Lead Where Id = :lead3.Id ]; 
      
      System.assert(lead2.Status == 'Not a Lead - DUPLICATE');
      System.assert(lead3.Status == 'Not a Lead - DUPLICATE');   
      
    }  
    static testMethod void testLeadDuplicateforOpp() {
      
      Server_Info__c serverinfo = New Server_Info__c();
      serverinfo.Name = 'Test';
      insert serverinfo;   
    
      //create a lead
      Lead ld = new Lead (
            FirstName = 'Test',
            LastName = 'Lead',
            Company = 'Lead, Test',
            Street = '123 Test St',
            City = 'Test City',
            State = 'PA',
            PostalCode = '19403',
            County__c = 'Chester',
            Phone = '(215) 555-1212',
            Email = 'test@test.com',
            Method_of_Contact__c = 'Referral', 
            LeadSource = 'Portal Referral',
            Lead_Source_Detail__c = 'Professional',
            Site_Type__c = 'Residential'
            //Lead_Source_Detail_2__c = 'Channel',
           // Lead_Source_Detail_4__c = 'Astrum Solar Connect'
      );
      insert ld;

      //convert to oppty      
      Database.LeadConvert lc = new Database.LeadConvert();
      lc.setLeadId(ld.Id);
      lc.setConvertedStatus('Qualified');
      Database.LeadConvertResult lcr = Database.convertLead(lc);
      System.assert(lcr.isSuccess());
        
      //create a lead
      Lead ld2 = new Lead (
            FirstName = 'Test',
            LastName = 'Lead',
            Company = 'Lead, Test',
            Street = '123 Test St',
            City = 'Test City',
            State = 'PA',
            PostalCode = '19403',
            County__c = 'Chester',
            Phone = '(215) 555-1212',
            Email = 'test@test.com',
            Method_of_Contact__c = 'Referral', 
            LeadSource = 'Portal Referral',
            Lead_Source_Detail__c = 'Professional',
            Site_Type__c = 'Residential'
            //Lead_Source_Detail_2__c = 'Channel',
           // Lead_Source_Detail_4__c = 'Astrum Solar Connect'
      );
      
      
      Test.startTest();
      insert ld2;
      Test.stopTest();
      
      ld2 = [Select Status from Lead Where Id = :ld2.Id ]; 
      
      System.assert(ld2.Status == 'Not a Lead - DUPLICATE');    
   }   
      
}