src/objects/County__c.object
<CustomObject>
    <description>Represents a County in a State</description>
    <fields>
        <fullName>Sales_Region__c</fullName>
        <label>Sales Region</label>
        <picklist>
            <picklistValues>
                <fullName>MA Region</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>MD Region</fullName>
                <color>#6600CC</color>
            </picklistValues>
            <picklistValues>
                <fullName>NYC Region</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>OH Region</fullName>
                <color>#3366FF</color>
            </picklistValues>
            <picklistValues>
                <fullName>PA Region</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>WNY Region</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <picklistValues>
                <fullName>CA Region</fullName>
                <color>#006600</color>
            </picklistValues>
            <picklistValues>
                <fullName>CT Region</fullName>
                <color>#33FFFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>NJ Region</fullName>
                <color>#F96FB7</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/County_Schedule_Availability__c.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>County</label>
        <referenceTo>County__c</referenceTo>
        <relationshipLabel>Counties Schedule Availability</relationshipLabel>
        <relationshipName>Counties_Schedule_Availability</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Counties_Schedule_Availability</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>County Schedule Availability</label>
    <nameField>
        <displayFormat>CSA-{0000}</displayFormat>
        <label>CSA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Counties Schedule Availability</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Employee__c.object
<CustomObject>
    <description>AstrumTIME - An Astrum Solar Employee Record for the AstumTIME app</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Monthly_Sales_Goals__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Monthly_Sales_Revenue_Goal__c</fullName>
        <label>Monthly Sales Revenue Goal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Monthly_Sales_Revenue_Stretch__c</fullName>
        <label>Monthly Sales Revenue Stretch</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Monthly Sales Goals</label>
</CustomObject>

src/objects/SCRB_SalesOrder__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The SalesOrder object is the result of a Closed Won Opportunity and handles the hand off from the sales team to the operations team.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sales_Region__c</fullName>
        <label>Sales Region</label>
        <picklist>
            <picklistValues>
                <fullName>MA Region</fullName>
                <color>#FFCC66</color>
            </picklistValues>
            <picklistValues>
                <fullName>MD Region</fullName>
                <color>#6600CC</color>
            </picklistValues>
            <picklistValues>
                <fullName>NYC Region</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>NYW Region</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <picklistValues>
                <fullName>OH Region</fullName>
                <color>#3366FF</color>
            </picklistValues>
            <picklistValues>
                <fullName>PA Region</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>CA Region</fullName>
                <color>#006600</color>
            </picklistValues>
            <picklistValues>
                <fullName>CT Region</fullName>
                <color>#33FFFF</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StatusCode__c</fullName>
        <label>Status Code</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>Submit Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Assigned to Sales Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Submit To Sales Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Coordinator Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Manager Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Coordinator Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final/Accounting Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Administrator Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated to VP Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VP Sales Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VP Sales Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Controller Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Proposal Creation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Proposal Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Ongoing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Controller Rejected - Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Admin Approved - Finance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Time_Original_Submit_Sales_Rep__c</fullName>
        <label>Time Original Submit Sales Rep</label>
        <type>DateTime</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MonthlyRevenueByRegionController.cls
/*  FILE: MonthlyRevenueByRegionController.cls
    AUTHOR: Dan Kelner
    DATE: 10/29/2014
    PURPOSE: Controller for MonthlyRevenueByRegion VF component.
    MODIFICATION HISTORY
        02/06/15  DK  Added year selection input
*/
public class MonthlyRevenueByRegionController {
    
    public String defaultMonth {get { if (defaultMonth == null)
                                          return monthList.get(Date.today().month() - 1);
                                      else
                                          return defaultMonth; } set;}    //VF Component attribute
    public String selectedMonth {get; set;}    //Chosen picklist value
    public String monthLabel {get { if (monthLabel == null)
                                        return defaultMonth;
                                    else
                                        return monthLabel; } set;}    //Month name to be displayed over the chart
    public Boolean allowMonthChange {get; set;}
    public String year {get; set;}
    public static Map<String, Integer> regionRepCounts {get { regionRepCounts = new Map<String, Integer>();    //Region name --> Number of sales reps
                                                              for (AggregateResult ar : [SELECT COUNT_DISTINCT(Employee__c), County__r.Sales_Region__c salesregion 
                                                                                         FROM County_Schedule_Availability__c GROUP BY County__r.Sales_Region__c LIMIT 10000]){
                                                                  regionRepCounts.put((String)ar.get('salesregion'), (Integer)ar.get('expr0'));
                                                              }
                                                              return regionRepCounts; } set;}
    
    private String[] monthList = new String[]{'January', 'February', 'March', 'April', 'May', 'June', 'July', 
                                              'August', 'September', 'October', 'November', 'December'};
    
    public MonthlyRevenueByRegionController(){
        year = String.valueOf(Date.today().year());
    }
    
    public SelectOption[] getMonthPicklist(){
        if (String.isBlank(selectedMonth))
            selectedMonth = defaultMonth;    //Set the default picklist value
        SelectOption[] months = new SelectOption[]{};
        for (String m : monthList)
            months.add(new SelectOption(m, m));
        return months;
    }
    
    public ChartData[] getRevenueData(){
        if (String.isBlank(year))
            year = String.valueOf(Date.today().year());
        if (String.isNotBlank(selectedMonth) && allowMonthChange != false)
            monthLabel = selectedMonth;    //User override
        Integer monthParam = getMonthNum(monthLabel);
        Integer theYear = Integer.valueOf(year);
        AggregateResult[] closedSalesOrders = [SELECT SUM(Amount__c), Sales_Region__c FROM SCRB_SalesOrder__c 
                                               WHERE CALENDAR_MONTH(convertTimezone(Time_Original_Submit_Sales_Rep__c)) = :monthParam 
                                               AND CALENDAR_YEAR(convertTimezone(Time_Original_Submit_Sales_Rep__c)) = :theYear 
                                               AND StatusCode__c != 'Canceled' AND Sales_Region__c != null 
                                               GROUP BY Sales_Region__c];
                                               
        AggregateResult[] canceledSalesOrders = [SELECT SUM(Amount__c), Sales_Region__c FROM SCRB_SalesOrder__c 
                                                 WHERE CALENDAR_MONTH(convertTimezone(Time_Original_Submit_Sales_Rep__c)) = :monthParam 
                                                 AND CALENDAR_YEAR(convertTimezone(Time_Original_Submit_Sales_Rep__c)) = :theYear 
                                                 AND StatusCode__c = 'Canceled' AND Sales_Region__c != null 
                                                 GROUP BY Sales_Region__c];
        Map<String, Double> closedMap = new Map<String, Double>();    //Region Name --> Aggregate Amount (closed)
        Map<String, Double> canceledMap = new Map<String, Double>();    //Region Name --> Aggregate Amount (canceled)
        Set<String> regions = new Set<String>();    //Sales Order regions from both queries
        
        for (AggregateResult ar : closedSalesOrders){
            closedMap.put((String)ar.get('Sales_Region__c'), (Double)ar.get('expr0'));
            regions.add((String)ar.get('Sales_Region__c'));
        }
        
        for (AggregateResult ar : canceledSalesOrders){
            canceledMap.put((String)ar.get('Sales_Region__c'), (Double)ar.get('expr0'));
            regions.add((String)ar.get('Sales_Region__c'));
        }
        
        //Populate the array for the chart
        String[] regionList = new List<String>(regions);
        ChartData[] datapoints = new ChartData[]{};
        for (String name : regionList){
            Double closedOrdersTotal = closedMap.containsKey(name) ? closedMap.get(name) : 0;
            Double canceledOrdersTotal = canceledMap.containsKey(name) ? canceledMap.get(name) : 0;
            datapoints.add(new ChartData(name, closedOrdersTotal, canceledOrdersTotal));
        }
        datapoints = selectionSort(datapoints);
        return datapoints;
    }
    
    private ChartData[] selectionSort(ChartData[] arr){
        for (Integer i = 0; i < arr.size() - 1; i++){
            Integer index = i;
            for (Integer j = i + 1; j < arr.size(); j++)
                if (arr[j].closedAmount > arr[index].closedAmount) 
                    index = j;
      
            ChartData larger = arr[index];  
            arr[index] = arr[i];
            arr[i] = larger;
        }
        return arr;
    }
    
    public SelectOption[] getYearOptions(){
        SelectOption[] opts = new SelectOption[]{};
        opts.add(new SelectOption(String.valueOf(Date.today().year() - 1), String.valueOf(Date.today().year() - 1)));
        opts.add(new SelectOption(String.valueOf(Date.today().year()), String.valueOf(Date.today().year())));
        return opts;
    }

    private Integer getMonthNum(String monthStr){
        Integer monthNum = 0;
        if (monthStr == 'January'){
            monthNum = 1;
        } else if (monthStr == 'February'){
            monthNum = 2;
        } else if (monthStr == 'March'){
            monthNum = 3;
        } else if (monthStr == 'April'){
            monthNum = 4;
        } else if (monthStr == 'May'){
            monthNum = 5;
        } else if (monthStr == 'June'){
            monthNum = 6;
        } else if (monthStr == 'July'){
            monthNum = 7;
        } else if (monthStr == 'August'){
            monthNum = 8;
        } else if (monthStr == 'September'){
            monthNum = 9;
        } else if (monthStr == 'October'){
            monthNum = 10;
        } else if (monthStr == 'November'){
            monthNum = 11;
        } else if (monthStr == 'December'){
            monthNum = 12;
        }
        return monthNum;
    }
    
    class ChartData {
        public String salesOrderRegion {get; set;}
        public Double closedAmount {get; set;}
        public Double canceledAmount {get; set;}
        public Double monthlyGoal {get; set;}
        public Double monthlyStretch {get; set;}
        
        public ChartData(String regionName, Double closedTotal, Double canceledTotal){
            salesOrderRegion = regionName;
            closedAmount = closedTotal;
            canceledAmount = canceledTotal;
            monthlyGoal = 0;
            monthlyStretch = 0;
            try {
                monthlyGoal = Monthly_Sales_Goals__c.getOrgDefaults().Monthly_Sales_Revenue_Goal__c * MonthlyRevenueByRegionController.regionRepCounts.get(salesOrderRegion);
                monthlyStretch = Monthly_Sales_Goals__c.getOrgDefaults().Monthly_Sales_Revenue_Stretch__c * MonthlyRevenueByRegionController.regionRepCounts.get(salesOrderRegion);
            } catch (NullPointerException e){
                System.debug('Error in MonthlyRevenueByRegionController on line ' + e.getLineNumber() + ': ' + e.getMessage());
            }
        }
    }
}