src/objects/County__c.object
<CustomObject>
    <description>Represents a County in a State</description>
    <fields>
        <fullName>FIPS_Code__c</fullName>
        <description>FIPS Code for county (2-digit state + 3 digit county code)</description>
        <externalId>true</externalId>
        <label>FIPS Code</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Pricing_Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pricing Region</label>
        <referenceTo>Pricing_Region__c</referenceTo>
        <relationshipLabel>Counties</relationshipLabel>
        <relationshipName>Counties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Region__c</fullName>
        <label>Sales Region</label>
        <picklist>
            <picklistValues>
                <fullName>MA Region</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>MD Region</fullName>
                <color>#6600CC</color>
            </picklistValues>
            <picklistValues>
                <fullName>NYC Region</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>OH Region</fullName>
                <color>#3366FF</color>
            </picklistValues>
            <picklistValues>
                <fullName>PA Region</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>WNY Region</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <picklistValues>
                <fullName>CA Region</fullName>
                <color>#006600</color>
            </picklistValues>
            <picklistValues>
                <fullName>CT Region</fullName>
                <color>#33FFFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>NJ Region</fullName>
                <color>#F96FB7</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>State_Abbreviation__c</fullName>
        <formula>State__r.State_Abbreviation__c</formula>
        <label>State Abbreviation</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>State County belongs to</description>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Counties</relationshipLabel>
        <relationshipName>Counties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/County_Schedule_Availability__c.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>County</label>
        <referenceTo>County__c</referenceTo>
        <relationshipLabel>Counties Schedule Availability</relationshipLabel>
        <relationshipName>Counties_Schedule_Availability</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>County Schedule Availability</label>
    <nameField>
        <displayFormat>CSA-{0000}</displayFormat>
        <label>CSA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Counties Schedule Availability</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Sales_Region__c</fullName>
        <label>Sales Region</label>
        <picklist>
            <picklistValues>
                <fullName>MA Region</fullName>
                <color>#FFCC66</color>
            </picklistValues>
            <picklistValues>
                <fullName>MD Region</fullName>
                <color>#6600CC</color>
            </picklistValues>
            <picklistValues>
                <fullName>NYC Region</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>OH Region</fullName>
                <color>#3366FF</color>
            </picklistValues>
            <picklistValues>
                <fullName>PA Region</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>WNY Region</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <picklistValues>
                <fullName>CA Region</fullName>
                <color>#006600</color>
            </picklistValues>
            <picklistValues>
                <fullName>CT Region</fullName>
                <color>#33FFFF</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Property State Associated with This Opportunity</description>
        <formula>TEXT(Property__r.Property_State__c)</formula>
        <inlineHelpText>Property State Associated with This Opportunity</inlineHelpText>
        <label>State</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SCRB_SalesOrder__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The SalesOrder object is the result of a Closed Won Opportunity and handles the hand off from the sales team to the operations team.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Owner_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Region__c</fullName>
        <label>Sales Region</label>
        <picklist>
            <picklistValues>
                <fullName>MA Region</fullName>
                <color>#FFCC66</color>
            </picklistValues>
            <picklistValues>
                <fullName>MD Region</fullName>
                <color>#6600CC</color>
            </picklistValues>
            <picklistValues>
                <fullName>NYC Region</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>NYW Region</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <picklistValues>
                <fullName>OH Region</fullName>
                <color>#3366FF</color>
            </picklistValues>
            <picklistValues>
                <fullName>PA Region</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>CA Region</fullName>
                <color>#006600</color>
            </picklistValues>
            <picklistValues>
                <fullName>CT Region</fullName>
                <color>#33FFFF</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StatusCode__c</fullName>
        <label>Status Code</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>Submit Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Assigned to Sales Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Submit To Sales Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Coordinator Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Manager Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Coordinator Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final/Accounting Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Administrator Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated to VP Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VP Sales Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VP Sales Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Controller Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Proposal Creation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Proposal Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Ongoing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Controller Rejected - Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Admin Approved - Finance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Time_Original_Submit_Sales_Rep__c</fullName>
        <label>Time Original Submit Sales Rep</label>
        <type>DateTime</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/State__c.object
<CustomObject>
    <description>Represents a State</description>
    <fields>
        <fullName>FIPS_Code__c</fullName>
        <description>2-digit FIPS state code</description>
        <label>FIPS Code</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>State_Abbreviation__c</fullName>
        <externalId>true</externalId>
        <label>State Abbreviation</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SalesLeaderboardChartsTest.cls
/*  FILE: SalesLeaderboardChartsTest
    AUTHOR: Dan Kelner
    DATE: 05/01/15
    PURPOSE: Test class for all the sales reports classes
    MODIFICATION HISTORY
*/
@isTest(seeAllData = false)
public class SalesLeaderboardChartsTest {

	private static void setUpTestData(){
		SCRB_SalesOrder__c[] salesOrders = new SCRB_SalesOrder__c[]{};
		for (Integer i = 1; i <= 12; i++){
			if (Math.mod(i, 2) == 0)
				salesOrders.add(new SCRB_SalesOrder__c(Name = 'Test Sales Order ' + i, Time_Original_Submit_Sales_Rep__c = System.now(), StatusCode__c = 'Submitted', 
													   Sales_Region__c = 'CA Region', Amount__c = 50, Owner_User__c = UserInfo.getUserId()));
			else
				salesOrders.add(new SCRB_SalesOrder__c(Name = 'Test Sales Order ' + 1, Time_Original_Submit_Sales_Rep__c = System.now(), StatusCode__c = 'Canceled', 
													   Sales_Region__c = 'MD Region', Amount__c = 50, Owner_User__c = UserInfo.getUserId()));
		}
		insert salesOrders;

		State__c[] states = new State__c[]{new State__c(Name = 'California', State_Abbreviation__c = 'CA', FIPS_Code__c = '06'), 
										   new State__c(Name = 'Maryland', State_Abbreviation__c = 'MD', FIPS_Code__c = '24')};
		insert states;

		Pricing_Region__c[] pricingRegions = new Pricing_Region__c[]{new Pricing_Region__c(Name = 'Maryland'), new Pricing_Region__c(Name = 'California')};
		insert pricingRegions;

		County__c[] counties = new County__c[]{new County__c(Name = 'Test County 1', State__c = states[0].ID, Pricing_Region__c = pricingRegions[0].ID, FIPS_Code__c = '0000'), 
											   new County__c(Name = 'Test County 2', State__c = states[1].ID, Pricing_Region__c = pricingRegions[1].ID, FIPS_Code__c = '0001')};
		insert counties;

		County_Schedule_Availability__c[] csaList = new County_Schedule_Availability__c[]{};
		csaList.add(new County_Schedule_Availability__c(County__c = counties[0].ID, Employee__c = UserInfo.getUserId()));
		csaList.add(new County_Schedule_Availability__c(County__c = counties[1].ID, Employee__c = UserInfo.getUserId()));
		insert csaList;

		Account acct = new Account(Name = 'Test Account');
		insert acct;

		Opportunity[] opps = new Opportunity[]{};
		opps.add(new Opportunity(Name = 'Test Opp 1', AccountID = acct.ID, CloseDate = Date.today().addDays(-1), StageName = 'Cancel Pending', Sales_Region__c = 'MD Region'));
		opps.add(new Opportunity(Name = 'Test Opp 2', AccountID = acct.ID, CloseDate = Date.today().addDays(-1), StageName = 'Cancel Pending', Sales_Region__c = 'CA Region'));
		Opportunity_Trigger_Utility.skipOpportunityTrigger = true;
		insert opps;
		Opportunity_Trigger_Utility.skipOpportunityTrigger = false;
	}

	public testmethod static void testMonthlyOppCloseByRegion(){
		setUpTestData();

		Test.startTest();

		MonthlyOppCloseByRegionController ctrl1 = new MonthlyOppCloseByRegionController();
		ctrl1.getRevenueData();
		ctrl1.getMonthPicklist();
		ctrl1.getYearOptions();

		MonthlyOppCloseLeaderboardController ctrl2 = new MonthlyOppCloseLeaderboardController();
		ctrl2.getRevenueData();
		ctrl2.getMonthPicklist();
		ctrl2.getYearOptions();

		MonthlyRevenueLeaderboardsController ctrl3 = new MonthlyRevenueLeaderboardsController();
		ctrl3.getRevenueData();
		ctrl3.getMonthPicklist();
		ctrl3.getYearOptions();

		YTD_OppClosesByRegionController ctrl4 = new YTD_OppClosesByRegionController();
		ctrl4.getYearOptions();

		YTD_OppClosesLeaderboardController ctrl5 = new YTD_OppClosesLeaderboardController();
		ctrl5.getYearOptions();

		YTD_RevenueByRegionController ctrl6 = new YTD_RevenueByRegionController();
		ctrl6.getYearOptions();

		YTD_RevenueLeaderboardController ctrl7 = new YTD_RevenueLeaderboardController();
		ctrl7.getYearOptions();

		Trailing12WeekOppClosedController ctrl8 = new Trailing12WeekOppClosedController();

		Trailing12WeekOppClosedRegionController ctrl9 = new Trailing12WeekOppClosedRegionController();
		Test.StopTest();
	}
}