src/objects/County__c.object
<CustomObject>
    <description>Represents a County in a State</description>
    <fields>
        <fullName>Sales_Region__c</fullName>
        <label>Sales Region</label>
        <picklist>
            <picklistValues>
                <fullName>MA Region</fullName>
                <color>#FFCC33</color>
            </picklistValues>
            <picklistValues>
                <fullName>MD Region</fullName>
                <color>#6600CC</color>
            </picklistValues>
            <picklistValues>
                <fullName>NYC Region</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>OH Region</fullName>
                <color>#3366FF</color>
            </picklistValues>
            <picklistValues>
                <fullName>PA Region</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>WNY Region</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <picklistValues>
                <fullName>CA Region</fullName>
                <color>#006600</color>
            </picklistValues>
            <picklistValues>
                <fullName>CT Region</fullName>
                <color>#33FFFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>NJ Region</fullName>
                <color>#F96FB7</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/County_Schedule_Availability__c.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>County</label>
        <referenceTo>County__c</referenceTo>
        <relationshipLabel>Counties Schedule Availability</relationshipLabel>
        <relationshipName>Counties_Schedule_Availability</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Counties_Schedule_Availability</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>County Schedule Availability</label>
    <nameField>
        <displayFormat>CSA-{0000}</displayFormat>
        <label>CSA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Counties Schedule Availability</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Employee__c.object
<CustomObject>
    <description>AstrumTIME - An Astrum Solar Employee Record for the AstumTIME app</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Monthly_Sales_Goals__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Monthly_Opportunity_Close_Goal__c</fullName>
        <label>Monthly Opportunity Close Goal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Monthly_Opportunity_Close_Stretch__c</fullName>
        <label>Monthly Opportunity Close Stretch</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Monthly Sales Goals</label>
</CustomObject>

src/objects/SCRB_SalesOrder__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The SalesOrder object is the result of a Closed Won Opportunity and handles the hand off from the sales team to the operations team.</description>
    <fields>
        <fullName>Sales_Region__c</fullName>
        <label>Sales Region</label>
        <picklist>
            <picklistValues>
                <fullName>MA Region</fullName>
                <color>#FFCC66</color>
            </picklistValues>
            <picklistValues>
                <fullName>MD Region</fullName>
                <color>#6600CC</color>
            </picklistValues>
            <picklistValues>
                <fullName>NYC Region</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>NYW Region</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <picklistValues>
                <fullName>OH Region</fullName>
                <color>#3366FF</color>
            </picklistValues>
            <picklistValues>
                <fullName>PA Region</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>CA Region</fullName>
                <color>#006600</color>
            </picklistValues>
            <picklistValues>
                <fullName>CT Region</fullName>
                <color>#33FFFF</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StatusCode__c</fullName>
        <label>Status Code</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>Submit Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Assigned to Sales Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Submit To Sales Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Coordinator Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Manager Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Coordinator Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final/Accounting Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Administrator Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated to VP Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VP Sales Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VP Sales Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Controller Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Proposal Creation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Proposal Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Ongoing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Controller Rejected - Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Admin Approved - Finance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Time_Original_Submit_Sales_Rep__c</fullName>
        <label>Time Original Submit Sales Rep</label>
        <type>DateTime</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/YTD_OppClosesByRegionController.cls
/*  FILE: YTD_OppClosesByRegionController.cls
    AUTHOR: Dan Kelner
    DATE: 10/29/2014
    PURPOSE: Controller for YTD_OppClosesByRegion VF component.
    MODIFICATION HISTORY
        02/09/15  DK  Added year selection input
*/
public class YTD_OppClosesByRegionController {
    
    public ChartData[] revenueData {get; set;}
    public static Map<String, Integer> regionRepCounts;
    public String year {get; set;}
    
    public YTD_OppClosesByRegionController (){
        regionRepCounts = new Map<String, Integer>();    //Region name --> Number of sales reps
        for (AggregateResult ar : [SELECT COUNT_DISTINCT(Employee__c), County__r.Sales_Region__c salesregion FROM County_Schedule_Availability__c GROUP BY County__r.Sales_Region__c LIMIT 10000]){
            regionRepCounts.put((String)ar.get('salesregion'), (Integer)ar.get('expr0'));
        }
        revenueData = populateChartData();
    }
    
    private ChartData[] populateChartData(){
        if (String.isBlank(year))
            year = String.valueOf(Date.today().year());
        Integer theYear = Integer.valueOf(year);
        AggregateResult[] closedSalesOrders = [SELECT COUNT(ID), Sales_Region__c FROM SCRB_SalesOrder__c 
                                               WHERE CALENDAR_YEAR(convertTimezone(Time_Original_Submit_Sales_Rep__c)) = :theYear 
                                               AND StatusCode__c != 'Canceled' AND Sales_Region__c != null 
                                               GROUP BY Sales_Region__c];
                                               
        AggregateResult[] canceledSalesOrders = [SELECT COUNT(ID), Sales_Region__c FROM SCRB_SalesOrder__c 
                                                 WHERE CALENDAR_YEAR(convertTimezone(Time_Original_Submit_Sales_Rep__c)) = :theYear 
                                                 AND StatusCode__c = 'Canceled' AND Sales_Region__c != null 
                                                 GROUP BY Sales_Region__c];
                                                 
        Map<String, Integer> closedMap = new Map<String, Integer>();    //Region Name --> Count (closed)
        Map<String, Integer> canceledMap = new Map<String, Integer>();    //Region Name --> Count (canceled)
        Set<String> regions = new Set<String>();    //Sales Order regions from both queries
        
        for (AggregateResult ar : closedSalesOrders){
            closedMap.put((String)ar.get('Sales_Region__c'), (Integer)ar.get('expr0'));
            regions.add((String)ar.get('Sales_Region__c'));
        }
        
        for (AggregateResult ar : canceledSalesOrders){
            canceledMap.put((String)ar.get('Sales_Region__c'), (Integer)ar.get('expr0'));
            regions.add((String)ar.get('Sales_Region__c'));
        }
        
        //Populate the array for the chart
        String[] regionList = new List<String>(regions);
        ChartData[] datapoints = new ChartData[]{};
        for (String name : regionList){
            Integer closedOrdersTotal = closedMap.containsKey(name) ? closedMap.get(name) : 0;
            Integer canceledOrdersTotal = canceledMap.containsKey(name) ? canceledMap.get(name) : 0;
            datapoints.add(new ChartData(name, closedOrdersTotal, canceledOrdersTotal));
        }
        datapoints = selectionSort(datapoints);
        return datapoints;
    }
    
    private ChartData[] selectionSort(ChartData[] arr){
        for (Integer i = 0; i < arr.size() - 1; i++){
            Integer index = i;
            for (Integer j = i + 1; j < arr.size(); j++)
                if (arr[j].closedCount > arr[index].closedCount) 
                    index = j;
      
            ChartData larger = arr[index];  
            arr[index] = arr[i];
            arr[i] = larger;
        }
        return arr;
    }
    
    public SelectOption[] getYearOptions(){
        SelectOption[] opts = new SelectOption[]{};
        opts.add(new SelectOption(String.valueOf(Date.today().year() - 1), String.valueOf(Date.today().year() - 1)));
        opts.add(new SelectOption(String.valueOf(Date.today().year()), String.valueOf(Date.today().year())));
        return opts;
    }

    class ChartData {
        public String salesOrderRegion {get; set;}
        public Integer closedCount {get; set;}
        public Integer canceledCount {get; set;}
        public Double annualGoal {get; set;}
        public Double annualStretch {get; set;}
        
        public ChartData(String regionName, Integer closedNum, Integer canceledNum){
            salesOrderRegion = regionName;
            closedCount = closedNum;
            canceledCount = canceledNum;
            annualGoal = 0;
            annualStretch = 0;
            try {
                annualGoal = Monthly_Sales_Goals__c.getOrgDefaults().Monthly_Opportunity_Close_Goal__c * 12 * YTD_OppClosesByRegionController.regionRepCounts.get(salesOrderRegion);
                annualStretch = Monthly_Sales_Goals__c.getOrgDefaults().Monthly_Opportunity_Close_Stretch__c * 12 * YTD_OppClosesByRegionController.regionRepCounts.get(salesOrderRegion);
            } catch (NullPointerException e){
                System.debug('Error in YTD_OppClosesByRegionController on line ' + e.getLineNumber());
            }
        }
    }
}