src/objects/Credit_Report_Log__c.object
<CustomObject>
    <description>Credit Reporting History for Accounts</description>
    <fields>
        <fullName>Account__c</fullName>
        <inlineHelpText>Customer Account</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit Report Logs</relationshipLabel>
        <relationshipName>Credit_Report_Logs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Related_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Credit Report Logs</relationshipLabel>
        <relationshipName>Credit_Report_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Credit Report Log</label>
    <nameField>
        <displayFormat>CRL-{000000}</displayFormat>
        <label>Credit Report Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Report Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CreditReportLogExtension.cls
/* FILE: CreditReportLogExtension .cls
 * AUTHOR: Tino Mattheou
 * DATE: January 4, 2013
 * PURPOSE: Extension for CreditReportLogEdit. Gets account-related opportunities.
 * MODIFICATION HISTORY
 */

public class CreditReportLogExtension {

    private ApexPages.StandardController controller;
    
    public String opportunityId { get; set; }

    public CreditReportLogExtension (ApexPages.StandardController controller) {
        this.controller = controller;
        Credit_Report_Log__c crl = (Credit_Report_Log__c)controller.getRecord();
        this.opportunityId = crl.Related_Opportunity__c;
    }

    public List<SelectOption> opportunities {
        get {
            if (opportunities == null) {
                opportunities = new List<SelectOption>();
                Credit_Report_Log__c crl = (Credit_Report_Log__c)controller.getRecord();
                if (crl.Account__c != null) {
                    List<Opportunity> opps = 
                        [SELECT Id, Name, CloseDate, StageName
                        FROM Opportunity
                        WHERE AccountId = :crl.Account__c
                        ORDER BY CloseDate DESC];
                    if (opps.size() > 1) {
                        opportunities.add(new SelectOption('', '-- Select --'));
                    }
                    for (Opportunity opp : opps) {
                        opportunities.add(new SelectOption(opp.Id,
                            opp.Name + ' (' + opp.CloseDate.format() + ' ' + opp.StageName + ')'));
                    }
                }
            }
            return opportunities;
        }
        private set;
    }

    public PageReference savePage() {
        try {
            Credit_Report_Log__c crl = (Credit_Report_Log__c)controller.getRecord();
            if (String.isNotBlank(opportunityId)) {
                crl.Related_Opportunity__c = opportunityId;
            } else {
                crl.Related_Opportunity__c = null;
            }
            controller.save();
            return controller.view();
        } catch (Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
            return null;
        }
    }
}