src/objects/Customer_Survey__c.object
<CustomObject>
    <fields>
        <fullName>MD5Code__c</fullName>
        <description>MD5 Code for Id</description>
        <label>MD5Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Overall_Experience__c</fullName>
        <label>Overall Experience</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PM_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PM Project</label>
        <referenceTo>PM_Project__c</referenceTo>
        <relationshipLabel>Customer Surveys</relationshipLabel>
        <relationshipName>Customer_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Survey Completed ?</label>
        <type>Checkbox</type>
    </fields>
    <label>Customer Survey</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Customer Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Property__c.Property_Owner__r.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PM_Project__c.object
<CustomObject>
    <description>Astrum PM 2.0 Project Object</description>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>SCRB_SalesOrder__c</referenceTo>
        <relationshipLabel>PM Projects</relationshipLabel>
        <relationshipName>PM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PM Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PM Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <description>AstrumPM/AstrumCRM - Each account can have one or more properties.  A property is defined by its street address.</description>
    <label>Property</label>
    <nameField>
        <label>Property Address 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SCRB_SalesOrder__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The SalesOrder object is the result of a Closed Won Opportunity and handles the hand off from the sales team to the operations team.</description>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>R00N300000011q88EAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CustomerSurveyTest.cls
/* FILE: CustomerSurveyTest.cls
 * AUTHOR: Rohit Jain
 * DATE: June 4, 2013
 * PURPOSE: Test class for CustomerSurvey Process
 * MODIFICATION HISTORY:
 *
 */

@isTest(seeAllData=true)
public class CustomerSurveyTest{
    
  static testMethod void Change_Request_BIBU_Test() {
    
    Account customer = new Account(Name = 'Test Customer');
    insert customer;
    Contact ct = new Contact(LastName = 'RG', Email='Test@rest.comm', AccountId = customer.Id);
    insert ct;
    Property__c property = CreateAstrumPM2ProjectTest.createProperty(customer.Id, '123 Test St');
    Opportunity opp = CreateAstrumPM2ProjectTest.createOpportunity(customer.Id, 'Test Oppty');    
    SCRB_SalesOrder__c salesOrder = CreateAstrumPM2ProjectTest.createSalesOrder(property.Id, opp.Id);
    salesOrder.AccountId__c = customer.Id;
    update salesOrder;    
    Test.setCurrentPage(Page.CreateAstrumPM2Project);    
    RootstockAutomation amr = new RootstockAutomation();
    String projectId = amr.createProject(salesOrder );
    PM_Project__c prj = [Select Id,Sales_Order__c from PM_Project__c where Id = :projectId];
    
    Test.startTest();
        ApexPages.StandardController pmcontroller = new ApexPages.StandardController(prj);
        
        CustomerSurveySendExtension surveyext = new CustomerSurveySendExtension(pmcontroller );    
        List<SelectOption> options = surveyext.getContacts();
        String ContactId = options[0].getValue();
        CustomerSurveySendExtension.sendSurvey(ContactId );
        
        Customer_Survey__c survey = [Select Id,PM_Project__c,md5Code__c from Customer_Survey__c Where PM_Project__c = :projectId];
        
        System.assertEquals(projectid,survey.Pm_Project__c);
        
        Test.setCurrentPage(Page.CustomerSurveyHome);
        ApexPages.currentPage().getParameters().put('Id', survey.md5Code__c);
        
        CustomerSurveyController cs = new CustomerSurveyController();
        cs.survey.Overall_Experience__c = 'Good';
        Pagereference pr = cs.submit();
        
        survey = [Select Id,PM_Project__c,md5Code__c,Survey_Completed__c from Customer_Survey__c Where PM_Project__c = :projectId];
                
        System.assertEquals(survey.Survey_Completed__c,TRUE);
        
    Test.stopTest(); 
  }
}