src/objects/Customer_Survey__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Customer Surveys</relationshipLabel>
        <relationshipName>Customer_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MD5Code__c</fullName>
        <description>MD5 Code for Id</description>
        <label>MD5Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PM_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PM Project</label>
        <referenceTo>PM_Project__c</referenceTo>
        <relationshipLabel>Customer Surveys</relationshipLabel>
        <relationshipName>Customer_Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Survey_Completed_By__c</fullName>
        <label>Survey Completed By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Survey Completed ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Survey_Date_Completed__c</fullName>
        <label>Survey Date Completed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Survey_Date_Sent__c</fullName>
        <label>Survey Date Sent</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Survey_Re_Sent_Date__c</fullName>
        <label>Survey Re-Sent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Survey_Sent_To_Email__c</fullName>
        <label>Survey Sent To Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Survey_Sent_To__c</fullName>
        <label>Survey Sent To</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Customer Survey</label>
    <nameField>
        <displayFormat>CS-{00000}</displayFormat>
        <label>Customer Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PM_Project__c.object
<CustomObject>
    <description>Astrum PM 2.0 Project Object</description>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>SCRB_SalesOrder__c</referenceTo>
        <relationshipLabel>PM Projects</relationshipLabel>
        <relationshipName>PM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PM Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PM Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SCRB_SalesOrder__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The SalesOrder object is the result of a Closed Won Opportunity and handles the hand off from the sales team to the operations team.</description>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>R00N300000011q88EAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CustomerSurveySendExtension.cls
/* FILE: CustomerSurveySendExtension.cls
 * AUTHOR: Rohit Jain
 * DATE: Oct 18, 2013
 * PURPOSE: Customer Survey Send from PM Project.
 * MODIFICATION HISTORY 
 *     12/07/14  DK  Made sendSurvey() method global to fix Salesforce Console errors
 */
global class CustomerSurveySendExtension{

    private ApexPages.StandardController controller;
    public String selectedContact { get; set; }    
    PM_Project__c project;
    
    public CustomerSurveySendExtension(ApexPages.StandardController controller) {
        this.controller = controller;
        project = (PM_Project__c) controller.getRecord();    
        project = [Select Sales_Order__r.AccountId__c from PM_Project__c Where id = :project.Id  ] ;  
    }
    
    public List<SelectOption> getContacts() {
        List<SelectOption> result = new List<SelectOption>();
        List<Contact> contacts = 
            [SELECT Id,Name,Email
               FROM Contact
              WHERE AccountId = :project.Sales_Order__r.AccountId__c
                AND Email != null
           ORDER BY Name];
        for (Contact ct: contacts) {
            result.add(new SelectOption(ct.Id+';'+project.Id, ct.Name));             
        }    
        if(result.size() < 1)
        {
           result.add(new SelectOption('', 'No Contacts'));        
        }
            
        return result;     
       
    }
    
    @RemoteAction
    global static String sendSurvey(String contactprjId) {
        String contactId;
        String projectId;
        if(contactprjId == null || contactprjId == '')
        {
            return 'Pelase select the receipient.';
        }
        else
        {
            String[] ids = contactprjId.split(';');     
            contactId = ids[0];
            projectId = ids[1];
        }
        
        List<Customer_Survey__c> surveys = [Select Id,Survey_Sent_To__c,Survey_Date_Sent__c,Survey_Completed__c
                                                  ,Survey_Completed_By__c,Survey_Date_Completed__c ,Survey_Sent_To_Email__c
                                                  ,Contact__r.Email
                                              from Customer_Survey__c Where PM_Project__c = :projectId];
       
        
        if(surveys != null && !surveys.isEmpty())
        {
            if(surveys[0].Survey_Completed__c)
            {
                return 'Survey has been sent for this project and was completed by '+surveys[0].Survey_Completed_By__c + ' on '+ surveys[0].Survey_Date_Completed__c ;      
            }
            else
            {
                if(surveys[0].Contact__c ==  contactId  &&  surveys[0].Contact__r.Email == surveys[0].Survey_Sent_To_Email__c )
                {
                    return 'Survey has been sent for this project to '+surveys[0].Survey_Sent_To__c + ' on '+ surveys[0].Survey_Date_Sent__c.format() ;      
                }
                else
                {
                     surveys[0].Survey_Sent_To_Email__c = surveys[0].Contact__r.Email;
                     surveys[0].Survey_Re_Sent_Date__C = System.Today(); 
                     update surveys[0];
                     return 'Survey is being Re Sent due to change of Email Address.'; 
                }    
            }    
        }
        else
        {
            System.debug('***contactId  '+contactId );
            Contact ct = [Select Id,Name,Email from Contact Where Id = :contactId];
            Customer_Survey__c   survey = new Customer_Survey__c();
            survey.PM_Project__c = projectId;
            survey.Survey_Date_Sent__C = System.Today();  
            survey.Contact__c = contactId;         
            survey.Survey_Sent_To__c = ct.Name;
            survey.Survey_Sent_To_Email__c = ct.Email;       
            insert survey;   
                 
            String surveyId = survey.Id;           
            String md5Coded = EncodingUtil.convertToHex(Crypto.generateDigest('MD5', Blob.valueOf(surveyId )));
            survey.md5code__c = md5Coded ;
            update survey;
            return ''; 
            
        }
    } 
}