src/objects/D2D_Proposal__c.object
<CustomObject>
    <description>The calculated values necessary to display a proposal in the D2D application.</description>
    <fields>
        <fullName>Utility_Company_Master__c</fullName>
        <label>Utility Company</label>
        <referenceTo>Utility_Company_master__c</referenceTo>
        <relationshipLabel>D2D Proposals</relationshipLabel>
        <relationshipName>D2D_Proposals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>D2D Proposal</label>
    <nameField>
        <displayFormat>D2D-{0000}</displayFormat>
        <label>D2D Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>D2D Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <picklist>
            <picklistValues>
                <fullName>CONNECTICUT =&gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fairfield CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hartford CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Litchfield CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middlesex CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Haven CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New London CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tolland CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Windham CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DISTRICT OF COLUMBIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DELAWARE =&gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kent DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Castle DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sussex DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MARYLAND =&gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allegany MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anne Arundel MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baltimore City MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baltimore MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Calvert MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caroline MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carroll MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cecil MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charles MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dorchester MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Frederick MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Garrett MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Harford MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Howard MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kent MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rockland NY</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>D2D_System_Size__c</fullName>
        <label>D2D System Size</label>
        <picklist>
            <controllingField>D2D_State__c</controllingField>
            <picklistValues>
                <fullName>16 Panel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24 Panel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>36 Panel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Utility_Company_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Company Master</label>
        <referenceTo>Utility_Company_master__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>County__c</fullName>
        <label>County</label>
        <picklist>
            <picklistValues>
                <fullName>CONNECTICUT =&gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fairfield CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hartford CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Litchfield CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middlesex CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Haven CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New London CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tolland CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Windham CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DISTRICT OF COLUMBIA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DELAWARE =&gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kent DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Castle DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sussex DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MARYLAND =&gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allegany MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anne Arundel MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baltimore City MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Baltimore MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Calvert MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caroline MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Carroll MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cecil MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charles MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dorchester MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Frederick MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Garrett MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Harford MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Howard MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kent MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rockland NY</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Portal_Referral__c.object
<CustomObject>
    <description>Referrals from the Partner Program website</description>
    <fields>
        <fullName>D2D_Lead_Status__c</fullName>
        <label>D2D Lead Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed - Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Generated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Opt-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Opt-Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Door Hanger</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing Utility Bill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA Visit 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA Visit 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passed Validation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Photos Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit Scheduled</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>D2D_Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>D2D Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Portal_Referrals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>D2D_System_Size__c</fullName>
        <label>D2D System Size</label>
        <picklist>
            <controllingField>State__c</controllingField>
            <picklistValues>
                <fullName>16 Panel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24 Panel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>36 Panel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Portal Referrals</relationshipLabel>
        <relationshipName>Portal_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Portal Referrals</relationshipLabel>
        <relationshipName>Portal_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SSG_Accepted__c</fullName>
        <defaultValue>&quot;false&quot;</defaultValue>
        <label>SSG_Accepted</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Portal Referral</label>
    <nameField>
        <displayFormat>REF-{000000}</displayFormat>
        <label>Portal Referral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <description>AstrumPM/AstrumCRM - Each account can have one or more properties.  A property is defined by its street address.</description>
    <fields>
        <fullName>Utility_Company_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>DEPRECATED AS OF 11/25/14</description>
        <label>Utility Company Master</label>
        <referenceTo>Utility_Company_master__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Address 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/System_Designers_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>System_Designers_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>System Designers Assignment</label>
    <nameField>
        <displayFormat>SDA-{000000}</displayFormat>
        <label>System Designers Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Designers Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/D2D_SolarSavingsGuidePreviewCtrlrTest.cls
@isTest
private class D2D_SolarSavingsGuidePreviewCtrlrTest {
    private static boolean runalltests = true; // true to run all tests; false to skip tests and only run those where the 'if' is commented out

	@testSetup static void setupData() {
		D2DTestUtility.InitializeRequiredMethods();
		D2DTestUtility.CreateCustomSettings('sales.coordinator@email.com');
		
		D2DTestUtility.CreateManagerUsers(1);
		User d2dMg = D2DTestUtility.d2dManagerUsers[0];

		D2DTestUtility.CreateSalesRepUsers(1);
		User d2dSr = D2DTestUtility.d2dSalesRepUsers[0];

		D2DTestUtility.CreatePortalReferralRequiredObjects(1, 'NY', '24 Panel');
		D2DTestUtility.CreatePortalReferralsWithLeads(1, d2dMg.Id, d2dSr.Id, 'QUALIFIED', 'Prospect New', '24 Panel', '2', 'ref', 'Joe', '101 Boolean Way', 'Stony Point', 'NY', '10980', '', false);
	}

	@isTest static void test_InvalidData() {
		if(!runalltests){ return; }

		Portal_Referral__c referral = [SELECT Id, D2D_Sales_Rep__c, Lead__c, D2D_System_Size__c, Email__c FROM Portal_Referral__c LIMIT 1];
		Lead lead = [SELECT Id, Utility_Company_Master__c, County__c FROM Lead WHERE Id = :referral.Lead__c];
		Utility_Company_Master__c ucm = [SELECT Id FROM Utility_Company_Master__c LIMIT 1];
		User d2dSr = [SELECT Id FROM User WHERE Id = :referral.D2D_Sales_Rep__c];

		PageReference pageRef = Page.D2D_SolarSavingsGuidePreview;
		pageRef.getParameters().put('id', referral.Id);
		Test.setCurrentPage(pageRef);

		Test.startTest();

		Boolean hasExpectedMessage = false;
		System.runAs(d2dSr){
			D2D_SolarSavingsGuidePreviewController controller = new D2D_SolarSavingsGuidePreviewController();

			ApexPages.Message[] pageMessages = ApexPages.getMessages();
			for(ApexPages.Message message : pageMessages){
				system.debug('**SZ: message = ' + message.getSeverity() + '; ' + message.getSummary());
				if(message.getSummary().contains('county specified')){
					hasExpectedMessage = true;
					break;
				}
			}
			system.assert(hasExpectedMessage);
		}

		hasExpectedMessage = false;
		lead.County__c = 'Rockland NY';
		update lead;

		System.runAs(d2dSr){
			pageRef = null;
			pageRef = Page.D2D_SolarSavingsGuidePreview;
			pageRef.getParameters().put('id', referral.Id);
			Test.setCurrentPage(pageRef);

			D2D_SolarSavingsGuidePreviewController controller = new D2D_SolarSavingsGuidePreviewController();

			ApexPages.Message[] pageMessages = ApexPages.getMessages();
			for(ApexPages.Message message : pageMessages){
				system.debug('**SZ: message = ' + message.getSeverity() + '; ' + message.getSummary());
				if(message.getSummary().contains('Guide was not found')){
					hasExpectedMessage = true;
					break;
				}
			}
			system.assert(hasExpectedMessage);
		}

		hasExpectedMessage = false;
		lead.Utility_Company_Master__c = ucm.Id;
		update lead;

		System.runAs(d2dSr){
			pageRef = null;
			pageRef = Page.D2D_SolarSavingsGuidePreview;
			pageRef.getParameters().put('id', referral.Id);
			Test.setCurrentPage(pageRef);

			D2D_SolarSavingsGuidePreviewController controller = new D2D_SolarSavingsGuidePreviewController();

			ApexPages.Message[] pageMessages = ApexPages.getMessages();
			for(ApexPages.Message message : pageMessages){
				system.debug('**SZ: message = ' + message.getSeverity() + '; ' + message.getSummary());
				if(message.getSummary().contains('did not contain an attachment')){
					hasExpectedMessage = true;
					break;
				}
			}
			system.assert(hasExpectedMessage);
		}

		Test.stopTest();
	}

	@isTest static void test_AcceptSSG() {
		if(!runalltests){ return; }

		Portal_Referral__c referral = [SELECT Id, D2D_Sales_Rep__c, Lead__c, D2D_System_Size__c, Email__c FROM Portal_Referral__c LIMIT 1];
		Lead lead = [SELECT Id, Utility_Company_Master__c, County__C FROM Lead WHERE Id = :referral.Lead__c];
		User d2dSr = [SELECT Id FROM User WHERE Id = :referral.D2D_Sales_Rep__c];
		Utility_Company_Master__c utilityCompanyMaster = [SELECT Id FROM Utility_Company_Master__c LIMIT 1];
		D2D_Proposal__c d2dProposal = [SELECT Id FROM D2D_Proposal__c LIMIT 1];
		System_Designers_Assignment__c assignment = [SELECT USer__c FROM System_Designers_Assignment__c LIMIT 1];

		lead.County__c = 'Rockland NY';
		lead.Utility_Company_Master__c = utilityCompanyMaster.Id;
		update lead;

        Attachment att = new Attachment(
	        Name = 'sampleSSG.pdf',
	        Body = Blob.valueOf('Sample SSG Attachment'),
	        ContentType = 'application/pdf',
	        ParentId = d2dProposal.Id
    	);
        insert att;

		PageReference pageRef = Page.D2D_SolarSavingsGuidePreview;
		pageRef.getParameters().put('id', referral.Id);
		Test.setCurrentPage(pageRef);

		Test.startTest();

		System.runAs(d2dSr){
			D2D_SolarSavingsGuidePreviewController controller = new D2D_SolarSavingsGuidePreviewController();
			PageReference pr = controller.ssgAccepted();
			system.debug('**SZ: pr = ' + pr);
			ApexPages.Message[] pageMessages = ApexPages.getMessages();
			for(ApexPages.Message message : pageMessages){
				system.debug('**SZ: message = ' + message.getSeverity() + '; ' + message.getSummary());
			}
		}

		Test.stopTest();

		referral = [SELECT Id, Lead__c, Opportunity__c, SSG_Accepted__c, D2D_Lead_Status__c FROM Portal_Referral__c LIMIT 1];
		lead = [SELECT Id, Status, IsConverted FROM Lead WHERE Id = :referral.Lead__c LIMIT 1];
		Opportunity opp = [SELECT Id, Property__c FROM Opportunity LIMIT 1];
		Property__c prop = [SELECT Id FROM Property__c WHERE Id = :opp.Property__c LIMIT 1];
		Event ssEvent = [SELECT Id, OwnerId FROM Event WHERE WhatId = :opp.Id LIMIT 1];
		system.debug('**SZ: referral = ' + referral);
		system.debug('**SZ: lead = ' + lead);
		system.debug('**SZ: opp = ' + opp);
		system.debug('**SZ: prop = ' + prop);
		system.debug('**SZ: ssEvent = ' + ssEvent);

		system.assertEquals('True', referral.SSG_Accepted__c);
		system.assertEquals('Customer Opt-In', referral.D2D_Lead_Status__c);

		system.assert(lead.IsConverted);
		system.assert(lead.Status.contains('Qualified'));

		system.assertNotEquals(null, opp);
		system.assertNotEquals(null, prop);
		system.assertNotEquals(null, ssEvent);
		system.assertEquals(assignment.USer__c, ssEvent.OwnerId);
	}
}