src/objects/Deleted_Time_Sheet__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Deleted Time Sheets</relationshipLabel>
        <relationshipName>Deleted_Time_Sheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>For_The_Week_Starting__c</fullName>
        <label>For The Week Starting</label>
        <type>Date</type>
    </fields>
    <label>Deleted Time Sheet</label>
    <nameField>
        <label>Deleted Time Sheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deleted Time Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Deleted_Time_Sheet_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Half_Hour_Lunch_Break__c</fullName>
        <label>Half Hour Lunch Break</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Client_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project/Client/Job</label>
        <referenceTo>Install_Project__c</referenceTo>
        <relationshipLabel>Deleted Time Sheet Entries</relationshipLabel>
        <relationshipName>Deleted_Time_Sheet_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <label>Purpose</label>
        <picklist>
            <picklistValues>
                <fullName>Install</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Install-Electric</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warranty Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Bonus Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Bonus Warranty Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid Time Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holiday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sick Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vacation Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First 2 Weeks of Training</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Time_Off_Site__c</fullName>
        <label>Start Time Off Site</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Time_On_Site__c</fullName>
        <label>Start Time On Site</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Timesheet_Purpose__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Timesheet Purpose</label>
        <referenceTo>Timesheet_Purpose__c</referenceTo>
        <relationshipLabel>Deleted Time Sheet Entries</relationshipLabel>
        <relationshipName>Deleted_Time_Sheet_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deleted Time Sheet Entry</label>
    <nameField>
        <label>Deleted Time Sheet Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deleted Time Sheet Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Employee__c.object
<CustomObject>
    <description>AstrumTIME - An Astrum Solar Employee Record for the AstumTIME app</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Time_Sheet__c.object
<CustomObject>
    <description>AstrumTIME - Employee Time Sheet</description>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Employee Who is Submitting This Time Sheet</description>
        <inlineHelpText>Employee Who is Submitting This Time Sheet</inlineHelpText>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Time Sheets</relationshipLabel>
        <relationshipName>Time_Sheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>For_The_Week_Starting__c</fullName>
        <defaultValue>TODAY()+(2-MOD( TODAY() - DATE(1900, 1, 6), 7))</defaultValue>
        <description>The date of Monday of the week for which this time sheet is entered</description>
        <inlineHelpText>Monday of this Time Sheet&apos;s effective week.</inlineHelpText>
        <label>For The Week Starting</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Time Sheet</label>
    <nameField>
        <displayFormat>TimeSheet-{000000}</displayFormat>
        <label>Time Sheet Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time_Sheet_Entry__c.object
<CustomObject>
    <description>AstrumTIME - A Single Entry For An Astrum Solar Time Sheet</description>
    <fields>
        <fullName>Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Approved by Manager ?</description>
        <inlineHelpText>Approved by Manager ?</inlineHelpText>
        <label>Approved ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <description>End Time</description>
        <inlineHelpText>End Time</inlineHelpText>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Half_Hour_Lunch_Break__c</fullName>
        <description>Half Hour Lunch Break</description>
        <inlineHelpText>Did you take a half hour lunch break during this time?</inlineHelpText>
        <label>Half Hour Lunch Break</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Client_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Which Project Are You Working On?</description>
        <inlineHelpText>Which Project Are You Working On?</inlineHelpText>
        <label>Project/Client/Job</label>
        <referenceTo>Install_Project__c</referenceTo>
        <relationshipLabel>Time Sheet Entries</relationshipLabel>
        <relationshipName>Time_Sheet_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <description>Purpose</description>
        <inlineHelpText>Purpose</inlineHelpText>
        <label>Purpose</label>
        <picklist>
            <picklistValues>
                <fullName>Install</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Install-Electrical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warranty Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Bonus Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Bonus Warranty Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid Time Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holiday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sick Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vacation Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First 2 Weeks of Training</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Time_Off_Site__c</fullName>
        <description>Start Time Off Site</description>
        <inlineHelpText>Start Time Off Site</inlineHelpText>
        <label>Start Time Off Site</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Time_On_Site__c</fullName>
        <description>Start Time On Site</description>
        <inlineHelpText>Start Time On Site</inlineHelpText>
        <label>Start Time On Site</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>Start Time</description>
        <inlineHelpText>Start Time</inlineHelpText>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Time_Sheet__c</fullName>
        <description>The Astrum Solar Time Sheet Containing this Entry</description>
        <inlineHelpText>The Astrum Solar Time Sheet Containing this Entry</inlineHelpText>
        <label>Time Sheet</label>
        <referenceTo>Time_Sheet__c</referenceTo>
        <relationshipLabel>Time Sheet Entries</relationshipLabel>
        <relationshipName>Time_Sheet_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Timesheet_Purpose__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Timesheet Purpose</label>
        <referenceTo>Timesheet_Purpose__c</referenceTo>
        <relationshipLabel>Time Sheet Entries</relationshipLabel>
        <relationshipName>Time_Sheet_Entries</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Time Sheet Entry</label>
    <nameField>
        <displayFormat>Entry-{0000000}</displayFormat>
        <label>Time Sheet Entry</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Sheet Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Timesheet_Purpose__c.object
<CustomObject>
    <label>Timesheet Purpose</label>
    <nameField>
        <label>Timesheet Purpose Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Timesheet Purposes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TimeSheetDeleteUtilityTest.cls
@isTest
private class TimeSheetDeleteUtilityTest {
    private static boolean runalltests = true; // true to run all tests; false to skip tests and only run those where the 'if' is commented out

    @isTest
    static void test_DeleteSingleTimesheet() {
        if(!runalltests){ return; }

        AstrumTimeTestData testData = new AstrumTimeTestData();
        testData.PopulateTestData();

        List<Time_Sheet__c> timeSheets = new List<Time_Sheet__c>();
        
        Time_Sheet__c tsInstall = new Time_Sheet__c();
        tsInstall.Employee__c = testData.employeesNameIdMap.get('Test Installer');
        tsInstall.For_The_Week_Starting__c = testData.weekStart;
        timeSheets.add(tsInstall);
        
        insert timeSheets;

        List<Time_Sheet_Entry__c> timeSheetEntries = new List<Time_Sheet_Entry__c>();
        
        Time_Sheet_Entry__c tseInstall = new Time_Sheet_Entry__c();
        tseInstall.Start_Time__c = datetime.newInstance(testData.today,time.newInstance(9, 0, 0, 0));
        tseInstall.Start_Time_On_Site__c = tseInstall.Start_Time__c.addHours(1);
        tseInstall.Start_Time_Off_Site__c = tseInstall.Start_Time__c.addHours(9);
        tseInstall.End_Time__c = tseInstall.Start_Time__c.addHours(12);
        tseInstall.Purpose__c = 'Install';
        tseInstall.Timesheet_Purpose__c = testData.timesheetPurposeMap.get('Install');
        tseInstall.Project_Client_Job__c = testData.installProjectsNameIdMap.get('Install Project');
        tseInstall.Half_Hour_Lunch_Break__c = 'Yes';
        tseInstall.Approved__c = true;
        tseInstall.Time_Sheet__c = tsInstall.id;
        timeSheetEntries.add(tseInstall);

        Time_Sheet_Entry__c tseInstall2 = new Time_Sheet_Entry__c();
        tseInstall2.Start_Time__c = datetime.newInstance(testData.today,time.newInstance(9, 0, 0, 0));
        tseInstall2.Start_Time_On_Site__c = tseInstall.Start_Time__c.addHours(1);
        tseInstall2.Start_Time_Off_Site__c = tseInstall.Start_Time__c.addHours(9);
        tseInstall2.End_Time__c = tseInstall.Start_Time__c.addHours(12);
        tseInstall2.Purpose__c = 'Maintenance';
        tseInstall2.Timesheet_Purpose__c = testData.timesheetPurposeMap.get('Maintenance');
        tseInstall2.Project_Client_Job__c = testData.installProjectsNameIdMap.get('Install Project');
        tseInstall2.Half_Hour_Lunch_Break__c = 'Yes';
        tseInstall2.Approved__c = true;
        tseInstall2.Time_Sheet__c = tsInstall.id;
        timeSheetEntries.add(tseInstall2);
        
        insert timeSheetEntries;
        
        // Delete the timesheet
        Test.startTest();
        
        delete tsInstall;
        List<Deleted_Time_Sheet__c> deletedTimesheets = [SELECT Id FROM Deleted_Time_Sheet__c];
        List<Deleted_Time_Sheet_Entry__c> deletedTimesheetEntries = [SELECT Id FROM Deleted_Time_Sheet_Entry__c];

        system.assertEquals(1, deletedTimesheets.size());
        system.assertEquals(2, deletedTimesheetEntries.size());

        Test.stopTest();        
    }
    
    @isTest
    static void test_DeleteMultipleTimesheets() {
        if(!runalltests){ return; }

        AstrumTimeTestData testData = new AstrumTimeTestData();
        testData.PopulateTestData();

        List<Time_Sheet__c> timeSheets = new List<Time_Sheet__c>();
        
        Time_Sheet__c tsInstall = new Time_Sheet__c();
        tsInstall.Employee__c = testData.employeesNameIdMap.get('Test Installer');
        tsInstall.For_The_Week_Starting__c = testData.weekStart;
        timeSheets.add(tsInstall);
        
        Time_Sheet__c tsElec = new Time_Sheet__c();
        tsElec.Employee__c = testData.employeesNameIdMap.get('Test Electrician');
        tsElec.For_The_Week_Starting__c = testData.weekStart;
        timeSheets.add(tsElec);
        
        insert timeSheets;

        List<Time_Sheet_Entry__c> timeSheetEntries = new List<Time_Sheet_Entry__c>();
        
        Time_Sheet_Entry__c tseInstall = new Time_Sheet_Entry__c();
        tseInstall.Start_Time__c = datetime.newInstance(testData.today,time.newInstance(9, 0, 0, 0));
        tseInstall.Start_Time_On_Site__c = tseInstall.Start_Time__c.addHours(1);
        tseInstall.Start_Time_Off_Site__c = tseInstall.Start_Time__c.addHours(9);
        tseInstall.End_Time__c = tseInstall.Start_Time__c.addHours(12);
        tseInstall.Purpose__c = 'Install';
        tseInstall.Timesheet_Purpose__c = testData.timesheetPurposeMap.get('Install');
        tseInstall.Project_Client_Job__c = testData.installProjectsNameIdMap.get('Install Project');
        tseInstall.Half_Hour_Lunch_Break__c = 'Yes';
        tseInstall.Approved__c = true;
        tseInstall.Time_Sheet__c = tsInstall.id;
        timeSheetEntries.add(tseInstall);

        Time_Sheet_Entry__c tseInstall2 = new Time_Sheet_Entry__c();
        tseInstall2.Start_Time__c = datetime.newInstance(testData.today,time.newInstance(9, 0, 0, 0));
        tseInstall2.Start_Time_On_Site__c = tseInstall.Start_Time__c.addHours(1);
        tseInstall2.Start_Time_Off_Site__c = tseInstall.Start_Time__c.addHours(9);
        tseInstall2.End_Time__c = tseInstall.Start_Time__c.addHours(12);
        tseInstall2.Purpose__c = 'Maintenance';
        tseInstall2.Timesheet_Purpose__c = testData.timesheetPurposeMap.get('Maintenance');
        tseInstall2.Project_Client_Job__c = testData.installProjectsNameIdMap.get('Install Project');
        tseInstall2.Half_Hour_Lunch_Break__c = 'Yes';
        tseInstall2.Approved__c = true;
        tseInstall2.Time_Sheet__c = tsInstall.id;
        timeSheetEntries.add(tseInstall2);
        
        Time_Sheet_Entry__c tseElec = new Time_Sheet_Entry__c();
        tseElec.Start_Time__c = datetime.newInstance(testData.today,time.newInstance(9, 0, 0, 0));
        tseElec.Start_Time_On_Site__c = tseElec.Start_Time__c.addHours(1);
        tseElec.Start_Time_Off_Site__c = tseElec.Start_Time__c.addHours(9);
        tseElec.End_Time__c = tseElec.Start_Time__c.addHours(12);
        tseElec.Purpose__c = 'Install';
        tseElec.Timesheet_Purpose__c = testData.timesheetPurposeMap.get('Install');
        tseElec.Project_Client_Job__c = testData.installProjectsNameIdMap.get('Install Project');
        tseElec.Half_Hour_Lunch_Break__c = 'Yes';
        tseElec.Approved__c = true;
        tseElec.Time_Sheet__c = tsElec.id;
        timeSheetEntries.add(tseElec);

        Time_Sheet_Entry__c tseElec2 = new Time_Sheet_Entry__c();
        tseElec2.Start_Time__c = datetime.newInstance(testData.today,time.newInstance(9, 0, 0, 0));
        tseElec2.Start_Time_On_Site__c = tseElec.Start_Time__c.addHours(1);
        tseElec2.Start_Time_Off_Site__c = tseElec.Start_Time__c.addHours(9);
        tseElec2.End_Time__c = tseElec.Start_Time__c.addHours(12);
        tseElec2.Purpose__c = 'Maintenance';
        tseElec2.Timesheet_Purpose__c = testData.timesheetPurposeMap.get('Maintenance');
        tseElec2.Project_Client_Job__c = testData.installProjectsNameIdMap.get('Install Project');
        tseElec2.Half_Hour_Lunch_Break__c = 'Yes';
        tseElec2.Approved__c = true;
        tseElec2.Time_Sheet__c = tsElec.id;
        timeSheetEntries.add(tseElec2);
        
        insert timeSheetEntries;
        
        // Delete the timesheets
        Test.startTest();

        delete timeSheets;
        List<Deleted_Time_Sheet__c> deletedTimesheets = [SELECT Id FROM Deleted_Time_Sheet__c];
        List<Deleted_Time_Sheet_Entry__c> deletedTimesheetEntries = [SELECT Id FROM Deleted_Time_Sheet_Entry__c];

        system.assertEquals(2, deletedTimesheets.size());
        system.assertEquals(4, deletedTimesheetEntries.size());

        Test.stopTest();        
    }
    
    @isTest
    static void test_DeleteMultipleTimesheetEntries() {
        if(!runalltests){ return; }

        AstrumTimeTestData testData = new AstrumTimeTestData();
        testData.PopulateTestData();

        List<Time_Sheet__c> timeSheets = new List<Time_Sheet__c>();
        
        Time_Sheet__c tsInstall = new Time_Sheet__c();
        tsInstall.Employee__c = testData.employeesNameIdMap.get('Test Installer');
        tsInstall.For_The_Week_Starting__c = testData.weekStart;
        timeSheets.add(tsInstall);
        
        Time_Sheet__c tsElec = new Time_Sheet__c();
        tsElec.Employee__c = testData.employeesNameIdMap.get('Test Electrician');
        tsElec.For_The_Week_Starting__c = testData.weekStart;
        timeSheets.add(tsElec);
        
        insert timeSheets;

        List<Time_Sheet_Entry__c> timeSheetEntries = new List<Time_Sheet_Entry__c>();
        
        Time_Sheet_Entry__c tseInstall = new Time_Sheet_Entry__c();
        tseInstall.Start_Time__c = datetime.newInstance(testData.today,time.newInstance(9, 0, 0, 0));
        tseInstall.Start_Time_On_Site__c = tseInstall.Start_Time__c.addHours(1);
        tseInstall.Start_Time_Off_Site__c = tseInstall.Start_Time__c.addHours(9);
        tseInstall.End_Time__c = tseInstall.Start_Time__c.addHours(12);
        tseInstall.Purpose__c = 'Install';
        tseInstall.Timesheet_Purpose__c = testData.timesheetPurposeMap.get('Install');
        tseInstall.Project_Client_Job__c = testData.installProjectsNameIdMap.get('Install Project');
        tseInstall.Half_Hour_Lunch_Break__c = 'Yes';
        tseInstall.Approved__c = true;
        tseInstall.Time_Sheet__c = tsInstall.id;
        timeSheetEntries.add(tseInstall);

        Time_Sheet_Entry__c tseInstall2 = new Time_Sheet_Entry__c();
        tseInstall2.Start_Time__c = datetime.newInstance(testData.today,time.newInstance(9, 0, 0, 0));
        tseInstall2.Start_Time_On_Site__c = tseInstall.Start_Time__c.addHours(1);
        tseInstall2.Start_Time_Off_Site__c = tseInstall.Start_Time__c.addHours(9);
        tseInstall2.End_Time__c = tseInstall.Start_Time__c.addHours(12);
        tseInstall2.Purpose__c = 'Maintenance';
        tseInstall2.Timesheet_Purpose__c = testData.timesheetPurposeMap.get('Maintenance');
        tseInstall2.Project_Client_Job__c = testData.installProjectsNameIdMap.get('Install Project');
        tseInstall2.Half_Hour_Lunch_Break__c = 'Yes';
        tseInstall2.Approved__c = true;
        tseInstall2.Time_Sheet__c = tsInstall.id;
        timeSheetEntries.add(tseInstall2);
        
        Time_Sheet_Entry__c tseElec = new Time_Sheet_Entry__c();
        tseElec.Start_Time__c = datetime.newInstance(testData.today,time.newInstance(9, 0, 0, 0));
        tseElec.Start_Time_On_Site__c = tseElec.Start_Time__c.addHours(1);
        tseElec.Start_Time_Off_Site__c = tseElec.Start_Time__c.addHours(9);
        tseElec.End_Time__c = tseElec.Start_Time__c.addHours(12);
        tseElec.Purpose__c = 'Install';
        tseElec.Timesheet_Purpose__c = testData.timesheetPurposeMap.get('Install');
        tseElec.Project_Client_Job__c = testData.installProjectsNameIdMap.get('Install Project');
        tseElec.Half_Hour_Lunch_Break__c = 'Yes';
        tseElec.Approved__c = true;
        tseElec.Time_Sheet__c = tsElec.id;
        timeSheetEntries.add(tseElec);

        Time_Sheet_Entry__c tseElec2 = new Time_Sheet_Entry__c();
        tseElec2.Start_Time__c = datetime.newInstance(testData.today,time.newInstance(9, 0, 0, 0));
        tseElec2.Start_Time_On_Site__c = tseElec.Start_Time__c.addHours(1);
        tseElec2.Start_Time_Off_Site__c = tseElec.Start_Time__c.addHours(9);
        tseElec2.End_Time__c = tseElec.Start_Time__c.addHours(12);
        tseElec2.Purpose__c = 'Maintenance';
        tseElec2.Timesheet_Purpose__c = testData.timesheetPurposeMap.get('Maintenance');
        tseElec2.Project_Client_Job__c = testData.installProjectsNameIdMap.get('Install Project');
        tseElec2.Half_Hour_Lunch_Break__c = 'Yes';
        tseElec2.Approved__c = true;
        tseElec2.Time_Sheet__c = tsElec.id;
        timeSheetEntries.add(tseElec2);
        
        insert timeSheetEntries;
        
        // Delete the timesheets
        Test.startTest();

        delete timeSheetEntries[0];
        timeSheetEntries.remove(0);
        List<Deleted_Time_Sheet_Entry__c> deletedTimesheetEntries = [SELECT Id FROM Deleted_Time_Sheet_Entry__c];
        system.assertEquals(1, deletedTimesheetEntries.size());

        delete timeSheetEntries;
        deletedTimesheetEntries = [SELECT Id FROM Deleted_Time_Sheet_Entry__c];
        system.assertEquals(4, deletedTimesheetEntries.size());

        Test.stopTest();        
    }
}