src/objects/Employee__c.object
<CustomObject>
    <description>AstrumTIME - An Astrum Solar Employee Record for the AstumTIME app</description>
    <fields>
        <fullName>Employee_PIN__c</fullName>
        <label>Employee PIN</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/EmployeePINGenerator.cls
public with sharing class EmployeePINGenerator {
	
    // The extension constructor initializes the private member
    // variable mysObject by using the getRecord method from the standard
    // controller.
    Employee__c emp;
    private ApexPages.StandardController controller;

    public EmployeePINGenerator(ApexPages.StandardController stdController) {    
        this.controller = stdController;
        emp = (Employee__c)stdController.getRecord();
    }

    public PageReference getRandomInt()
    {
        emp.Employee_PIN__c =  String.valueOf(Math.round(Math.random() * (9999 - 1099)) + 1099);
        update emp;
        return controller.cancel();
    }
}