src/objects/Employee__c.object
<CustomObject>
    <description>AstrumTIME - An Astrum Solar Employee Record for the AstumTIME app</description>
    <fields>
        <fullName>Employee_Number__c</fullName>
        <description>Insperity Employee Number</description>
        <externalId>true</externalId>
        <inlineHelpText>Insperity Employee Number</inlineHelpText>
        <label>Employee Number</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Home_Office_Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A lookup to the office location to have information about potential CA overtime rules</description>
        <label>Home Office Location</label>
        <referenceTo>Office_Location__c</referenceTo>
        <relationshipLabel>Employees (Office Location)</relationshipLabel>
        <relationshipName>Employees1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Office_Location__c.object
<CustomObject>
    <label>Office Location</label>
    <nameField>
        <label>Office Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/State__c.object
<CustomObject>
    <description>Represents a State</description>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time_Sheet__c.object
<CustomObject>
    <description>AstrumTIME - Employee Time Sheet</description>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Employee Who is Submitting This Time Sheet</description>
        <inlineHelpText>Employee Who is Submitting This Time Sheet</inlineHelpText>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Time Sheets</relationshipLabel>
        <relationshipName>Time_Sheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time Sheet</label>
    <nameField>
        <displayFormat>TimeSheet-{000000}</displayFormat>
        <label>Time Sheet Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Timesheet_Payroll_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Timesheet Payroll Entries</relationshipLabel>
        <relationshipName>Timesheet_Payroll_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Timesheet Payroll Entry</label>
    <nameField>
        <displayFormat>TPE-{000000}</displayFormat>
        <label>Timesheet Payroll Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheet Payroll Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TimesheetEntryPostController.cls
/* MODIFICATION HISTORY
 * 04/03/2015 SZ - Update code to retrieve the correct office state based on Home_Office_c changing to a lookup instead of a picklist
 * 04/06/2015 SZ - Update code to take the entry state into account based on the Project_Client_Job__c field
 */
public with sharing class TimesheetEntryPostController {

	
    public Time_Sheet__c timeSheet{get;set;}     
    public List<TimeSheet_Payroll_Entry__c> payrollEntries{get;set;}
    

    public TimesheetEntryPostController(ApexPages.StandardController stdController) {
        this.timeSheet = (Time_Sheet__c)stdController.getRecord();
        // SZ: Change query to retrieve State__c from the lookup
        timeSheet = [Select Id, Employee__r.Home_Office_Location__r.State__c,Employee__r.Name,Employee__r.Employee_Number__c from Time_Sheet__c where id = :timeSheet.Id];
        // SZ: Refactor to use the TimesheetService class
        payrollEntries = TimesheetService.ProcessTimesheets(timeSheet);
    }

    public PageReference PostEntries()
	{		
		// SZ: Refactor to use the TimesheetService
		TimesheetService.ProcessPost(this.timeSheet, payrollEntries);

		return new PageReference('/' + timeSheet.Id );
	}
}