src/objects/Employee__c.object
<CustomObject>
    <description>AstrumTIME - An Astrum Solar Employee Record for the AstumTIME app</description>
    <fields>
        <fullName>Employee_Number__c</fullName>
        <description>Insperity Employee Number</description>
        <externalId>true</externalId>
        <inlineHelpText>Insperity Employee Number</inlineHelpText>
        <label>Employee Number</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Home_Office_Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>A lookup to the office location to have information about potential CA overtime rules</description>
        <label>Home Office Location</label>
        <referenceTo>Office_Location__c</referenceTo>
        <relationshipLabel>Employees (Office Location)</relationshipLabel>
        <relationshipName>Employees1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Install_Project__c.object
<CustomObject>
    <description>AstrumTIME - Installation Project For the Bonus Program</description>
    <fields>
        <fullName>Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Order</label>
        <referenceTo>rstk__wocst__c</referenceTo>
        <relationshipLabel>Install Projects</relationshipLabel>
        <relationshipName>Install_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Install Project</label>
    <nameField>
        <label>Install Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Install Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Office_Location__c.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <description>Two-letter state code</description>
        <inlineHelpText>Two-letter state code</inlineHelpText>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>Office Location</label>
    <nameField>
        <label>Office Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/State__c.object
<CustomObject>
    <description>Represents a State</description>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time_Sheet__c.object
<CustomObject>
    <description>AstrumTIME - Employee Time Sheet</description>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Employee Who is Submitting This Time Sheet</description>
        <inlineHelpText>Employee Who is Submitting This Time Sheet</inlineHelpText>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Time Sheets</relationshipLabel>
        <relationshipName>Time_Sheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time Sheet</label>
    <nameField>
        <displayFormat>TimeSheet-{000000}</displayFormat>
        <label>Time Sheet Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time_Sheet_Entry__c.object
<CustomObject>
    <description>AstrumTIME - A Single Entry For An Astrum Solar Time Sheet</description>
    <fields>
        <fullName>End_Time__c</fullName>
        <description>End Time</description>
        <inlineHelpText>End Time</inlineHelpText>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Entry_Date__c</fullName>
        <formula>DATEVALUE(Start_Time__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Entry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Labor_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Labor Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Posted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Posted to Payroll Entry</description>
        <label>Posted ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Client_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Which Project Are You Working On?</description>
        <inlineHelpText>Which Project Are You Working On?</inlineHelpText>
        <label>Project/Client/Job</label>
        <referenceTo>Install_Project__c</referenceTo>
        <relationshipLabel>Time Sheet Entries</relationshipLabel>
        <relationshipName>Time_Sheet_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>Start Time</description>
        <inlineHelpText>Start Time</inlineHelpText>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Time_Sheet__c</fullName>
        <description>The Astrum Solar Time Sheet Containing this Entry</description>
        <inlineHelpText>The Astrum Solar Time Sheet Containing this Entry</inlineHelpText>
        <label>Time Sheet</label>
        <referenceTo>Time_Sheet__c</referenceTo>
        <relationshipLabel>Time Sheet Entries</relationshipLabel>
        <relationshipName>Time_Sheet_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Timesheet_Purpose__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Timesheet Purpose</label>
        <referenceTo>Timesheet_Purpose__c</referenceTo>
        <relationshipLabel>Time Sheet Entries</relationshipLabel>
        <relationshipName>Time_Sheet_Entries</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Hours__c</fullName>
        <description>Total Hours For This Entry</description>
        <inlineHelpText>Total Hours For This Entry</inlineHelpText>
        <label>Total Hours</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Time Sheet Entry</label>
    <nameField>
        <displayFormat>Entry-{0000000}</displayFormat>
        <label>Time Sheet Entry</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Sheet Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Timesheet_Purpose__c.object
<CustomObject>
    <fields>
        <fullName>DE_Code__c</fullName>
        <description>DE Code Assignment</description>
        <label>DE Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Timesheet Purpose</label>
    <nameField>
        <label>Timesheet Purpose Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Timesheet Purposes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TimeSheetLaborEntryEoMProcessor.cls
/* FILE: TimeSheetLaborEntryEoMProcessor.cls
 * AUTHOR: Pavitra Burla
 * DATE: Feb 10, 2015
 * PURPOSE: Create Labor Entries for corresponding Time Sheet Entries for EoM processsing
 * MODIFICATION HISTORY
 * 04/17/2015 SZ - Updated the query to account for the new way of determining the State 
 * 06/23/2015 PB - Added filter for CreatedDate to the query
 */
global class TimeSheetLaborEntryEoMProcessor extends TimeSheetLaborEntryProcessor implements Schedulable{
    
    public override String getQuery(){
        
        String endOfWeek =  String.valueof(date.today().toStartOfMonth().addDays(16));
		String startOfWeek =  String.valueof(date.today().toStartOfWeek().addDays(1));		
		        
        //String query = 'SELECT End_Time__c,Entry_Date__c,Id,Name,Posted__c,Project_Client_Job__r.Work_Order__c, Project_Client_Job__r.Work_Order__r.rstk__wocst_qtyreq__c, Project_Client_Job__r.Work_Order__r.rstk__externalid__c ,Start_Time__c,Timesheet_Purpose__r.name, Timesheet_Purpose__r.DE_Code__c ,Time_Sheet__r.Employee__c,Time_Sheet__r.Employee__r.Home_Office_Location__c,Total_Hours__c,Time_Sheet__r.Employee__r.Employee_Number__c';
        String query = 'SELECT End_Time__c,Entry_Date__c,Id,Name,Posted__c,Project_Client_Job__r.Work_Order__c, Project_Client_Job__r.Work_Order__r.rstk__wocst_qtyreq__c, Project_Client_Job__r.Work_Order__r.rstk__externalid__c , Start_Time__c,Timesheet_Purpose__r.name, Timesheet_Purpose__r.DE_Code__c ,Time_Sheet__r.Employee__c, Time_Sheet__r.Employee__r.Home_Office_Location__r.State__c,Total_Hours__c,Time_Sheet__r.Employee__r.Employee_Number__c';
        query+= ' FROM Time_Sheet_Entry__c';
        query+= ' WHERE CreatedDate = LAST_N_DAYS:45';
        query+= ' AND Posted__c = true';
        query+= ' AND Entry_Date__c >=' + startOfWeek;
        query+= ' AND Entry_Date__c <' + endOfWeek;
        query+= ' AND Timesheet_Purpose__r.DE_Code__c = \'9005\'';
        query+= ' AND Labor_Processed__c = false';
        query+= ' AND Total_Hours__c > 0';
        query+= ' ORDER BY Time_Sheet__r.Employee__r.Employee_Number__c, Entry_Date__c';
        
        return query;
        
    }    

}