src/objects/Employee__c.object
<CustomObject>
    <description>AstrumTIME - An Astrum Solar Employee Record for the AstumTIME app</description>
    <fields>
        <fullName>Hourly_Rate_String__c</fullName>
        <description>Hourly rate string</description>
        <inlineHelpText>Hourly rate string</inlineHelpText>
        <label>Hourly Rate String</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hourly_Rate__c</fullName>
        <description>Employee&apos;s Standard Hourly Rate</description>
        <inlineHelpText>Employee&apos;s Standard Hourly Rate</inlineHelpText>
        <label>Hourly Rate</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Overtime_Hourly_Rate_String__c</fullName>
        <description>Overtime Hourly Rate String</description>
        <inlineHelpText>Overtime Hourly Rate String</inlineHelpText>
        <label>Overtime Hourly Rate String</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Overtime_Rate__c</fullName>
        <description>Overtime Rate in $/hr is 1.5 Standard Hourly Rate</description>
        <formula>Hourly_Rate__c * 1.5</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Overtime Rate in $/hr is 1.5 Standard Hourly Rate</inlineHelpText>
        <label>Overtime Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AstrumTime_Employee_Trigger_Utility.cls
public with sharing class AstrumTime_Employee_Trigger_Utility {
	
	public static void checkForDuplicateEmployeeName(List<Employee__c> newEmployees) {

		List<Employee__c> currentEmployees = [select id, name from Employee__c];

		for (Employee__c tempNewEmployee : newEmployees) {
			for (Employee__c tempCurrentEmployee : currentEmployees) {

				Boolean diffId = tempNewEmployee.Id != tempCurrentEmployee.Id;
				Boolean sameName = tempNewEmployee.Name == tempCurrentEmployee.Name;
				
				if (diffId && sameName) {					
					tempNewEmployee.Name.addError('Duplicate employee names are not allowed.');
				}				
			}	
		}
	}	
	
	public static void copyHourlyRates(List<Employee__c> newEmployees) {

		for (Employee__c tempNewEmployee : newEmployees) {
			// copy hourly rate
			tempNewEmployee.Hourly_Rate_String__c = getValue(tempNewEmployee.Hourly_Rate__c);
			
			// copy overtime rate
			tempNewEmployee.Overtime_Hourly_Rate_String__c = getValue(tempNewEmployee.Overtime_Rate__c);
		}		
	}	
	
	private static String getValue(Decimal theField) {
		String result = null;
		
		if (theField != null) {
			result = theField.toPlainString();
		}
		else {
			result = '0.00';
		}
		
		return result;	
	}
}