src/objects/Enphase_Pull_Log__c.object
<CustomObject>
    <description>Stores audit of production data pulled from enphase on a monthly basis.</description>
    <fields>
        <fullName>Apr_Prod__c</fullName>
        <label>April Production (Wh)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Batch_Date__c</fullName>
        <description>Date the back was run</description>
        <label>Batch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Feb_Prod__c</fullName>
        <label>February Production (Wh)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Installed_System__c</fullName>
        <label>Installed System</label>
        <referenceTo>Installed_System__c</referenceTo>
        <relationshipLabel>Enphase Pull Logs</relationshipLabel>
        <relationshipName>Enphase_Pull_Logs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Jan_Prod__c</fullName>
        <label>January Production (Wh)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Jun_Prod__c</fullName>
        <label>June Production (Wh)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mar_Prod__c</fullName>
        <label>March Production (Wh)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>May_Prod__c</fullName>
        <label>May Production (Wh)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_of_Year__c</fullName>
        <description>Start of the production year</description>
        <label>Start of Year</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Enphase Pull Log</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Pull ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enphase Pull Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Installed_System__c.object
<CustomObject>
    <fields>
        <fullName>Enphase_ID__c</fullName>
        <externalId>true</externalId>
        <label>Enphase ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Generation_Start_Date__c</fullName>
        <label>Generation Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Monthly_Production_Factor_Apr__c</fullName>
        <label>Monthly Production Factor Apr</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Monthly_Production_Factor_Aug__c</fullName>
        <label>Monthly Production Factor Aug</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Monthly_Production_Factor_Dec__c</fullName>
        <label>Monthly Production Factor Dec</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Monthly_Production_Factor_Feb__c</fullName>
        <description>Monthly Production Factor Feb</description>
        <label>Monthly Production Factor Feb</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Monthly_Production_Factor_Jan__c</fullName>
        <description>Monthly Production Factor Jan</description>
        <label>Monthly Production Factor Jan</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Monthly_Production_Factor_Jul__c</fullName>
        <label>Monthly Production Factor Jul</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Monthly_Production_Factor_Jun__c</fullName>
        <label>Monthly Production Factor Jun</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Monthly_Production_Factor_Mar__c</fullName>
        <label>Monthly Production Factor Mar</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Monthly_Production_Factor_May__c</fullName>
        <label>Monthly Production Factor May</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Monthly_Production_Factor_Nov__c</fullName>
        <label>Monthly Production Factor Nov</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Monthly_Production_Factor_Oct__c</fullName>
        <label>Monthly Production Factor Oct</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Monthly_Production_Factor_Sep__c</fullName>
        <label>Monthly Production Factor Sep</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>PM_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Astrum PM 2.0 Project</description>
        <inlineHelpText>Astrum PM 2.0 Project</inlineHelpText>
        <label>PM 2.0 Project</label>
        <referenceTo>PM_Project__c</referenceTo>
        <relationshipLabel>Installed Systems</relationshipLabel>
        <relationshipName>Installed_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Production_Estimate_Started__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Production Estimate Started</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Milestone1_Project__c</referenceTo>
        <relationshipLabel>Installed Systems</relationshipLabel>
        <relationshipName>Installed_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Installed Systems</relationshipLabel>
        <relationshipName>Installed_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quoted_System_Design__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quoted System Design</label>
        <referenceTo>System_Design_Quote__c</referenceTo>
        <relationshipLabel>Installed Systems</relationshipLabel>
        <relationshipName>Installed_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Installed System</label>
    <nameField>
        <displayFormat>SYS-{000000}</displayFormat>
        <label>Installed System Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installed Systems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Monthly_Production__c.object
<CustomObject>
    <description>Stores Monthly Production data from Enphase, production guarantees, and GATS/GIS reported production</description>
    <fields>
        <fullName>Astrum_Estimated__c</fullName>
        <inlineHelpText>Monthly Production based on Astrum estimates</inlineHelpText>
        <label>Astrum Estimated (kWh)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Enphase_kWh__c</fullName>
        <inlineHelpText>Enphase Production</inlineHelpText>
        <label>Enphase (kWh)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Installed_System__c</fullName>
        <label>Installed System</label>
        <referenceTo>Installed_System__c</referenceTo>
        <relationshipLabel>Monthly Production</relationshipLabel>
        <relationshipName>Monthly_Production</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Production_Guarantee__c</fullName>
        <label>Production Guarantee (kWh)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_of_Month__c</fullName>
        <label>Start of Month</label>
        <type>Date</type>
    </fields>
    <label>Monthly Production</label>
    <nameField>
        <displayFormat>MP-{0000000}</displayFormat>
        <label>Monthly Production ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Production</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PM_Project__c.object
<CustomObject>
    <description>Astrum PM 2.0 Project Object</description>
    <fields>
        <fullName>Approved_Utility_Interconnect_Part_2__c</fullName>
        <label>Approved Utility Interconnect Part 2</label>
        <type>Date</type>
    </fields>
    <label>PM Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PM Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <description>AstrumPM/AstrumCRM - Each account can have one or more properties.  A property is defined by its street address.</description>
    <fields>
        <fullName>Snow_De_Rate_kWh_y_kW__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Snow De-Rate</description>
        <label>Snow De-Rate (kWh/y/kW)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Address 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PVWatts_Production_Estimates__c.object
<CustomObject>
    <description>This object stores PVWatts monthly production estimates based on projected annual production.</description>
    <fields>
        <fullName>Annual_Total__c</fullName>
        <label>Annual Total</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>April__c</fullName>
        <label>April</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>August__c</fullName>
        <label>August</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>December__c</fullName>
        <label>December</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>February__c</fullName>
        <label>February</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Installed_System__c</fullName>
        <label>Installed System</label>
        <referenceTo>Installed_System__c</referenceTo>
        <relationshipLabel>PVWatts Production Estimates</relationshipLabel>
        <relationshipName>PVWatts_Production_Estimates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>January__c</fullName>
        <label>January</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>July__c</fullName>
        <label>July</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>June__c</fullName>
        <label>June</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>March__c</fullName>
        <label>March</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>May__c</fullName>
        <label>May</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>November__c</fullName>
        <label>November</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>October__c</fullName>
        <label>October</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>September__c</fullName>
        <label>September</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>PVWatts Production Estimates</label>
    <nameField>
        <displayFormat>PVW-{0000000}</displayFormat>
        <label>PVWatts ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PVWatts Production Estimates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/System_Design_Quote__c.object
<CustomObject>
    <description>AstrumCRM - System Design Quote.  Each System Design can have one or more System Design Quotes.  Each quote provides the sales consultant with the ability to adjust the negotiated price of the System Design based on the Calculated System Price.  Opportunities must choose a winning System Design Quote in order to close.</description>
    <fields>
        <fullName>System_Design__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>System Design</label>
        <referenceTo>System_Design__c</referenceTo>
        <relationshipLabel>System Design Quotes</relationshipLabel>
        <relationshipName>System_Design_Quotes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_System_Size_kW__c</fullName>
        <label>Total System Size (kW)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>System Design Quote</label>
    <nameField>
        <displayFormat>SDQ-{0}</displayFormat>
        <label>System Design Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Design Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EnphaseMonthlyProductionPullBatch.cls
/* FILE: EnphaseMonthlyProductionPullBatch.cls
 * AUTHOR: Rohit Jain
 * DATE: May 14, 2013
 * PURPOSE: Collects enphase production data and updates database
 *   to invoke: EnphaseMonthlyProductionPullBatch batch = new EnphaseMonthlyProductionPullBatch();
 *              Id batchId = Database.executeBatch(batch, 10); //must be 10 - callout governor limit
 *   enphase limits calls to 25 at a time, then throws 503 errors
 * MODIFICATION HISTORY 
 */
global class EnphaseMonthlyProductionPullBatch implements Database.Batchable<sObject>,Database.AllowsCallouts,Schedulable,Database.Stateful{
    public String query;
    private String batchErrors = '';
    private Integer batchNumber = 0;

    global Database.QueryLocator start(Database.BatchableContext BC){
        query = 'SELECT Id, Generation_Start_date__C,Enphase_ID__c, Quoted_System_Design__r.System_Design__r.Total_System_Size_kW__c,Quoted_System_Design__r.System_Design__r.Total_Projected_Annual_Output_kWh_y__c  ' ;
        query = query + '  ,Property__r.Snow_De_Rate_kWh_y_kW__c, Monthly_Production_Factor_Jan__c ,Monthly_Production_Factor_Feb__c,Monthly_Production_Factor_Mar__c,Monthly_Production_Factor_Apr__c,Monthly_Production_Factor_May__c  ' ;
        query = query + '  ,Monthly_Production_Factor_Jun__c ,Monthly_Production_Factor_Jul__c,Monthly_Production_Factor_Aug__c,Monthly_Production_Factor_Sep__c,Monthly_Production_Factor_Oct__c ,Monthly_Production_Factor_Nov__c ,Monthly_Production_Factor_Dec__c  ' ;
        query = query + ' , PM_Project__r.Approved_Utility_Interconnect_Part_2__c ' ;
        query = query + ' , PM_Project__c , Project__c,production_estimate_started__c ' ;
        query = query + '  FROM Installed_System__c WHERE Enphase_ID__c <> NULL AND Id NOT IN  ' ; 
        query = query + ' (SELECT Installed_System__c FROM Enphase_Pull_Log__c WHERE Batch_Date__c = THIS_MONTH) ' ;
              
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope){
        
        String status; 
        List<Monthly_Production__c> productionToUpdate = new List<Monthly_Production__c>();   
        List<Enphase_Pull_Log__c> pullLogs = new List<Enphase_Pull_Log__c>();   
        List<Installed_System__c> installSystemUpdate = new List<Installed_System__c>();            
        for(sObject s : scope)
        {
          
          Installed_System__c sys = (Installed_System__c)s;
          status =       processSystem(sys,productionToUpdate  ,pullLogs,installSystemUpdate   );             
                
        }   
        
        if (!pullLogs.isEmpty()) {
          insert pullLogs;
        }
    
        if (!productionToUpdate.isEmpty()) {
          upsert productionToUpdate;
        }    
        
        if (!installSystemUpdate   .isEmpty()) {
          update installSystemUpdate;
        }   
    }
    
    global void execute(SchedulableContext SC) {
      EnphaseMonthlyProductionPullBatch  batch = new EnphaseMonthlyProductionPullBatch ();
      Id batchId = Database.executeBatch(batch, 10);
    }
    
    global void finish(Database.BatchableContext bc) {
        
        if (batchErrors != '') {
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setTargetObjectId(UserInfo.getUserId());
            mail.setSubject('Enphase Monthly Production Pull Batch Errors');
            mail.setPlainTextBody(batchErrors);
            mail.setSaveAsActivity(false);
            Messaging.sendEmail(new Messaging.Email[] { mail }, false);     
        }
        
        if (batchNumber > 0) {
            //EnphaseBatchHelper.runNextPull(lastEnphaseId);
        }
        
    } 
    
    public String processSystem(Installed_System__c sys, List<Monthly_Production__c> productionToUpdate   ,List<Enphase_Pull_Log__c> pullLogs ,List<Installed_System__c> installSystemUpdate ) {
    
        batchNumber++;
        Date thisMonthStart = System.today().toStartOfMonth();
        Date lastMonthStart = thisMonthStart.addMonths(-1);
        Boolean estimateStarted = sys.production_estimate_started__c;
        Boolean sysUpdated = false;
        
        System.debug('*processSystem - '+ Sys.Enphase_ID__c );     
    
        //get the currently monthly production    
        List<Monthly_Production__c> monthlyProduction = 
          [SELECT Id, Installed_System__c, Start_of_Month__c, Enphase_kWh__c, Production_Guarantee__c, Astrum_Estimated__c
          FROM Monthly_Production__c
          WHERE Installed_System__c = :sys.Id];        
        
        Map<Date, Monthly_Production__c> productionMap = new Map<Date, Monthly_Production__c>(); 
    
        //put into installed system, date map
        for (Monthly_Production__c mp : monthlyProduction) {
          productionMap.put(mp.Start_of_Month__c.toStartOfMonth(), mp); 
        }
        
        EnphaseAPI api = new EnphaseAPI();   
        Integer recordNumber = 0;
        try {
            
          //get lifetime production by month from Enphase
          List<EnphaseAPI.EnphaseProduction> production;
          if(!Test.isRunningTest())
          {
              production = api.energy_lifetime_monthly(Integer.valueOf(sys.Enphase_ID__c));
          }
          else
          {
              production = new List<EnphaseAPI.EnphaseProduction>();             
              EnphaseAPI.EnphaseProduction prod = new  EnphaseAPI.EnphaseProduction();
              
              prod.productiondate = System.now() - 40 ;
              prod.wattHours  = 0;
              production.add(prod);  
              
              EnphaseAPI.EnphaseProduction prod1 = new  EnphaseAPI.EnphaseProduction();
              prod1.productiondate = System.now();
              prod1.wattHours  = 0;
              production.add(prod1);  
          }    
          
          if (production.isEmpty()) {
            System.debug('*processSystem - '+ 'No Production Data' );  
            return 'No Production Data';
          }
         
          
          if(sys.Generation_Start_Date__C == null )
          {
              sys.Generation_Start_date__C =  production[0].productionDate.date();
              sysUpdated  = true;
          }    
          
          
          //calculate production estimates / guarantees
          List<PVWatts_Production_Estimates__c> pvw = 
            [SELECT January__c, February__c, March__c, April__c, May__c, June__c,
            July__c, August__c, September__c, October__c, November__c, December__c, Annual_Total__c
            FROM PVWatts_Production_Estimates__c
            WHERE Installed_System__c = :sys.Id
            ORDER BY LastModifiedDate DESC 
            LIMIT 1];
    
          Map<Date, ProductionMonthlyGuaranteeCalculator.ProductionGuarantee> guaranteeMap 
            = new Map<Date, ProductionMonthlyGuaranteeCalculator.ProductionGuarantee>();
    
          if (!pvw.isEmpty()) {
            System.debug('*pvw[0]- '+pvw[0]);  
            List<ProductionMonthlyGuaranteeCalculator.ProductionGuarantee> guar 
              = ProductionMonthlyGuaranteeCalculator.getProductionGuarantee (
                pvw[0],
                sys,              // Installed System
                production[0].productionDate.date()  // Production start Date
              );
    
            for (ProductionMonthlyGuaranteeCalculator.ProductionGuarantee g : guar) {
              guaranteeMap.put(g.startOfMonth, g);
            }
          }
          
          Enphase_Pull_Log__c accum = new Enphase_Pull_Log__c();
          
          for (EnphaseAPI.EnphaseProduction prod : production) {
            
                
            Integer year = prod.productionDate.year();
            if (accum.Start_of_Year__c == null) {
              accum.Start_of_Year__c = Date.newInstance(year, 1, 1);
              accum.Installed_System__c = sys.Id;
              accum.Batch_Date__c = System.today();
            } else if (year != accum.Start_of_Year__c.year()) {
              pullLogs.add(accum);
              accum = new Enphase_Pull_Log__c();
            }
            Integer month = prod.productionDate.month();
           
            if (month == 1) {
              accum.Jan_Prod__c = prod.wattHours;
            } else if (month == 2) {
              accum.Feb_Prod__c = prod.wattHours;
            } else if (month == 3) {
              accum.Mar_Prod__c = prod.wattHours;
            } else if (month == 4) {
              accum.Apr_Prod__c = prod.wattHours;
            } else if (month == 5) {
              accum.May_Prod__c = prod.wattHours;
            } else if (month == 6) {
              accum.Jun_Prod__c = prod.wattHours;
            } else if (month == 7) {
              accum.Jul_Prod__c = prod.wattHours;
            } else if (month == 8) {
              accum.Aug_Prod__c = prod.wattHours;
            } else if (month == 9) {
              accum.Sep_Prod__c = prod.wattHours;
            } else if (month == 10) {
              accum.Oct_Prod__c = prod.wattHours;
            } else if (month == 11) {
              accum.Nov_Prod__c = prod.wattHours;
            } else if (month == 12) {
              accum.Dec_Prod__c = prod.wattHours;
            }
              
            //update monthly production, if not this month
            if (prod.productionDate.date() < thisMonthStart) {
              Monthly_Production__c mp = productionMap.get(prod.productionDate.date().toStartOfMonth()); 
              if (mp == null) {
                mp = new Monthly_Production__c (
                  Installed_System__c = sys.Id,
                  Start_of_Month__c = prod.productionDate.date().toStartOfMonth()
                );
               // System.debug('*mp - '+mp  ); 
                productionMap.put(prod.productionDate.date(), mp);
              } 
              
              Boolean changed = false;
              
              if (mp.Enphase_kWh__c != prod.kilowattHours) {
                mp.Enphase_kWh__c = prod.kilowattHours;
                
                changed = true;
              }
              
              ProductionMonthlyGuaranteeCalculator.ProductionGuarantee pg 
                = guaranteeMap.get(mp.Start_of_Month__c.toStartOfMonth());
              
              //System.debug('*pg  - '+pg );   
              if (pg != null) {
              
                if (mp.Production_Guarantee__c != pg.guarantee_kWh) {
                  mp.Production_Guarantee__c = pg.guarantee_kWh;
                  changed = true;
                }
                
                
                //System.debug('*pg.estimate_kWh- '+pg.estimate_kWh  ); 
                //System.debug('*prod.kilowattHours- '+prod.kilowattHours  ); 
                //System.debug('*prod.firstfullmonth- '+ prod.firstfullmonth  ); 
                if(prod.FirstFullMOnth == null)
                {
                  prod.FirstFullMOnth = false;
                }
                if (mp.Astrum_Estimated__c != pg.estimate_kWh && (estimateStarted || prod.FirstFullMOnth)) {                    
                  estimateStarted = true;
                  mp.Astrum_Estimated__c = pg.estimate_kWh;
                  changed = true;
                }
              
              }
              
              if (changed == true) {
                productionToUpdate.add(mp);
              }
              
            }
            
          }
          if(sys.production_estimate_started__c != estimateStarted )
          {
              sys.production_estimate_started__c =  estimateStarted ;
              sysUpdated = true;  
          }  
          if (sysUpdated )
          {
            installSystemUpdate.add(sys); 
          }
            
          if (accum.Start_of_Year__c != null) {
            pullLogs.add(accum);
          }
            
        } 
        catch (NullPointerException e) {
          batchErrors += 'Batch #' + batchNumber + ' Record #' + recordNumber + ' ' + sys.Enphase_ID__c + ' ' + sys.Id + ' \n' + 'Production Factor not defined for Installed System' + ' \n' + e.getStackTraceString() + '\n\n';
        }  
        catch (Exception e) {
          batchErrors += 'Batch #' + batchNumber + ' Record #' + recordNumber + ' ' + sys.Enphase_ID__c + ' ' + sys.Id + ' \n' + e.getMessage() + ' \n' + e.getStackTraceString() + '\n\n';
        }          
     
        return 'Success';    
        
      }
}