src/objects/Event.object
<CustomObject>
    <recordTypes>
        <fullName>Sales_Visit_Onsite</fullName>
        <active>true</active>
        <description>Sales Visit Onsite - in person</description>
        <label>Sales Visit Onsite</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Portal_Referral__c.object
<CustomObject>
    <description>Referrals from the Partner Program website</description>
    <fields>
        <fullName>Detail__c</fullName>
        <label>Detail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Portal Referrals</relationshipLabel>
        <relationshipName>Portal_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Portal Referrals</relationshipLabel>
        <relationshipName>Portal_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>OPEN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QUALIFIED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Portal Referral</label>
    <nameField>
        <displayFormat>REF-{000000}</displayFormat>
        <label>Portal Referral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EventPortalReferralTriggerTest.cls
/* FILE: EventPortalReferralTriggerTest.cls
 * AUTHOR: Tino Mattheou
 * DATE: September 6, 2012
 * PURPOSE: test class for EventPortalReferral trigger
 * MODIFICATION HISTORY
 *    12/01/14  DK  Added assertion statements to test EventTriggerHandler.setOriginalDateFields()
 */
 
@isTest(SeeAllData = true)
public class EventPortalReferralTriggerTest {

    static testMethod void opp_completeSalesVisit_statusChanged() {
                
        Portal_Referral__c referral = OpportunityPortalReferralTriggerTest.createReferralWithOpp();
        
        RecordType salesVisit = [SELECT Id FROM RecordType 
            WHERE SObjectType='Event' AND DeveloperName = 'Sales_Visit_Onsite'];
        
        Event evt = new Event(
            RecordTypeId = salesVisit.Id,
            WhatId = referral.Opportunity__c,
            StartDateTime = Datetime.now().addHours(-2),
            EndDateTime = Datetime.now().addHours(-1)
        );
        insert evt;
        
        Opportunity opp = new Opportunity (Id = referral.Opportunity__c, StageName = 'Qualified');
        update opp;
            
        referral = [SELECT Id, Lead__c, Opportunity__c, Status__c, Detail__c
            FROM Portal_Referral__c
            WHERE Id = :referral.Id];
            
        System.assertEquals(PortalReferralStatus.Qualified_STATUS, referral.Status__c);
        System.assertEquals('Evaluation in Progress', referral.Detail__c);      
        
        Test.startTest();
        
        evt.Completed__c = true;
        update evt;
        
        Test.stopTest();

        referral = [SELECT Id, Lead__c, Status__c, Detail__c
            FROM Portal_Referral__c
            WHERE Id = :referral.Id];
            
        System.assertEquals(PortalReferralStatus.QUALIFIED_STATUS, referral.Status__c);
        System.assertEquals('Sales Call Completed', referral.Detail__c);
        
        //[DK] Test EventTriggerHandler.setOriginalDateFields()
        evt = [SELECT Original_Start_Date_Time__c, Original_End_Date_Time__c, StartDateTime, EndDateTime FROM Event WHERE ID = :evt.ID];
        System.assertEquals(evt.StartDateTime, evt.Original_Start_Date_Time__c);
        System.assertEquals(evt.EndDateTime, evt.Original_End_Date_Time__c);
    }

}