src/objects/Installed_System__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Installed Systems</relationshipLabel>
        <relationshipName>Installed_Systems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Enphase_ID__c</fullName>
        <externalId>true</externalId>
        <label>Enphase ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Installed System</label>
    <nameField>
        <displayFormat>SYS-{000000}</displayFormat>
        <label>Installed System Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installed Systems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EnphaseBatchProcessTest.cls
/* FILE: EnphaseBatchTest.cls
 * AUTHOR: Rohit Jain
 * DATE: April 26, 2012
 * PURPOSE: Test class for EnphaseBatch processes
 * MODIFICATION HISTORY:
 *
 */

@isTest
public class EnphaseBatchProcessTest {
    /*
    static testMethod void runProductionPullBatch() {
        
        Account customer = new Account ( Name = 'Test Customer' );
        insert customer;
        
        Installed_System__c sys = new Installed_System__c (
            Account__c = customer.Id,
            Enphase_ID__c = '12345'
        );
        insert sys;
                
        EnphaseBatchProductionPull batch = new EnphaseBatchProductionPull();
                
        Test.startTest();
        Id batchId = Database.executeBatch(batch, 10);
        Test.stopTest();      
        
    }

    static testMethod void runProductionAlertsPullBatch() {
        
        Account customer = new Account ( Name = 'Test Customer' );
        insert customer;
        
        Installed_System__c sys = new Installed_System__c (
            Account__c = customer.Id,
            Enphase_ID__c = '12345'
        );
        insert sys;
                
        EnphaseBatchProductionAlertsPull batch = new EnphaseBatchProductionAlertsPull();
                
        Test.startTest();
        Id batchId = Database.executeBatch(batch, 10);
        Test.stopTest();      
        
    } */
}