src/objects/Installed_System__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Installed Systems</relationshipLabel>
        <relationshipName>Installed_Systems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Enphase_ID__c</fullName>
        <externalId>true</externalId>
        <label>Enphase ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Installed System</label>
    <nameField>
        <displayFormat>SYS-{000000}</displayFormat>
        <label>Installed System Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installed Systems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EnphaseBatchTest.cls
/* FILE: EnphaseBatchTest.cls
 * AUTHOR: Tino Mattheou
 * DATE: October 25, 2012
 * PURPOSE: Test class for EnphaseBatchController
 * MODIFICATION HISTORY:
 *
 */

@isTest
public class EnphaseBatchTest {

	static testMethod void runBatch() {
		
		Account customer = new Account ( Name = 'Test Customer' );
		insert customer;
		
		Installed_System__c sys = new Installed_System__c (
			Account__c = customer.Id,
			Enphase_ID__c = '12345'
		);
		insert sys;
		
		Test.startTest();
		
		Test.setCurrentPage(Page.EnphaseBatch);
		EnphaseBatchController controller = new EnphaseBatchController();

		System.assertNotEquals(true, controller.completed);		
		System.assertNotEquals(true, controller.paused);
		System.assertEquals(null, controller.startTime);	
		System.assertEquals(null, controller.completeTime);	
		System.assertEquals(1, controller.total);	
		System.assertEquals(0, controller.processed);	
		System.assertEquals(0, controller.errors);	
		
		List<EnphaseBatchController.ProcessStatus> systems = controller.statuses;
		System.assertEquals(1, systems.size());

		controller.pause();
		System.assertEquals(true, controller.paused);		

		controller.resume();
		System.assertNotEquals(true, controller.paused);
		
		controller.updateState();
		System.assertEquals(true, controller.completed);		
		System.assertNotEquals(true, controller.paused);
		System.assertNotEquals(null, controller.startTime);	
		System.assertNotEquals(null, controller.completeTime);	
		System.assertEquals(1, controller.total);	
		System.assertEquals(1, controller.processed);
		System.assertEquals(1, controller.errors);
		System.assertEquals('No Production Data', controller.statuses[0].status);	
		
		Test.stopTest();
		
	}

	static testMethod void runAlertsBatch() {
		
		Account customer = new Account ( Name = 'Test Customer' );
		insert customer;
		
		Installed_System__c sys = new Installed_System__c (
			Account__c = customer.Id,
			Enphase_ID__c = '12345'
		);
		insert sys;
		
		Test.startTest();
		
		Test.setCurrentPage(Page.EnphaseBatch);
		EnphaseAlertsBatchController controller = new EnphaseAlertsBatchController();

		System.assertNotEquals(true, controller.completed);		
		System.assertNotEquals(true, controller.paused);
		System.assertEquals(null, controller.startTime);	
		System.assertEquals(null, controller.completeTime);	
		System.assertEquals(1, controller.total);	
		System.assertEquals(0, controller.processed);	
		System.assertEquals(0, controller.errors);	
		
		List<EnphaseAlertsBatchController.ProcessStatus> systems = controller.statuses;
		System.assertEquals(1, systems.size());

		controller.pause();
		System.assertEquals(true, controller.paused);		

		controller.resume();
		System.assertNotEquals(true, controller.paused);
		
		controller.updateState();
		System.assertEquals(true, controller.completed);		
		System.assertNotEquals(true, controller.paused);
		System.assertNotEquals(null, controller.startTime);	
		System.assertNotEquals(null, controller.completeTime);	
		System.assertEquals(1, controller.total);	
		System.assertEquals(1, controller.processed);
		System.assertEquals(0, controller.errors);
		System.assertEquals('Success', controller.statuses[0].status);	
		
		Test.stopTest();
		
	}
}