src/objects/Install_Location__c.object
<CustomObject>
    <description>AstrumPM - This object is defined as a single location on a property that has a measured TSRF, Pitch, and Azimuth.</description>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Install Locations</relationshipLabel>
        <relationshipName>Install_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Install Location</label>
    <nameField>
        <label>Install Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Install Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Milestone1_Project__c.object
<CustomObject>
    <description>AstrumPM - A solar installation project.  A project can have many milestones.</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>A general description of the project.</inlineHelpText>
        <label>Description</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <formula>HYPERLINK( &quot;/&quot;+Sales_Order__r.OpportunityId__r.Property__r.Id  ,  Sales_Order__r.OpportunityId__r.Property__r.Name  )</formula>
        <label>Property</label>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Property__c.Property_Owner__r.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SCRB_SalesOrder__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The SalesOrder object is the result of a Closed Won Opportunity and handles the hand off from the sales team to the operations team.</description>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>R00N300000011q88EAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BillingCity__c</fullName>
        <label>Billing City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BillingCountry__c</fullName>
        <label>Billing Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BillingFax__c</fullName>
        <label>Billing Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>BillingPhone__c</fullName>
        <label>Billing Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>BillingPostalCode__c</fullName>
        <label>Billing Zip/Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BillingState__c</fullName>
        <label>Billing State/Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BillingStreet__c</fullName>
        <label>Billing Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DiscountAmount__c</fullName>
        <label>Discount Amount</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DocumentDate__c</fullName>
        <label>Document Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DocumentNumber__c</fullName>
        <externalId>true</externalId>
        <label>Document Number</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Failed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Failed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FreightAmount__c</fullName>
        <label>Freight Amount</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LineItemAmount__c</fullName>
        <label>Line Item Amount</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OpportunityId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>R00N300000011q6hEAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OriginatingDocument__c</fullName>
        <label>Originating Document</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PaymentTerms__c</fullName>
        <label>Payment Terms</label>
        <picklist>
            <picklistValues>
                <fullName>Net 30</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2% 10/Net 30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net 45</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Net 60</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Pricebook__c</fullName>
        <label>Price Book</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestedShipmentOn__c</fullName>
        <defaultValue>Today() + 60</defaultValue>
        <label>Requested Installation On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ShippingCity__c</fullName>
        <label>Shipping City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShippingContact__c</fullName>
        <label>Shipping Contact</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShippingCountry__c</fullName>
        <label>Shipping Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShippingFax__c</fullName>
        <label>Shipping Fax</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ShippingLocation__c</fullName>
        <label>Shipping Location</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShippingMethod__c</fullName>
        <label>Shipping Method</label>
        <picklist>
            <picklistValues>
                <fullName>Airborne</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DHL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FedEx</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full Load</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Will Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ground</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Delivery</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ShippingPhone__c</fullName>
        <label>Shipping Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ShippingPostalCode__c</fullName>
        <label>Shipping Zip/Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShippingState__c</fullName>
        <label>Shipping State/Province</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShippingStreet__c</fullName>
        <label>Shipping Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>StatusCode__c</fullName>
        <label>Status Code</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>Submit Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Assigned to Sales Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Submit To Sales Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Coordinator Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Manager Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Coordinator Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final/Accounting Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Administrator Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated to VP Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VP Sales Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VP Sales Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Controller Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Proposal Creation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Proposal Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Ongoing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Controller Rejected - Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Admin Approved - Finance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SubmitMessage__c</fullName>
        <label>Submit Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Tax__c</fullName>
        <label>Tax</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TotalDiscountAmount__c</fullName>
        <description>Total of line item discounts plus the header discount</description>
        <label>Total Discount Amount</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TrackingNumber__c</fullName>
        <label>Tracking Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Order</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Invoice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quote</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Milestone1_Project_Controller.cls
public with sharing class Milestone1_Project_Controller {
    private final Milestone1_Project__c proj;
    // The extension constructor initializes the private member
    // variable acct by using the getRecord method from the standard
    // controller.
    public Milestone1_Project_Controller(ApexPages.StandardController stdController) {
        this.proj = (Milestone1_Project__c)stdController.getRecord();
/*      
        SCRB_SalesOrder__c so = [
        Select so.Property__c,
            so.Type__c,
            so.TrackingNumber__c,
            so.TotalDiscountAmount__c,
            so.Tax__c,
            so.SubmitMessage__c,
            so.StatusCode__c,
            so.ShippingStreet__c,
            so.ShippingState__c,
            so.ShippingPostalCode__c,
            so.ShippingPhone__c,
            so.ShippingMethod__c,
            so.ShippingLocation__c,
            so.ShippingFax__c,
            so.ShippingCountry__c,
            so.ShippingContact__c,
            so.ShippingCity__c,
            so.RequestedShipmentOn__c,
            so.Pricebook__c,
            so.PaymentTerms__c,
            so.OriginatingDocument__c,
            so.OpportunityId__c,
            so.LineItemAmount__c,
            so.FreightAmount__c,
            so.Failed__c,
            so.DocumentNumber__c,
            so.DocumentDate__c,
            so.DiscountAmount__c,
            so.Description__c,
            so.BillingStreet__c,
            so.BillingState__c,
            so.BillingPostalCode__c,
            so.BillingPhone__c,
            so.BillingFax__c,
            so.BillingCountry__c,
            so.BillingCity__c,
            so.Amount__c,
            so.AccountId__c,
            so.SystemModstamp,
            so.LastModifiedById,
            so.LastModifiedDate,
            so.CreatedById,
            so.CreatedDate,
            so.Name,
            so.IsDeleted,
            so.OwnerId,
            so.Id
        From SCRB_SalesOrder__c so
        Where so.Id = :proj.Sales_Order__r.id
        ];
        proj.Sales_Order__c = so.Id;*/
    }
    
    public String getGreeting() {
        return 'Hello ' + proj.name + ' (' + proj.id + ')';
    }
    /*  
    public Property__c getProperty(){
    
        Property__c prop = [ 
        Select
            p.RecordTypeId, 
            p.Property_ZIP__c, 
            p.Property_State__c, 
            p.Property_Owner__c, 
            p.Property_County__c, 
            p.Property_City__c, 
            p.Property_Address_2__c, 
            p.Name, 
            p.Id, 
            p.HOA_Contact_Phone__c, 
            p.HOA_Contact_Name__c, 
            p.HOA_Contact_Email__c, 
            p.Authorization_Bodies__c, 
            p.Astrum_Office__c 
        From Property__c p 
        where id = :proj.Sales_Order__r.Id
        limit 1];
        return prop;
    }
    
    public List<Install_Location__c> getInstallLocations(){
    List<Install_Location__c> locations = [
            select id, 
                Name,
                Utility_Service__r.Name,
                TSRF__c,
                Tilt__c,
                Surface_Type__c,
                Stuctural_Members__c,
                Orientation__c
            from Install_Location__c i
            where Install_Location__c.Property__c = :proj.Property__c
            ];
        return locations;   }
    
    public Account getPropertyOwner(){
        Account acct = [
            Select 
                a.Website, 
                a.Type, 
                a.ShippingStreet, 
                a.ShippingState, 
                a.ShippingPostalCode, 
                a.ShippingCountry, 
                a.ShippingCity, 
                a.Phone, 
                a.ParentId, 
                a.OwnerId, 
                a.NumberOfEmployees, 
                a.Name, 
                a.MasterRecordId, 
                a.Industry, 
                a.Id, 
                a.Fax, 
                a.Description, 
                a.BillingStreet, 
                a.BillingState, 
                a.BillingPostalCode, 
                a.BillingCountry, 
                a.BillingCity, 
                a.AnnualRevenue, 
                a.AccountNumber 
            From Account a
            where a.Id = :getProperty().Property_Owner__r.id
            limit 1];
        return acct;
    }
    
    public List<OpportunityContactRole> getOppContacts(){
        
        String OppId = proj.Sales_Order__r.OpportunityId__r.id;
        
        List<OpportunityContactRole> ocrList = [
            Select o.Role, 
                o.OpportunityId, 
                o.IsPrimary, 
                o.Id, 
                o.ContactId 
            From OpportunityContactRole o
            where o.OpportunityId = :OppId];
        
        return ocrList;
    
    }
    */
}