src/objects/Installed_System__c.object
<CustomObject>
    <fields>
        <fullName>Monthly_Production_Factor_Apr__c</fullName>
        <label>Monthly Production Factor Apr</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Monthly_Production_Factor_Aug__c</fullName>
        <label>Monthly Production Factor Aug</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Monthly_Production_Factor_Dec__c</fullName>
        <label>Monthly Production Factor Dec</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Monthly_Production_Factor_Feb__c</fullName>
        <description>Monthly Production Factor Feb</description>
        <label>Monthly Production Factor Feb</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Monthly_Production_Factor_Jan__c</fullName>
        <description>Monthly Production Factor Jan</description>
        <label>Monthly Production Factor Jan</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Monthly_Production_Factor_Jul__c</fullName>
        <label>Monthly Production Factor Jul</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Monthly_Production_Factor_Jun__c</fullName>
        <label>Monthly Production Factor Jun</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Monthly_Production_Factor_Mar__c</fullName>
        <label>Monthly Production Factor Mar</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Monthly_Production_Factor_May__c</fullName>
        <label>Monthly Production Factor May</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Monthly_Production_Factor_Nov__c</fullName>
        <label>Monthly Production Factor Nov</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Monthly_Production_Factor_Oct__c</fullName>
        <label>Monthly Production Factor Oct</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Monthly_Production_Factor_Sep__c</fullName>
        <label>Monthly Production Factor Sep</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>PM_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Astrum PM 2.0 Project</description>
        <inlineHelpText>Astrum PM 2.0 Project</inlineHelpText>
        <label>PM 2.0 Project</label>
        <referenceTo>PM_Project__c</referenceTo>
        <relationshipLabel>Installed Systems</relationshipLabel>
        <relationshipName>Installed_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Milestone1_Project__c</referenceTo>
        <relationshipLabel>Installed Systems</relationshipLabel>
        <relationshipName>Installed_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quoted_System_Design__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quoted System Design</label>
        <referenceTo>System_Design_Quote__c</referenceTo>
        <relationshipLabel>Installed Systems</relationshipLabel>
        <relationshipName>Installed_Systems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Installed System</label>
    <nameField>
        <displayFormat>SYS-{000000}</displayFormat>
        <label>Installed System Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installed Systems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Milestone1_Task__c.object
<CustomObject>
    <description>AstrumPM - An activity that has hours, budget, and is assigned to a User.</description>
    <fields>
        <fullName>Due_Date__c</fullName>
        <inlineHelpText>The date this task is due to be completed. Defaults to milestone due date if left blank.</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProjectId__c</fullName>
        <formula>Project_Milestone__r.Project__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProjectId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>HYPERLINK(Project_Milestone__r.Project__c, Project_Milestone__r.Project__r.Name,&apos;_self&apos;)</formula>
        <inlineHelpText>A link to the Project which this task is included in via its milestone.</inlineHelpText>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PM_Project__c.object
<CustomObject>
    <description>Astrum PM 2.0 Project Object</description>
    <fields>
        <fullName>Approved_Utility_Interconnect_Part_2__c</fullName>
        <label>Approved Utility Interconnect Part 2</label>
        <type>Date</type>
    </fields>
    <label>PM Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PM Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PVWatts_Production_Estimates__c.object
<CustomObject>
    <description>This object stores PVWatts monthly production estimates based on projected annual production.</description>
    <fields>
        <fullName>April__c</fullName>
        <label>April</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>August__c</fullName>
        <label>August</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>December__c</fullName>
        <label>December</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>February__c</fullName>
        <label>February</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Installed_System__c</fullName>
        <label>Installed System</label>
        <referenceTo>Installed_System__c</referenceTo>
        <relationshipLabel>PVWatts Production Estimates</relationshipLabel>
        <relationshipName>PVWatts_Production_Estimates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>January__c</fullName>
        <label>January</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>July__c</fullName>
        <label>July</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>June__c</fullName>
        <label>June</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>March__c</fullName>
        <label>March</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>May__c</fullName>
        <label>May</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>November__c</fullName>
        <label>November</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>October__c</fullName>
        <label>October</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>September__c</fullName>
        <label>September</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>PVWatts Production Estimates</label>
    <nameField>
        <displayFormat>PVW-{0000000}</displayFormat>
        <label>PVWatts ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PVWatts Production Estimates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/System_Design__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The Solar System Design.  Each Property can have one or more System Designs created as the result of a site Survey and the discovery of Install Locations.  Each System Design is made up of one or more System Design Arrays.</description>
    <label>System Design</label>
    <nameField>
        <displayFormat>SD-{0}</displayFormat>
        <label>System Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Designs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/System_Design_Quote__c.object
<CustomObject>
    <description>AstrumCRM - System Design Quote.  Each System Design can have one or more System Design Quotes.  Each quote provides the sales consultant with the ability to adjust the negotiated price of the System Design based on the Calculated System Price.  Opportunities must choose a winning System Design Quote in order to close.</description>
    <fields>
        <fullName>System_Design__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>System Design</label>
        <referenceTo>System_Design__c</referenceTo>
        <relationshipLabel>System Design Quotes</relationshipLabel>
        <relationshipName>System_Design_Quotes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>System Design Quote</label>
    <nameField>
        <displayFormat>SDQ-{0}</displayFormat>
        <label>System Design Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Design Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProductionMonthlyGuaranteeCalculator.cls
/* FILE: ProductionMonthlyGuaranteeCalculator .cls
 * AUTHOR: Rohit Jain
 * DATE: May 13, 2013
 * PURPOSE: Calculates astrum estimate and production guarantees based on PVWatts, 
 *          total system size, generation start date, and snow derate 
 * MODIFICATION HISTORY
 *
 */

public class ProductionMonthlyGuaranteeCalculator {
    
    public static final Date PRODUCTION_GUARANTEE_START = Date.newInstance(2011,7,1);
    public static final Double PRODUCTION_GUARANTEE_PCT = 0.95; //95%
    public static final Double GUARANTEE_ANNUAL_DERATE_PCT = .005; //0.5%
    
    //jan-dec and total
    private static String[] fieldNames = new String[] {
        'January__c', 'February__c', 'March__c', 'April__c', 'May__c', 'June__c',
        'July__c', 'August__c', 'September__c', 'October__c', 'November__c', 'December__c'
    };

        //jan-dec and total
    private static String[] productionFactorFields = new String[] {
        'Monthly_Production_Factor_Jan__c', 'Monthly_Production_Factor_Feb__c', 'Monthly_Production_Factor_Mar__c', 'Monthly_Production_Factor_Apr__c', 'Monthly_Production_Factor_May__c', 'Monthly_Production_Factor_Jun__c',
        'Monthly_Production_Factor_Jul__c', 'Monthly_Production_Factor_Aug__c', 'Monthly_Production_Factor_Sep__c', 'Monthly_Production_Factor_Oct__c', 'Monthly_Production_Factor_Nov__c', 'Monthly_Production_Factor_Dec__c'
    };
    
    //snow de-rate normal distribution Dec - Mar (15%, 35%, 35%, 15% = 100%)
    private static Double[] snowRatio = new Double[] { .35, .35, .15, 0, 0, 0, 0, 0, 0, 0, 0, .15 };

    public static List<ProductionGuarantee> getProductionGuarantee(PVWatts_Production_Estimates__c pvw, Installed_System__c sys ,Date generationStart) {
        
        List<ProductionGuarantee> result = new List<ProductionGuarantee>();
        Boolean guranteeFlag = false;
        Date utilityConnectDate;
        Integer guaranteeStartYear;
        System.debug('*generationStart' + generationStart);
        Integer currentMonth = Date.today().month();
        System.debug('*currentMonth ' + currentMonth );
        
        Decimal projectAnnualOutput = sys.Quoted_System_Design__r.System_Design__r.Total_Projected_Annual_Output_kWh_y__c ;
        //System.debug('*projectAnnualOutput ' + projectAnnualOutput );
        
        if(generationStart >= PRODUCTION_GUARANTEE_START)
        {
            guranteeFlag = true;    
        }
        if(guranteeFlag )
        {
            if (sys.PM_Project__c != null)
            {
                utilityConnectDate = sys.PM_Project__r.Approved_Utility_Interconnect_Part_2__c;    
                 System.debug('*pm2 utilityConnectDate ' + utilityConnectDate );
                //System.debug('*pm2-utilityConnectDate ' + utilityConnectDate );
            }
            else if(sys.Project__c != null)
            {    System.debug('*pm1 Project__c ' + sys.Project__c);
                 String prjId = Sys.Project__c;
                 if(prjId.length() >=15)
                 {
                    prjId = prjId.substring(0,15);
                 }
                 System.debug('*pm1 prjId  ' + prjId );
                try{
                    Milestone1_Task__c appTask = [Select Due_Date__c From Milestone1_Task__c Where Name = 'Received Certificate of Completion/Net Meter Rider' and ProjectId__c = :prjId  ];
                    utilityConnectDate = apptask.Due_Date__c;
                     System.debug('*pm1 utilityConnectDate ' + utilityConnectDate );
                    //System.debug('*pm1-utilityConnectDate ' + utilityConnectDate );
                }
                catch(Exception e)
                {
                    System.debug('*Err ' + e);
                    utilityConnectDate = null;  
                }
            }
            else
            {
                utilityConnectDate  =    generationStart; 
                 System.debug('*gs utilityConnectDate ' + utilityConnectDate );
            }
            
            Date guaranteeStartDate = utilityConnectDate  > generationStart ? utilityConnectDate  : generationStart ;
            
            if(guaranteeStartDate != null)
            {
                guaranteeStartYear = guaranteeStartDate.year() + 1;
                if (guaranteeStartDate.month() == 1 && guaranteeStartDate.day() == 1) {
                    guaranteeStartYear = guaranteeStartDate.year();
                }       
            }
            else
            {
                guranteeFlag = false;     
            
            }
            System.debug('*gs guranteeFlag ' + guranteeFlag );
            
        } 
        
        Date startOfMonth;
        if(generationStart.day() != 1)
        {
            startOfMonth = generationStart.toStartOfMonth().addMonths(1);
        }
        else
        {
            startOfMonth = generationStart.toStartOfMonth();
        }       
                
        Date startOfThisMonth = Date.today().toStartOfMonth();         
        Decimal productionFactor = (Decimal)sys.get(productionFactorFields[startOfMonth.month()-1] );
        //System.debug('**productionFactor ' + productionFactor );
        Double monthIndex = 0;  
        Double derateFactor = 1-(.005/12);          
        while (startOfMonth < startOfThisMonth) {
            //Double yearsDiff = Math.max(startOfMonth.year() - guaranteeStartYear, 0);
            //Integer monthIndex = startOfMonth.month() - 1;
            ProductionGuarantee pg = new ProductionGuarantee();
            pg.startOfMonth = startOfMonth;
            //System.debug('**monthIndex  ' + monthIndex  );
            Decimal estimate = (projectAnnualOutput) * (productionFactor/100)  * (Math.pow(derateFactor , monthIndex));
            pg.estimate_kWh = estimate.setScale(2);           
            if (guranteeFlag  && startOfMonth.year() >= guaranteeStartYear) {
                Decimal gurantee = pg.estimate_kWh * PRODUCTION_GUARANTEE_PCT;
                pg.guarantee_kWh = gurantee.setScale(2);                 
            }
            result.add(pg);
            startOfMonth = startOfMonth.addMonths(1);          
            productionFactor = (Decimal)sys.get(productionFactorFields[startOfMonth.month()-1] );
            //System.debug('**productionFactor ' + productionFactor );
            monthIndex = monthIndex + 1;
        }
                
        return result;          
        
    }

    public class ProductionGuarantee {
        public Date startOfMonth;
        public Double guarantee_kWh;
        public Double estimate_kWh;
    }

}