src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Affiliate_Community_Program__c</fullName>
        <label>Affiliate Community Program</label>
        <picklist>
            <picklistValues>
                <fullName>CUNY/Pepsi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D2D Atlantic City Electric</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D2D BG&amp;E</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D2D ConEd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D2D Connecticut L&amp;P</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D2D Delmarva</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D2D JCP&amp;L</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D2D Long Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D2D National Grid MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D2D NSTAR MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D2D Pacific Gas &amp; Electric</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D2D PEPCO MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D2D PSEG NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D2D SCE - 10B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D2D United Illuminating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE Delmarva</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE Houston Employee Offer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gloucester Challenge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mass Energy Solar Connect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Norwalk CPO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retrofit Baltimore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solarize Sagewell</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solarize SecondChance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solarize VCCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temple Sinai Solar Co-Op DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temple Sinai Solar Co-Op MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temple Sinai Solar Co-Op VA</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>D2D_System_Size__c</fullName>
        <label>D2D System Size</label>
        <picklist>
            <controllingField>D2D_State__c</controllingField>
            <picklistValues>
                <fullName>16 Panel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24 Panel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>36 Panel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead_Created_Date__c</fullName>
        <description>Custom field that contains a copy of the CreatedDate</description>
        <label>Lead Created Date</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Portal_Referral__c.object
<CustomObject>
    <description>Referrals from the Partner Program website</description>
    <fields>
        <fullName>City__c</fullName>
        <description>City for referral</description>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>D2D_Lead_Status__c</fullName>
        <label>D2D Lead Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed - Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Generated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Opt-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Opt-Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Door Hanger</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing Utility Bill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA Visit 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA Visit 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passed Validation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Photos Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit Scheduled</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>D2D_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>D2D Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Portal_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>D2D_System_Size__c</fullName>
        <label>D2D System Size</label>
        <picklist>
            <controllingField>State__c</controllingField>
            <picklistValues>
                <fullName>16 Panel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24 Panel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>36 Panel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of referral</description>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of referral</description>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Created_Date__c</fullName>
        <label>Lead Created Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Portal Referrals</relationshipLabel>
        <relationshipName>Portal_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>Street of Referral</description>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Portal Referral</label>
    <nameField>
        <displayFormat>REF-{000000}</displayFormat>
        <label>Portal Referral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/State__c.object
<CustomObject>
    <description>Represents a State</description>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/D2D_InitialLeadPortalReferralBatch.cls
global class D2D_InitialLeadPortalReferralBatch implements Database.Batchable<sObject>, Database.Stateful {
	
	global final String query;
	global List<Portal_Referral__c> toInsert;

	global final Set<String> affiliateCommunityPrograms;
	global final Map<String, Id> cityToManager;
	global final Set<String> cities;
	
	global D2D_InitialLeadPortalReferralBatch(String queryToRun, Map<String, Id> citiesToManagers) {
		affiliateCommunityPrograms = new Set<String>();
        List<Schema.PicklistEntry> ple = Lead.Affiliate_Community_Program__c.getDescribe().getPicklistValues();
        for(Schema.PicklistEntry f : ple)
        {
        	if(f.getValue().contains('D2D')){
	            affiliateCommunityPrograms.add(f.getValue());
        	}
        }

		cityToManager = citiesToManagers;

		cities = cityToManager.keySet();

		query = queryToRun;

		toInsert = new List<Portal_Referral__c>();
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope) {
   		toInsert = new List<Portal_Referral__c>();
		for(Lead lead : (List<Lead>)scope){
			toInsert.add(new Portal_Referral__c(
				Lead__c = lead.Id, D2D_System_Size__c = lead.D2D_System_Size__c, D2D_Lead_Status__c = 'Prospect New', Last_Name__c = lead.LastName, First_Name__c = lead.FirstName,
				Street__c = lead.Street, City__c = lead.City, State__c = lead.State, Zip__c = lead.PostalCode, Lead_Created_Date__c = Date.today(),
				D2D_Manager__c = cityToManager.get(lead.City.toLowerCase())
			));
		}
		insert toInsert;
	}
	
	global void finish(Database.BatchableContext BC) { }
}