src/objects/Lease_Fund__c.object
<CustomObject>
    <fields>
        <fullName>Eligible_Leasing_Options__c</fullName>
        <label>Eligible Leasing Options</label>
        <picklist>
            <picklistValues>
                <fullName>Low-Upfront - Monthly</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>One-Pay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>One-Pay - Keep SRECs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low-Upfront - Massachusetts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low-Upfront - Monthly - Keep SRECs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>One-Pay - Massachusetts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPF - Complex Rebate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPF - Astrum Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Financing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SAC Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Term Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed-Rate PPA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portfolio PPA</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Eligible_States__c</fullName>
        <label>Eligible States</label>
        <picklist>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Fund_Open_Date__c</fullName>
        <label>Fund Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fund_Partner__c</fullName>
        <label>Fund Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Lease Funds</relationshipLabel>
        <relationshipName>Lease_Funds</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Lease Fund</label>
    <nameField>
        <label>Lease Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lease Funds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/PM_Project__c.object
<CustomObject>
    <description>Astrum PM 2.0 Project Object</description>
    <fields>
        <fullName>Project_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>PM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>SCRB_SalesOrder__c</referenceTo>
        <relationshipLabel>PM Projects</relationshipLabel>
        <relationshipName>PM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PM Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PM Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <description>AstrumPM/AstrumCRM - Each account can have one or more properties.  A property is defined by its street address.</description>
    <fields>
        <fullName>Utility_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>DEPRECATED AS OF 11/25/14</description>
        <label>Utility Rate Code</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Utility_Company__c.RecordType.Name</field>
                <operation>notEqual</operation>
                <value>Custom</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Utility_Company__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Address 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <recordTypes>
        <fullName>Residential</fullName>
        <active>true</active>
        <label>Residential</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SCRB_SalesOrder__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The SalesOrder object is the result of a Closed Won Opportunity and handles the hand off from the sales team to the operations team.</description>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>R00N300000011q88EAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lease_Fund__c</fullName>
        <description>Lease Fund</description>
        <inlineHelpText>Lease Fund</inlineHelpText>
        <label>Lease Fund</label>
        <picklist>
            <picklistValues>
                <fullName>ASTRUM - M210</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASTRUM - SUNPOWER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CITI1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CITI2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CITI2 - M210</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GOLDMAN1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goldman - Do Not Install</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA - SPECIAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ - SPECIAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA - ASTRUM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA - TBR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tredegar Solar Fund I, LLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NRG Residential Solar Solutions, LLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunnova Energy Corporation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goldman - Do Not Install - Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Astrum Fund 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Astrum 1603</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kilowatt Systems, LLC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT Lease</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/System_Design__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The Solar System Design.  Each Property can have one or more System Designs created as the result of a site Survey and the discovery of Install Locations.  Each System Design is made up of one or more System Design Arrays.</description>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>System Designs</relationshipLabel>
        <relationshipName>System_Designs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>System Design</label>
    <nameField>
        <displayFormat>SD-{0}</displayFormat>
        <label>System Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Designs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility_Company__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - Each Utility Service is attached to a single Utility Company.</description>
    <fields>
        <fullName>State_Serviced__c</fullName>
        <label>State Serviced</label>
        <picklist>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Utility Rate Code</label>
    <nameField>
        <label>Utility Rate Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Rate Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility_Service__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - Each Property can have one or more Utility Service(s).  A Utility Service is primarily defined by the Meter ID and the Utility Company to which is connects.</description>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Utility Services</relationshipLabel>
        <relationshipName>Utility_Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service_Account_Number__c</fullName>
        <externalId>true</externalId>
        <label>Service Account Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Company</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Utility_Company__c.RecordType.Name</field>
                <operation>notEqual</operation>
                <value>Custom</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Utility_Company__c</referenceTo>
        <relationshipLabel>Utility Services</relationshipLabel>
        <relationshipName>Utility_Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Service</label>
    <nameField>
        <label>Meter ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PMProjectFactSheetTest.cls
/* FILE: PMProjectFactSheetTest.cls
 * AUTHOR: Tino Mattheou
 * DATE: June 11, 2012
 * PURPOSE: Test class for PMProjectFactSheet page  
 * MODIFICATION HISTORY
 *
 */ 

@isTest
public class PMProjectFactSheetTest {
	
	static testMethod void project_getFactSheet_dataFound() {
		
		Account customer = new Account(Name = 'Test Customer');
		insert customer;

		Account partner = new Account(Name = 'Fund Partner');
		insert partner;
	
		Lease_Fund__c leasefund = new Lease_Fund__c(
			Name = 'NRG Residential Solar Solutions, LLC',
			Fund_Partner__c = partner.id,
			Fund_Open_Date__c = date.today(),
			Eligible_States__c = 'CA;CT;DC;DE;KY;MA;MD;MI;NJ;NY;OH;PA;VA;WV',
			Eligible_Leasing_Options__c = 'One-Pay - Keep SRECs'
		);
		insert(leasefund);	
		
		Lease_Fund__c leasefund2 = new Lease_Fund__c(
			Name = 'Sunnova Energy Corporation',
			Fund_Partner__c = partner.id,
			Fund_Open_Date__c = date.today(),
			Eligible_States__c = 'CA;CT;DC;DE;KY;MA;MD;MI;NJ;NY;OH;PA;VA;WV',
			Eligible_Leasing_Options__c = 'One-Pay - Keep SRECs'
		);					
		insert(leasefund2);

		Contact contact1 = new Contact ( AccountId = customer.Id, LastName = 'Customer 1');
		insert contact1; 
		
		Property__c property = CreateAstrumPM2ProjectTest.createProperty(customer.Id, '123 Test St');
		SCRB_SalesOrder__c salesOrder = CreateAstrumPM2ProjectTest.createSalesOrder(property.Id, null);
		salesOrder.AccountId__c = customer.Id;
		update salesOrder;
		
		Utility_Company__c utility = new Utility_Company__c (
			State_Serviced__c = 'PA'
		);
		insert utility;
		
		Utility_Service__c service = new Utility_Service__c (
			Property__c = property.Id,
			Service_Account_Number__c = 'ABC',
			Utility_Company__c = utility.Id
		);
		insert service;	
	
		PM_Project__c project = new PM_Project__c (
			Name = 'Test Project',
			Sales_Order__c = salesOrder.Id
		);
		insert project;
		
		project = [SELECT Id, Name, Project_Lead__c, Kickoff__c, Install__c, Inspection__c,
			Sales_Order__r.AccountId__c,
			Sales_Order__r.Property__c,
			Sales_Order__r.System_Design_Quote__r.System_Design__c
			FROM PM_Project__c 
			WHERE Id = :project.Id];

		Test.setCurrentPage(Page.PMProjectFactSheet);
		ApexPages.StandardController controller = new ApexPages.StandardController(project);


		Test.startTest();

		PMProjectFactSheetExtension extension = new PMProjectFactSheetExtension(controller);
		
		System.assertEquals(1, extension.contacts.size());
		System.assertEquals(contact1.LastName, extension.contacts[0].LastName);

		System.assertEquals(1, extension.utilityServices.size());

		System.assertEquals(0, extension.installLocations.size());
		System.assertEquals(0, extension.cbPanels.size());
		System.assertEquals(0, extension.systemDesignArrays.size());
		System.assertEquals(0, extension.systemDesignItems.size());
		
		Test.stopTest();

	}

}