src/objects/Milestone1_Task__c.object
<CustomObject>
    <description>AstrumPM - An activity that has hours, budget, and is assigned to a User.</description>
    <fields>
        <fullName>Blocked__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this task blocked for some reason?</inlineHelpText>
        <label>Blocked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>The status of this task. A task is either in-complete or complete.</inlineHelpText>
        <label>Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Requires_Documentation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Requires Documentation</label>
        <type>Checkbox</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TaskDetailHolder.cls
public with sharing class TaskDetailHolder {

	public String milestoneName {get; set;}
	public String milestoneColor {get; private set;}

	public Milestone1_Task__c task {get; set;}		
	
	public String complete {get; set;}
	public String blocked {get; set;}
	public String requiresDocumentation {get; set;}

	public String taskColor {get; private set;}
	
	public static final String YES = 'Yes';
	public static final String NO = 'No';
		
	public TaskDetailHolder(String theMilestoneName, String theMilestoneColor, Milestone1_Task__c theTask, String theTaskColor) {
		milestoneName = theMilestoneName;
		milestoneColor = theMilestoneColor;
		
		task = theTask;
		taskColor = theTaskColor;
		
		complete = toStringYesNo(task.complete__c);
		blocked = toStringYesNo(task.blocked__c);
		requiresDocumentation = toStringYesNo(task.Requires_Documentation__c);		
	}

	public static String toStringYesNo(Boolean flag) {
		String result = null;
				
		if (flag) {
			result = YES;
		}
		else {
			result = NO;
		}
		
		return result;
	}	
}