src/objects/Milestone1_Milestone__c.object
<CustomObject>
    <description>AstrumPM - Milestones are significant events that mark the phases in the life-cycle of a Project. Milestones can have tasks and sub-milestones associated with them.</description>
    <fields>
        <fullName>Complete_Date__c</fullName>
        <label>Complete Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This signifies that this milestone has been completed.</inlineHelpText>
        <label>Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>The date that this deadline needs to be finished by.</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_Milestone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The parent milestone for this milestone if applicable.</inlineHelpText>
        <label>Parent Milestone</label>
        <referenceTo>Milestone1_Milestone__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Child_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The project this milestone is assigned to. If this is a sub-milestone this field is empty.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Milestone1_Project__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Project_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Project Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone1_Project__c.object
<CustomObject>
    <description>AstrumPM - A solar installation project.  A project can have many milestones.</description>
    <fields>
        <fullName>Astrum_Office__c</fullName>
        <formula>TEXT(Sales_Order__r.OpportunityId__r.Property__r.Astrum_Office__c)</formula>
        <label>Astrum Office</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <formula>HYPERLINK( &quot;/&quot;+Sales_Order__r.OpportunityId__r.Property__r.Id  ,  Sales_Order__r.OpportunityId__r.Property__r.Name  )</formula>
        <label>Property</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>SCRB_SalesOrder__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone1_Task__c.object
<CustomObject>
    <description>AstrumPM - An activity that has hours, budget, and is assigned to a User.</description>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The user responsible for completing the task. Defaults to current user if left blank.</inlineHelpText>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Tasks_Assigned</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Complete_Date__c</fullName>
        <label>Complete Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>The status of this task. A task is either in-complete or complete.</inlineHelpText>
        <label>Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Milestone__c</fullName>
        <inlineHelpText>The milestone that this task is assigned to.</inlineHelpText>
        <label>Milestone</label>
        <referenceTo>Milestone1_Milestone__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>HYPERLINK(Project_Milestone__r.Project__c, Project_Milestone__r.Project__r.Name,&apos;_self&apos;)</formula>
        <inlineHelpText>A link to the Project which this task is included in via its milestone.</inlineHelpText>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <description>AstrumPM/AstrumCRM - Each account can have one or more properties.  A property is defined by its street address.</description>
    <fields>
        <fullName>Astrum_Office__c</fullName>
        <label>Astrum Office</label>
        <picklist>
            <picklistValues>
                <fullName>Columbia, MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corona, CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cromwell, CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fresno, CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Henrietta, NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hopkinton, MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Long Island, NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middletown, NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Norristown, PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pennsauken, NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>San Diego, CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Simi Valley, CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Syracuse, NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taunton, MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Westford, MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Youngstown, OH</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Optimal_Site_Quality_kWh_y_kW__c</fullName>
        <label>Optimal Site Quality (kWh/y/kW)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Permit_Jurisdiction__c</fullName>
        <description>Jurisdiction (county, township, etc) for property permitting</description>
        <label>Permit Jurisdiction</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_City__c</fullName>
        <label>Property City</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>Property State</label>
        <picklist>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property_ZIP__c</fullName>
        <label>Property ZIP</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Address 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SCRB_SalesOrder__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The SalesOrder object is the result of a Closed Won Opportunity and handles the hand off from the sales team to the operations team.</description>
    <fields>
        <fullName>Astrum_Office__c</fullName>
        <description>Astrum Office serving this Property</description>
        <formula>TEXT(Property__r.Astrum_Office__c)</formula>
        <inlineHelpText>Astrum Office serving this Property</inlineHelpText>
        <label>Astrum Office</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StatusCode__c</fullName>
        <label>Status Code</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>Submit Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Assigned to Sales Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Submit To Sales Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Coordinator Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Manager Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Coordinator Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final/Accounting Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Administrator Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated to VP Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VP Sales Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VP Sales Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Controller Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Proposal Creation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Proposal Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Ongoing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Controller Rejected - Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Admin Approved - Finance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Milestone1_ChangeTaskOwnership_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class Milestone1_ChangeTaskOwnership_Test {

	static String testMilestoneName = 'ms1-test';

    public static testMethod void changeFirstTaskOwnerShipTest() {

		System.assert(true);
		
		/*
        // setup
        Milestone1_Milestone__c myMilestone = createMilestone();
        List<Milestone1_Task__c> tasks = getSampleTasksNotComplete(myMilestone, 3);
        insert tasks;
        
        List<Milestone1_Milestone__c> oldMilestones = new List<Milestone1_Milestone__c>();
        oldMilestones.add(myMilestone);
        
        List<Milestone1_Milestone__c> newMilestones = getMilestones(testMilestoneName);        		

		List<User> users = getTestUsers();
		
		User ben = users.get(0);
		User josh = users.get(1);
		
		// execute: change the owner of the first task for each milestone
		updateFirstTaskOwner(josh, oldMilestones);
		updateMilestonesOwner(ben, newMilestones);
		
        // assert
        assertFirstTaskOwner(ben, josh);
        */
    }

    public static testMethod void changeMilestoneOwnerShipTest() {

		System.assert(true);

		/*
        // setup
        Milestone1_Milestone__c myMilestone = createMilestone();
        List<Milestone1_Task__c> tasks = getSampleTasksNotComplete(myMilestone, 3);
        insert tasks;
        
        List<Milestone1_Milestone__c> oldMilestones = new List<Milestone1_Milestone__c>();
        oldMilestones.add(myMilestone);

        List<Milestone1_Milestone__c> newMilestones = getMilestones(testMilestoneName);        		

		List<User> users = getTestUsers();
		
		User ben = users.get(0);
		User josh = users.get(1);
		
		updateMilestonesOwner(ben, newMilestones);
		        
        // execute
		showOwnerIds(oldMilestones);
		
		showOwnerIds(newMilestones);
				        
        // assert
        assertMilestones(ben);
        */
    }
	
	private static Milestone1_Milestone__c createMilestone() {
        //create Property
        Property__c prop = new Property__c();
        prop.Name = '123 Main St';       
        prop.Optimal_Site_Quality_kWh_y_kW__c = double.valueOf('1250');
        prop.Property_State__c = 'MD';
        prop.Property_City__c = 'Annapolis Junction';
        prop.Property_ZIP__c = '20701';
        prop.Permit_Jurisdiction__c = 'Howard';
        prop.Astrum_Office__c = testdata.defaultOffLocationName;// FPO Phase4 //'Annapolis Junction, MD';
        insert prop;
        
        //create sales order
        SCRB_SalesOrder__c order = new SCRB_SalesOrder__c();
        order.name = 'SO-TEST';
        order.StatusCode__c = 'Submitted';
        order.Property__c = prop.id;
        
        insert order; 
	
        Milestone1_Project__c proj = new Milestone1_Project__c();
        proj.name = 'proj-test';
        proj.Sales_Order__c = order.id;        
        insert proj;
        
        //create a milestone
        Milestone1_Milestone__c ms1 = Milestone1_Test_Utility.sampleMilestone(proj);
        ms1.Name = testMilestoneName;
        
		insert ms1;
		
		return ms1;
	}    
	
	private static List<Milestone1_Task__c> getSampleTasks(Milestone1_Milestone__c milestone, Integer numberOfTasks, Boolean allComplete) {
        List<Milestone1_Task__c> tasks = new List<Milestone1_Task__c>();
        
        for(Integer i = 0; i < numberOfTasks; i++){
            Id parentMilestoneId = milestone.Id;
            Milestone1_Task__c taskRec = Milestone1_Test_Utility.sampleTask(parentMilestoneId);
            tasks.add(taskRec);
			
			// complete the task 
			if (allComplete) {           
				taskRec.Complete__c = true;
				taskRec.Complete_Date__c = Date.today();
			}
        }
		
		return tasks;
	}
	
	private static List<Milestone1_Task__c> getSampleTasksNotComplete(Milestone1_Milestone__c milestone, Integer numberOfTasks) {
		Boolean complete = false;
		return getSampleTasks(milestone, numberOfTasks, complete);
	}   
	
	
	private static void assertFirstTaskOwner(User milestoneOwner, User firstTaskOwner) {
        List<Milestone1_Milestone__c> theMilestones = getMilestones(testMilestoneName);
        
        Set<ID> newMilestoneIds = Milestone1_Milestone_Trigger_Utility.getIds(theMilestones);
        List<Milestone1_Task__c> allMilestoneTasks = [select Name, Assigned_To__c, Project_Milestone__c 
                                                       FROM Milestone1_Task__c 
                                                       WHERE Project_Milestone__c IN: newMilestoneIds];
        
        // now confirm milestone is owned by ben and each task owned by ben EXCEPT first task        
        for (Milestone1_Milestone__c tempMilestone : theMilestones) {
        	
        	System.debug('tempMilestone.ownerId = ' + tempMilestone.ownerId);
        	System.debug('milestoneOwner.id = ' + milestoneOwner.id);
        	
        	System.assertEquals(tempMilestone.ownerId, milestoneOwner.id);	
        	
            // Get tasks for this milestone         
            List<Milestone1_Task__c> milestoneTasks = Milestone1_Milestone_Trigger_Utility.getMilestoneTasks(tempMilestone.id, allMilestoneTasks);
        	
        	Integer taskCounter = 0;
        	for (Milestone1_Task__c tempTask : milestoneTasks) {
        		
	        	System.debug('assertFirstTask: tempTask.assigned_to__c = ' + tempTask.assigned_to__c);
	        	System.debug('assertFirstTask: firstTaskOwner.id = ' + firstTaskOwner.id);

        		if (taskCounter == 0) {
        			// compare against firstTaskOwner
        			System.assertEquals(tempTask.assigned_to__c, firstTaskOwner.id);	        	        				
        		}
        		else {
        			System.assertEquals(tempTask.assigned_to__c, milestoneOwner.id);	        	
        		}
        		
        		taskCounter++;	
        	}
        }		
	}
	    
	private static void assertMilestones(User theOwner) {
        List<Milestone1_Milestone__c> theMilestones = getMilestones(testMilestoneName);
        
        Set<ID> newMilestoneIds = Milestone1_Milestone_Trigger_Utility.getIds(theMilestones);
        List<Milestone1_Task__c> allMilestoneTasks = [select Name, Assigned_To__c, Project_Milestone__c 
                                                       FROM Milestone1_Task__c 
                                                       WHERE Project_Milestone__c IN: newMilestoneIds];
        
        // now confirm milestone is owned by ben and each task owned by ben
        for (Milestone1_Milestone__c tempMilestone : theMilestones) {
        	System.assertEquals(tempMilestone.ownerId, theOwner.id);	
        	
            // Get tasks for this milestone         
            List<Milestone1_Task__c> milestoneTasks = Milestone1_Milestone_Trigger_Utility.getMilestoneTasks(tempMilestone.id, allMilestoneTasks);
        	
        	for (Milestone1_Task__c tempTask : milestoneTasks) {
        		System.assertEquals(tempTask.assigned_to__c, theOwner.id);	        		
        	}
        }		
	}
	
	
	private static List<Milestone1_Milestone__c>  getMilestones(String milestoneName) {
        List<Milestone1_Milestone__c> newMilestones = 
        		[SELECT Id,
                      Name,
                      Project__c,
                      Parent_Milestone__c,
                      Complete__c,
                      Deadline__c,
                      Description__c,
                      Expense_Budget__c,
                      Hours_Budget__c,
                      OwnerId,
                      KickOff__c
                      FROM Milestone1_Milestone__c
                      WHERE Name = :milestoneName
                     ];

		return newMilestones;				
	}
	
    private static void updateMilestonesOwner(User theUser, List<Milestone1_Milestone__c> theMilestones) {
    		
    	List<Milestone1_Milestone__c> theMilestonesToUpdate = new List<Milestone1_Milestone__c>();
    		
    	for (Milestone1_Milestone__c tempMilestone : theMilestones) {
    		tempMilestone.OwnerId = theUser.Id;
    		theMilestonesToUpdate.add(tempMilestone);
    	}
    	
		update theMilestonesToUpdate;    	
    }

    private static void updateFirstTaskOwner(User theUser, List<Milestone1_Milestone__c> theMilestones) {
    		
        Set<ID> newMilestoneIds = Milestone1_Milestone_Trigger_Utility.getIds(theMilestones);
        List<Milestone1_Task__c> allMilestoneTasks = [select Name, Assigned_To__c, Project_Milestone__c 
                                                       FROM Milestone1_Task__c 
                                                       WHERE Project_Milestone__c IN: newMilestoneIds];
        
        for (Milestone1_Milestone__c tempMilestone : theMilestones) {
        	
            // Get tasks for this milestone         
            List<Milestone1_Task__c> milestoneTasks = Milestone1_Milestone_Trigger_Utility.getMilestoneTasks(tempMilestone.id, allMilestoneTasks);

			System.debug('updateFirstTaskOwner: Tasks found: ' + milestoneTasks.size());
			
			if (!milestoneTasks.isEmpty()) {
				Milestone1_Task__c tempTask = milestoneTasks.get(0);
				tempTask.Assigned_To__c = theUser.Id;
				
				update tempTask;
			}   			     	
        }		
    }
    
    private static void showOwnerIds(List<Milestone1_Milestone__c> theMilestones) {
    		
    	for (Milestone1_Milestone__c tempMilestone : theMilestones) {
    		System.debug('The milestone owner id = ' + tempMilestone.OwnerId);
    	}
    }
    
    private static List<User> getTestUsers() {
    
    	List<User> users = [SELECT Id, FirstName, LastName, email 
    						FROM User u 
    						WHERE email LIKE 'josh@astrumsolar.com%' OR email LIKE 'ben.davis@astrumsolar.com%' 
    						ORDER BY firstName
                            ];
    	
    	return users;
    }
    
}