src/objects/Milestone1_Milestone__c.object
<CustomObject>
    <description>AstrumPM - Milestones are significant events that mark the phases in the life-cycle of a Project. Milestones can have tasks and sub-milestones associated with them.</description>
    <fields>
        <fullName>Blocked_Tasks_in_Tasks__c</fullName>
        <inlineHelpText>How many tasks are flagged as blocked?</inlineHelpText>
        <label>Blocked Tasks (in Tasks)</label>
        <summaryFilterItems>
            <field>Milestone1_Task__c.Blocked__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Milestone1_Task__c.Project_Milestone__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Complete_Date__c</fullName>
        <label>Complete Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This signifies that this milestone has been completed.</inlineHelpText>
        <label>Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>The date that this deadline needs to be finished by.</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Late_Tasks_in_Tasks__c</fullName>
        <inlineHelpText>Number of incomplete and overdue tasks related to this milestone</inlineHelpText>
        <label>Late Tasks (in Tasks)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The project this milestone is assigned to. If this is a sub-milestone this field is empty.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Milestone1_Project__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Project_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Project Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone1_Project__c.object
<CustomObject>
    <description>AstrumPM - A solar installation project.  A project can have many milestones.</description>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>The date by which the project is scheduled to be completed by.</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone1_Task__c.object
<CustomObject>
    <description>AstrumPM - An activity that has hours, budget, and is assigned to a User.</description>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The user responsible for completing the task. Defaults to current user if left blank.</inlineHelpText>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Tasks_Assigned</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Blocked__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this task blocked for some reason?</inlineHelpText>
        <label>Blocked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Complete_Date__c</fullName>
        <label>Complete Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>The status of this task. A task is either in-complete or complete.</inlineHelpText>
        <label>Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Days_Late__c</fullName>
        <inlineHelpText>How many days late is this task?</inlineHelpText>
        <label>Days Late</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <inlineHelpText>The date this task is due to be completed. Defaults to milestone due date if left blank.</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Milestone__c</fullName>
        <inlineHelpText>The milestone that this task is assigned to.</inlineHelpText>
        <label>Milestone</label>
        <referenceTo>Milestone1_Milestone__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>HYPERLINK(Project_Milestone__r.Project__c, Project_Milestone__r.Project__r.Name,&apos;_self&apos;)</formula>
        <inlineHelpText>A link to the Project which this task is included in via its milestone.</inlineHelpText>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requires_Documentation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Requires Documentation</label>
        <type>Checkbox</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Milestone1_Project_Controller_Extension.cls
public with sharing class Milestone1_Project_Controller_Extension {

    public static final String OPEN_COLOR = '#4ABEDE';
    public static final String LATE_BLOCKED_COLOR = '#EF4839';
    public static final String COMPLETE_COLOR = '#FEFEFE';

    public List<TaskDetailHolder> taskDetailHolders {get; private set;}
    public String openColor {get; private set;}
    public String lateBlockedColor {get; private set;}
    public String completeColor {get; private set;}
     
    public Milestone1_Project_Controller_Extension(ApexPages.StandardController stdController) {
        Milestone1_Project__c project = (Milestone1_Project__c) stdController.getRecord();
        
        openColor = OPEN_COLOR;
        lateBlockedColor = LATE_BLOCKED_COLOR;
        completeColor = COMPLETE_COLOR;
        
        loadData(project.id);        
    }

    private void loadData(String projectId) {
        // get all milestones
        List<Milestone1_Milestone__c> milestones = loadMilestones(projectId);
        
        List<Id> milestoneIds = getMilestoneIds(milestones);
        
        List<Milestone1_Task__c> tasks = getTasks(milestoneIds);
        
        Map<Id, List<Milestone1_Task__c>> tasksByMilestoneId = groupTasksByMilestoneId(tasks);
        
        // taskDetailHolders = buildMap(tasks);
        taskDetailHolders = buildMap(milestoneIds, tasksByMilestoneId);
    }
    
    private Map<Id, List<Milestone1_Task__c>> groupTasksByMilestoneId(List<Milestone1_Task__c> theTasks) {
        Map<Id, List<Milestone1_Task__c>> tasksByMilestoneId = new Map<Id, List<Milestone1_Task__c>>();

        for (Milestone1_Task__c tempTask : theTasks) {
            
            Id milestoneId = tempTask.Project_Milestone__c;
            
            List<Milestone1_Task__c> tasksForMilestone = null;
            
            if (tasksByMilestoneId.containsKey(milestoneId)) {
                tasksForMilestone = tasksByMilestoneId.get(milestoneId);
            }
            else {
                tasksForMilestone = new List<Milestone1_Task__c>();
                tasksByMilestoneId.put(milestoneId, tasksForMilestone);                 
            }
            
            tasksForMilestone.add(tempTask);    
        }
        
        return tasksByMilestoneId;  
    }

    private List<TaskDetailHolder> buildMap(List<Id> milestoneIds, Map<Id, List<Milestone1_Task__c>> tasksByMilestoneId) {
        List<TaskDetailHolder> taskDetailHolders = new List<TaskDetailHolder>();

        for (Id tempId : milestoneIds) {        
            List<Milestone1_Task__c> theTasks = tasksByMilestoneId.get(tempId);

            if (theTasks != null) {
                Boolean firstEntry = true;          
                for (Milestone1_Task__c tempTask : theTasks) {
                    String milestoneId = tempTask.Project_Milestone__r.id;
                    String milestoneName = null;
                    
                    if (firstEntry) {
                        milestoneName = tempTask.Project_Milestone__r.name;
                        firstEntry = false;
                    }
                    else {
                        milestoneName = null;                   
                    }
                    
                    String milestoneColor = computeMilestoneColor(tempTask);
                    String taskColor = computeTaskColor(tempTask);
                    
                    TaskDetailHolder tempTaskDetailHolder = new TaskDetailHolder(milestoneName, milestoneColor, tempTask, taskColor);
                    taskDetailHolders.add(tempTaskDetailHolder);                
                }
            }           
        }
        
        return taskDetailHolders;
    }
        
    private String computeMilestoneColor(Milestone1_Task__c theTask) {
        String color = null;
        
        if (theTask.Project_Milestone__r.Complete__c) {
            color = COMPLETE_COLOR;
        }
        else if (theTask.Project_Milestone__r.Blocked_Tasks_in_Tasks__c > 0 || theTask.Project_Milestone__r.Late_Tasks_in_Tasks__c > 0 || theTask.Project_Milestone__r.Deadline__c < Date.today()) {
            color = LATE_BLOCKED_COLOR;
        }
        else {
            color = OPEN_COLOR; 
        }
        
        return color;   
    }

    private String computeTaskColor(Milestone1_Task__c theTask) {
        String color = null;
        
        if (theTask.Complete__c) {
            color = COMPLETE_COLOR;
        }
        else if (theTask.Blocked__c || theTask.Due_Date__c < Date.today()) {
            color = LATE_BLOCKED_COLOR;
        }
        else {
            color = OPEN_COLOR; 
        }
        
        return color;   
    }
    
    private List<Milestone1_Milestone__c> loadMilestones(String projectId) {
        List<Milestone1_Milestone__c> theMilestones = [SELECT Id,
                                                           Name,
                                                           Deadline__c
                                                    FROM Milestone1_Milestone__c
                                                    WHERE Project__c = :projectId
                                                    ORDER BY Deadline__c
                                                   ];       
        return theMilestones;
    }
    
    private List<Milestone1_Task__c> getTasks(List<Id> milestoneIds) {
        List<Milestone1_Task__c> tasks = [SELECT Id,
                                                 Name,
                                                 Assigned_To__r.name,
                                                 Project_Milestone__r.id,
                                                 Project_Milestone__r.name,
                                                 Project_Milestone__r.Complete__c,
                                                 Project_Milestone__r.Late_Tasks_in_Tasks__c,
                                                 Project_Milestone__r.Blocked_Tasks_in_Tasks__c,
                                                 Project_Milestone__r.Deadline__c,
                                                 Complete__c,
                                                 Complete_Date__c,
                                                 Requires_Documentation__c,
                                                 Days_Late__c,
                                                 Blocked__c,
                                                 Due_Date__c
                                           FROM Milestone1_Task__c
                                           WHERE Project_Milestone__c IN :milestoneIds
                                           ORDER BY Due_Date__c
                                           ];   
        
        return tasks;
    }
    
    private List<Id> getMilestoneIds(List<Milestone1_Milestone__c> theMilestones) {
        List<Id> theIds = new List<Id>();
        
        for (Milestone1_Milestone__c tempProj : theMilestones) {
            theIds.add(tempProj.id);    
        }
        
        return theIds;          
    }
            
}