src/objects/Milestone1_Milestone__c.object
<CustomObject>
    <description>AstrumPM - Milestones are significant events that mark the phases in the life-cycle of a Project. Milestones can have tasks and sub-milestones associated with them.</description>
    <fields>
        <fullName>Complete_Date__c</fullName>
        <label>Complete Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This signifies that this milestone has been completed.</inlineHelpText>
        <label>Complete</label>
        <type>Checkbox</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Project Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone1_Project__c.object
<CustomObject>
    <description>AstrumPM - A solar installation project.  A project can have many milestones.</description>
    <fields>
        <fullName>Astrum_Office__c</fullName>
        <formula>TEXT(Sales_Order__r.OpportunityId__r.Property__r.Astrum_Office__c)</formula>
        <label>Astrum Office</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <formula>HYPERLINK( &quot;/&quot;+Sales_Order__r.OpportunityId__r.Property__r.Id  ,  Sales_Order__r.OpportunityId__r.Property__r.Name  )</formula>
        <label>Property</label>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone1_Task__c.object
<CustomObject>
    <description>AstrumPM - An activity that has hours, budget, and is assigned to a User.</description>
    <fields>
        <fullName>Complete_Date__c</fullName>
        <label>Complete Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>The status of this task. A task is either in-complete or complete.</inlineHelpText>
        <label>Complete</label>
        <type>Checkbox</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <description>AstrumPM/AstrumCRM - Each account can have one or more properties.  A property is defined by its street address.</description>
    <fields>
        <fullName>Astrum_Office__c</fullName>
        <label>Astrum Office</label>
        <picklist>
            <picklistValues>
                <fullName>Columbia, MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corona, CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cromwell, CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fresno, CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Henrietta, NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hopkinton, MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Long Island, NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middletown, NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Norristown, PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pennsauken, NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>San Diego, CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Simi Valley, CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Syracuse, NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Taunton, MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Westford, MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Youngstown, OH</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Optimal_Site_Quality_kWh_y_kW__c</fullName>
        <label>Optimal Site Quality (kWh/y/kW)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Permit_Jurisdiction__c</fullName>
        <description>Jurisdiction (county, township, etc) for property permitting</description>
        <label>Permit Jurisdiction</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_City__c</fullName>
        <label>Property City</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_County__c</fullName>
        <label>Property County</label>
        <picklist>
            <controllingField>Property_State__c</controllingField>
            <picklistValues>
                <fullName>Accomack</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adams</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alameda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albemarle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alcona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alexandria City</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alger</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allegan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allegany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alleghany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allegheny</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alpena</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alpine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amador</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amelia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amherst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anne Arundel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antrim</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apache</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appomattox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arenac</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arlington</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armstrong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ashland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ashtabula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Athens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Atlantic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auglaize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Howard</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>Property State</label>
        <picklist>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property_ZIP__c</fullName>
        <label>Property ZIP</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Address 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SCRB_SalesOrder__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The SalesOrder object is the result of a Closed Won Opportunity and handles the hand off from the sales team to the operations team.</description>
    <fields>
        <fullName>Astrum_Office__c</fullName>
        <description>Astrum Office serving this Property</description>
        <formula>TEXT(Property__r.Astrum_Office__c)</formula>
        <inlineHelpText>Astrum Office serving this Property</inlineHelpText>
        <label>Astrum Office</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Milestone1_Milestone_Autocomplete_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class Milestone1_Milestone_Autocomplete_Test {

    public static testMethod void testIsMilestoneReadyForAutoCompleteWhenOneTaskIsNotComplete() {

		// setup
		Milestone1_Milestone__c ms1 = createMilestone();	
				
        //create tasks linked to milestones
        Integer numberOfTasks = 3;
        List<Milestone1_Task__c> tasks = getSampleTasks(ms1, numberOfTasks, true);
		
		// change first task to incomplete
		tasks[0].Complete__c = false;
		tasks[0].Complete_Date__c = null;
		                				
		// execute		
        insert tasks;
		
		// assert
		Boolean expected = false;
		
		Milestone1_Milestone__c testMilestone = [Select Name, Complete__c, Complete_Date__c from Milestone1_Milestone__c where id = :ms1.id LIMIT 1];
		System.assertEquals(expected, testMilestone.Complete__c);
    }

    public static testMethod void testIsMilestoneReadyForAutoCompleteWhenNoTaskIsComplete() {

		// setup
		Milestone1_Milestone__c ms1 = createMilestone();	
				
        //create tasks linked to milestones
        Integer numberOfTasks = 3;        
        List<Milestone1_Task__c> tasks = getSampleTasksNotComplete(ms1, numberOfTasks);				                
				
		// execute		
        insert tasks;
		
		// assert
		Boolean expected = false;
		
		Milestone1_Milestone__c testMilestone = [Select Name, Complete__c, Complete_Date__c from Milestone1_Milestone__c where id = :ms1.id LIMIT 1];
		System.assertEquals(expected, testMilestone.Complete__c);
    }
	
    public static testMethod void testGetMilestonesForTasks() {

		Integer expectedSize = 1;
		
		// setup
		Milestone1_Milestone__c ms1 = createMilestone();	
				
        //create tasks linked to milestones
        Integer numberOfTasks = 3;        
        List<Milestone1_Task__c> tasks = getSampleTasksNotComplete(ms1, numberOfTasks);
        insert tasks;
				
		// execute
		Map<Id, Milestone1_Milestone__c> milestones = Milestone1_Task_Trigger_Utility.getMilestonesForTasks(tasks);
		Integer actualSize = milestones.values().size();
		
		// assert
		System.assertEquals(expectedSize, actualSize);
    }


    public static testMethod void testGetAllTasksForMilestones() {

		Integer expectedMilestoneCount = 1;
				
		// setup
		Milestone1_Milestone__c ms1 = createMilestone();	
				
        //create tasks linked to milestones
        Integer numberOfTasks = 3;        
        List<Milestone1_Task__c> tasks = getSampleTasksNotComplete(ms1, numberOfTasks);
        insert tasks;
				
		// execute
		List<Milestone1_Milestone__c> milestones = new List<Milestone1_Milestone__c>();
		milestones.add(ms1);
				
		Map<Id, List<Milestone1_Task__c>> milestoneMap = Milestone1_Task_Trigger_Utility.getAllTasksForMilestones(milestones);
		Integer milestoneCount = milestoneMap.keySet().size();
		
		Integer tasksCount = getTotalTaskCount(milestoneMap);
				
		// assert
		System.assertEquals(expectedMilestoneCount, milestoneCount);
		System.assertEquals(numberOfTasks, tasksCount);
    }
	
    
	private static Milestone1_Milestone__c createMilestone() {
        //create Property
        Property__c prop = new Property__c();
        prop.Name = '123 Main St';       
        prop.Optimal_Site_Quality_kWh_y_kW__c = double.valueOf('1250');
        prop.Property_State__c = 'MD';
        prop.Property_City__c = 'Annapolis Junction';
        prop.Property_ZIP__c = '20701';
        prop.Permit_Jurisdiction__c = 'Howard';
        prop.Property_County__c = 'Howard';
        prop.Astrum_Office__c = testdata.defaultOffLocationName;// FPO Phase4 //'Annapolis Junction, MD';
        insert prop;
        
        //create sales order
        SCRB_SalesOrder__c order = new SCRB_SalesOrder__c();
        order.name = 'SO-TEST';
        order.StatusCode__c = 'Submitted';
        order.Property__c = prop.id;
        
        insert order; 
	
        Milestone1_Project__c proj = new Milestone1_Project__c();
        proj.name = 'proj-test';
        proj.Sales_Order__c = order.id;        
        insert proj;
        
        //create a milestone
        Milestone1_Milestone__c ms1 = Milestone1_Test_Utility.sampleMilestone(proj);
		insert ms1;
		
		return ms1;
	}    
	
	private static Integer getTotalTaskCount(Map<Id, List<Milestone1_Task__c>> milestoneMap) {
		
		Integer tasksCount = 0;		
		for (Id tempMilestoneId : milestoneMap.keySet()) {
			List<Milestone1_Task__c> theTasks = milestoneMap.get(tempMilestoneId);
			tasksCount += theTasks.size();	
		}

		return tasksCount;		
	}
	
	private static List<Milestone1_Task__c> getSampleTasks(Milestone1_Milestone__c milestone, Integer numberOfTasks, Boolean allComplete) {
        List<Milestone1_Task__c> tasks = new List<Milestone1_Task__c>();
        
        for(Integer i = 0; i < numberOfTasks; i++){
            Id parentMilestoneId = milestone.Id;
            Milestone1_Task__c taskRec = Milestone1_Test_Utility.sampleTask(parentMilestoneId);
            tasks.add(taskRec);
			
			// complete the task 
			if (allComplete) {           
				taskRec.Complete__c = true;
				taskRec.Complete_Date__c = Date.today();
			}
        }
		
		return tasks;
	}
	
	private static List<Milestone1_Task__c> getSampleTasksNotComplete(Milestone1_Milestone__c milestone, Integer numberOfTasks) {
		Boolean complete = false;
		return getSampleTasks(milestone, numberOfTasks, complete);
	}
	
}