src/objects/Office_Location__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Main_Site__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Main Site</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rootstock_Division__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rootstock Division</label>
        <referenceTo>rstk__sydiv__c</referenceTo>
        <relationshipLabel>Office Locations</relationshipLabel>
        <relationshipName>Office_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State_Coverage__c</fullName>
        <description>Install States Covered by Astrum Office</description>
        <inlineHelpText>Install States Covered by Astrum Office</inlineHelpText>
        <label>State Coverage</label>
        <picklist>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Two-letter state code</description>
        <inlineHelpText>Two-letter state code</inlineHelpText>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Office Location</label>
    <nameField>
        <label>Office Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/State__c.object
<CustomObject>
    <description>Represents a State</description>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OfficeLocationTriggerTest.cls
/* FILE: OfficeLocationTriggerTest.cls
 * AUTHOR: Pavitra Burla
 * DATE: July 24, 2015
 * PURPOSE: Test for OfficeLocationTrigger
 */
@isTest(SeeAlldata=true)
public class OfficeLocationTriggerTest {

    static testmethod void mainSiteTest(){
    	
    	Id  divId;
        Office_Location__c existingOffLoc;
        try{
            existingOffLoc = [SELECT Rootstock_Division__c 
                                FROM Office_Location__c 
                                WHERE Rootstock_Division__c!= null 
                                AND Active__c = true 
                                AND Main_Site__c = true LIMIT 1];

        }catch(QueryException qe){}
        
        if(existingOffLoc == null){
            try{
                existingOffLoc = [SELECT Rootstock_Division__c 
                                FROM Office_Location__c 
                                WHERE Rootstock_Division__c!= null  LIMIT 1];

            }catch(QueryException qe){}
        }
        
        if(existingOffLoc == null){
            divId = [SELECT Id FROM rstk__sydiv__c limit 1].Id;
            existingOffLoc = new Office_Location__c(Name = 'Test Existing location, MD',Rootstock_Division__c = divId,Main_Site__c= true,Street__c = '345 test st', City__c = 'Annapolis Junction', State__c = 'MD', Zip_Code__c = '20701',State_Coverage__c = '', Location__Latitude__s = 39.125951, Location__Longitude__s = -76.794940, Active__c = true);
            insert existingOffLoc;
        }

        divId = existingOffLoc.Rootstock_Division__c;
        existingOffLoc.Active__c = true;
        existingOffLoc.Main_Site__c= true;
        update existingOffLoc;
        
        Office_Location__c testOffice1 = new Office_Location__c(Name = 'Test location1, MD',Rootstock_Division__c = divId,Street__c = '123 test st', City__c = 'Annapolis Junction', State__c = 'MD', Zip_Code__c = '20701',State_Coverage__c = '', Location__Latitude__s = 39.125951, Location__Longitude__s = -76.794940, Active__c = true);
        insert testOffice1;
        testOffice1 = [SELECT Id FROM Office_Location__c WHERE Id=:testOffice1.Id];
        System.assertNotEquals(null,testOffice1.Id);
        
        testOffice1.Main_Site__c=true;
        try{
        	//This will cause a dml exception since we can't have 2 office locations as main site with same div
        	update testOffice1;
        }catch(DmlException de){
            System.debug(loggingLevel.ERROR,'***In exception' + de.getMessage());

        }

        testOffice1 = [SELECT Main_Site__c FROM Office_Location__c WHERE Id=:testOffice1.Id];
        System.assertEquals(false,testOffice1.Main_Site__c);        
        
    }   

}