src/objects/Office_Location__c.object
<CustomObject>
    <fields>
        <fullName>Rootstock_Division__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rootstock Division</label>
        <referenceTo>rstk__sydiv__c</referenceTo>
        <relationshipLabel>Office Locations</relationshipLabel>
        <relationshipName>Office_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Office Location</label>
    <nameField>
        <label>Office Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PM_Project__c.object
<CustomObject>
    <description>Astrum PM 2.0 Project Object</description>
    <fields>
        <fullName>Inspection_Verified__c</fullName>
        <inlineHelpText>Inspection has been verified by either the VP of Ops or the Controller.</inlineHelpText>
        <label>Inspection Verified</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Install__c</fullName>
        <label>Install</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Job_Id__c</fullName>
        <description>Accounting Job Id</description>
        <formula>Sales_Order__r.Job_Id__c</formula>
        <inlineHelpText>Accounting Job Id</inlineHelpText>
        <label>Job Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proof_of_Inspection__c</fullName>
        <label>Proof of Inspection</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>SCRB_SalesOrder__c</referenceTo>
        <relationshipLabel>PM Projects</relationshipLabel>
        <relationshipName>PM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Completed__c</fullName>
        <label>Work Completed</label>
        <type>Date</type>
    </fields>
    <label>PM Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PM Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <description>AstrumPM/AstrumCRM - Each account can have one or more properties.  A property is defined by its street address.</description>
    <fields>
        <fullName>Astrum_Office_New__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Astrum Office Lookup</label>
        <referenceTo>Office_Location__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Address 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SCRB_SalesOrder__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The SalesOrder object is the result of a Closed Won Opportunity and handles the hand off from the sales team to the operations team.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Financing_Option__c</fullName>
        <description>What Type of Financing is This Customer Using?</description>
        <inlineHelpText>What Type of Financing is This Customer Using?</inlineHelpText>
        <label>Financing Option</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financing_Type__c</fullName>
        <description>Lease or Buy?</description>
        <inlineHelpText>Lease or Buy?</inlineHelpText>
        <label>Financing Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Id__c</fullName>
        <label>Job Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Close_Date__c</fullName>
        <label>Opportunity Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StatusCode__c</fullName>
        <label>Status Code</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>Submit Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Assigned to Sales Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Submit To Sales Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Coordinator Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Manager Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Coordinator Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final/Accounting Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Administrator Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated to VP Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VP Sales Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VP Sales Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Controller Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Proposal Creation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Proposal Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Ongoing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Controller Rejected - Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Admin Approved - Finance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>System_Makeup__c</fullName>
        <label>System Makeup</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>System_Size_kW__c</fullName>
        <label>System Size (kW)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PMProjectReport.cls
/* FILE: PMProjectReport.cls
 * AUTHOR: Pavitra Burla
 * DATE: Dec 30, 2015
 * PURPOSE: Controller for PMProjectReport page
 */
public class PMProjectReport {

    public String propertyType {get; set;}
    public Date startDate {get; set;}
    public Date endDate {get; set;}
    public Integer startRange {get; set;}
    public Integer endRange {get; set;}
    public String proofOfInspection {get; set;}
    transient public List<CustomReport> reportListHelper{get;set;}

    public PMProjectReport(){
        if(endRange == null){
            endRange = 100;
        }
        if(startRange == null){
            startRange = 0;
        }
        if(String.isBlank(proofOfInspection)){
            proofOfInspection = 'No';
        }
    }

    public Pagereference generateReport(){
        getRecords();
        return null;
    }
    
    public Pagereference exportToExcel(){
        Pagereference pr = new Pagereference('/apex/PMProjectExcelReport');
        getRecords();
        return pr;
    }

    public static List<SelectOption> getPropertyTypes(){
        List<SelectOption> options = new List<SelectOption>();

        Map<String, Schema.RecordTypeInfo> resultMap = Schema.SObjectType.Property__c.getRecordTypeInfosByName();
        options.add(new SelectOption('None','-- Select --'));
        for(String option:resultMap.keySet()){
            options.add(new SelectOption(option,option));
        }
        return options;
    }
    
    public class CustomReport{
        //Sales Order
        public SCRB_SalesOrder__c salesorder{get; private set;}        
        
        //Sales Invoice
        public Decimal salesInvoiceTotal {get; private set;}        

        public Decimal actualLabor {get;set;}
        public Decimal estimatedLabor {get;set;}
        public Decimal actualMaterial {get;set;}
        public Decimal estimatedMaterial {get;set;}
        public Decimal actualOther {get;set;}
        public Decimal estOther {get;set;}
        public Decimal percCompl {get;set;}

        public String projCreationDate {get;set;}
        public String opportunityCloseDate {get;set;}
        public String installDate {get;set;}
        public String workComplete {get;set;}
        public String proofOfInspection {get;set;}
        public String inspectionVerified {get;set;}
        
        public CustomReport(SCRB_SalesOrder__c salesorder){
            this.salesorder = salesorder;
            this.actualOther = 0.00;
            this.estOther = 0.00;
            this.percCompl = 0.00;
            this.actualLabor = 0.00;
            this.estimatedLabor = 0.00;
            this.actualMaterial = 0.00;
            this.estimatedMaterial = 0.00;
            this.salesInvoiceTotal = 0.00;
        }           
    }
    
    public void getRecords(){

        Map<Id,CustomReport> reportMap = new Map<Id,CustomReport>();
        Map<String,SCRB_SalesOrder__c> jobOrdersMap = new Map<String,SCRB_SalesOrder__c>();
        Date queryenddate;
        
        System.debug('***start date:' + startDate);
        System.debug('***end date:' + endDate);
        System.debug('***start range:' + startRange);
        System.debug('***end range:' + endRange);
        System.debug('***propertytype:' + propertyType);
        
        String query = 'SELECT Name';
        query+= ', CreatedDate';
        query+= ', Job_Id__c';
        query+= ', Property__r.Astrum_Office_New__r.Rootstock_Division__c';
        query+= ', Opportunity_Close_Date__c';
        query+= ', StatusCode__c';
        query+= ', Financing_Option__c';
        query+= ', System_Makeup__c';
        query+= ', System_Size_kW__c';
        query+= ', Property__r.Astrum_Office_New__r.Name'; 
        query+= ', Amount__c';
        query+= ', Property__r.RecordType.Name';
        query+= ', Financing_Type__c';
        query+= ', (SELECT Name';
        query+= '    , CreatedDate';
        query+= '    , Work_Completed__c';
        query+= '    , Install__c';        
        query+= '    , Proof_of_Inspection__c';
        query+= '    , Inspection_Verified__c'; 
        query+= '    FROM PM_Projects__r';

        if(proofOfInspection.equalsIgnoreCase('Yes')){
            query+= ' WHERE Proof_of_Inspection__c <> null)';
        }else{
            query+= ' WHERE Proof_of_Inspection__c = null)';
        }

        query+= ' FROM SCRB_SalesOrder__c';

        if(propertyType != 'None'){
            query+= ' WHERE Property__r.RecordType.Name =:propertyType';
            if(startDate != null){
                query+= ' AND CreatedDate >= :startDate';
            }
            if(endDate != null){
                queryenddate = endDate.addDays(1);                
                query+= ' AND CreatedDate < :queryenddate';
            }                        
        }else if(startDate != null){
            query+= ' WHERE CreatedDate >= :startDate';
            if(endDate != null){
                queryenddate = endDate.addDays(1);                
                query+= ' AND CreatedDate < :queryenddate';
            }
        }else if(endDate != null){
            queryenddate = endDate.addDays(1);                
            query+= ' WHERE CreatedDate < :queryenddate';
        } 

        query+= ' ORDER BY Job_Id__c DESC';
        if(Test.isRunningTest()){
            //query+= ' LIMIT 1';
        }
        System.debug(loggingLevel.ERROR,'***query:' + query);

        Map<Id,SCRB_SalesOrder__c> salesorderMap 
            = new Map<Id,SCRB_SalesOrder__c>((List<SCRB_SalesOrder__c>)Database.query(query));             
       
        //PM Projs
        for(SCRB_SalesOrder__c so:salesorderMap.values()){
            /*jobOrdersMap.put(so.Job_Id__c,so);
            reportMap.put(so.Id, new CustomReport(so));
            CustomReport report = reportMap.get(so.Id);
            if(so.Opportunity_Close_Date__c != null){
                report.opportunityCloseDate = so.Opportunity_Close_Date__c.format();
            }*/
            if(so.PM_Projects__r != null && so.PM_Projects__r.size() > 0){
                jobOrdersMap.put(so.Job_Id__c,so);
                reportMap.put(so.Id, new CustomReport(so));
                CustomReport report = reportMap.get(so.Id);
                if(so.Opportunity_Close_Date__c != null){
                    report.opportunityCloseDate = so.Opportunity_Close_Date__c.format();
                }

                report.projCreationDate = (so.PM_Projects__r[0].CreatedDate.format('MM/dd/YYYY'));                
                if(so.PM_Projects__r[0].Install__c != null){
                    report.installDate = so.PM_Projects__r[0].Install__c.format();
                }        
                if(so.PM_Projects__r[0].Work_Completed__c != null){
                    report.workComplete = so.PM_Projects__r[0].Work_Completed__c.format();
                }
                if(so.PM_Projects__r[0].Proof_of_Inspection__c != null){
                    report.proofOfInspection = so.PM_Projects__r[0].Proof_of_Inspection__c.format();
                }
                if(so.PM_Projects__r[0].Inspection_Verified__c != null){
                    report.inspectionVerified = so.PM_Projects__r[0].Inspection_Verified__c.format();
                }
            }        
        }
        
        //Invoices
        List<AggregateResult> invoices = [SELECT  Sales_Order__c, SUM(c2g__NetTotal__c) netTotal FROM c2g__codaInvoice__c WHERE Sales_Order__c IN:reportMap.keySet() GROUP BY Sales_Order__c];
        
        if(invoices!= null){
            for(AggregateResult result:invoices){
                reportMap.get((Id)result.get('Sales_Order__c')).salesInvoiceTotal = ((Decimal)result.get('netTotal')).setScale(2); 
            }
        }
        
        //ProjCst
        List<rstk__pjproj__c> projMasters = new List<rstk__pjproj__c>(); 
                
        projMasters = [SELECT Id,rstk__pjproj_div__c,rstk__pjproj_proj__c
                       , (SELECT rstk__pjprojcst_costs_subtot__c
                          , rstk__pjprojcst_budget_subtot__c
                          , rstk__pjprojcst_cstlab__c
                          , rstk__pjprojcst_cstmtl__c
                          , rstk__pjprojcst_baclab__c
                          , rstk__pjprojcst_bacmtl__c
                          FROM rstk__pjprojcsts__r)
                       FROM rstk__pjproj__c 
                       WHERE  rstk__pjproj_proj__c IN :jobOrdersMap.keySet()
                       AND rstk__pjproj_proj__c <> NULL];
        
        Decimal percentComplete = 0.00;
                 
        for(rstk__pjproj__c projMaster:projMasters){
            
            if( projMaster.rstk__pjproj_div__c  == jobOrdersMap.get(projMaster.rstk__pjproj_proj__c.capitalize()).Property__r.Astrum_Office_New__r.Rootstock_Division__c){
                 CustomReport report = reportMap.get(jobOrdersMap.get(projMaster.rstk__pjproj_proj__c.capitalize()).Id);
                 rstk__pjprojcst__c projCost = projMaster.rstk__pjprojcsts__r[0];
                 report.actualOther = (projCost.rstk__pjprojcst_costs_subtot__c - projCost.rstk__pjprojcst_cstlab__c - projCost.rstk__pjprojcst_cstmtl__c).setScale(2) ;
                 report.estOther = (projCost.rstk__pjprojcst_budget_subtot__c - projCost.rstk__pjprojcst_baclab__c - projCost.rstk__pjprojcst_bacmtl__c).setScale(2);
                 if(projCost.rstk__pjprojcst_budget_subtot__c != 0){                    
                    percentComplete = ((projCost.rstk__pjprojcst_costs_subtot__c)/ 
                        (projCost.rstk__pjprojcst_budget_subtot__c)) * 100;
                    report.percCompl = percentComplete<100?percentComplete.setScale(2):100;
                 }
                 report.actualLabor = projCost.rstk__pjprojcst_cstlab__c.setScale(2);
                 report.estimatedLabor = projCost.rstk__pjprojcst_baclab__c.setScale(2);
                 report.actualMaterial = projCost.rstk__pjprojcst_cstmtl__c.setScale(2);
                 report.estimatedMaterial = projCost.rstk__pjprojcst_bacmtl__c.setScale(2);
            }
        }

        //filter based on percent complete
        if(startRange!= null && endRange!=null){
            List<CustomReport> reportBasedOnPercCompl = new List<CustomReport>();        
            for(CustomReport report :reportMap.values()){
                if(report.percCompl >= startRange && report.percCompl <= endRange){
                    //System.debug('**perc compl' + report.percCompl + ':' + report.salesorder.Name);
                    reportBasedOnPercCompl.add(report);
                }
            }
            reportListHelper = reportBasedOnPercCompl;
            System.debug(reportListHelper.size());
            return;
        }
              
        reportListHelper = reportMap.values();
        System.debug(reportListHelper.size());
    }
}