src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Closed_Reason__c</fullName>
        <description>The reason for closing this opportunity.</description>
        <inlineHelpText>The reason for closing this opportunity.</inlineHelpText>
        <label>Closed Reason</label>
        <picklist>
            <controllingField>Closed_Type__c</controllingField>
            <picklistValues>
                <fullName>Site Quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cannot Afford/Borrow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ROI - Not Worth It</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HOA - Third Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aesthetics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Roof/Installation Problems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spouse Veto</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown/Unspecified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Offering - Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Offering - Financial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timeliness/Responsiveness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relationship with Rep/Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TSRF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insufficient Savings</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Portal_Referral__c.object
<CustomObject>
    <description>Referrals from the Partner Program website</description>
    <fields>
        <fullName>D2D_Lead_Status__c</fullName>
        <label>D2D Lead Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed - Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Generated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Opt-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Opt-Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Door Hanger</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing Utility Bill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA Visit 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA Visit 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passed Validation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Photos Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit Scheduled</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>D2D_Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>D2D Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Portal_Referrals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of referral</description>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Portal Referrals</relationshipLabel>
        <relationshipName>Portal_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Portal Referral</label>
    <nameField>
        <displayFormat>REF-{000000}</displayFormat>
        <label>Portal Referral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Site_Survey_Disqualified_Controller_Test.cls
@isTest
private class Site_Survey_Disqualified_Controller_Test {
    private static boolean runalltests = true; // true to run all tests; false to skip tests and only run those where the 'if' is commented out
	
	@isTest static void test_D2DEventDisqualified() {
		if(!runalltests){ return; }

		testData.setupCustomSettings();
		D2DTestUtility.InitializeRequiredMethods();

		D2DTestUtility.CreateManagerUsers(1);
		User d2dMg = D2DTestUtility.d2dManagerUsers[0];

		D2DTestUtility.CreateSalesRepUsers(1);
		User d2dSr = D2DTestUtility.d2dSalesRepUsers[0];

		Opportunity opp = Milestone1_Test_Utility.CreateTestOpp();

		Test.startTest();

		Event theEvent = createEvent(opp, true);

    	Portal_Referral__c referral = new Portal_Referral__c(
    		Last_Name__c = 'Test',
			D2D_Lead_Status__c = 'Visit Scheduled',
			D2D_Sales_Rep__c = d2dSr.Id,
			Opportunity__c = opp.Id
		);
		insert referral;

    	// execute
		ApexPages.Standardcontroller standController = new ApexPages.Standardcontroller(theEvent);
		Site_Survey_Disqualified_Controller_Ext controller = new Site_Survey_Disqualified_Controller_Ext(standController);
    	
    	// populate the response: Insufficient Savings, but no referral email will trigger an error
    	Integer pageMessageCount = ApexPages.getMessages().size();
    	controller.opp.Closed_Reason__c = 'Insufficient Savings';
    	controller.updateEventCompleted();
    	system.assertNotEquals(pageMessageCount, ApexPages.getMessages().size());

    	referral.Email__c = 'referral@email.com';
    	update referral;

    	// populate the response: Insufficient Savings
    	pageMessageCount = ApexPages.getMessages().size();
    	controller.opp.Closed_Reason__c = 'Insufficient Savings';
    	controller.updateEventCompleted();
    	system.assertEquals(pageMessageCount, ApexPages.getMessages().size());

    	// populate the response: TSRF
    	pageMessageCount = ApexPages.getMessages().size();
    	controller.opp.Closed_Reason__c = 'TSRF';
    	controller.updateEventCompleted();
    	system.assertEquals(pageMessageCount, ApexPages.getMessages().size());

    	Test.stopTest();
	}
	
	@isTest static void test_NonD2DEventDisqualified() {
		if(!runalltests){ return; }

		testData.setupCustomSettings();
		D2DTestUtility.InitializeRequiredMethods();

		Opportunity opp = Milestone1_Test_Utility.CreateTestOpp();

		Test.startTest();

		Event theEvent = createEvent(opp, false);
    	
    	// execute
		ApexPages.Standardcontroller standController = new ApexPages.Standardcontroller(theEvent);
		Site_Survey_Disqualified_Controller_Ext controller = new Site_Survey_Disqualified_Controller_Ext(standController);

		// No response to closed reason
    	Integer pageMessageCount = ApexPages.getMessages().size();
    	controller.updateEventCompleted();
    	system.assertNotEquals(pageMessageCount, ApexPages.getMessages().size());

    	Test.stopTest();
	}

	private static Event createEvent(Opportunity opp, Boolean isD2D) {

		Event tempEvent = new Event();
		tempEvent.OwnerId = UserInfo.getUserId();
		  
		tempEvent.Subject = 'Test';
		tempEvent.StartDateTime = Datetime.now();
		tempEvent.EndDateTime = Datetime.now().addDays(14);
		tempEvent.WhatId = opp.Id;
		tempEvent.D2D_Survey_Request__c = isD2D;

		insert tempEvent;			
	
		return tempEvent;
	}
}