src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Property_City__c</fullName>
        <description>Initially used in code to cut back on extra SOQL queries in triggers.</description>
        <formula>Property__r.Property_City__c</formula>
        <label>Property City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_County__c</fullName>
        <formula>TEXT(Property__r.Property_County__c)</formula>
        <label>Property County</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <formula>TEXT(Property__r.Property_State__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Zip__c</fullName>
        <description>Initially used in code to cut back on extra SOQL queries in triggers.</description>
        <formula>Property__r.Property_ZIP__c</formula>
        <label>Property Zip</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Property__c.Property_Owner__r.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QAS_Property_County__c</fullName>
        <description>Initially used in code to cut back on extra SOQL queries in triggers.</description>
        <formula>Property__r.QAS_Property_County__c</formula>
        <label>QAS Property County</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Design_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>System Design Quote</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>System_Design_Quote__c.System_Design__r.Property__c</field>
                <operation>equals</operation>
                <valueField>$Source.Property__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>System_Design_Quote__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <description>AstrumPM/AstrumCRM - Each account can have one or more properties.  A property is defined by its street address.</description>
    <fields>
        <fullName>Property_City__c</fullName>
        <label>Property City</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_County__c</fullName>
        <label>Property County</label>
        <picklist>
            <controllingField>Property_State__c</controllingField>
            <picklistValues>
                <fullName>Accomack</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adams</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alameda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albemarle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alcona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alexandria City</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alger</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allegan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allegany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alleghany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allegheny</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alpena</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alpine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amador</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amelia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amherst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anne Arundel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antrim</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apache</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appomattox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arenac</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arlington</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armstrong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ashland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ashtabula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Athens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Atlantic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auglaize</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account that represents the Owner of this Building.  This may be a Family or a Business.</description>
        <label>Property Owner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>Property State</label>
        <picklist>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property_ZIP__c</fullName>
        <label>Property ZIP</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QAS_Property_County__c</fullName>
        <description>Auto-Populated County From QAS</description>
        <inlineHelpText>Auto-Populated County From QAS</inlineHelpText>
        <label>QAS Property County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utility_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>DEPRECATED AS OF 11/25/14</description>
        <label>Utility Rate Code</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Utility_Company__c.RecordType.Name</field>
                <operation>notEqual</operation>
                <value>Custom</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Utility_Company__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Address 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/System_Design_Quote__c.object
<CustomObject>
    <description>AstrumCRM - System Design Quote.  Each System Design can have one or more System Design Quotes.  Each quote provides the sales consultant with the ability to adjust the negotiated price of the System Design based on the Calculated System Price.  Opportunities must choose a winning System Design Quote in order to close.</description>
    <fields>
        <fullName>CPF_Customer_Id__c</fullName>
        <label>CPF Customer Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CPF_Eligibility_Initiate_Message__c</fullName>
        <label>CPF Eligibility Initiate Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CPF_Eligibility_Initiate__c</fullName>
        <label>CPF Eligibility Initiate</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_City__c</fullName>
        <description>Initially used in code to cut back on extra SOQL queries in triggers.</description>
        <formula>System_Design__r.Property__r.Property_City__c</formula>
        <label>Property City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_County__c</fullName>
        <description>Initially used in code to cut back on extra SOQL queries in triggers.</description>
        <formula>text(System_Design__r.Property__r.Property_County__c)</formula>
        <label>Property County</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <description>Initially used in code to cut back on extra SOQL queries in triggers.</description>
        <formula>text(System_Design__r.Property__r.Property_State__c)</formula>
        <label>Property State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Zip__c</fullName>
        <description>Initially used in code to cut back on extra SOQL queries in triggers.</description>
        <formula>System_Design__r.Property__r.Property_ZIP__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property Zip</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QAS_Property_County__c</fullName>
        <description>Initially used in code to cut back on extra SOQL queries in triggers.</description>
        <formula>System_Design__r.Property__r.QAS_Property_County__c</formula>
        <label>QAS Property County</label>
        <type>Text</type>
    </fields>
    <label>System Design Quote</label>
    <nameField>
        <displayFormat>SDQ-{0}</displayFormat>
        <label>System Design Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Design Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility_Company__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - Each Utility Service is attached to a single Utility Company.</description>
    <label>Utility Rate Code</label>
    <nameField>
        <label>Utility Rate Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Rate Codes</pluralLabel>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CPFRequestCreditController.cls
// Commented by RJ 05/5/2015
public with sharing class CPFRequestCreditController {

    /*
    private opportunity opty;

    // The extension constructor initializes the private member
    // variable mysObject by using the getRecord method from the standard
    // controller.
    public CPFRequestCreditController (ApexPages.StandardController stdController) {
        this.opty = (Opportunity)stdController.getRecord();
        opty = [Select AccountId,System_Design_Quote__c,System_Design_Quote__r.CPF_Eligibility_Initiate__c, System_Design_Quote__r.CPF_Customer_Id__c
                      ,Property__r.QAS_Property_County__c, Property__r.Property_County__c, Property__r.Property_ZIP__c
                      ,Property__r.Property_State__c, Property__r.Property_City__c, Property__r.Name, Property__c , Property__r.Property_Owner__c
                      ,Property__r.Utility_Company__r.Name,Property__r.Utility_Company__c
                 from Opportunity 
                Where Id = :opty.Id];
    }

    public PageReference initiateCreditCheck() {
        PageReference requestPage = Page.LeaseFundDetailSoap;  
        System_Design_Quote__c sdq;     
        // Check if Opportunity is linked to SDQ 
        if(opty.System_Design_Quote__c == null )
        {        
            requestPage.getParameters().put('leadsent','CSDQ');
            requestPage.setRedirect(true);
            return requestPage;     
        }

        // Check if Utility is associated
        if(opty.Property__r.Utility_Company__c == null )
        {        
            requestPage.getParameters().put('leadsent','NPU');
            requestPage.setRedirect(true);
            return requestPage;     
        }
        // Check if Credit Request is already being sent
        if(opty.System_Design_Quote__r.CPF_Eligibility_Initiate__c == 'success')
        {        
            PageReference requestPage1 = Page.CPFResendCreditRequest;
            requestPage1.getParameters().put('id',opty.Id);
            requestPage1.setRedirect(true);
            return requestPage1;     
        }

        // Check if CPF Customer Exists
        if(opty.System_Design_Quote__r.CPF_Customer_Id__c == null || opty.System_Design_Quote__r.CPF_Customer_Id__c == '' )
        {        
            requestPage.getParameters().put('leadsent','CCN');
            requestPage.setRedirect(true);
            return requestPage;     
        }
        else
        {
            sdq = [Select CPF_Eligibility_Initiate__c,CPF_Eligibility_Initiate_Message__c,CPF_Customer_Id__c 
                                           From System_Design_Quote__c 
                                          Where Id = :opty.System_Design_Quote__c];

            CPFIntegrationProcessor cpi = new CPFIntegrationProcessor();
            sdq = cpi.initiateCPFElligibility(sdq,false);
            update sdq;
        }
        PageReference sdqPage = new PageReference('/'+sdq.Id);     
        sdqPage.setRedirect(true); 
        return sdqPage;
    }
    
    public PageReference ResendCreditRequest() {
        PageReference requestPage = Page.LeaseFundDetailSoap;   
        System_Design_Quote__c sdq;    
        // Check if Opportunity is linked to SDQ 
        if(opty.System_Design_Quote__c == null )
        {        
            requestPage.getParameters().put('leadsent','NSDQ');
            requestPage.setRedirect(true);
            return requestPage;     
        }

        // Check if Utility is associated
        if(opty.Property__r.Utility_Company__c == null )
        {        
            requestPage.getParameters().put('leadsent','NPU');
            requestPage.setRedirect(true);
            return requestPage;     
        }        

        // Check if CPF Customer Exists
        if(opty.System_Design_Quote__r.CPF_Customer_Id__c == null || opty.System_Design_Quote__r.CPF_Customer_Id__c == '' )
        {        
            requestPage.getParameters().put('leadsent','CCN');
            requestPage.setRedirect(true);
            return requestPage;     
        }
        else
        {
            sdq = [Select CPF_Eligibility_Initiate__c,CPF_Eligibility_Initiate_Message__c,CPF_Customer_Id__c 
                                           From System_Design_Quote__c 
                                          Where Id = :opty.System_Design_Quote__c];

            CPFIntegrationProcessor cpi = new CPFIntegrationProcessor();
            sdq = cpi.initiateCPFElligibility(sdq,true);
            update sdq;
        }
        PageReference sdqPage = new PageReference('/'+sdq.Id);     
        sdqPage.setRedirect(true); 
        return sdqPage;
    }
    
    */
    
}