src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Property__c.Property_Owner__r.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PM_Project__c.object
<CustomObject>
    <description>Astrum PM 2.0 Project Object</description>
    <fields>
        <fullName>Handoff_Bridge_Model_Number__c</fullName>
        <description>Model number of communication bridge installed</description>
        <inlineHelpText>Model number of communication bridge installed</inlineHelpText>
        <label>Handoff Bridge Model Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Handoff_Bridge_Type__c</fullName>
        <label>Handoff Bridge Type</label>
        <picklist>
            <picklistValues>
                <fullName>Powerline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wireless</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>One Antenna Ubiquiti</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Two Antenna Ubiquiti</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tenda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Handoff_Check_list_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Handoff Check list Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Handoff_Checklist_Comments__c</fullName>
        <label>Handoff Checklist Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Handoff_Checklist_Completion_Date__c</fullName>
        <description>Handoff Checklist Completion Date</description>
        <inlineHelpText>Handoff Checklist Completion Date</inlineHelpText>
        <label>Handoff Checklist Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Handoff_Checklist_Status__c</fullName>
        <label>Handoff Checklist Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Verified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Handoff Email Sent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Handoff_Checklist_Verification_Date__c</fullName>
        <label>Handoff Checklist Verification Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Handoff_Customer_Care_Comments__c</fullName>
        <description>Comments by Customer Care</description>
        <inlineHelpText>Comments by Customer Care</inlineHelpText>
        <label>Handoff Customer Care Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Handoff_Dedicate_Outlet_Breaker_Location__c</fullName>
        <label>Handoff Dedicate Outlet Breaker Location</label>
        <picklist>
            <picklistValues>
                <fullName>Main Panel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PV Sub Panel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PV Combiner Panel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Handoff_Dedicated_Outlet_for_Envoy__c</fullName>
        <label>Handoff Dedicated Outlet for Envoy</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Handoff_Dedicated_Outlet_is_GFCI__c</fullName>
        <description>Is the dedicated electrical outlet for Envoy GFCI ?</description>
        <inlineHelpText>Is the dedicated electrical outlet for Envoy GFCI ?</inlineHelpText>
        <label>Handoff Dedicated Outlet is GFCI</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Handoff_Distance_to_Mail_Supply_ft__c</fullName>
        <label>Handoff Distance to Mail Supply (ft.)</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Handoff_Email_Sent_Date__c</fullName>
        <label>Handoff Email Sent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Handoff_Enlighten_Activated__c</fullName>
        <label>Handoff Enlighten Activated</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Handoff_Enlighten_Verification_Date__c</fullName>
        <description>Date that Project Lead confirmed Enlighten design and registration was completed correctly with no alerts present</description>
        <inlineHelpText>Date that Project Lead confirmed Enlighten design and registration was completed correctly with no alerts present</inlineHelpText>
        <label>Handoff Enlighten Verification Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Handoff_Enphase_ID__c</fullName>
        <description>ID of system in Enphase Enlighten portal</description>
        <inlineHelpText>ID of system in Enphase Enlighten portal</inlineHelpText>
        <label>Handoff Enphase ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Handoff_Envoy_Location_Explanation__c</fullName>
        <description>If not next to panel, explanation of location</description>
        <inlineHelpText>If not next to panel, explanation of location</inlineHelpText>
        <label>Handoff Envoy Location Explanation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Handoff_Envoy_Location__c</fullName>
        <label>Handoff Envoy Location</label>
        <picklist>
            <picklistValues>
                <fullName>Immediately next to panel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not immediately next to panel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Handoff_Is_Internet_Access__c</fullName>
        <label>Handoff Is Internet Access</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Handoff_Other_Big_Ticket_Electrical__c</fullName>
        <description>Other Big Ticket Electrical Item Type</description>
        <inlineHelpText>Other Big Ticket Electrical Item Type</inlineHelpText>
        <label>Handoff Other Big Ticket Electrical</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Handoff_Other_Bridge_Install_Type__c</fullName>
        <description>Type of communication bridge installed if not one of the options on Bridge Type picklist</description>
        <inlineHelpText>Type of communication bridge installed if not one of the options on Bridge Type picklist</inlineHelpText>
        <label>Handoff Other Bridge Install Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Handoff_Other_Internet_Access_Type__c</fullName>
        <description>Type of internet connection if not one of the options on Type of Internet Access picklist</description>
        <inlineHelpText>Type of internet connection if not one of the options on Type of Internet Access picklist</inlineHelpText>
        <label>Handoff Other Internet Access Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Handoff_Other_Outlet_Breaker_Location__c</fullName>
        <label>Handoff Other Outlet Breaker Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Handoff_Other_Revenue_Grade_Meter_Make__c</fullName>
        <description>Name of Manufacturer of Revenue Grade Meter</description>
        <inlineHelpText>Name of Manufacturer of Revenue Grade Meter</inlineHelpText>
        <label>Handoff Other Revenue Grade Meter Make</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Handoff_Other_Revenue_Grade_Meter_Model__c</fullName>
        <description>Model Number of Revenue Grade Meter</description>
        <inlineHelpText>Model Number of Revenue Grade Meter</inlineHelpText>
        <label>Handoff Other Revenue Grade Meter Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Handoff_Other_System_Location__c</fullName>
        <description>Location of system if not one of the options on picklist of System Location</description>
        <inlineHelpText>Location of system if not one of the options on picklist of System Location</inlineHelpText>
        <label>Handoff Other System Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Handoff_Revenue_Grade_Meter_Installed__c</fullName>
        <label>Handoff Revenue Grade Meter Installed</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Handoff_Revenue_Grade_Meter_Type__c</fullName>
        <label>Handoff Revenue Grade Meter Type</label>
        <picklist>
            <picklistValues>
                <fullName>Enphase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Locus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hialeah</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Itron</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Handoff_System_Location__c</fullName>
        <label>Handoff System Location</label>
        <picklist>
            <picklistValues>
                <fullName>Main House</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Garage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ground Mount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Handoff_Type_of_Internet_Access__c</fullName>
        <description>Type of internet connection used by homeowner</description>
        <inlineHelpText>Type of internet connection used by homeowner</inlineHelpText>
        <label>Handoff Type of Internet Access</label>
        <picklist>
            <picklistValues>
                <fullName>Wireless/Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WiFi/Air Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PM Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PM Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SCRB_SalesOrder__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The SalesOrder object is the result of a Closed Won Opportunity and handles the hand off from the sales team to the operations team.</description>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>R00N300000011q88EAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProjectHandoffTest.cls
/* FILE: ProjectHandoffTest.cls
 * AUTHOR: Rohit Jain
 * DATE: June 4, 2013
 * PURPOSE: Test class for ChangeRequest Process
 * MODIFICATION HISTORY:
 *
 */

@isTest(seeAllData=true)
public class ProjectHandoffTest{

    
  static testMethod void Project_Handoff_Verify_Test() {
    
    Account customer = new Account(Name = 'Test Customer');
    insert customer;
    Property__c property = CreateAstrumPM2ProjectTest.createProperty(customer.Id, '123 Test St');
    Opportunity opp = CreateAstrumPM2ProjectTest.createOpportunity(customer.Id, 'Test Oppty');    
    SCRB_SalesOrder__c salesOrder = CreateAstrumPM2ProjectTest.createSalesOrder(property.Id, opp.Id);
    salesOrder.AccountId__c = customer.Id;
    update salesOrder;
    
    Test.setCurrentPage(Page.CreateAstrumPM2Project);
    ApexPages.StandardController controller = new ApexPages.StandardController(salesOrder);
    //CreateAstrumPM2ProjectExtension extension = new CreateAstrumPM2ProjectExtension(controller);
    //PageReference result = extension.createProject();
    //String projectId = result.getUrl().substring(1);  
    
    RootstockAutomation amr = new RootstockAutomation();
    String projectId = amr.createProject(salesOrder );
    
    PM_Project__C pmprj = [Select p.Handoff_Type_of_Internet_Access__c, p.Handoff_System_Location__c, p.Handoff_Revenue_Grade_Meter_Type__c
    , p.Handoff_Revenue_Grade_Meter_Installed__c, p.Handoff_Other_System_Location__c, p.Handoff_Other_Revenue_Grade_Meter_Model__c
    , p.Handoff_Other_Revenue_Grade_Meter_Make__c, p.Handoff_Other_Outlet_Breaker_Location__c, p.Handoff_Other_Internet_Access_Type__c
    , p.Handoff_Other_Bridge_Install_Type__c, p.Handoff_Other_Big_Ticket_Electrical__c, p.Handoff_Is_Internet_Access__c
    , p.Handoff_Envoy_Location__c, p.Handoff_Envoy_Location_Explanation__c, p.Handoff_Enphase_ID__c, p.Handoff_Enlighten_Verification_Date__c
    , p.Handoff_Enlighten_Activated__c, p.Handoff_Email_Sent_Date__c, p.Handoff_Distance_to_Mail_Supply_ft__c, p.Handoff_Dedicated_Outlet_is_GFCI__c
    , p.Handoff_Dedicated_Outlet_for_Envoy__c, p.Handoff_Dedicate_Outlet_Breaker_Location__c, p.Handoff_Customer_Care_Comments__c
    , p.Handoff_Checklist_Verification_Date__c, p.Handoff_Checklist_Status__c, p.Handoff_Checklist_Completion_Date__c, p.Handoff_Checklist_Comments__c
    , p.Handoff_Check_list_Completed__c, p.Handoff_Bridge_Type__c, p.Handoff_Bridge_Model_Number__c, p.Handoff_Bridge_Installed__c
    , p.Handoff_Big_Ticket_Electrical_Type__c, p.Handoff_Big_Ticket_Electrical_Item__c From PM_Project__c p where id = :projectId ];
     
    Test.startTest();
    Test.setCurrentPage(Page.ProjectHandoff);
    controller = new ApexPages.StandardController(pmprj);
    ProjectHandoffExtension phe = new ProjectHandoffExtension (controller);
    
    PageReference result1 = phe.checkListCompleted(); 
     phe.pmproject.Handoff_System_Location__c = 'Other';
    result1 = phe.checkListCompleted();     
    System.assert(phe.errorfields.contains('[1]')); 
    phe.pmproject.Handoff_System_Location__c = 'Garage';
    result1 = phe.checkListCompleted();     
    System.assert(phe.errorfields.contains('[1]')); 
    phe.pmproject.Handoff_System_Location__c = 'Main House';
    result1 = phe.checkListCompleted();     
    System.assert(phe.errorfields.contains('[1]'));        

    phe.pmproject.Handoff_Is_Internet_Access__c  = 'Yes';
    result1 = phe.checkListCompleted();     
    System.assert(phe.errorfields.contains('[1]'));

    phe.pmproject.Handoff_Is_Internet_Access__c  = 'No';
    result1 = phe.checkListCompleted();     
    System.assert(phe.errorfields.contains('[1]'));
    
    
    phe.pmproject.Handoff_Bridge_Installed__c = 'Yes';
    result1 = phe.checkListCompleted();     
    System.assert(phe.errorfields.contains('[1]'));
    
    phe.pmproject.Handoff_Bridge_Installed__c = 'No';
    result1 = phe.checkListCompleted();     
    System.assert(phe.errorfields.contains('[1]'));
    
    phe.pmproject.Handoff_Envoy_Location__c = 'Immediately next to panel';
    result1 = phe.checkListCompleted();     
    System.assert(phe.errorfields.contains('[1]'));
    
    phe.pmproject.Handoff_Dedicate_Outlet_Breaker_Location__c  = 'Main Panel';
    result1 = phe.checkListCompleted();     
    System.assert(phe.errorfields.contains('[1]')); 
    
    
    phe.pmproject.Handoff_Dedicated_Outlet_for_Envoy__c  = 'Yes';
    result1 = phe.checkListCompleted();     
    System.assert(phe.errorfields.contains('[1]'));
    
    phe.pmproject.Handoff_Dedicated_Outlet_for_Envoy__c  = 'No';
    result1 = phe.checkListCompleted();     
    System.assert(phe.errorfields.contains('[1]'));
    
    phe.pmproject.Handoff_Revenue_Grade_Meter_Installed__c  = 'Yes';
    result1 = phe.checkListCompleted();     
    System.assert(phe.errorfields.contains('[1]'));
    
    phe.pmproject.Handoff_Revenue_Grade_Meter_Installed__c  = 'No';
    result1 = phe.checkListCompleted();     
    System.assert(phe.errorfields.contains('[1]'));
    
    
    phe.pmproject.Handoff_Big_Ticket_Electrical_Item__c  = 'Yes';
    result1 = phe.checkListCompleted();     
    System.assert(phe.errorfields.contains('[1]'));
    
    phe.pmproject.Handoff_Big_Ticket_Electrical_Type__c = 'Pool';
    result1 = phe.checkListCompleted();     
    System.assert(phe.errorfields.contains('[1]'));
    
    phe.pmproject.Handoff_Big_Ticket_Electrical_Item__c  = 'No';
    result1 = phe.checkListCompleted();     
    System.assert(phe.errorfields.contains('[1]'));
    phe.pmproject.Handoff_Enlighten_Activated__c =  'No';
    
    phe.pmproject.Handoff_Enlighten_Verification_Date__c = System.Today();
    phe.pmproject.Handoff_Enphase_ID__c  = '1234';
   
    
    PageReference result2 = phe.SavePage(); 
    
    PageReference result3 = phe.checkListCompleted(); 
    PageReference result4 = phe.verifyChecklist(); 
    
    String retUrl = phe.getReturnURL();
    
    ApexPages.currentPage().getParameters().put('emailsent', 'true'); 
    phe.updateProject();
    
    Test.stopTest(); 
      
  }
  
  static testMethod void Project_Handoff_NotVerify_Test() {
    
    Account customer = new Account(Name = 'Test Customer');
    insert customer;
    Property__c property = CreateAstrumPM2ProjectTest.createProperty(customer.Id, '123 Test St');
    Opportunity opp = CreateAstrumPM2ProjectTest.createOpportunity(customer.Id, 'Test Oppty');    
    SCRB_SalesOrder__c salesOrder = CreateAstrumPM2ProjectTest.createSalesOrder(property.Id, opp.Id);
    salesOrder.AccountId__c = customer.Id;
    update salesOrder;
    
    Test.setCurrentPage(Page.CreateAstrumPM2Project);
    ApexPages.StandardController controller = new ApexPages.StandardController(salesOrder);
    //CreateAstrumPM2ProjectExtension extension = new CreateAstrumPM2ProjectExtension(controller);
    //PageReference result = extension.createProject();
    //String projectId = result.getUrl().substring(1);  
    
    RootstockAutomation amr = new RootstockAutomation();
    String projectId = amr.createProject(salesOrder );
    
    PM_Project__C pmprj = [Select p.Handoff_Type_of_Internet_Access__c, p.Handoff_System_Location__c, p.Handoff_Revenue_Grade_Meter_Type__c
    , p.Handoff_Revenue_Grade_Meter_Installed__c, p.Handoff_Other_System_Location__c, p.Handoff_Other_Revenue_Grade_Meter_Model__c
    , p.Handoff_Other_Revenue_Grade_Meter_Make__c, p.Handoff_Other_Outlet_Breaker_Location__c, p.Handoff_Other_Internet_Access_Type__c
    , p.Handoff_Other_Bridge_Install_Type__c, p.Handoff_Other_Big_Ticket_Electrical__c, p.Handoff_Is_Internet_Access__c
    , p.Handoff_Envoy_Location__c, p.Handoff_Envoy_Location_Explanation__c, p.Handoff_Enphase_ID__c, p.Handoff_Enlighten_Verification_Date__c
    , p.Handoff_Enlighten_Activated__c, p.Handoff_Email_Sent_Date__c, p.Handoff_Distance_to_Mail_Supply_ft__c, p.Handoff_Dedicated_Outlet_is_GFCI__c
    , p.Handoff_Dedicated_Outlet_for_Envoy__c, p.Handoff_Dedicate_Outlet_Breaker_Location__c, p.Handoff_Customer_Care_Comments__c
    , p.Handoff_Checklist_Verification_Date__c, p.Handoff_Checklist_Status__c, p.Handoff_Checklist_Completion_Date__c, p.Handoff_Checklist_Comments__c
    , p.Handoff_Check_list_Completed__c, p.Handoff_Bridge_Type__c, p.Handoff_Bridge_Model_Number__c, p.Handoff_Bridge_Installed__c
    , p.Handoff_Big_Ticket_Electrical_Type__c, p.Handoff_Big_Ticket_Electrical_Item__c From PM_Project__c p where id = :projectId ];
     
    Test.startTest();
    Test.setCurrentPage(Page.ProjectHandoff);
    controller = new ApexPages.StandardController(pmprj);
    ProjectHandoffExtension phe = new ProjectHandoffExtension (controller);
    
         
   
    phe.pmproject.Handoff_System_Location__c = 'Main House';
    phe.pmproject.Handoff_Is_Internet_Access__c  = 'No';
    phe.pmproject.Handoff_Bridge_Installed__c = 'No';  
    phe.pmproject.Handoff_Envoy_Location__c = 'Immediately next to panel';    
    phe.pmproject.Handoff_Dedicate_Outlet_Breaker_Location__c  = 'Main Panel';
       
    phe.pmproject.Handoff_Dedicated_Outlet_for_Envoy__c  = 'No';
       
    phe.pmproject.Handoff_Revenue_Grade_Meter_Installed__c  = 'No';
       
    phe.pmproject.Handoff_Big_Ticket_Electrical_Item__c  = 'No';
   
    phe.pmproject.Handoff_Enlighten_Activated__c =  'No';
    
    phe.pmproject.Handoff_Enlighten_Verification_Date__c = System.Today();
    phe.pmproject.Handoff_Enphase_ID__c  = '1234';
   
    
    PageReference result2 = phe.SavePage(); 
    
    PageReference result3 = phe.checkListCompleted(); 
    PageReference result4 = phe.rejectChecklist(); 
    System.assert(phe.errorfields.contains('[1]'));
    phe.pmproject.Handoff_Customer_Care_Comments__c = 'Test';
    result4 = phe.rejectChecklist();
    
    Test.stopTest(); 
      
  }
}