src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Financing_Type__c</fullName>
        <description>Will the Customer Purchase or Lease This System?</description>
        <inlineHelpText>Will the Customer Purchase or Lease This System?</inlineHelpText>
        <label>Purchase/Lease</label>
        <picklist>
            <picklistValues>
                <fullName>Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lease</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Property__c.Property_Owner__r.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Region__c</fullName>
        <label>Sales Region</label>
        <picklist>
            <picklistValues>
                <fullName>MA Region</fullName>
                <color>#FFCC66</color>
            </picklistValues>
            <picklistValues>
                <fullName>MD Region</fullName>
                <color>#6600CC</color>
            </picklistValues>
            <picklistValues>
                <fullName>NYC Region</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>OH Region</fullName>
                <color>#3366FF</color>
            </picklistValues>
            <picklistValues>
                <fullName>PA Region</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>WNY Region</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <picklistValues>
                <fullName>CA Region</fullName>
                <color>#006600</color>
            </picklistValues>
            <picklistValues>
                <fullName>CT Region</fullName>
                <color>#33FFFF</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <description>AstrumPM/AstrumCRM - Each account can have one or more properties.  A property is defined by its street address.</description>
    <fields>
        <fullName>Sales_Region__c</fullName>
        <label>Sales Region</label>
        <picklist>
            <picklistValues>
                <fullName>CA Region</fullName>
                <color>#006600</color>
            </picklistValues>
            <picklistValues>
                <fullName>CT Region</fullName>
                <color>#33FFFF</color>
            </picklistValues>
            <picklistValues>
                <fullName>MA Region</fullName>
                <color>#FFCC66</color>
            </picklistValues>
            <picklistValues>
                <fullName>MD Region</fullName>
                <color>#6600CC</color>
            </picklistValues>
            <picklistValues>
                <fullName>NJ Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NYC Region</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>OH Region</fullName>
                <color>#3366FF</color>
            </picklistValues>
            <picklistValues>
                <fullName>PA Region</fullName>
                <color>#33CC00</color>
            </picklistValues>
            <picklistValues>
                <fullName>WNY Region</fullName>
                <color>#FFFF66</color>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Address 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OpportunitySalesRegionTriggerTest.cls
/* FILE: OpportunitySalesRegionTriggerTest.cls
 * AUTHOR: Tino Mattheou
 * DATE: August 16, 2012
 * PURPOSE: Test class for OpportunitySalesRegion trigger
 * MODIFICATION HISTORY
 *
 */
 
@isTest(seeAllData=true)
public class OpportunitySalesRegionTriggerTest {
	
	static testMethod void newOpp_insert_SalesRegionSet() {
		
		Account customer = new Account(Name = 'Test Customer');
		insert customer;
		Property__c property =  CreateAstrumPM2ProjectTest.createProperty(customer.Id, '123 Test St');
		property.Sales_Region__c = 'TEST Region';
		update property;
		
		Test.startTest();

		Opportunity opp = new Opportunity(
			Name = 'ABC123',
			AccountId = customer.Id,
			StageName = 'Test',
			CloseDate = System.today().addDays(-8),
			Financing_Type__c = 'Lease',
			Property__c = property.Id
		);
		
		insert opp;
		
		Test.stopTest();
		
		opp = [SELECT Id, Sales_Region__c FROM Opportunity WHERE Id = :opp.Id];
		System.assertEquals(property.Sales_region__c, opp.Sales_Region__c);
		
	}
	
	static testMethod void bypassTriggers_insert_SalesRegionNotSet() {
		
		Account customer = new Account(Name = 'Test Customer');
		insert customer;
		Property__c property =  CreateAstrumPM2ProjectTest.createProperty(customer.Id, '123 Test St');
		property.Sales_Region__c = 'TEST Region';
		update property;
		
		Test.startTest();

		SalesRegionHelper.bypassSalesRegionTriggers = true;
		
		Opportunity opp = new Opportunity(
			Name = 'ABC123',
			AccountId = customer.Id,
			StageName = 'Test',
			CloseDate = System.today().addDays(-8),
			Financing_Type__c = 'Lease',
			Property__c = property.Id
		);
		
		insert opp;
		
		Test.stopTest();
		
		opp = [SELECT Id, Sales_Region__c FROM Opportunity WHERE Id = :opp.Id];
		System.assertEquals(null, opp.Sales_Region__c);
		
	}
	
	static testMethod void reprocess_updates_SalesRegionSet() {
		
		Account customer = new Account(Name = 'Test Customer');
		insert customer;
		Property__c property =  CreateAstrumPM2ProjectTest.createProperty(customer.Id, '123 Test St');
		property.Sales_Region__c = 'TEST Region';
		update property;
		
		SalesRegionHelper.bypassSalesRegionTriggers = true;
		
		Opportunity opp = new Opportunity(
			Name = 'ABC123',
			AccountId = customer.Id,
			StageName = 'Test',
			CloseDate = System.today().addDays(-8),
			Financing_Type__c = 'Lease',
			Property__c = property.Id,
			Sales_Region__c = 'ABC Test'
		);
		
		insert opp;

		SalesRegionHelper.bypassSalesRegionTriggers = false;

		opp = [SELECT Id, Sales_Region__c FROM Opportunity WHERE Id = :opp.Id];
		System.assertEquals('ABC Test', opp.Sales_Region__c);

		Test.startTest();

		SalesRegionHelper.reprocessSalesRegions = true;
		Opportunity opp2 = new Opportunity(Id = opp.Id);
		update opp2;
		
		Test.stopTest();
		
		opp = [SELECT Id, Sales_Region__c FROM Opportunity WHERE Id = :opp.Id];
		System.assertEquals('TEST Region', opp.Sales_Region__c);
		
	}
	
}