src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Property__c.Property_Owner__r.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <description>AstrumPM/AstrumCRM - Each account can have one or more properties.  A property is defined by its street address.</description>
    <fields>
        <fullName>Property_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account that represents the Owner of this Building.  This may be a Family or a Business.</description>
        <label>Property Owner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Address 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PropertyControllerExtension.cls
public class PropertyControllerExtension {
    private final Property__c prop;
    private final Id propOwner;
    
    public String oppId{
        get;
        // *** setter is NOT being called ***
        set {
            oppId= value;
            System.debug('oppId: '+value);
        }
    }


    public propertyControllerExtension (ApexPages.StandardController stdController) {
        this.prop= (Property__c)stdController.getRecord();
        this.propOwner = [Select id, Property_Owner__c from Property__c p where p.id = :prop.id limit 1].Property_Owner__c;
        System.debug('propOwner --> ' + propOwner );
    }
    
    public PageReference doAssignToOpp(){
        System.debug('oppId --> ' + oppId );
        Opportunity opp = [select id, Name, Property__c, closedate  from Opportunity o where o.Id = :oppId limit 1];
        System.debug('opp --> ' + opp );
        opp.Property__c = prop.Id;
        update opp;
        return null;
    }
    
    public List<Opportunity> getAccountOpportunities(){
        List<Opportunity> opps = [select id, Name, Account.Name from Opportunity o where o.AccountId = :propOwner];
        System.debug('opps --> ' + opps);
        return opps;
    }
}