src/objects/PM_Project__c.object
<CustomObject>
    <description>Astrum PM 2.0 Project Object</description>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>SCRB_SalesOrder__c</referenceTo>
        <relationshipLabel>PM Projects</relationshipLabel>
        <relationshipName>PM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PM Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PM Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SCRB_SalesOrder__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The SalesOrder object is the result of a Closed Won Opportunity and handles the hand off from the sales team to the operations team.</description>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>R00N300000011q88EAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Canceled_Comments__c</fullName>
        <label>Canceled Comments</label>
        <length>50000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SalesOrderCancellationEmailController.cls
public class SalesOrderCancellationEmailController {
    public SalesOrderWrapper salesOrderInfo;
    public String salesorderId{get{return salesorderId;}set;}
    public SalesOrderWrapper getSalesOrderInfo(){
        List<SCRB_SalesOrder__c> salesorders =  [SELECT Name, AccountId__r.Name, Canceled_Comments__c FROM SCRB_SalesOrder__c WHERE Id =: salesorderId];
        List<PM_Project__c> pmprojects = new List<PM_Project__c>();
        pmprojects = [SELECT Id, Name FROM PM_Project__c WHERE Sales_Order__c = :salesorderId];
        if((!salesorders.isEmpty())){
            salesOrderInfo = new SalesOrderWrapper(salesorders[0],null);
        }
        if(!pmprojects.isEmpty()){
            salesOrderInfo.projectName = pmprojects[0].Name;
        }
        return salesOrderInfo;        
    }
    
    public class SalesOrderWrapper{
        
        private SCRB_SalesOrder__c salesOrder;
        
        public SalesOrderWrapper(SCRB_SalesOrder__c salesOrder, String projectName){
            this.salesOrder = salesOrder;
            this.projectName = projectName;
        }
        
        public String salesOrderNumber{get{return salesOrder.Name;}}
        public String accountName{get{return salesOrder.AccountId__r.Name;}}
        public String projectName{get;set;}
        public String comments{get{return salesOrder.Canceled_Comments__c;}}        
        
    }
}