src/objects/PM_Project__c.object
<CustomObject>
    <description>Astrum PM 2.0 Project Object</description>
    <fields>
        <fullName>Lease_Funding_Status__c</fullName>
        <label>Lease Funding Status</label>
        <picklist>
            <picklistValues>
                <fullName>Change Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Prepare</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Install</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>SCRB_SalesOrder__c</referenceTo>
        <relationshipLabel>PM Projects</relationshipLabel>
        <relationshipName>PM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PM Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PM Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SCRB_SalesOrder__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The SalesOrder object is the result of a Closed Won Opportunity and handles the hand off from the sales team to the operations team.</description>
    <fields>
        <fullName>Escalation_Comments__c</fullName>
        <inlineHelpText>CA Escalation Comments</inlineHelpText>
        <label>Escalation Comments</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>StatusCode__c</fullName>
        <label>Status Code</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>Submit Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Assigned to Sales Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Submit To Sales Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Coordinator Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Manager Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancel Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Coordinator Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final/Accounting Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Administrator Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalated to VP Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VP Sales Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VP Sales Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Controller Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Proposal Creation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Proposal Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Ongoing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conversion Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Controller Rejected - Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Admin Approved - Finance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SalesOrderLeasingActionController.cls
public with sharing class SalesOrderLeasingActionController {

    private SCRB_SalesOrder__c so;
    private PM_project__c project;
    public boolean actionDone {get; private set;}
    public String comments {get; set;} 
  
    public SalesOrderLeasingActionController(ApexPages.StandardController stdController) {
        so = (SCRB_SalesOrder__c) stdController.getRecord();         
        try
        {
        
            project = [Select Lease_Funding_Status__c from PM_Project__C where Sales_Order__c = :so.Id ];
        }  
        catch(Exception e)
        {
            project = null;
        }  
               
    }

   public PageReference submitCancellation() {    
    
        if (so != null) {
        
            so.StatusCode__C = 'Canceled';
            update so;  
            try{
              List<ProcessInstanceWorkitem> processitems = [Select ID From ProcessInstanceWorkitem p Where p.ProcessInstance.TargetObjectId = :so.Id and 
                                        p.ProcessInstance.Status = 'Pending'];
              for(ProcessInstanceWorkitem processItem : processitems )
              {
                  System.debug('*Rem-'+processitem.Id);
                  Approval.ProcessWorkitemRequest req2 = 
                    new Approval.ProcessWorkitemRequest();          
            
                  req2.setAction('Removed');     
                  // Use the ID from the newly created item to specify the item to be worked
                  req2.setWorkitemId(processitem.Id);
                  // Submit the request for approval
                  Approval.ProcessResult result2 =  Approval.process(req2);  
              }
            }
            
            catch(Exception e)
            {
              System.debug('No Pending Actions');
            }
              
            // update the event
            //so.Escalation_Comments__c = comments ;       
            project.Lease_Funding_Status__c = 'Cancelled'; 
            project.Status__c = 'Cancelled';
            update project;
              
              
          // send notification email
          //Sales_Visit_Complete_Utility.sendNotificationEmail(tempEvent);            
        }
        
        
        
        //  After Save, navigate to the default view page:  
            return (new ApexPages.StandardController(so)).view();
      }    
      
      public PageReference submitReadyToPrepare() {
              
        // update the event
        //so.Escalation_Comments__c = comments ;       
        project.Lease_Funding_Status__c = 'Ready to Prepare'; 
        update project;
         
        //  After Save, navigate to the default view page:  
        return (new ApexPages.StandardController(so)).view();
      }    
   
}