src/objects/PM_Project__c.object
<CustomObject>
    <description>Astrum PM 2.0 Project Object</description>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>SCRB_SalesOrder__c</referenceTo>
        <relationshipLabel>PM Projects</relationshipLabel>
        <relationshipName>PM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PL Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PM Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PM Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Property__c.object
<CustomObject>
    <description>AstrumPM/AstrumCRM - Each account can have one or more properties.  A property is defined by its street address.</description>
    <label>Property</label>
    <nameField>
        <label>Property Address 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SCRB_SalesOrder__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The SalesOrder object is the result of a Closed Won Opportunity and handles the hand off from the sales team to the operations team.</description>
    <fields>
        <fullName>Director_of_Operations__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Director of Operations</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Director_of_Ops</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PMProjectStatusChangeTriggerTest.cls
/* FILE: PMProjectStatusChangeTriggerTest.cls
 * AUTHOR: Tino Mattheou
 * DATE: June 9, 2012
 * PURPOSE: Test class for PMProjectStatusChangeNotification  
 * MODIFICATION HISTORY
 * 08/23/2012 TCM - fix test due to changing BingMaps trigger to not perform callouts under test
 */ 

@isTest 
public class PMProjectStatusChangeTriggerTest {

	static testMethod void newProject_setActive_notificationSent() {
		
		Account customer = new Account(Name = 'Test Customer');
		insert customer;
		Property__c property = CreateAstrumPM2ProjectTest.createProperty(customer.Id, '123 Test St');
		SCRB_SalesOrder__c salesOrder = CreateAstrumPM2ProjectTest.createSalesOrder(property.Id, null);
		salesOrder.Director_of_Operations__c = UserInfo.getUserId();
		update salesOrder;

		PM_Project__c project = new PM_Project__c (
			Name = 'Test Project',
			Sales_Order__c = salesOrder.Id
		);
		insert project;

		//make sure project is setup correctly
		project = [SELECT Id, Status__c, Sales_Order__c FROM PM_Project__c WHERE Id = :project.Id];
		System.assertEquals('New', project.Status__c);
		System.assertEquals(salesOrder.Id, project.Sales_Order__c);

		Test.startTest();

		project.Status__c = 'Active';
		update project;	
		
		Test.stopTest();	
		
		//TCM - this works according to debug log but governor limit not set
		//System.assertEquals(1, Limits.getEmailInvocations());
		
	}

	static testMethod void newProjectNoOpsDirector_setActive_notificationSent() {
		
		Account customer = new Account(Name = 'Test Customer');
		insert customer;
		Property__c property = CreateAstrumPM2ProjectTest.createProperty(customer.Id, '123 Test St');
		SCRB_SalesOrder__c salesOrder = CreateAstrumPM2ProjectTest.createSalesOrder(property.Id, null);

		PM_Project__c project = new PM_Project__c (
			Name = 'Test Project',
			Sales_Order__c = salesOrder.Id
		);
		insert project;

		Test.startTest();

		project.Status__c = 'Active';
		update project;	
		
		Test.stopTest();	
		
		System.assertEquals(0, Limits.getEmailInvocations());
		
	}

	static testMethod void newProjectNoSalesOrder_setActive_noNotificationSent() {

		PM_Project__c project = new PM_Project__c (
			Name = 'Test Project'
		);
		insert project;

		Test.startTest();

		project.Status__c = 'Active';
		update project;	
		
		Test.stopTest();	
		
		System.assertEquals(0, Limits.getEmailInvocations());

	}
}