src/objects/PM_Project__c.object
<CustomObject>
    <description>Astrum PM 2.0 Project Object</description>
    <fields>
        <fullName>Sales_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Order</label>
        <referenceTo>SCRB_SalesOrder__c</referenceTo>
        <relationshipLabel>PM Projects</relationshipLabel>
        <relationshipName>PM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related Rootstock Work Order. This lookup is used to update the related Work Order when the PM Project is updated.</description>
        <inlineHelpText>The related Rootstock Work Order.</inlineHelpText>
        <label>Primary Work Order</label>
        <referenceTo>rstk__wocst__c</referenceTo>
        <relationshipLabel>PM Projects</relationshipLabel>
        <relationshipName>PM_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>PM Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PM Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SCRB_SalesOrder__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The SalesOrder object is the result of a Closed Won Opportunity and handles the hand off from the sales team to the operations team.</description>
    <fields>
        <fullName>System_Design_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>System Design Quote</label>
        <referenceTo>System_Design_Quote__c</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>Sales_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/System_Design__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The Solar System Design.  Each Property can have one or more System Designs created as the result of a site Survey and the discovery of Install Locations.  Each System Design is made up of one or more System Design Arrays.</description>
    <label>System Design</label>
    <nameField>
        <displayFormat>SD-{0}</displayFormat>
        <label>System Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Designs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/System_Design_Quote__c.object
<CustomObject>
    <description>AstrumCRM - System Design Quote.  Each System Design can have one or more System Design Quotes.  Each quote provides the sales consultant with the ability to adjust the negotiated price of the System Design based on the Calculated System Price.  Opportunities must choose a winning System Design Quote in order to close.</description>
    <label>System Design Quote</label>
    <nameField>
        <displayFormat>SDQ-{0}</displayFormat>
        <label>System Design Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Design Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WorkOrderDetailControllerTest.cls
/* FILE: WordOrderDetailControllerTest.cls
 * AUTHOR: Pavitra Burla
 * DATE: Aug 20, 2015
 * PURPOSE: Test class for WordOrderDetailController
 * MODIFICATION HISTORY 
 */
@isTest(seeAllData=true)
public class WorkOrderDetailControllerTest {
    static testmethod void opstest(){
        
        List<PM_Project__c> projs = [SELECT Work_Order__c ,Sales_Order__r.System_Design_Quote__r.System_Design__c
                                        FROM PM_Project__c 
                                        WHERE Work_Order__r.rstk__wocst_ordsts_pl__c = '2-Firm' LIMIT 1];
        if(projs!=null && projs.size()>0){

            Test.setCurrentPage(Page.WordOrderDetail);
            ApexPages.StandardController controller = new ApexPages.StandardController(projs[0]);
            WorkOrderDetailController extn = new WorkOrderDetailController(controller);
            Id woId = extn.workorder.Id;

            Test.startTest();
            List<rstk__woordop__c> ops = [SELECT Id FROM rstk__woordop__c WHERE rstk__woordop_ordno__c = :woId];
            System.debug(loggingLevel.ERROR,'ops:' + ops + 'size:' +ops.size());
            extn.deleteOperations();
            
            ops = [SELECT Id FROM rstk__woordop__c WHERE rstk__woordop_ordno__c = :woId];
            System.debug(loggingLevel.ERROR,'ops:' + ops + 'size:' +ops.size());
            System.assertEquals(0,ops.size());
        
            //Since sydata executes in batch , the result of below operations are not immediate for us to verify.
            extn.extractOperations();
            extn.generatePicklist();
            extn.reGeneratePicklist();
            extn.completeWO();
            extn.closeWO();
            Test.stopTest();
        } 
    }

}