src/objects/Portal_Referral__c.object
<CustomObject>
    <description>Referrals from the Partner Program website</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Referring Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Portal Referrals</relationshipLabel>
        <relationshipName>Portal_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City for referral</description>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Detail__c</fullName>
        <label>Detail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of referral</description>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of referral</description>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Portal_Referral_Fee__c</fullName>
        <inlineHelpText>Amount earned for this referral (per referral basis)</inlineHelpText>
        <label>Portal Referral Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Referred_by__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referred by</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Partner Portal Referrals</relationshipLabel>
        <relationshipName>Portal_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sold_Referral_Fee__c</fullName>
        <description>Fee paid from a sold referral</description>
        <label>Sold Referral Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>OPEN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QUALIFIED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Portal Referral</label>
    <nameField>
        <displayFormat>REF-{000000}</displayFormat>
        <label>Portal Referral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Portal_Referral_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Portal Referral Payments</relationshipLabel>
        <relationshipName>Portal_Referral_Payments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <label>Portal Referral Payment</label>
    <nameField>
        <displayFormat>PRP-{000000}</displayFormat>
        <label>Portal Referral Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Referral Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/State__c.object
<CustomObject>
    <description>Represents a State</description>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PortalAffiliateTest.cls
/* FILE: PortalAffiliateTest.cls
 * AUTHOR: Rohit Jain
 * DATE: September 12, 2012
 * PURPOSE: Test class for PortalAffiliate Home page and PortalAffiliateHomeController
 * MODIFICATION HISTORY
 *
 */

@isTest 
public class PortalAffiliateTest {

    static testMethod void referrals_viewHome() {
        
        User u = PortalToolsTest.createAffiliatePortalUser();

        Account a = [SELECT Id, Name FROM Account];
        
        Contact c = new Contact (
            LastName = 'Partner2',
            AccountId = a.Id
        );
        insert c;

        Portal_Referral__c newReferral = new Portal_Referral__c (
            Status__c = PortalReferralStatus.OPEN_STATUS,
            Detail__c = 'New',
            Account__c = a.Id,
            First_Name__c = 'New',
            Last_Name__c = 'Referral',
            City__c = 'Somewhere',
            State__c = 'PA',
            Referred_By__c = c.Id,
            Portal_Referral_Fee__c = 25
        );
        insert newReferral;
         
        Portal_Referral__c soldReferral = new Portal_Referral__c (
            Status__c = PortalReferralStatus.SOLD_STATUS,
            Detail__c = '9/11/2012',
            Account__c = a.Id,
            First_Name__c = 'Sold',
            Last_Name__c = 'Referral',
            City__c = 'Somewhere',
            State__c = 'PA',
            Referred_By__c = c.Id,
            Sold_Referral_Fee__c = 1200
        );
        insert soldReferral;
        
        Portal_Referral_Payment__c payment = new Portal_Referral_Payment__c (
            Account__c = a.Id,
            Payment_Date__c = System.today(),
            Payment_Amount__c = 1200
        );
        insert payment;
        
        System.runAs(u) {
            
            Test.setCurrentPage(Page.PortalAffiliateHomePage);
            PortalAffiliateHomeController controller = new PortalAffiliateHomeController();
            
            
            System.assertEquals(2, controller.totalReferrals );
            System.assertEquals(1, controller.totalSold);   
            
        }
        
    }

}