src/objects/Portal_Referral__c.object
<CustomObject>
    <description>Referrals from the Partner Program website</description>
    <fields>
        <fullName>D2D_Lead_Status__c</fullName>
        <label>D2D Lead Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed - Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Generated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Opt-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Opt-Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Door Hanger</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing Utility Bill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA Visit 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA Visit 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passed Validation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Photos Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit Scheduled</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>First_Visit_Datetime__c</fullName>
        <label>First Visit Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>First_Visit_Notes__c</fullName>
        <label>First Visit Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Full_Name__c</fullName>
        <formula>Last_Name__c  &amp; &apos;, &apos; &amp; First_Name__c</formula>
        <label>Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Portal Referrals</relationshipLabel>
        <relationshipName>Portal_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Portal Referrals</relationshipLabel>
        <relationshipName>Portal_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Second_Visit_Datetime__c</fullName>
        <label>Second Visit Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Second_Visit_Notes__c</fullName>
        <label>Second Visit Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Third_Visit_Datetime__c</fullName>
        <label>Third Visit Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Third_Visit_Notes__c</fullName>
        <label>Third Visit Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Portal Referral</label>
    <nameField>
        <displayFormat>REF-{000000}</displayFormat>
        <label>Portal Referral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/D2D_RecordVisitController.cls
public without sharing class D2D_RecordVisitController extends D2D_BaseReferralController {

    public override List<String> getPortalReferralFields(){
        return new List<String> {
            'D2D_Lead_Status__c',
            'First_Visit_Datetime__c',
            'First_Visit_Notes__c',
            'Full_Name__c',
            'Id',
            'Lead__c',
            'Opportunity__c',
            'Second_Visit_Datetime__c',
            'Second_Visit_Notes__c',
            'Third_Visit_Datetime__c',
            'Third_Visit_Notes__c'
        };
    }

    public override List<String> getLeadFields(){
        return new List<String> {
            'Id',
            'Status'
        };
    }

    public String newVisitNote {get;set;}

    public List<VisitWrapper> visits {
        get {
            if(visits == null) {
                visits = getListFromReferral(referral);
            }
            return visits;
        }
        set;
    }

	public D2D_RecordVisitController() {
		newVisitNote = '';
	}

    public PageReference submitVisit() {
        try{
            if(visits.size() == 0) {
                referral.First_Visit_Datetime__c = Datetime.now();
                referral.First_Visit_Notes__c = newVisitNote;
                if(referral.D2D_Lead_Status__c == 'Prospect New'){
                    referral.D2D_Lead_Status__c = 'NA Visit 1';
                }
            } else if (visits.size() == 1) {
                referral.Second_Visit_Datetime__c = Datetime.now();
                referral.Second_Visit_Notes__c = newVisitNote;
                if(referral.D2D_Lead_Status__c == 'NA Visit 1'){
                    referral.D2D_Lead_Status__c = 'NA Visit 2';
                }
            } else {
                referral.Third_Visit_Datetime__c = Datetime.now();
                referral.Third_Visit_Notes__c = newVisitNote;
                if(referral.D2D_Lead_Status__c == 'NA Visit 2'){
                    referral.D2D_Lead_Status__c = 'Door Hanger';
                }

                // Update the lead to reassign to Inside Sales
                Group insideSalesQueue = [SELECT Id, Name FROM Group WHERE DeveloperName = 'InsideSalesQueue' LIMIT 1];
                relatedLead.OwnerId = insideSalesQueue.Id;
                relatedLead.Status = 'Prospect Unresponsive';
                update relatedLead;
            }
            update referral;
        } catch (Exception ex){
            ApexPages.addMessages(ex);
            stackTrace = ex.getStackTraceString();
        }

        visits = null;
        newVisitNote = '';
        return null;
    }

    /// WRAPPER CLASSES ///
    public class VisitWrapper {
        public String VisitDatetime {get;set;}
        public String VisitType {get;set;}
        public String VisitNotes {get;set;}

        public VisitWrapper(Datetime dt, String type, String notes) {
            this.VisitDatetime = dt.format();
            this.VisitType = type;
            this.VisitNotes = notes;
        }
    }

    private List<VisitWrapper> getListFromReferral(Portal_Referral__c referral) {
        List<VisitWrapper> visits = new List<VisitWrapper>();
        if(referral.First_Visit_Datetime__C != null) {
            visits.add(new VisitWrapper(referral.First_Visit_Datetime__C, 'NA Visit 1', referral.First_Visit_Notes__c));
        }
        if(referral.Second_Visit_Datetime__C != null) {
            visits.add(new VisitWrapper(referral.Second_Visit_Datetime__C, 'NA Visit 2', referral.Second_Visit_Notes__c));
        }
        if(referral.Third_Visit_Datetime__C != null) {
            visits.add(new VisitWrapper(referral.Third_Visit_Datetime__C, 'Door Hanger', referral.Third_Visit_Notes__c));
        }
        return visits;
    }
}