src/objects/Portal_Referral__c.object
<CustomObject>
    <description>Referrals from the Partner Program website</description>
    <fields>
        <fullName>D2D_Lead_Status__c</fullName>
        <label>D2D Lead Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed - Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Generated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Opt-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Opt-Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Door Hanger</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing Utility Bill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA Visit 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA Visit 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passed Validation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Photos Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit Scheduled</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>D2D_Sales_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>D2D Sales Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Portal_Referrals1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>D2D_Scheduled_Visit_Datetime__c</fullName>
        <label>D2D Scheduled Visit Datetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Portal Referrals</relationshipLabel>
        <relationshipName>Portal_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>Street of Referral</description>
        <label>Street</label>
        <type>TextArea</type>
    </fields>
    <label>Portal Referral</label>
    <nameField>
        <displayFormat>REF-{000000}</displayFormat>
        <label>Portal Referral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SCRB_SalesOrder__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The SalesOrder object is the result of a Closed Won Opportunity and handles the hand off from the sales team to the operations team.</description>
    <fields>
        <fullName>OpportunityId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Orders</relationshipLabel>
        <relationshipName>R00N300000011q6hEAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Order</label>
    <nameField>
        <label>Sales Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/D2D_PropertyPhotosControllerTest.cls
@isTest
private class D2D_PropertyPhotosControllerTest {
    private static boolean runalltests = true; // true to run all tests; false to skip tests and only run those where the 'if' is commented out

	@testSetup static void setupData() {
		D2DTestUtility.InitializeRequiredMethods();
		D2DTestUtility.CreateCustomSettings(false, 'd2d.tester@email.com');

		D2DTestUtility.CreateManagerUsers(1);
		User d2dMg = D2DTestUtility.d2dManagerUsers[0];

		D2DTestUtility.CreateSalesRepUsers(1);
		User d2dSr = D2DTestUtility.d2dSalesRepUsers[0];

		D2DTestUtility.CreatePortalReferralRequiredObjects(1, 'NY', '24 Panel');
		D2DTestUtility.CreatePortalReferralsWithLeads(1, d2dMg.Id, d2dSr.Id, 'OPEN', 'Prospect New', '24 Panel', '2', 'ref', 'Bob', '1010 Boolean Ave', 'Stony Point', 'NY', '10980', 'Rockland', false);
		D2DTestUtility.CreatePortalReferralsWithConvertedLeads(1, d2dMg.Id, d2dSr.Id, 'OPEN', 'Prospect New', '36 Panel', '3', 'ref', 'Joe', '1010 Tenth St', 'Stony Point', 'NY', '10980', 'Rockland', true);
	}

	@isTest static void test_InvalidReferral() {
		if(!runalltests){ return; }

		Portal_Referral__c referral = [SELECT Id, D2D_Sales_Rep__c, D2D_Lead_Status__c, D2D_Scheduled_Visit_Datetime__c FROM Portal_Referral__c WHERE Street__c LIKE '1010 Bool%' LIMIT 1];
		User repUser = [SELECT Id FROM User WHERE Id = :referral.D2D_Sales_Rep__c];

		System.runAs(repUser){
			PageReference pageRef = Page.D2D_PropertyPhotos;
			pageRef.getParameters().put('id', referral.Id);
			Test.setCurrentPage(pageRef);

			Test.startTest();

			D2D_PropertyPhotosController controller = new D2D_PropertyPhotosController();
			controller.upload();

			Test.stopTest();
		}
	}

	@isTest static void test_Upload() {
		if(!runalltests){ return; }

		Portal_Referral__c referral = [SELECT Id, D2D_Sales_Rep__c, D2D_Lead_Status__c, D2D_Scheduled_Visit_Datetime__c, Opportunity__c FROM Portal_Referral__c WHERE Street__c LIKE '1010 Tent%' LIMIT 1];
		User repUser = [SELECT Id FROM User WHERE Id = :referral.D2D_Sales_Rep__c];

		SCRB_SalesOrder__c salesOrder = new SCRB_SalesOrder__c(OpportunityId__c = referral.Opportunity__c);
		insert salesOrder;

		System.runAs(repUser){
			PageReference pageRef = Page.D2D_PropertyPhotos;
			pageRef.getParameters().put('id', referral.Id);
			Test.setCurrentPage(pageRef);

			Test.startTest();

			D2D_PropertyPhotosController controller = new D2D_PropertyPhotosController();
			
			system.assertEquals(0, controller.propertyAttachments.size());

			// Upload files, at least one set multiple
			controller.photoType = 'fp';
			controller.uploadFile.Body = Blob.valueOf('Sample FP Attachment 1');
			controller.upload();

			controller.photoType = 'fp';
			controller.uploadFile.Body = Blob.valueOf('Sample FP Attachment 2');
			controller.upload();

			for(Attachment att : controller.propertyAttachments){
				system.debug('**SZ: att.Name = ' + att.Name);
			}
			system.assertEquals(2, controller.getFpAttachments().size());

            controller.photoType = 'rp';
			controller.uploadFile.Body = Blob.valueOf('Sample RP Attachment');
			controller.upload();
			system.assertEquals(1, controller.getRpAttachments().size());

            controller.photoType = 's1';
			controller.uploadFile.Body = Blob.valueOf('Sample S1 Attachment');
			controller.upload();
			system.assertEquals(1, controller.getS1Attachments().size());

            controller.photoType = 's2';
			controller.uploadFile.Body = Blob.valueOf('Sample S2 Attachment');
			controller.upload();
			system.assertEquals(1, controller.getS2Attachments().size());

            controller.photoType = 'ub';
			controller.uploadFile.Body = Blob.valueOf('Sample UB Attachment');
			controller.upload();
			system.assertEquals(1, controller.getUbAttachments().size());

            controller.photoType = 'em';
			controller.uploadFile.Body = Blob.valueOf('Sample EM Attachment');
			controller.upload();
			system.assertEquals(1, controller.getEmAttachments().size());

			referral.D2D_Lead_Status__c = 'Sold';
			update referral;
			
			controller = new D2D_PropertyPhotosController();

			controller.photoType = 'vc';
			controller.uploadFile.Body = Blob.valueOf('Sample VC Attachment');
			controller.upload();
			system.assertEquals(1, controller.getVcAttachments().size());

			Test.stopTest();
		}
	}
	
	@isTest static void test_LoadAndSubmit() {
		if(!runalltests){ return; }

		Portal_Referral__c referral = [SELECT Id, D2D_Sales_Rep__c, D2D_Lead_Status__c, D2D_Scheduled_Visit_Datetime__c FROM Portal_Referral__c WHERE Street__c LIKE '1010 Tent%' LIMIT 1];
		User repUser = [SELECT Id FROM User WHERE Id = :referral.D2D_Sales_Rep__c];

		System.runAs(repUser){
			PageReference pageRef = Page.D2D_PropertyPhotos;
			pageRef.getParameters().put('id', referral.Id);
			Test.setCurrentPage(pageRef);

			Test.startTest();

			D2D_PropertyPhotosController controller = new D2D_PropertyPhotosController();
			controller.submit();

			Test.stopTest();
		}
	}
}