src/objects/Portal_Referral__c.object
<CustomObject>
    <description>Referrals from the Partner Program website</description>
    <fields>
        <fullName>Credit_Approved__c</fullName>
        <label>Credit_Approved</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>D2D_Lead_Status__c</fullName>
        <label>D2D Lead Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed - Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract Generated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Opt-In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Opt-Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Door Hanger</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing Utility Bill</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA Visit 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA Visit 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passed Validation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Photos Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prospect New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit Scheduled</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Full_Name__c</fullName>
        <formula>Last_Name__c  &amp; &apos;, &apos; &amp; First_Name__c</formula>
        <label>Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Portal Referrals</relationshipLabel>
        <relationshipName>Portal_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Portal Referrals</relationshipLabel>
        <relationshipName>Portal_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Portal Referral</label>
    <nameField>
        <displayFormat>REF-{000000}</displayFormat>
        <label>Portal Referral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/D2D_CreditCheckController.cls
public without sharing class D2D_CreditCheckController extends D2D_BaseReferralController {

    public override List<String> getPortalReferralFields(){
        return new List<String> {
            'D2D_Lead_Status__c',
            'Id',
            'Lead__c',
            'Opportunity__c',
            'Credit_Approved__c',
            'Full_Name__c'
        };
    }

    public override List<String> getLeadFields(){
    	return new List<String> {
    		'Id'
    	};
    }

    public override List<String> getOpportunityFields(){
    	return new List<String> {
    		'Id',
    		'StageName',
    		'Closed_Reason__c'
    	};
    }

    public String creditCheckUrl {
    	get { return D2D_Utility.d2dSettings.Credit_Check_Url__c; }
    }

    public List<SelectOption> creditApproved {
        get { return D2D_Utility.GetPicklistOptions(Portal_Referral__c.Credit_Approved__c.getDescribe(), true, '-- Select --'); }
    }

	public D2D_CreditCheckController() {
		
	}

	public PageReference submit(){
		PageReference pr = null;
		try{
			Map<String,String> params = ApexPages.currentPage().getParameters();
	        String creditApprovedSelection = params.get('creditApprovedRadioBtn');
	        
	        if(creditApprovedSelection == 'Yes'){
	        	referral.Credit_Approved__c = 'Yes';
				referral.D2D_Lead_Status__c = 'Credit Approved';
	            pr = new PageReference('/d2d/D2D_ContractPreview?id=' + referralId);
				pr.setRedirect(true);
			} else if(creditApprovedSelection == 'No') {
				referral.Credit_Approved__c = 'No';
				referral.D2D_Lead_Status__c = 'Closed - Lost';
				relatedOpportunity.StageName = 'Closed - Lost';
	            pr = new PageReference('/d2d/D2D_LeadMenu?id=' + referralId);
				pr.setRedirect(true);
				relatedOpportunity.Closed_Reason__c = 'Denied Credit';
			} else if(creditApprovedSelection == 'Pending') {
				referral.Credit_Approved__c = 'Pending';
	            pr = new PageReference('/d2d/D2D_LeadMenu?id=' + referralId);
				pr.setRedirect(true);
			} else {

			}

			update referral;
			update relatedOpportunity;
		} catch (Exception ex){
			ApexPages.addMessages(ex);
			stackTrace = ex.getStackTraceString();
		}
		
        return pr;
	}
}