src/objects/Portal_Referral__c.object
<CustomObject>
    <description>Referrals from the Partner Program website</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Referring Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Portal Referrals</relationshipLabel>
        <relationshipName>Portal_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City for referral</description>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Detail__c</fullName>
        <label>Detail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of referral</description>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of referral</description>
        <label>Last Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Created_Date__c</fullName>
        <label>Lead Created Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Referred_by__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referred by</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Partner Portal Referrals</relationshipLabel>
        <relationshipName>Portal_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>OPEN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QUALIFIED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SOLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLOSED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Portal Referral</label>
    <nameField>
        <displayFormat>REF-{000000}</displayFormat>
        <label>Portal Referral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portal Referrals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/State__c.object
<CustomObject>
    <description>Represents a State</description>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EP_MyDashboardTest.cls
/* FILE: EP_MyDashboardTest.cls
 * AUTHOR: Tino Mattheou
 * DATE: January 2, 2013
 * PURPOSE: Tests for EP_MyDashboard page, EP_MyDashboardController
 * MODIFICATION HISTORY
 * 
 */

@isTest
public class EP_MyDashboardTest {

	static testMethod void referrals_viewDashboard_visible() {
		
		User u = EP_SubmitLeadsTest.createPortalUser();

		Account a = [SELECT Id, Name FROM Account];
		
		Contact c = new Contact (
			LastName = 'Partner2',
			AccountId = a.Id
		);
		insert c;

    	Portal_Referral__c newReferral = new Portal_Referral__c (
    		Lead_Created_Date__c = Date.newInstance(2013,1,15),
    		Status__c = PortalReferralStatus.OPEN_STATUS,
    		Detail__c = 'New',
    		Account__c = a.Id,
    		First_Name__c = 'New',
    		Last_Name__c = 'Referral',
    		City__c = 'Somewhere',
    		State__c = 'PA',
    		Referred_By__c = c.Id
    	);
    	insert newReferral;
		 
    	Portal_Referral__c soldReferral = new Portal_Referral__c (
    		Lead_Created_Date__c = Date.newInstance(2013,1,12),
    		Status__c = PortalReferralStatus.SOLD_STATUS,
    		Detail__c = '9/11/2012',
    		Account__c = a.Id,
    		First_Name__c = 'Sold',
    		Last_Name__c = 'Referral',
    		City__c = 'Somewhere',
    		State__c = 'PA',
    		Referred_By__c = c.Id
    	);
    	insert soldReferral;
    	
    	System.runAs(u) {
    		
    		Test.setCurrentPage(Page.EP_MyDashboard);
    		EP_MyDashboardController controller = new EP_MyDashboardController();
    		
    		System.assertEquals(2, controller.totalReferrals);
    		System.assertEquals(1, controller.totalOpen);
    		System.assertEquals(1, controller.totalSold);
    		
    		System.assertEquals('DESC', controller.sortDirection);
    		System.assertEquals('Lead_Created_Date__c', controller.sortExpression);
    		
    		List<Portal_Referral__c> referrals = controller.referrals;
    		System.assertEquals(2, referrals.size());
    		System.assertEquals(newReferral.Id, referrals[0].Id);
    		System.assertEquals(soldReferral.Id, referrals[1].Id);
    		
			//change sort direction
    		controller.sortExpression = 'Lead_Created_Date__c';
    		controller.refresh();
    		
    		referrals = controller.referrals;
    		System.assertEquals(soldReferral.Id, referrals[0].Id);
    		System.assertEquals(newReferral.Id, referrals[1].Id);
    		
    	}
    	
	}


}