src/objects/Property__c.object
<CustomObject>
    <description>AstrumPM/AstrumCRM - Each account can have one or more properties.  A property is defined by its street address.</description>
    <label>Property</label>
    <nameField>
        <label>Property Address 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/System_Design__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The Solar System Design.  Each Property can have one or more System Designs created as the result of a site Survey and the discovery of Install Locations.  Each System Design is made up of one or more System Design Arrays.</description>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>System Designs</relationshipLabel>
        <relationshipName>System_Designs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>System Design</label>
    <nameField>
        <displayFormat>SD-{0}</displayFormat>
        <label>System Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Designs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/System_Design_Array__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The Solar System Design Array.  Each System Design is made up of one or more System Design Arrays.  Primarily defined by their mounting system and CB Panel connection, System Design Arrays are made up of one or more System Design Items.</description>
    <fields>
        <fullName>System_Design__c</fullName>
        <label>System Design</label>
        <referenceTo>System_Design__c</referenceTo>
        <relationshipLabel>System Design Arrays</relationshipLabel>
        <relationshipName>System_Design_Arrays</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>System Design Array</label>
    <nameField>
        <displayFormat>SDA-{0}</displayFormat>
        <label>System Design Array Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Design Arrays</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/System_Design_Item__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - System Design Item.  A collection of one or more System Design Products that are to be placed on a single Install Location.</description>
    <fields>
        <fullName>Property__c</fullName>
        <formula>System_Design_Array__r.System_Design__r.Property__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Design_Array__c</fullName>
        <label>System Design Array</label>
        <referenceTo>System_Design_Array__c</referenceTo>
        <relationshipLabel>System Design Items</relationshipLabel>
        <relationshipName>System_Design_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>System_Design__c</fullName>
        <description>System Design Id</description>
        <formula>System_Design_Array__r.System_Design__r.Id</formula>
        <inlineHelpText>System Design Id</inlineHelpText>
        <label>System Design</label>
        <type>Text</type>
    </fields>
    <label>System Design Item</label>
    <nameField>
        <label>System Design Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Design Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PropertyCommonUtil.cls
/* FILE: PropertyCommonUtil.cls
	 * AUTHOR: Mike Katulka	
	 * DATE: March 17, 2014
	 * PURPOSE: Class meant for methods that can be used anywhere that relate to the Property object and child records.
	 * MODIFICATION HISTORY 
*/
public without sharing class PropertyCommonUtil {
	
	public static void UpdateSDIsFromPropertyIDs(set <id> propIDs){
		//Fetch array IDs linked to this property		
		if(!propIDs.isEmpty()){
			set<id> sdaIds = (new Map<Id,SObject>([select Id From System_Design__c where Property__c in:propIDs])).keySet();		
			
			//Fetch SDIs linked to these arrays and update them in order to initiate rollups
			if(sdaIDs != null && !sdaIDs.isEmpty()){
			  list<System_Design_Item__c> sdis = [Select id from System_Design_Item__c where System_Design_Array__c in : SDAIds];
			  if(sdis != null && !sdis.isEmpty()) update sdis;
			}
		}
	}

}