src/objects/Property__c.object
<CustomObject>
    <description>AstrumPM/AstrumCRM - Each account can have one or more properties.  A property is defined by its street address.</description>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>Property State</label>
        <picklist>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Utility_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>DEPRECATED AS OF 11/25/14</description>
        <label>Utility Rate Code</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Utility_Company__c.RecordType.Name</field>
                <operation>notEqual</operation>
                <value>Custom</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Utility_Company__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Address 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility_Company__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - Each Utility Service is attached to a single Utility Company.</description>
    <fields>
        <fullName>State_Serviced__c</fullName>
        <label>State Serviced</label>
        <picklist>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>States_Serviced__c</fullName>
        <label>States Serviced</label>
        <picklist>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Utility Rate Code</label>
    <nameField>
        <label>Utility Rate Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Rate Codes</pluralLabel>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility_Service__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - Each Property can have one or more Utility Service(s).  A Utility Service is primarily defined by the Meter ID and the Utility Company to which is connects.</description>
    <fields>
        <fullName>Property_State__c</fullName>
        <formula>TEXT(Property__r.Property_State__c)</formula>
        <label>Property State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Utility Services</relationshipLabel>
        <relationshipName>Utility_Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Utility_Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Company</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Utility_Company__c.RecordType.Name</field>
                <operation>notEqual</operation>
                <value>Custom</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Utility_Company__c</referenceTo>
        <relationshipLabel>Utility Services</relationshipLabel>
        <relationshipName>Utility_Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Service</label>
    <nameField>
        <label>Meter ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Utility_Service_Controller_Ext.cls
/*
    12/09/14  DK  Commented out the Utility Rate Code selection
*/
public with sharing class Utility_Service_Controller_Ext {
    private final Utility_Service__c util_svc;
    // The extension constructor initializes the private member
    // variable acct by using the getRecord method from the standard
    // controller.
    public Utility_Service_Controller_Ext(ApexPages.StandardController stdController) {
        this.util_svc = (Utility_Service__c)stdController.getRecord();
    }
    
    //public String getRateCode() {
    //    return util_svc.Utility_Company__r.name;
    //}

    //public void setRateCode(String rateCodeId) {
    //    String rcid = rateCodeId;
    //    System.debug('Inside setRateCode()');
    //
    //    Utility_Company__c rc = [select id, name 
    //            from Utility_Company__c c 
    //            where Utility_Company__c.Id = :rcid
    //            limit 1]; 
    //    System.debug('Selected Rate Code ID --> ' + rc.Id);
    //    util_svc.Utility_Company__c = rc.id;
    //} 
    
    //public List<SelectOption> getUtilityRateCodes() {
    //    String PropId = System.currentPageReference().getParameters().get('CF00NC0000004Weeu_lkid');
    //    List<SelectOption> options = new List<SelectOption>();
    //    if( PropId <> null ){
    //        System.debug('Property Id --> ' + PropId );
    //        Property__c prop = [select id, Property_State__c from Property__c where id = :PropId limit 1];
    //        System.debug('PropertyState --> ' + prop.Property_State__c );
    //        List<Utility_Company__c> rateCodes = [select id, name, states_serviced__c 
    //                                              from Utility_Company__c
    //                                              where state_serviced__c = :prop.Property_State__c];
    //        for (Utility_Company__c rc : rateCodes){
    //            options.add(new SelectOption(rc.id, rc.name));
    //            System.debug('Adding ' + rc.id + ' --> ' + rc.name );
    //        }
    //    }
    //    return options;
    //}
    
    public PageReference save() {
        //System.debug('util_svc.Utility_Company__r.Id --> ' + util_svc.Utility_Company__r.Id);
        //System.debug('util_svc.Utility_Company__r.name --> ' + util_svc.Utility_Company__r.name);
        
        upsert util_svc;
        return  (new ApexPages.StandardController(util_svc)).view();
    }
    
}