src/objects/Property__c.object
<CustomObject>
    <description>AstrumPM/AstrumCRM - Each account can have one or more properties.  A property is defined by its street address.</description>
    <fields>
        <fullName>DC_to_AC_Derate__c</fullName>
        <defaultValue>0.925</defaultValue>
        <description>Derate accounting for DC to AC conversion</description>
        <inlineHelpText>Derate accounting for DC to AC conversion</inlineHelpText>
        <label>DC-to-AC Derate</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Latitude__c</fullName>
        <label>Latitude</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Longitude__c</fullName>
        <label>Longitude</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Site_Quality__c</fullName>
        <description>Max Site Quality</description>
        <label>Max Site Quality (kWh/y/kW)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Optimal_Site_Quality_kWh_y_kW__c</fullName>
        <label>Optimal Site Quality (kWh/y/kW)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>Property State</label>
        <picklist>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WV</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>QAS_Latitude__c</fullName>
        <description>QAS Auto-Populated Latitude</description>
        <inlineHelpText>QAS Auto-Populated Latitude</inlineHelpText>
        <label>QAS Latitude</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QAS_Longitude__c</fullName>
        <description>QAS Auto-Populated Longitude</description>
        <inlineHelpText>QAS Auto-Populated Longitude</inlineHelpText>
        <label>QAS Longitude</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Snow_De_Rate_kWh_y_kW__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Snow De-Rate</description>
        <label>Snow De-Rate (kWh/y/kW)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Address 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PVWattsReCallExtension.cls
public class PVWattsReCallExtension {

	private ApexPages.StandardController controller;
	
	public PVWattsReCallExtension(ApexPages.StandardController controller) {
		this.controller = controller;
	}
	
	public PageReference reCallPVWatts() {

		/*

		Property__c property = (Property__c) controller.getRecord();

		property = 
			[SELECT Id, DC_to_AC_Derate__c, Latitude__c, Longitude__c, QAS_Latitude__c, QAS_Longitude__c, Snow_De_Rate_kWh_y_kW__c,Property_State__c
			FROM Property__c
			WHERE Id = :property.Id];
			
		Double latitude = property.QAS_Latitude__c != null ? Double.valueOf(property.QAS_Latitude__c) : property.Latitude__c; 
		Double longitude = property.QAS_Longitude__c != null ? Double.valueOf(property.QAS_Longitude__c) : property.Longitude__c;
		
		if (property.DC_to_AC_Derate__c == null) {
			property.DC_to_AC_Derate__c = 0.925;
		} 
		
		if (latitude != null && longitude != null && property.DC_to_AC_Derate__c != null) {
			
			Double maxSiteQuality = PVWatts_ServiceClient.getSiteQuality(latitude, longitude, property.DC_to_AC_Derate__c,property.Property_State__c);
			
			if (maxSiteQuality != null) {
		        property.Max_Site_Quality__c = maxSiteQuality;        
				property.Optimal_Site_Quality_kWh_y_kW__c = maxSiteQuality;
				if (property.Snow_De_Rate_kWh_y_kW__c != null) {
					property.Optimal_Site_Quality_kWh_y_kW__c = property.Optimal_Site_Quality_kWh_y_kW__c - property.Snow_De_Rate_kWh_y_kW__c;
				}
				update property;
			}
		
		}
		*/
		
		return controller.cancel();
	} 

}