src/objects/Property__c.object
<CustomObject>
    <description>AstrumPM/AstrumCRM - Each account can have one or more properties.  A property is defined by its street address.</description>
    <fields>
        <fullName>Latitude__c</fullName>
        <label>Latitude</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Longitude__c</fullName>
        <label>Longitude</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Address 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PropertyMapExtension.cls
public with sharing class PropertyMapExtension {

	private Property__c property;

    // The extension constructor initializes the private member
    // variable mysObject by using the getRecord method from the standard
    // controller.
    public PropertyMapExtension(ApexPages.StandardController stdController) {
        this.property = (Property__c)stdController.getRecord();
        property = [Select Confirmed_Location__Longitude__s, Longitude__c , Confirmed_Location__Latitude__s,Latitude__c from Property__c Where id= :property.Id];
    }

    public Decimal Longitude {
        get{
            return (property.Confirmed_Location__Longitude__s != null ? property.Confirmed_Location__Longitude__s : property.Longitude__c );
            
        }
    }

    public Decimal Latitude {
        get{
             return (property.Confirmed_Location__Latitude__s != null ? property.Confirmed_Location__Latitude__s : property.Latitude__c );
        }
    }
}