src/objects/Property__c.object
<CustomObject>
    <description>AstrumPM/AstrumCRM - Each account can have one or more properties.  A property is defined by its street address.</description>
    <label>Property</label>
    <nameField>
        <label>Property Address 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <recordTypes>
        <fullName>Residential</fullName>
        <active>true</active>
        <label>Residential</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/System_Design__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The Solar System Design.  Each Property can have one or more System Designs created as the result of a site Survey and the discovery of Install Locations.  Each System Design is made up of one or more System Design Arrays.</description>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>System Designs</relationshipLabel>
        <relationshipName>System_Designs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>System Design</label>
    <nameField>
        <displayFormat>SD-{0}</displayFormat>
        <label>System Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Designs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/System_Design_Clone_ControllerTest.cls
@isTest
public class System_Design_Clone_ControllerTest {
    @isTest static void cloneController(){
		        
        testData.setupCustomSettings();
        testdata.setupCustomConfigObjects();
        Id sdID = testData.setupSystemDesign('Residential', 'Purchase', null, true, 12000);
        System_Design__c sysDes = [SELECT Id, Property__c FROM System_Design__c WHERE Id=:sdID];
        
        Test.startTest();
        ApexPages.StandardController stdCntrl = new ApexPages.StandardController(sysDes);
        System_Design_Clone_Controller cntrl = new System_Design_Clone_Controller(stdCntrl);
        
		Test.stopTest();
        System.assertEquals(false, ApexPages.hasMessages());
        
    }
}