src/objects/Proposal__c.object
<CustomObject>
    <fields>
        <fullName>Annual_Power_Price_Escalator__c</fullName>
        <label>Annual Power Price Escalator</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Scenario_1_Annual_Degradation_Factor__c</fullName>
        <label>Scenario 1 Annual Degradation Factor</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Scenario_1_Estimated_Operational_Start_D__c</fullName>
        <label>Scenario 1 Estimated Operational Start D</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Scenario_1_FIT_Annual_Earnings_After_Tax__c</fullName>
        <label>Scenario 1 FIT Annual Earnings After Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Scenario_1_FIT_Term_Length_Months__c</fullName>
        <label>Scenario 1 FIT Term Length (Months)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scenario_1_Financing_Plan__c</fullName>
        <label>Scenario 1 Financing Plan</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scenario_1_Proposal_Term_months__c</fullName>
        <label>Scenario 1 Proposal Term (months)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scenario_2_Annual_Degradation_Factor__c</fullName>
        <label>Scenario 2 Annual Degradation Factor</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Scenario_2_Estimated_Operational_Start_D__c</fullName>
        <label>Scenario 2 Estimated Operational Start D</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Scenario_2_FIT_Annual_Earnings_After_Tax__c</fullName>
        <label>Scenario 2 FIT Annual Earnings After Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Scenario_2_FIT_Term_Length_Months__c</fullName>
        <label>Scenario 2 FIT Term Length (Months)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scenario_2_Financing_Plan__c</fullName>
        <label>Scenario 2 Financing Plan</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scenario_2_Proposal_Term_months__c</fullName>
        <label>Scenario 2 Proposal Term (months)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scenario_3_Annual_Degradation_Factor__c</fullName>
        <label>Scenario 3 Annual Degradation Factor</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Scenario_3_Estimated_Operational_Start_D__c</fullName>
        <label>Scenario 3 Estimated Operational Start D</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Scenario_3_FIT_Annual_Earnings_After_Tax__c</fullName>
        <label>Scenario 3 FIT Annual Earnings After Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Scenario_3_FIT_Term_Length_Months__c</fullName>
        <label>Scenario 3 FIT Term Length (Months)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scenario_3_Financing_Plan__c</fullName>
        <label>Scenario 3 Financing Plan</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scenario_3_Proposal_Term_months__c</fullName>
        <label>Scenario 3 Proposal Term (months)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scenario_4_Annual_Degradation_Factor__c</fullName>
        <label>Scenario 4 Annual Degradation Factor</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Scenario_4_Estimated_Operational_Start_D__c</fullName>
        <label>Scenario 4 Estimated Operational Start D</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Scenario_4_FIT_Annual_Earnings_After_Tax__c</fullName>
        <label>Scenario 4 FIT Annual Earnings After Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Scenario_4_FIT_Term_Length_Months__c</fullName>
        <label>Scenario 4 FIT Term Length (Months)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scenario_4_Financing_Plan__c</fullName>
        <label>Scenario 4 Financing Plan</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scenario_4_Proposal_Term_months__c</fullName>
        <label>Scenario 4 Proposal Term (months)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>System_Design_Quote__c</fullName>
        <label>System Design Quote</label>
        <referenceTo>System_Design_Quote__c</referenceTo>
        <relationshipLabel>Proposals</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Proposal</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/System_Design_Quote__c.object
<CustomObject>
    <description>AstrumCRM - System Design Quote.  Each System Design can have one or more System Design Quotes.  Each quote provides the sales consultant with the ability to adjust the negotiated price of the System Design based on the Calculated System Price.  Opportunities must choose a winning System Design Quote in order to close.</description>
    <fields>
        <fullName>Pricing_Date__c</fullName>
        <label>Pricing Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Scenario_1_FIT_Annual_Earnings_After_Tax__c</fullName>
        <label>Scenario 1 FIT Annual Earnings After Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Scenario_1_FIT_Term_Length_Months__c</fullName>
        <label>Scenario 1 FIT Term Length (Months)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scenario_1_Net_Initial_Outlay__c</fullName>
        <formula>IF( AND(ISPICKVAL(Scenario_1_Financing_Type__c,&apos;Purchase&apos;), Scenario_1_Term_Loan__c == Null), ( 
Scenario_1_Final_EPC_Price__c + Scenario_1_Total_Net_Adjustment__c - Scenario_1_Federal_Tax_Credit_Amount__c - Scenario_1_State_Rebate_Amount__c - Scenario_1_State_Tax_Credit_Amount__c - Scenario_1_Utility_Rebate_Amount__c - Scenario_1_County_Tax_Credit_Amount__c - Scenario_1_Depreciation_Basis__c - Scenario_1_Upfront_SREC_Amount__c) ,Scenario_1_Down_Payment__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Scenario 1 Net Initial Outlay</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Scenario_1_Proposal_Term_Months__c</fullName>
        <label>Scenario 1 Proposal Term Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scenario_1_SREC_Cash_Back__c</fullName>
        <label>Scenario 1 SREC Cash Back</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Scenario_1_Total_Net_Adjustment__c</fullName>
        <formula>Scenario_1_Standard_Net_Adjustment__c + Scenario_1_Program_Net_Adjustment__c + Scenario_1_VP_Override_Net_Adjustment__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Scenario 1 Total Net Adjustment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Scenario_2_FIT_Annual_Earnings_After_Tax__c</fullName>
        <label>Scenario 2 FIT Annual Earnings After Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Scenario_2_FIT_Term_Length_Months__c</fullName>
        <label>Scenario 2 FIT Term Length (Months)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scenario_2_Proposal_Term_Months__c</fullName>
        <label>Scenario 2 Proposal Term Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scenario_2_SREC_Cash_Back__c</fullName>
        <label>Scenario 2 SREC Cash Back</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Scenario_2_Total_Net_Adjustment__c</fullName>
        <formula>Scenario_2_Standard_Net_Adjustment__c + Scenario_2_Program_Net_Adjustment__c + Scenario_2_VP_Override_Net_Adjustment__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Scenario 2 Total Net Adjustment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Scenario_3_FIT_Annual_Earnings_After_Tax__c</fullName>
        <label>Scenario 3 FIT Annual Earnings After Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Scenario_3_FIT_Term_Length_Months__c</fullName>
        <label>Scenario 3 FIT Term Length (Months)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scenario_3_Proposal_Term_Months__c</fullName>
        <label>Scenario 3 Proposal Term Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scenario_3_SREC_Cash_Back__c</fullName>
        <label>Scenario 3 SREC Cash Back</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Scenario_3_Total_Net_Adjustment__c</fullName>
        <formula>Scenario_3_Standard_Net_Adjustment__c + Scenario_3_Program_Net_Adjustment__c + Scenario_3_VP_Override_Net_Adjustment__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Scenario 3 Total Net Adjustment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Scenario_4_FIT_Annual_Earnings_After_Tax__c</fullName>
        <label>Scenario 4 FIT Annual Earnings After Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Scenario_4_FIT_Term_Length_Months__c</fullName>
        <label>Scenario 4 FIT Term Length (Months)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scenario_4_Proposal_Term_Months__c</fullName>
        <label>Scenario 4 Proposal Term Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scenario_4_SREC_Cash_Back__c</fullName>
        <label>Scenario 4 SREC Cash Back</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Scenario_4_Total_Net_Adjustment__c</fullName>
        <formula>Scenario_4_Standard_Net_Adjustment__c + Scenario_4_Program_Net_Adjustment__c + Scenario_4_VP_Override_Net_Adjustment__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Scenario 4 Total Net Adjustment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>System_Design__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>System Design</label>
        <referenceTo>System_Design__c</referenceTo>
        <relationshipLabel>System Design Quotes</relationshipLabel>
        <relationshipName>System_Design_Quotes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>System Design Quote</label>
    <nameField>
        <displayFormat>SDQ-{0}</displayFormat>
        <label>System Design Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Design Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UpdateProposalCashBenefit.cls
/*  
    AUTHOR: Dan Kelner
    DATE: 03/04/16
    PURPOSE: Batch class to update Proposals for CPQ-747
    MODIFICATION HISTORY
*/
global class UpdateProposalCashBenefit implements Database.Batchable<sObject>{
    global String[] specificIDs;
    global String query = 'SELECT System_Design_Quote__r.System_Design__c, Annual_Power_Price_Escalator__c, Scenario_1_Financing_Plan__c, Scenario_2_Financing_Plan__c, Scenario_3_Financing_Plan__c, Scenario_4_Financing_Plan__c, ' + 
                            'Scenario_1_Annual_Degradation_Factor__c, Scenario_2_Annual_Degradation_Factor__c, Scenario_3_Annual_Degradation_Factor__c, Scenario_4_Annual_Degradation_Factor__c, ' + 
                            'Scenario_1_FIT_Annual_Earnings_After_Tax__c, Scenario_2_FIT_Annual_Earnings_After_Tax__c, Scenario_3_FIT_Annual_Earnings_After_Tax__c, Scenario_4_FIT_Annual_Earnings_After_Tax__c, ' + 
                            'Scenario_1_FIT_Term_Length_Months__c, Scenario_2_FIT_Term_Length_Months__c, Scenario_3_FIT_Term_Length_Months__c, Scenario_4_FIT_Term_Length_Months__c, ' + 
                            'Scenario_1_Estimated_Operational_Start_D__c, Scenario_2_Estimated_Operational_Start_D__c, Scenario_3_Estimated_Operational_Start_D__c, Scenario_4_Estimated_Operational_Start_D__c, ' + 
                            'Scenario_1_Proposal_Term_months__c, Scenario_2_Proposal_Term_months__c, Scenario_3_Proposal_Term_months__c, Scenario_4_Proposal_Term_months__c ' + 
                            'FROM Proposal__c';

    global UpdateProposalCashBenefit(String commaSeparatedIDs){
        if (String.isNotBlank(commaSeparatedIDs)){
            specificIDs = commaSeparatedIDs.split(',');
            query += ' WHERE ID IN :specificIDs';
        }
    }

    global Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc, List<sObject> scope){
        Proposal__c[] props = new Proposal__c[]{};
        Map<ID, ID> propsToQuotes = new Map<ID, ID>();
        Map<ID, ID> propsToSysDesigns = new Map<ID, ID>();
        for (sObject s : scope){
            Proposal__c prop = (Proposal__c)s;
            propsToQuotes.put(prop.ID, prop.System_Design_Quote__c);
            propsToSysDesigns.put(prop.ID, prop.System_Design_Quote__r.System_Design__c);
            props.add(prop);
        }
        
        Map<ID, System_Design_Quote__c> sdqs = new Map<ID, System_Design_Quote__c>(
                                        [SELECT Pricing_Date__c, System_Design__c, Scenario_1_SREC_Cash_Back__c, Scenario_2_SREC_Cash_Back__c, Scenario_3_SREC_Cash_Back__c, Scenario_4_SREC_Cash_Back__c, 
                                         Scenario_1_Total_Net_Adjustment__c, Scenario_2_Total_Net_Adjustment__c, Scenario_3_Total_Net_Adjustment__c, Scenario_4_Total_Net_Adjustment__c, 
                                         Scenario_1_Net_Initial_Outlay__c, Scenario_2_Net_Initial_Outlay__c, Scenario_3_Net_Initial_Outlay__c, Scenario_4_Net_Initial_Outlay__c, 
                                         Scenario_1_Term_Loan__r.Financing_Term_Months__c, Scenario_2_Term_Loan__r.Financing_Term_Months__c, Scenario_3_Term_Loan__r.Financing_Term_Months__c, Scenario_4_Term_Loan__r.Financing_Term_Months__c, 
                                         Scenario_1_First_Month_Payment__c, Scenario_2_First_Month_Payment__c, Scenario_3_First_Month_Payment__c, Scenario_4_First_Month_Payment__c, 
                                         Scenario_1_Lease_Escalator__c, Scenario_2_Lease_Escalator__c, Scenario_3_Lease_Escalator__c, Scenario_4_Lease_Escalator__c 
                                         FROM System_Design_Quote__c WHERE ID IN :propsToQuotes.values()]);
        Map<ID, System_Design__c> sds = new Map<ID, System_Design__c>(
                                        [SELECT Default_CB_Panel__r.Utility_Service__r.Method_1_Net_Savings__c FROM System_Design__c WHERE ID IN :propsToSysDesigns.values()]);
        
        ProposalProcessor pp = new ProposalProcessor();
        for (Proposal__c prop : props){
            for (Integer i = 1; i <= 4; i++){
                if (prop.get('Scenario_' + i + '_Proposal_Term_months__c') != null){
                    System_Design_Quote__c sdq = sdqs.get(propsToQuotes.get(prop.ID));
                    System_Design__c sd = sds.get(propsToSysDesigns.get(prop.ID));
                    prop.put('Scenario_' + i + '_Cumulative_Cash_Benefit__c', pp.calcCumulativeCashBenefit(prop, sdq, sd, i, Integer.valueOf(prop.get('Scenario_' + i + '_Proposal_Term_months__c')) ));
                }
            }
        }
        
        update props;
    }

    global void finish(Database.BatchableContext bc){}
}