src/objects/Property__c.object
<CustomObject>
    <description>AstrumPM/AstrumCRM - Each account can have one or more properties.  A property is defined by its street address.</description>
    <label>Property</label>
    <nameField>
        <label>Property Address 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/System_Design__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The Solar System Design.  Each Property can have one or more System Designs created as the result of a site Survey and the discovery of Install Locations.  Each System Design is made up of one or more System Design Arrays.</description>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>System Designs</relationshipLabel>
        <relationshipName>System_Designs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>System Design</label>
    <nameField>
        <displayFormat>SD-{0}</displayFormat>
        <label>System Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Designs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility_Service__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - Each Property can have one or more Utility Service(s).  A Utility Service is primarily defined by the Meter ID and the Utility Company to which is connects.</description>
    <fields>
        <fullName>Property__c</fullName>
        <label>Property</label>
        <referenceTo>Property__c</referenceTo>
        <relationshipLabel>Utility Services</relationshipLabel>
        <relationshipName>Utility_Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Utility_Rate_Code_Before_Solar__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rate Code Before Solar</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Utility_Company__c.RecordType.Name</field>
                <operation>notEqual</operation>
                <value>Custom</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Utility_Company__c</referenceTo>
        <relationshipLabel>Utility Services (Utility Rate Code Before Solar)</relationshipLabel>
        <relationshipName>Utility_Services1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Service</label>
    <nameField>
        <label>Meter ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SystemDesignCalcUtilityPricing.cls
/*
    12/15/14  DK  Send the Utility Service's rate code to getUtilityServiceMonthlyProduction() instead of the Property's
*/
public with sharing class SystemDesignCalcUtilityPricing {
	
	private ApexPages.StandardController controller;
    
    public SystemDesignCalcUtilityPricing(ApexPages.StandardController controller) {
        this.controller = controller;
    }
    
    public PageReference getUtilityPricing() {
        
        System_Design__c sysDesign = (System_Design__c) controller.getRecord();
        sysDesign = [SELECT Property__c FROM System_Design__c WHERE ID = :sysDesign.ID LIMIT 1];  
        Utility_Service__c utilService = [SELECT Utility_Rate_Code_Before_Solar__c 
                                          FROM Utility_Service__c WHERE Property__c = :sysDesign.Property__c LIMIT 1];
        UtilityPricingProcessor upp = new UtilityPricingProcessor(sysDesign.ID,'Method_1');
		upp.getUtilityServiceMonthlyProduction(utilService.Utility_Rate_Code_Before_Solar__c);
        //SystemDesignSQCalculation.calculateSQ(sysDesign,'ASTRUM');
        return controller.cancel();
    } 
    
    
}