src/objects/Rate_Period__c.object
<CustomObject>
    <fields>
        <fullName>Period_Type__c</fullName>
        <label>Period Type</label>
        <picklist>
            <picklistValues>
                <fullName>Peak</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Part_Peak</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Off_Peak</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flat</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rate_Period__c</fullName>
        <label>Rate Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tier_1_Rate_kWh__c</fullName>
        <label>Tier 1 Rate ($/kWh)</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tier_2_Rate_kWh__c</fullName>
        <label>Tier 2 Rate ($/kWh)</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tier_3_Rate_kWh__c</fullName>
        <label>Tier 3 Rate ($/kWh)</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tier_4_Rate_kWh__c</fullName>
        <label>Tier 4 Rate ($/kWh)</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tier_5_Rate_kWh__c</fullName>
        <label>Tier 5 Rate ($/kWh)</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Utility_Company__c</fullName>
        <label>Utility Company</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Utility_Company__c.RecordType.Name</field>
                <operation>notEqual</operation>
                <value>Custom</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Utility_Company__c</referenceTo>
        <relationshipLabel>Rate Period</relationshipLabel>
        <relationshipName>Rate_Period</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Rate Period</label>
    <nameField>
        <label>Rate Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Period</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/System_Design__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The Solar System Design.  Each Property can have one or more System Designs created as the result of a site Survey and the discovery of Install Locations.  Each System Design is made up of one or more System Design Arrays.</description>
    <label>System Design</label>
    <nameField>
        <displayFormat>SD-{0}</displayFormat>
        <label>System Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Designs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/System_Design_Quote__c.object
<CustomObject>
    <description>AstrumCRM - System Design Quote.  Each System Design can have one or more System Design Quotes.  Each quote provides the sales consultant with the ability to adjust the negotiated price of the System Design based on the Calculated System Price.  Opportunities must choose a winning System Design Quote in order to close.</description>
    <fields>
        <fullName>System_Design__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>System Design</label>
        <referenceTo>System_Design__c</referenceTo>
        <relationshipLabel>System Design Quotes</relationshipLabel>
        <relationshipName>System_Design_Quotes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>System Design Quote</label>
    <nameField>
        <displayFormat>SDQ-{0}</displayFormat>
        <label>System Design Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Design Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility_Company__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - Each Utility Service is attached to a single Utility Company.</description>
    <fields>
        <fullName>Baseline_Consumption_kWh_day__c</fullName>
        <label>Baseline Consumption (kWh/day)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Baseline_Consumption_kWh_month__c</fullName>
        <label>Baseline Consumption (kWh/month)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Utility Rate Code</label>
    <nameField>
        <label>Utility Rate Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Rate Codes</pluralLabel>
    <recordTypes>
        <fullName>Custom</fullName>
        <active>true</active>
        <label>Custom</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UtilityPricingProcessorTest.cls
/*
	08/07/15  DK  Created test_method_two() to cover new code additions. CPQ-573.
*/
@isTest
private class UtilityPricingProcessorTest {
    private static boolean runalltests = true; // true to run all tests; false to skip tests and only run those where the 'if' is commented out

	@isTest static void test_method_one() {
		if(!runalltests){ return; }

        //Create Custom Settings
        testdata.setupCustomSettings();
        testdata.setupCustomConfigObjects();
        
        //Create System Design
        Id systemDesignID = testData.setupSystemDesign('Residential', 'Purchase', null, true, 12000);
        Utility_Company__c urc = [SELECT Id FROM Utility_Company__c WHERE Name = 'BG&E'];

        // Create Rate Periods
        List<Rate_Period__c> rps = new List<Rate_Period__c>();
		//for(Integer i = 1; i <= 12; i++) {
		for(Integer i = 1; i <= 6; i++) {
	        Rate_period__c rp = new Rate_period__c();
	        if (math.mod(12, i) == 0) {
		        rp.Period_Type__c = 'Peak';
	        } else if(math.mod(12, i) == 1) {
		        rp.Period_Type__c = 'Part_Peak';
	        } else {
		        rp.Period_Type__c = 'Off_Peak';
	        }
	        rp.Name = 'Period ' + i;
	        rp.Utility_Company__c = urc.id;
	        rp.Rate_Period__c = i;
	        rp.Tier_1_Rate_kWh__c = 0.14485;
	        rp.Tier_2_Rate_kWh__c = 0.14713;
	        rp.Tier_3_Rate_kWh__c = 0.16435;
	        rp.Tier_4_Rate_kWh__c = 1.1;
	        rp.Tier_5_Rate_kWh__c = 1.2;
	        rps.add(rp);
		}
        insert rps;

        test.startTest();

        UtilityPricingProcessor upp = new UtilityPricingProcessor(systemDesignID,'Method_1');
        upp.getUtilityServiceMonthlyProduction(urc.Id);

        urc.Baseline_Consumption_kWh_day__c = 'NA';
        urc.Baseline_Consumption_kWh_month__c = '341.00;310.80;341.00;330.00;341.00;465.00;480.50;480.50;465.00;341.00;330.00;341.00';
        update urc;

        upp.getUtilityServiceMonthlyProduction(urc.Id);

        test.stopTest();
	}

	@isTest static void test_method_two() {
		if(!runalltests){ return; }

		Opportunity_Trigger_Utility.skipOpportunityTrigger = true;	//Conserve SOQL

        //Create Custom Settings
        testdata.setupCustomSettings();
        testdata.setupCustomConfigObjects();
        
        //Create System Design
        System_Design_Quote__c sdq = testData.setupSystemDesignQuote('Residential', 'Purchase', null, true, 12000);
        Utility_Company__c urc = [SELECT Id FROM Utility_Company__c WHERE Name = 'R1'];

        // Create Rate Periods
        List<Rate_Period__c> rps = new List<Rate_Period__c>();
		for(Integer i = 1; i <= 6; i++) {
	        Rate_period__c rp = new Rate_period__c();
	        if (math.mod(12, i) == 0) {
		        rp.Period_Type__c = 'Peak';
	        } else if(math.mod(12, i) == 1) {
		        rp.Period_Type__c = 'Part_Peak';
	        } else {
		        rp.Period_Type__c = 'Off_Peak';
	        }
	        rp.Name = 'Period ' + i;
	        rp.Utility_Company__c = urc.id;
	        rp.Rate_Period__c = i;
	        rp.Tier_1_Rate_kWh__c = 0.22795;
	        rp.Tier_2_Rate_kWh__c = 0.23077;
	        rp.Tier_3_Rate_kWh__c = 0.25733;
	        rp.Tier_4_Rate_kWh__c = 0.27998;
	        rp.Tier_5_Rate_kWh__c = 0.31779;
	        rps.add(rp);
		}
        insert rps;

        test.startTest();

        UtilityPricingProcessor upp = new UtilityPricingProcessor(sdq.System_Design__c, 'Method_1');
        upp.getUtilityServiceMonthlyProduction(urc.Id);

        urc.Baseline_Consumption_kWh_day__c = 'NA';
        urc.Baseline_Consumption_kWh_month__c = '341.00;310.80;341.00;330.00;341.00;465.00;480.50;480.50;465.00;341.00;330.00;341.00';
        update urc;

        upp.getUtilityServiceMonthlyProduction(urc.Id);

        test.stopTest();

        Opportunity_Trigger_Utility.skipOpportunityTrigger = false;
	}
}