src/objects/System_Design__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The Solar System Design.  Each Property can have one or more System Designs created as the result of a site Survey and the discovery of Install Locations.  Each System Design is made up of one or more System Design Arrays.</description>
    <label>System Design</label>
    <nameField>
        <displayFormat>SD-{0}</displayFormat>
        <label>System Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Designs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/System_Design_Array__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The Solar System Design Array.  Each System Design is made up of one or more System Design Arrays.  Primarily defined by their mounting system and CB Panel connection, System Design Arrays are made up of one or more System Design Items.</description>
    <fields>
        <fullName>System_Design__c</fullName>
        <label>System Design</label>
        <referenceTo>System_Design__c</referenceTo>
        <relationshipLabel>System Design Arrays</relationshipLabel>
        <relationshipName>System_Design_Arrays</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>System Design Array</label>
    <nameField>
        <displayFormat>SDA-{0}</displayFormat>
        <label>System Design Array Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Design Arrays</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/System_Design_Item__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - System Design Item.  A collection of one or more System Design Products that are to be placed on a single Install Location.</description>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>System_Design_Array__c</fullName>
        <label>System Design Array</label>
        <referenceTo>System_Design_Array__c</referenceTo>
        <relationshipLabel>System Design Items</relationshipLabel>
        <relationshipName>System_Design_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>System_Design_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>System Design Product</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4) OR (5) OR (6 AND 7) OR (8 AND 9) OR 10</booleanFilter>
            <filterItems>
                <field>System_Design_Product__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Panel</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Panel</value>
            </filterItems>
            <filterItems>
                <field>System_Design_Product__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Inverter</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Inverter</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Mounting</value>
            </filterItems>
            <filterItems>
                <field>System_Design_Product__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Electrical</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Electrical</value>
            </filterItems>
            <filterItems>
                <field>System_Design_Product__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Trenching</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Trenching</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Special Part</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>System_Design_Product__c</referenceTo>
        <relationshipLabel>System Design Items</relationshipLabel>
        <relationshipName>System_Design_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Design__c</fullName>
        <description>System Design Id</description>
        <formula>System_Design_Array__r.System_Design__r.Id</formula>
        <inlineHelpText>System Design Id</inlineHelpText>
        <label>System Design</label>
        <type>Text</type>
    </fields>
    <label>System Design Item</label>
    <nameField>
        <label>System Design Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Design Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/System_Design_Product__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - System Design Products are the individual products (i.e. panels, inverters, etc) to be included in System Design Items.</description>
    <fields>
        <fullName>Micro_Inverter__c</fullName>
        <label>Micro Inverter</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>System Design Product</label>
    <nameField>
        <displayFormat>SDP-{0}</displayFormat>
        <label>System Design Product Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Design Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SalesInvoicePrintExtension.cls
/* FILE: SalesInvoicePrintExtension.cls
 * AUTHOR: Rohit Jain
 * DATE: Aug 6, 2013
 * PURPOSE: Sunnova Customization on Sales Invoice Print.
 * MODIFICATION HISTORY 
 */
public class SalesInvoicePrintExtension{

    private ApexPages.StandardController controller;
    private c2g__codaInvoice__c inv; 
    public SalesInvoicePrintExtension (ApexPages.StandardController controller) {
        this.controller = controller;
        inv = (c2g__codaInvoice__c)controller.getRecord();
        
        inv = [Select Sales_Order__r.System_Design_Quote__r.System_Design__c from c2g__codaInvoice__c Where id = :inv.Id  ];
        
    }
    
    public String inverterMakeup{
        get { 
            Id lastSystemDesignId = null;
            String systemMakeup = '';
            Boolean firstOne = false;
            if (inverterMakeup == null && inv.Sales_Order__r.System_Design_Quote__r.System_Design__c != null) {
                //User u = [SELECT Id, Alias FROM User WHERE Id = :UserInfo.getUserId()];
                AggregateResult[] results = 
                    [SELECT System_Design_Array__r.System_Design__c sdid, System_Design_Product__r.Micro_Inverter__c inv, SUM(Quantity__c) qty
                       FROM System_Design_Item__c
                      WHERE System_Design_Array__r.System_Design__c = :inv.Sales_Order__r.System_Design_Quote__r.System_Design__c
                        AND System_Design_Product__r.Micro_Inverter__c <> NULL
                   GROUP BY System_Design_Array__r.System_Design__c, System_Design_Product__r.Micro_Inverter__c
                    HAVING SUM(Quantity__c) > 0];
                
                
                for (AggregateResult ar : results) {
                    Id systemDesignId = (Id)ar.get('sdid');
                    if (systemDesignId != lastSystemDesignId) {
                        if (systemMakeup != '') {
                            systemMakeup = '';
                        }
                        lastSystemDesignId = systemDesignId;
                        firstOne = false;
                    }
                    
                    String des = (String)ar.get('inv');
                    if(des == 'M215')
                    {
                        des = 'Enphase M215 Mircoinverters';
                    }
                    else
                    {
                        des = des + ' Mircoinverters';
                    }
                    Decimal qty = (Decimal)ar.get('qty');

                    if (firstOne) {
                        systemMakeup += ', ';
                    }
                    firstOne = true;
                    systemMakeup += '(' + qty.intValue() + ') ' + des;
                }
            }
            return systemMakeup;
        }
        private set; 
    }
    
    
    
    
    

}