src/objects/System_Design__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The Solar System Design.  Each Property can have one or more System Designs created as the result of a site Survey and the discovery of Install Locations.  Each System Design is made up of one or more System Design Arrays.</description>
    <label>System Design</label>
    <nameField>
        <displayFormat>SD-{0}</displayFormat>
        <label>System Design Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Designs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/System_Design_Array__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - The Solar System Design Array.  Each System Design is made up of one or more System Design Arrays.  Primarily defined by their mounting system and CB Panel connection, System Design Arrays are made up of one or more System Design Items.</description>
    <fields>
        <fullName>Inverter_and_Transformer_Efficiency__c</fullName>
        <formula>Inverter_CEC_Efficiency__c *  DC_Optimizer_Efficiency__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Inverter and Transformer Efficiency</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>System_Design__c</fullName>
        <label>System Design</label>
        <referenceTo>System_Design__c</referenceTo>
        <relationshipLabel>System Design Arrays</relationshipLabel>
        <relationshipName>System_Design_Arrays</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Utility_Service__c</fullName>
        <formula>CB_Panel__r.Utility_Service__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Utility Service</label>
        <type>Text</type>
    </fields>
    <label>System Design Array</label>
    <nameField>
        <displayFormat>SDA-{0}</displayFormat>
        <label>System Design Array Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Design Arrays</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/System_Design_Item__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - System Design Item.  A collection of one or more System Design Products that are to be placed on a single Install Location.</description>
    <fields>
        <fullName>Apr_Solar_Access__c</fullName>
        <formula>Install_Location__r.Apr_Solar_Access__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Apr Solar Access</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Astrum_Balance_of_System_Derate_Text__c</fullName>
        <label>Astrum Balance of System Derate Text</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Astrum_Balance_of_System_Derate__c</fullName>
        <formula>IF(System_Design_Array__r.System_Design__r.Astrum_Balance_of_System_Derate__c &gt; 0 ,System_Design_Array__r.System_Design__r.Astrum_Balance_of_System_Derate__c,$Setup.System_Derate_Defaults__c.Astrum_Balance_of_System_Derate__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Astrum Balance of System Derate</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Astrum_PV_Watts_Derate_Text__c</fullName>
        <label>Astrum PV Watts Derate Text</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Astrum_PV_Watts_Derate__c</fullName>
        <formula>Astrum_Balance_of_System_Derate__c *  Inverter_and_Transformer_Efficiency__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Astrum PV Watts Derate</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Astrum_PV_Watts_Optimal_Site_Quality__c</fullName>
        <label>Astrum PV Watts Optimal Site Quality</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Astrum_PV_Watts_Site_Quality__c</fullName>
        <label>Astrum PV Watts Site Quality</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Aug_Solar_Access__c</fullName>
        <formula>Install_Location__r.Aug_Solar_Access__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Aug Solar Access</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Dec_Solar_Access__c</fullName>
        <formula>Install_Location__r.Dec_Solar_Access__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Dec Solar Access</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Feb_Solar_Access__c</fullName>
        <formula>Install_Location__r.Feb_Solar_Access__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Feb Solar Access</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Inverter_Transformer_Efficiency_Text__c</fullName>
        <label>Inverter/Transformer Efficiency Text</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Inverter_and_Transformer_Efficiency__c</fullName>
        <formula>System_Design_Array__r.Inverter_and_Transformer_Efficiency__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Inverter and Transformer Efficiency</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Jan_Solar_Access__c</fullName>
        <formula>Install_Location__r.Jan_Solar_Access__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Jan Solar Access</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Jul_Solar_Access__c</fullName>
        <formula>Install_Location__r.Jul_Solar_Access__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Jul Solar Access</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Jun_Solar_Access__c</fullName>
        <formula>Install_Location__r.Jun_Solar_Access__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Jun Solar Access</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Mar_Solar_Access__c</fullName>
        <formula>Install_Location__r.Mar_Solar_Access__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Mar Solar Access</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>May_Solar_Access__c</fullName>
        <formula>Install_Location__r.May_Solar_Access__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>May Solar Access</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>NRG_PV_Watts_De_Rate__c</fullName>
        <description>NRG PVWatts derate is calculated based on the specific inverter and whether the inverter is a central or microinverter.
NRG PV Watts Derate = AC-to-DC Derate Factor * Inverter CEC Efficiency * Shading Factor
AC-to-DC Derate is 0.946 for microinverters and 0.895 for string inverters
CEC Efficiency is the California Energy Commission (CEC) listed efficiency of the inverter
Shading Factor is the Solar Access percentage (SA) for string inverters and (0.4 + 0.6 * SA) for microinverters.</description>
        <formula>NRG_Balance_of_System_Derate__c  *  Inverter_and_Transformer_Efficiency__c  * (0.4 + (0.6 *  Panel_Annual_Solar_Access__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NRG PV Watts De-Rate</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NRG_Site_Quality__c</fullName>
        <label>NRG Site Quality</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nov_Solar_Access__c</fullName>
        <formula>Install_Location__r.Nov_Solar_Access__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Nov Solar Access</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Oct_Solar_Access__c</fullName>
        <formula>Install_Location__r.Oct_Solar_Access__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Oct Solar Access</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Panel_Annual_Solar_Access__c</fullName>
        <formula>Install_Location__r.Annual_Solar_Access__c</formula>
        <label>Panel Annual Solar Access</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Panel_Azimuth__c</fullName>
        <formula>Azimuth__c +  Install_Location__r.Azimuth__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Panel Azimuth</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Panel_Pitch__c</fullName>
        <description>Calculated pitch of the panels as mounted</description>
        <formula>Install_Location__r.Pitch__c  +  Tilt__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Panel Pitch</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <formula>System_Design_Array__r.System_Design__r.Property__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sep_Solar_Access__c</fullName>
        <formula>Install_Location__r.Sep_Solar_Access__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sep Solar Access</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Snow_De_Rate_kWh_y_kW__c</fullName>
        <formula>System_Design_Array__r.System_Design__r.Property__r.Snow_De_Rate_kWh_y_kW__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Snow De-Rate (kWh/y/kW)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Snow_Derate_Text__c</fullName>
        <label>Snow Derate Text</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>System_Design_Array__c</fullName>
        <label>System Design Array</label>
        <referenceTo>System_Design_Array__c</referenceTo>
        <relationshipLabel>System Design Items</relationshipLabel>
        <relationshipName>System_Design_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>System_Design__c</fullName>
        <description>System Design Id</description>
        <formula>System_Design_Array__r.System_Design__r.Id</formula>
        <inlineHelpText>System Design Id</inlineHelpText>
        <label>System Design</label>
        <type>Text</type>
    </fields>
    <label>System Design Item</label>
    <nameField>
        <label>System Design Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>System Design Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Utility_Company__c.object
<CustomObject>
    <description>AstrumCRM/AstrumPM - Each Utility Service is attached to a single Utility Company.</description>
    <fields>
        <fullName>Utility_Company_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Utility Company Master</label>
        <referenceTo>Utility_Company_master__c</referenceTo>
        <relationshipLabel>Utility Rate Codes</relationshipLabel>
        <relationshipName>Utility_Rate_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Utility Rate Code</label>
    <nameField>
        <label>Utility Rate Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Rate Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Utility_Company_master__c.object
<CustomObject>
    <description>Utility Company (distinct from Utility Rate Code)</description>
    <fields>
        <fullName>Solar_Compensation_Method__c</fullName>
        <label>Solar Compensation Method</label>
        <picklist>
            <picklistValues>
                <fullName>Net Metering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VOST</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Utility Company</label>
    <nameField>
        <label>Utility Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utility Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AstrumSQReCallExtension.cls
/* FILE: AstrumSQReCallExtension.cls
 * AUTHOR: Rohit Jain
 * DATE: July 24, 2013
 * PURPOSE: NRG Web Service Callout for Site Quality. Called from Button on Install Location.
 * MODIFICATION HISTORY 
      11/25/14  DK  Added Utility Service relationship lookups to the SDI query (for PVWatts_ServiceClient)
 */
public class AstrumSQReCallExtension {

    private ApexPages.StandardController controller;
    
    public AstrumSQReCallExtension (ApexPages.StandardController controller) {
        this.controller = controller;
    }
    
    public PageReference reCallAstrumSQ() {

        System_Design_Item__c item = (System_Design_Item__c) controller.getRecord();
        item = [Select System_Design_Array__r.System_Design__r.Default_CB_Panel__r.Utility_Service__r.Utility_Rate_Code_After_Solar__c
                      ,System_Design_Array__r.System_Design__r.Default_CB_Panel__r.Utility_Service__r.Utility_Company_Master__r.Solar_Compensation_Method__c
                      ,System_Design_Array__r.System_Design__r.Default_CB_Panel__r.Utility_Service__r.Utility_Value_of_Solar_Tariff__c
                      ,Panel_Annual_Solar_Access__c,NRG_Site_Quality__c
                      ,System_Design_Array__r.System_Design__r.Property__r.QAS_Latitude__c
                      ,System_Design_Array__r.System_Design__r.Property__r.QAS_Longitude__c
                       ,System_Design_Array__r.System_Design__r.Property__r.Latitude__c
                      ,System_Design_Array__r.System_Design__r.Property__r.Longitude__c
                      ,Panel_Azimuth__c,Panel_Pitch__c, System_Design_Array__r.System_Design__r.Property__r.Community_Program_Offer__r.OneRoof_SiteQuality__c
                      ,System_Design_Array__r.System_Design__r.Property__r.Property_State__c
                      ,System_Design_Array__r.System_Design__r.Property__r.Property_zip__c 
                      ,System_Design_Array__r.System_Design__r.Property__r.Utility_Company__c                      
                      ,Astrum_PV_Watts_Derate__c,Astrum_PV_Watts_Optimal_Site_Quality__c,Astrum_PV_Watts_Site_Quality__c
                      ,Astrum_Balance_of_System_Derate_Text__c,Astrum_PV_Watts_Derate_Text__c
                      ,Astrum_Balance_of_System_Derate__c,Inverter_and_Transformer_Efficiency__c
                      ,Inverter_Transformer_Efficiency_Text__c,Snow_Derate_Text__c,Snow_De_Rate_kWh_y_kW__c
                      ,Jan_Solar_Access__c,Feb_Solar_Access__c,Mar_Solar_Access__c,Apr_Solar_Access__c,May_Solar_Access__c,Jun_Solar_Access__c
                      ,Jul_Solar_Access__c,Aug_Solar_Access__c,Sep_Solar_Access__c,Oct_Solar_Access__c,Nov_Solar_Access__c,Dec_Solar_Access__c
                  from System_Design_Item__c Where id = :item.Id];       
         
         System.debug('JanSolar***'+item.Jan_Solar_Access__c);
         String latitude = (item.System_Design_Array__r.System_Design__r.Property__r.QAS_Latitude__c != null ? item.System_Design_Array__r.System_Design__r.Property__r.QAS_Latitude__c : String.valueOf(item.System_Design_Array__r.System_Design__r.Property__r.Latitude__c)  ) ;  
         String longitude = (item.System_Design_Array__r.System_Design__r.Property__r.QAS_Longitude__c != null ? item.System_Design_Array__r.System_Design__r.Property__r.QAS_Longitude__c : String.valueOf(item.System_Design_Array__r.System_Design__r.Property__r.Longitude__c)  ) ;  
        
        if( latitude == null ||  longitude == null  || item.System_Design_Array__r.System_Design__r.Property__r.Utility_Company__c == null )         
        {
            throw new customException ('One of Required fields - Latitude,Longitude,Utility are missing on Property record to calculate Astrum Site Quality.');
        }  
        if ( item.Panel_Azimuth__c != null 
            && item.Panel_Pitch__c != null && item.Panel_Annual_Solar_Access__c != null ) {             
              //siteQuality = PVWatts_ServiceClient.getNRGSiteQuality(item.System_Design_Array__r.System_Design__r.Property__r.QAS_Latitude__c, item.System_Design_Array__r.System_Design__r.Property__r.QAS_Longitude__c ,item.NRG_PV_Watts_De_Rate__c.toPlainString(),item.Panel_Pitch__c.toPlainString(),item.Panel_Azimuth__c.toPLainString());                       
              try {
                item = PVWatts_ServiceClient.getSiteQualityHourly(item,'ASTRUM');//item.System_Design_Array__r.System_Design__r.Property__r.QAS_Latitude__c, item.System_Design_Array__r.System_Design__r.Property__r.QAS_Longitude__c ,item.NRG_PV_Watts_De_Rate__c.toPlainString(),item.Panel_Pitch__c.toPlainString(),item.Panel_Azimuth__c.toPLainString());                       
              }
              catch(Exception e)
              {
                throw new customException (e.getMessage());        
              }
              update item;                    
        }
        else
        { 
            throw new customException ('One of Required fields - Azimuth,Tilt,Shading are missing on System Design Item record to calculate Astrum Site Quality.');
        }
        
        return controller.cancel();
    } 
    
    public class customException extends Exception {} 

}