src/objects/Time_Sheet__c.object
<CustomObject>
    <description>AstrumTIME - Employee Time Sheet</description>
    <label>Time Sheet</label>
    <nameField>
        <displayFormat>TimeSheet-{000000}</displayFormat>
        <label>Time Sheet Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Time_Sheet_Entry__c.object
<CustomObject>
    <description>AstrumTIME - A Single Entry For An Astrum Solar Time Sheet</description>
    <fields>
        <fullName>Bonus_Type__c</fullName>
        <description>Type of Employee Used for Bonus Calculations</description>
        <inlineHelpText>Type of Employee Used for Bonus Calculations</inlineHelpText>
        <label>Bonus Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <description>End Time</description>
        <inlineHelpText>End Time</inlineHelpText>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Half_Hour_Lunch_Break__c</fullName>
        <description>Half Hour Lunch Break</description>
        <inlineHelpText>Did you take a half hour lunch break during this time?</inlineHelpText>
        <label>Half Hour Lunch Break</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Hotel_Cost__c</fullName>
        <defaultValue>0</defaultValue>
        <description>How Much Did The Hotel Cost If You Checked &quot;Stayed Overnight&quot;?</description>
        <inlineHelpText>How Much Did The Hotel Cost If You Checked &quot;Stayed Overnight&quot;?</inlineHelpText>
        <label>Hotel Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Maintenance_Type__c</fullName>
        <description>If This Entry is MAINTENANCE, when did this Maintenance Occur?</description>
        <inlineHelpText>If This Entry is MAINTENANCE, when did this Maintenance Occur?</inlineHelpText>
        <label>Maintenance Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Posted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Posted to Payroll Entry</description>
        <label>Posted ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Client_Job__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Which Project Are You Working On?</description>
        <inlineHelpText>Which Project Are You Working On?</inlineHelpText>
        <label>Project/Client/Job</label>
        <referenceTo>Install_Project__c</referenceTo>
        <relationshipLabel>Time Sheet Entries</relationshipLabel>
        <relationshipName>Time_Sheet_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purpose__c</fullName>
        <description>Purpose</description>
        <inlineHelpText>Purpose</inlineHelpText>
        <label>Purpose</label>
        <picklist>
            <picklistValues>
                <fullName>Install</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Install-Electrical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warranty Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Bonus Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Bonus Warranty Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid Time Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holiday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sick Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vacation Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First 2 Weeks of Training</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Time_Off_Site__c</fullName>
        <description>Start Time Off Site</description>
        <inlineHelpText>Start Time Off Site</inlineHelpText>
        <label>Start Time Off Site</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Time_On_Site__c</fullName>
        <description>Start Time On Site</description>
        <inlineHelpText>Start Time On Site</inlineHelpText>
        <label>Start Time On Site</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <description>Start Time</description>
        <inlineHelpText>Start Time</inlineHelpText>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Stayed_Overnight__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Did you stay overnight after this shift?</description>
        <inlineHelpText>Did you stay overnight after this shift?</inlineHelpText>
        <label>Stayed Overnight</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Time_Sheet__c</fullName>
        <description>The Astrum Solar Time Sheet Containing this Entry</description>
        <inlineHelpText>The Astrum Solar Time Sheet Containing this Entry</inlineHelpText>
        <label>Time Sheet</label>
        <referenceTo>Time_Sheet__c</referenceTo>
        <relationshipLabel>Time Sheet Entries</relationshipLabel>
        <relationshipName>Time_Sheet_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Timesheet_Purpose__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Timesheet Purpose</label>
        <referenceTo>Timesheet_Purpose__c</referenceTo>
        <relationshipLabel>Time Sheet Entries</relationshipLabel>
        <relationshipName>Time_Sheet_Entries</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Hours__c</fullName>
        <description>Total Hours For This Entry</description>
        <inlineHelpText>Total Hours For This Entry</inlineHelpText>
        <label>Total Hours</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Time Sheet Entry</label>
    <nameField>
        <displayFormat>Entry-{0000000}</displayFormat>
        <label>Time Sheet Entry</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Sheet Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Timesheet_Purpose__c.object
<CustomObject>
    <label>Timesheet Purpose</label>
    <nameField>
        <label>Timesheet Purpose Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Timesheet Purposes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Time_Sheet_Controller_Extension.cls
public class Time_Sheet_Controller_Extension {
    
    private final Time_Sheet__c timeSheet; 
    public List<Time_Sheet_Entry__c> entries{get;set;}
     
    private void LoadData(){
        this.entries = [SELECT id, name, Time_Sheet__c, Project_Client_Job__c,Timesheet_Purpose__c, Purpose__c, Start_Time__c, Start_Time_On_Site__c, Start_Time_Off_Site__c, End_Time__c, Stayed_Overnight__c, Hotel_Cost__c, Half_Hour_Lunch_Break__c, Total_Hours__c, Bonus_Type__c, Maintenance_Type__c 
        FROM Time_Sheet_Entry__c WHERE Time_Sheet__c=:this.timeSheet.id And Posted__c = false];
    
    }
    
    public Time_Sheet_Controller_Extension(ApexPages.StandardController stdController) {
        this.timeSheet = (Time_Sheet__c)stdController.getRecord();
        LoadData();
    }
    
    public PageReference doAddEntry(){
        Time_Sheet_Entry__c tse = new Time_Sheet_Entry__c();
        tse.Time_Sheet__c = this.timeSheet.id;
        if(this.entries.size()>0){
            Time_Sheet_Entry__c cp = this.entries.get(this.entries.size()-1);
            tse.Project_Client_Job__c = cp.Project_Client_Job__c;
            tse.Timesheet_Purpose__c=cp.Timesheet_Purpose__c;
            tse.Purpose__c=cp.Purpose__c;
            tse.Start_Time__c=cp.Start_Time__c;
            tse.Start_Time_On_Site__c=cp.Start_Time_On_Site__c;
            tse.Start_Time_Off_Site__c=cp.Start_Time_Off_Site__c;
            tse.End_Time__c=cp.End_Time__c;
            tse.Half_Hour_Lunch_Break__c = cp.Half_Hour_Lunch_Break__c;
        }
        this.entries.add(tse);
        return null;
    }
    
    public PageReference doSaveEntries(){
        try{
            upsert this.entries;
        } Catch (DMLException e) {
            ApexPages.addMessages(e);
            return null;
        }
        LoadData();
        return new PageReference('/'+ApexPages.currentPage().getParameters().get('id'));
    }
    
    public PageReference doCancel(){
        return new PageReference('/'+ApexPages.currentPage().getParameters().get('id'));
    }
}